beyondessential/tupaia

packages/database/src/migrations/20200807061202-AddTotalScreenedForNCDRiskFactors-modifies-data.js

Add dashboard 
---
Relevant screenshots for this PR can be found here: https://github.com/beyondessential/tupaia-backlog/issues/843#issuecomment-679564328

Add Dashboard Total Screened For NCD Risk Factors

---

packages/database/src/DatabaseModel.js
packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/database/models/Answer.js
packages/meditrak-server/src/routes/importStriveLabResults/importStriveLabResults.js
packages/meditrak-server/src/routes/importSurveyResponses/assertCanImportSurveyResponses.js
packages/meditrak-server/src/routes/importSurveyResponses/importSurveyResponses.js
packages/meditrak-server/src/routes/importSurveyResponses/index.js
packages/meditrak-server/src/routes/index.js

- Added permissions checking for importing survey responses and importing strive lab results.

1026: Permissions checking: import survey responses

---

packages/devops/scripts/ci/deployBackend.sh
packages/devops/scripts/deployment/deployLatestRepositories.sh

A small devops tweak to make investigations easier

Show date and time on pm2 logs

---

packages/utils/src/testUtilities/addCustomJestMatchers.js

[No issue]
With the existing implementation, all matchers were treated as `async` which could create false positives for non-awaited "sync" matchers

Split async and sync matcher creation

---

packages/web-frontend/public/index.html

No issue (yet)
Change the color of the noscript message so that it is visible. In the first screenshot, it is almost invisible.
=>

Change noscript message colour

---

packages/database/src/migrations/20200825113028-AddLaosEocProject-modifies-data.js

[1085](https://github.com/beyondessential/tupaia-backlog/issues/1085) Create new project for Laos EOC
In this PR:
- a simple db migration to add Laos Emergency Operations Project.
- includes project, initial entity hierarchy and new dashboardGroup

Add migration for Laos EOC project

---

packages/web-config-server/src/apiV1/dataBuilders/generic/percentage/percentagesOfValueCounts.js

- fixed performance of percentagesOfValueCounts

1195: fixed performance of percentagesOfValueCounts

---

packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/routes/GETOptionSets.js
packages/meditrak-server/src/routes/GETOptions.js
packages/meditrak-server/src/routes/GETPermissionGroups.js
packages/meditrak-server/src/routes/GETQuestions.js
packages/meditrak-server/src/routes/index.js

- Added routes that required tupaia admin panel access

1133: Permissions checking: GET resources available for any admin panel user to view

---

packages/web-frontend/src/historyNavigation/constants.js
packages/web-frontend/src/historyNavigation/index.js
packages/web-frontend/src/historyNavigation/utils.js
packages/web-frontend/src/sagas.js
packages/web-frontend/src/screens/exporter/RootScreen/index.js

https://github.com/beyondessential/tupaia-backlog/issues/770
PR 8/? here: https://github.com/beyondessential/tupaia/pull/1063
I think that it is an encouraging sign that it is quite easy to add another parameter in the url (only changing the constants file).

Url refactor exports

---

packages/web-config-server/src/apiV1/DataAggregatingRouteHandler.js

Just tidying some code up as a way to get my head in the zone, only a single minor performance improvement here

Tidy up fetchDataSourceEntities

---

packages/admin-panel/src/pages/resources/UsersPage.js
packages/meditrak-server/src/routes/getRecords.js
packages/meditrak-server/src/routes/importUsers.js

Also addresses another occurrence of a neglected use of user_country_permission in importing users

1206 fix filtering by user

---

packages/access-policy/package.json
packages/aggregator/package.json
packages/auth/package.json
packages/data-api/package.json
packages/data-broker/package.json
packages/database/package.json
packages/dhis-api/package.json
packages/export-chart-lambda/package.json
packages/meditrak-server/package.json
packages/utils/package.json
packages/web-config-server/package.json

- Dev only: add source maps to packages to make debugging better

(Dev only) Add source maps to all packages

---

packages/web-frontend/src/actions.js
packages/web-frontend/src/utils/measures.js

No issue
This comment confused me when I was starting, and I only just figured out what it meant.

Remove confusing comments

---

packages/database/src/migrations/20200831024802-UpdateUNFPAReportToAddFPData-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/1156

Add Family Planning row to UNFPA report

---

packages/indicators/src/__tests__/builders/buildArithmetic/buildArithmetic.fixtures.ts
packages/indicators/src/__tests__/builders/buildArithmetic/buildArithmetic.test.ts
packages/indicators/src/builders/buildArithmetic.ts
packages/utils/src/tests/validation/validationFunctions.test.js
packages/utils/src/validation/validatorFunctions.js

https://github.com/beyondessential/tupaia-backlog/issues/1242

1242 support defaults arithmetic indicator

---

packages/database/src/migrations/20200903032810-AddStationProjectCodeAndProjectIdEntityTypes-modifies-schema.js

https://github.com/beyondessential/tupaia-backlog/issues/1227
Added 3 new entity types.
Is this a schema migration?

Add 3 new entity types

---

packages/database/src/migrations/20200804082610-AddTongaHpuReportNutritionClientsByAgeGender-modifies-data.js
packages/database/src/migrations/20200811090718-AddTongaHpuDashboardPieNumberNewQuitlineDistrict-modifies-data.js
packages/database/src/migrations/20200903032810-AddStationProjectCodeAndProjectIdEntityTypes-modifies-schema.js
packages/web-config-server/src/apiV1/dataBuilders/DataBuilder.js
packages/web-config-server/src/apiV1/dataBuilders/generic/sum/index.js
packages/web-config-server/src/apiV1/dataBuilders/generic/sum/sumByOrgUnit.js
packages/web-config-server/src/apiV1/dataBuilders/generic/sum/sumPerSeries.js
packages/web-frontend/src/projects/sagas.js
packages/web-frontend/src/reducers.js

1204-file-upload-fieldtest

---

packages/admin-panel/src/importExport/ImportModal.js
packages/ui-components/src/components/Button.js
packages/ui-components/src/components/Inputs/FileUploadField.js
packages/ui-components/src/components/Inputs/index.js
packages/ui-components/stories/inputs/fileUploadField.stories.js

- Add file upload field component
- Add file upload field storybook
- Update admin panel file import
---
**Chrome**
**Storybook**
**Safari**
**Firefox**

1204 file upload field

---

packages/database/src/migrations/20200909012517-AddParentToTongaPermissionGroup-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/1078
Screenshot here: https://github.com/beyondessential/tupaia-backlog/issues/1078#issuecomment-689253375

Migration to update parent

---

packages/meditrak-server/package.json

[No issue]
It somehow escaped my attention in https://github.com/beyondessential/tupaia/pull/1287

Add private field in meditrak-server

---

packages/meditrak-server/src/routes/importStriveLabResults/importStriveLabResults.js
packages/meditrak-server/src/routes/importSurveyResponses/assertCanImportSurveyResponses.js

Fix lodash import

---

packages/psss/.eslintrc
packages/psss/src/api/TupaiaApi.js
packages/psss/src/components/AlertsOutbreaksCard.js
packages/psss/src/components/Header.js
packages/psss/src/components/Layout.js
packages/psss/src/containers/Tables/CountrySummaryTable.js
packages/psss/src/containers/Tables/CountryTable.js
packages/psss/src/containers/Tables/SiteSummaryTable.js
packages/psss/src/store/weeklyReports/country.js
packages/psss/src/store/weeklyReports/site.js
packages/psss/src/views/CountriesReportsView.js
packages/psss/src/views/Tabs/WeeklyCasesTabView.js

I know that there is a lint package update coming soon thanks to Kostas but I wanted to get the lint errors fixed now and the rules are the same in the new package so it has to be done anyway.
- fix lint errors
- refactor layout component to make a bit drier

932 refactor to fix lint errors

---

packages/aggregator/src/analytics/aggregateAnalytics/aggregateAnalytics.js
packages/aggregator/src/analytics/aggregateAnalytics/aggregations/sumAcrossPeriods.js
packages/aggregator/src/tests/analytics/aggregateAnalytics/aggregations/sumAcrossPeriods.test.js
packages/utils/src/period/period.js
packages/utils/src/tests/period/period.test.js

Addresses https://github.com/beyondessential/tupaia-backlog/issues/1290 - at least in part

1290: Exclude future dates

---

packages/database/src/modelClasses/Entity.js
packages/web-config-server/src/models/Entity.js

Addressing https://github.com/beyondessential/tupaia-backlog/issues/1307

1307: Fix inability to import field station due to validation

---

packages/database/src/modelClasses/Entity.js
packages/web-config-server/src/models/Entity.js

Hot fix to address https://github.com/beyondessential/tupaia-backlog/issues/1307

Fix inability to import field station due to validation

---

packages/database/src/modelClasses/Entity.js
packages/web-config-server/src/models/Entity.js
packages/web-frontend/src/selectors/dashboardSelectors.js

Bug fixes 🐛 
- [1307](https://github.com/beyondessential/tupaia-backlog/issues/1307) Can't import field_station entities
- [No issue](https://github.com/beyondessential/tupaia/pull/1352/commits/c0963ca29f5c1bffad8fc3f9a68685e9593e442f) Enlarged dialog sometimes doesn't show

Hot fix two production bugs

---

packages/access-policy/package.json
packages/admin-panel/package.json
packages/aggregator/package.json
packages/auth/package.json
packages/data-api/package.json
packages/data-broker/package.json
packages/database/package.json
packages/dhis-api/package.json
packages/export-chart-lambda/package.json
packages/meditrak-app/package.json
packages/meditrak-server/package.json
packages/psss/package.json
packages/ui-components/package.json
packages/utils/package.json
packages/web-config-server/package.json
packages/web-frontend/package.json

Towards https://github.com/beyondessential/tupaia-backlog/issues/967

Add lint scripts

---

packages/database/src/migrations/20200921010041-FixLaosSchoolsSchoolIndicatorsEiESubNationalLevelsMapOverlaysEntityAggregation-modifies-data.js

- Migrate incorrect denominator
https://github.com/beyondessential/tupaia-backlog/issues/1312#issuecomment-695876807

1312: Hotfix laos schools subnational map overlays no data

---

packages/database/src/migrations/20200921010041-FixLaosSchoolsSchoolIndicatorsEiESubNationalLevelsMapOverlaysEntityAggregation-modifies-data.js
packages/meditrak-server/src/database/models/Option.js
packages/web-frontend/src/sagas.js

Same thing as: https://github.com/beyondessential/tupaia/pull/1357 without merging dev.

Hotfix expanded reports and option sets v2

---

packages/database/src/migrations/20200915040216-FixSamoaEntities-modifies-data.js

Addresses: https://github.com/beyondessential/tupaia-backlog/issues/1273

Fixes various entities in various tables for Samoa

---

packages/database/src/modelClasses/Entity.js
packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/routes/GETAccessRequests/GETAccessRequests.js
packages/meditrak-server/src/routes/GETAccessRequests/assertAccessRequestPermissions.js
packages/meditrak-server/src/routes/GETAccessRequests/index.js
packages/meditrak-server/src/routes/GETUserAccounts/GETUserAccounts.js
packages/meditrak-server/src/routes/GETUserAccounts/assertUserAccountPermissions.js
packages/meditrak-server/src/routes/GETUserAccounts/index.js
packages/meditrak-server/src/routes/GETUserEntityPermissions/GETUserEntityPermissions.js
packages/meditrak-server/src/routes/GETUserEntityPermissions/assertUserEntityPermissionPermissions.js
packages/meditrak-server/src/routes/GETUserEntityPermissions/index.js
packages/meditrak-server/src/routes/index.js

- userAccounts
- userEntityPermissions
- accessRequests
Added GETHandlers for each endpoint

Add permissions handling to user and permission GETs

---

packages/database/src/migrations/20200928061654-CreateLaosSchoolsCOVID19BarGraphDashboardReport-modifies-data.js

- Added covid 19 bar graph to laos schools.

1058: District, Provincial and National Level Dashboard: COVID-19 bar graph

---

packages/database/src/migrations/20200928063927-CreateLaosSchoolsWASHBarGraphDashboardReport-modifies-data.js

- Added wash bar graph to laos schools

1060: District, Provincial and National Level Dashboard: Water, Sanitation and Hygiene (WASH) bar graphs

---

packages/database/src/migrations/20200928065206-CreateLaosSchoolsTeachingAndLearningBarGraphDashboardReport-modifies-data.js

- Added teaching and learning bar graph laos schools

1063: District, Provincial and National Level Dashboard: Teaching and Learning bar graph

---

packages/access-policy/README.md
packages/access-policy/src/index.js
packages/meditrak-server/src/routes/accessRequests/GETAccessRequests.js
packages/meditrak-server/src/routes/accessRequests/assertAccessRequestPermissions.js
packages/meditrak-server/src/routes/userAccounts/GETUserAccounts.js
packages/meditrak-server/src/routes/userAccounts/assertUserAccountPermissions.js
packages/meditrak-server/src/routes/userEntityPermissions/GETUserEntityPermissions.js
packages/meditrak-server/src/routes/userEntityPermissions/assertUserEntityPermissionPermissions.js
packages/meditrak-server/src/routes/utilities/createAdminPanelDBFilter.js
packages/meditrak-server/src/routes/utilities/getAdminPanelAllowedEntityIds.js
packages/meditrak-server/src/routes/utilities/index.js

Converted permissions filtering for user and permissions GET functions to use pure SQL implementation.

Convert user and permissions GET filtering to pure SQL

---

packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/database/models/UserEntityPermission.js
packages/meditrak-server/src/routes/CRUDHandler/CRUDHandler.js
packages/meditrak-server/src/routes/DeleteHandler/DeleteHandler.js
packages/meditrak-server/src/routes/DeleteHandler/index.js
packages/meditrak-server/src/routes/accessRequests/assertAccessRequestPermissions.js
packages/meditrak-server/src/routes/index.js
packages/meditrak-server/src/routes/userAccounts/assertUserAccountPermissions.js
packages/meditrak-server/src/routes/userEntityPermissions/DeleteUserEntityPermissions.js
packages/meditrak-server/src/routes/userEntityPermissions/assertUserEntityPermissionPermissions.js
packages/meditrak-server/src/routes/userEntityPermissions/index.js

- Added Generic DeleteHandler
- Added DeleteUserEntityPermissionsHandler
- Added some extra error messages

Add permissions checking to user entity permissions DELETE endpoint

---

packages/database/src/TupaiaDatabase.js
packages/database/src/cachers/EntityHierarchyCacher.js
packages/database/src/migrations/20201006211507-BuildAncestorDescendantRelationCache-modifies-data.js
packages/database/src/testUtilities/index.js
packages/database/src/testUtilities/populateTestData.js
packages/database/src/tests/cachers/EntityHierarchyCacher.fixtures.js
packages/database/src/tests/cachers/EntityHierarchyCacher.test.js
packages/database/src/tests/scaffolding.test.js
packages/meditrak-server/src/index.js
packages/meditrak-server/src/tests/DummySyncQueue.js
packages/meditrak-server/src/tests/routeTests/changes/get.js
packages/meditrak-server/src/tests/routeTests/changes/post.js
packages/meditrak-server/src/tests/routeTests/surveyResponse/import.js
packages/meditrak-server/src/tests/routeTests/surveyResponse/put.js
packages/meditrak-server/src/tests/testUtilities/index.js
packages/utils/src/testUtilities/index.js
packages/utils/src/testUtilities/sleep.js
packages/web-config-server/src/app.js

Add cache invalidation and rebuild

Invalidate and rebuild ancestor_descendant_relation after changes

---

packages/database/src/migrations/20200928022356-AddEntityTypeCity-modifies-schema.js
packages/database/src/migrations/20200928061046-AddLaosEocEntities-modifies-data.js
packages/database/src/modelClasses/Entity.js

- Add entity type 'city'
- Import 10 most populous cities of Laos

995 laos eoc weather entities

---

packages/web-frontend/src/components/DateRangePicker/DateRangePicker.js
packages/web-frontend/src/containers/MeasureBar/Control.js
packages/web-frontend/src/containers/MeasureBar/index.js

Reverts beyondessential/tupaia#1436

Revert "1374 fix default date is wrong in map overlays"

---

packages/database/src/migrations/20201009061046-UpdateLaosEocEntities-modifies-data.js

Update entity names
---
This is the same PR as https://github.com/beyondessential/tupaia/pull/1294 but with different spellings.

Update Laos EOC entities

---

package.json

Outcome of this morning's incident response (dev admin panel white screening after login)

Reinstate postinstall step to build internal dependencies

---

packages/database/src/migrations/20201009035426-AddImmutableTableTrigger-modifies-schema.js
packages/database/src/runPostMigration.js

I was thinking of doing this for `entity_relation`, but thought I would go down the proper route (see earlier PR). However, this is still very useful for ancestor_descendant_relation (and any other derived tables in future)

Add trigger to disallow updating immutable table

---

packages/data-broker/src/__tests__/DataBroker/DataBroker.stubs.js
packages/data-broker/src/__tests__/getModels.test.js
packages/data-broker/src/__tests__/services/dhis/DhisService/DhisService.stubs.js
packages/data-broker/src/__tests__/services/dhis/DhisService/testPull/testPullAnalytics.js
packages/data-broker/src/__tests__/services/dhis/DhisService/testPull/testPullEvents.js
packages/data-broker/src/__tests__/services/dhis/buildAnalytics/buildAnalyticsFromDhisEventAnalytics.test.js
packages/data-broker/src/__tests__/services/tupaia/TupaiaService.stubs.js
packages/data-broker/src/__tests__/services/weather/DateSanitiser.test.js
packages/data-broker/src/__tests__/services/weather/WeatherService.stubs.js
packages/data-broker/src/__tests__/services/weather/WeatherService.test.js
packages/utils/src/testUtilities/createJestMockInstance.js
tupaia-packages.code-workspace

Your original PR looks awesome! I thought instead of requesting minor changes, I could as well do them myself, since some of them required some experimentation too

Data broker test tweaks

---

packages/admin-panel/src/pages/ProfilePage.js
packages/meditrak-server/src/dataAccessors/editUserAccount.js
packages/psss/src/store/auth.js
packages/psss/src/utils/createBase64Image.js
packages/psss/src/views/Tabs/ProfileTabView.js

- Add profile image field to PSSS
---
See issue https://github.com/beyondessential/tupaia-backlog/issues/1388

1388 psss profile photo

---

packages/database/src/cachers/EntityHierarchyCacher.js

If a rebuild was currently underway when another rebuild was scheduled, the one that was underway would resolve the newly added one too early (and other related issues with the shared instance fields). This fixes that issue.

Fix a race condition in entity hierarchy building

---

packages/database/src/cachers/EntityHierarchyCacher.js

To avoid running out of database connections

Batch deletes of subtrees in entity hierarchy cacher

---

packages/web-frontend/src/components/DateRangePicker/DateRangePicker.js
packages/web-frontend/src/containers/MeasureBar/Control.js
packages/web-frontend/src/containers/MeasureBar/index.js

* Prevent set dates to the same dates
* Measures use correct default date
* Minor PropTypes fix and cleanup
- Example
---

1374kstest

---

packages/database/src/migrations/20201015015257-DeleteAnswerWith9998-modifies-data.js

[Migrate 9998 to be no data](https://github.com/beyondessential/tupaia-backlog/issues/1203)
Delete all answers that have a value of 9998

1203-db-migration-delete-answer-with-9998

---

scripts/node/Script.js
scripts/node/refreshDatabase.js

Fix refresh-database script for MacOS users

---

packages/database/src/migrations/20201019011335-RemoveRedundantDataInFijiEntity-modifies-data.js

[1097: 2 facilities for CWMH Fiji in Tupaia](https://github.com/beyondessential/tupaia-backlog/issues/1097)
1. Update the `entity_id` in `survey_response` table where entity's name is `Colonial War Memorial Hospital`
2. Delete `CWMH Suva Hospital` in `entity` table

Merge 'Colonial War Memorial Hospital' into 'CWMH Suva Hospital'

---

packages/web-config-server/src/apiV1/dataBuilders/modules/disaster/countDisasterAffectedFacilitiesByType.js

https://github.com/beyondessential/tupaia-backlog/issues/1452

1452: Fix blank screen for 'DR_facility_type_affected_counts' report

---

packages/devops/scripts/utility/detectStage.sh
tupaia-packages.code-workspace

Reinstates functionality back to a working state

Fix detect stage script

---

packages/database/src/migrations/20201019011335-RemoveRedundantDataInFijiEntity-modifies-data.js
packages/devops/scripts/utility/detectStage.sh
packages/web-config-server/src/apiV1/dataBuilders/modules/disaster/countDisasterAffectedFacilitiesByType.js
tupaia-packages.code-workspace

1016kstest2

---

packages/dhis-api/src/DhisApi.js

Fix an issue with syncing event survey responses that I've found today
After upgrading DHIS2 to 2.35, syncing **event** survey responses started to have problem (my bad, I only smoke tested syncing **analytic** survey responses :( ). It gives the error: `Event.programStage does not point to a valid programStage: W9ijoiwH9mD`.
After investigating on DHIS2 2.35 code, particularly:
1. `ProgramStageCheck.java` (where it gives the error, line 61)
https://github.com/dhis2/dhis2-core/blob/ddb1f87fa26015b5fdb0e374ea863e499ec40280/dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/validation/ProgramStageCheck.java
2. And `WorkContext.getProgramStageIdScheme(), line 157` (this is where it find the programStage) …

Hotfix event survey res not syncing

---

packages/devops/scripts/utility/detectStage.sh
tupaia-packages.code-workspace

Same as https://github.com/beyondessential/tupaia/pull/1532, but for production.

Fix detect stage script (#1532)

---

packages/devops/scripts/utility/detectStage.sh
tupaia-packages.code-workspace

1466kstest

---

packages/web-frontend/.env.example
packages/web-frontend/cypress.env.example.json
packages/web-frontend/cypress.json
packages/web-frontend/cypress/README.md
packages/web-frontend/cypress/config/orgUnitMap.json
packages/web-frontend/cypress/constants.js
packages/web-frontend/cypress/e2e/dashboardReports.spec.js
packages/web-frontend/cypress/plugins/index.js
packages/web-frontend/cypress/scripts/createTestUser.js
packages/web-frontend/cypress/scripts/generateConfig.js
packages/web-frontend/cypress/scripts/generateDashboardReportConfig.js
packages/web-frontend/cypress/support/actions.js
packages/web-frontend/package.json
yarn.lock

https://github.com/beyondessential/tupaia-backlog/issues/1451
* Create test admin user, which is granted access to all top-level permissions for all countries
* Wait for `view` request instead of `dashboard` to tell when a report has loaded
* Refactor test user detail specification

1451: Create test admin user

---

packages/admin-panel/src/pages/resources/OptionSetsPage.js
packages/admin-panel/src/pages/resources/SurveysPage.js
packages/database/src/migrations/20201021060652-AddAttributesColumnIntoOptionTable-modifies-schema.js
packages/meditrak-app/app/assessment/specificQuestions/AutocompleteQuestion.js
packages/meditrak-app/app/database/schema.js
packages/meditrak-app/app/database/types/Option.js
packages/meditrak-server/src/routes/importOptionSets.js
packages/meditrak-server/src/routes/importSurveys/ConfigImporter/ConfigImporter.js
packages/meditrak-server/src/routes/importSurveys/ConfigImporter/processAutocompleteConfig.js
packages/meditrak-server/src/routes/importSurveys/ConfigImporter/processEntityConfig.js
packages/meditrak-server/src/routes/utilities/index.js
packages/meditrak-server/src/routes/utilities/translateQuestionDependentFields.js

- Allow filtering options by previous question

1232: Allow filtering options by a previous question

---

.eslintrc
packages/database/src/migrations/20201028234713-AddReportsTable-modifies-schema.js
packages/database/src/modelClasses/Report.js
packages/database/src/modelClasses/index.js
packages/database/src/types.js
packages/reports/package.json
packages/reports/src/app/addRoutesToApp.ts
packages/reports/src/routes/fetchReport.ts
yarn.lock

Also updated eslint config for reports package

1278: Added 'report' table and model

---

README.md

1475kstest

---

packages/admin-panel/src/utilities/convertSearchTermToFilter.js
packages/database/src/TupaiaDatabase.js

Allow filtering visualisation config in admin panel

---

packages/database/src/migrations/20201103092344-AddPSSSProject-modifies-data.js

- Add a migration file for creating PSSS project

1247 Add PSSS project and attach countries list with alternative hierarchy

---

LICENSE

1294-laos-eoc-observed-weather-map-overlays merge

---

packages/web-config-server/src/dhis/DhisApi.js

No issue
Fixes a bug introduced here: https://github.com/beyondessential/tupaia/pull/1442/files#diff-f74381228000d462c6a6d7428aacab2b375439b83e439ecac230a2cd6abc3eecR44-R48
Just a rename of: https://github.com/beyondessential/tupaia/pull/1584

Fix getDataValuesInSets

---

packages/database/src/modelClasses/Entity.js
packages/web-config-server/src/apiV1/organisationUnit.js
packages/web-config-server/src/apiV1/organisationUnitSearch.js

Relates to https://github.com/beyondessential/tupaia/pull/1577#issuecomment-724264862

Exclude cases from showing on tupaia frontend

---

packages/web-config-server/src/apiV1/dataBuilders/generic/dataDownload/surveyDataExport.js

Fixes for custom survey exports post model consolidation https://github.com/beyondessential/tupaia/pull/1484
In this PR
- add models to internal getDataBuilder call in SurveyDataExport

Fix custom survey exports

---

packages/database/src/migrations/20201110210258-AddFijiDistrictsToEntityRelation-modifies-data.js

Add Fiji districts to WISH entity_relations to fix WISH custom downloads

Add fiji districts to WISH entity relations

---

packages/meditrak-server/src/routes/userAccounts/EditUserAccounts.js
packages/meditrak-server/src/routes/userAccounts/GETUserAccounts.js
packages/meditrak-server/src/routes/userAccounts/assertUserAccountPermissions.js
packages/meditrak-server/src/tests/routes/userAccounts/EditUserAccounts.test.js
packages/meditrak-server/src/tests/routes/userAccounts/GETUserAccounts.test.js

Add GETUserAccounts.test.js and EditUserAccounts.test.js

1132: Add /userAccounts routes and unit tests

---

packages/meditrak-app/app/country/RequestCountryAccessPage.js
packages/web-frontend/src/containers/LoginForm/LoginFormComponent.js

To fix the attached screenshot, which pops up if you're running in dev mode

Pass event to submitForm

---

packages/web-config-server/src/apiV1/dataBuilders/DataBuilder.js

no issue, fix broken tonga fanafana dashbaoard that uses transform helper

pass in models to transform function

---

packages/web-config-server/src/apiV1/DataAggregatingRouteHandler.js

https://github.com/beyondessential/tupaia-backlog/issues/1555 Resolve soft conflict with existing dashboard report
caused by merge conflict

reorder getAncestorOfType params

---

full-testable-package.Dockerfile
package.json
scripts/bash/getInternalDependencies.sh
yarn.lock

https://github.com/beyondessential/tupaia-backlog/issues/1282
Also sorted some items alphabetically and removed an unused dependency

1282: Add reporting package to CI/CD

---

packages/reports/examples.http
packages/reports/package.json
packages/reports/src/app/addRoutesToApp.ts
packages/reports/src/app/createApp.ts
packages/reports/src/auth/index.ts
packages/reports/src/auth/middleware.ts
packages/reports/src/routes/fetchReport.ts
packages/reports/src/types.ts
yarn.lock

Worked out pretty cleanly in the end, thanks to our neatly abstracted auth and access-policy packages 😄 
For now, just supporting auth via username/pass, however in the future when we wire this up with the PSSS backend, we need to add support for auth via user token. This should be fairly easy to do, and can be copied from meditrak-server 👍

1281: Auth handling for Reporting package

---

packages/meditrak-app/app/authentication/actions.js

1294ksretest

---

packages/database/src/migrations/20201116002004-ChangeUNFPADefaultMeasure-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/1094
Just needed to change the default map overlay. It still works at regional level as the new default is not available there.

Change unfpa default measure

---

packages/database/src/migrations/20201006024935-AddLaosSchoolsTextbookStudentRatioBarGraph-modifies-data.js
packages/database/src/migrations/20201110234830-DeleteOldLaosSchoolsTextbookData-modifies-data.js
packages/database/src/migrations/20201116002004-ChangeUNFPADefaultMeasure-modifies-data.js
packages/meditrak-app/app/authentication/actions.js
packages/web-frontend/src/components/View/ChartWrapper/CartesianChart.js
packages/web-frontend/src/components/View/ChartWrapper/Tooltip.js
packages/web-frontend/src/utils/formatters.js

1024kstest

---

packages/database/src/migrations/20201117025041-DeleteTestDistrictEntity-modifies-data.js

- Deleted Test District
- Will also have to delete the entity from DHIS2. Will do that when this is merged into dev/prod

1591: Test data on production (UNFPA project, under Vanuatu)

---

packages/admin-panel/src/pages/resources/DisasterResponsePage.js
packages/admin-panel/src/pages/resources/UsersPage.js
packages/database/src/testUtilities/upsertDummyRecord.js
packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/routes/GETDisasters.js
packages/meditrak-server/src/routes/GETHandler/GETHandler.js
packages/meditrak-server/src/routes/GETHandler/helpers.js
packages/meditrak-server/src/tests/routes/GETDisasters.test.js

1633 Permission checking: Get disasters

---

packages/reports/package.json
packages/reports/src/app/createApp.ts
packages/reports/src/index.ts

Sorted using `npx sort-package-json`

Sort reports package.json

---

.eslintrc
README.md
full-testable-package.Dockerfile
packages/admin-panel/README.md
packages/database/src/migrations/20201006024935-AddLaosSchoolsTextbookStudentRatioBarGraph-modifies-data.js
packages/database/src/migrations/20201110234830-DeleteOldLaosSchoolsTextbookData-modifies-data.js
packages/database/src/migrations/20201116002004-ChangeUNFPADefaultMeasure-modifies-data.js
packages/database/src/migrations/20201117025041-DeleteTestDistrictEntity-modifies-data.js
packages/devops/Set up server.md
packages/expression-parser/README.md
packages/expression-parser/jest.config.json
packages/expression-parser/package.json
packages/expression-parser/src/__tests__/expression-parser/BooleanExpressionParser.test.js
packages/expression-parser/src/__tests__/expression-parser/ExpressionParser.test.js
packages/expression-parser/src/expression-parser/BooleanExpressionParser.js
packages/expression-parser/src/expression-parser/ExpressionParser.js
packages/expression-parser/src/expression-parser/index.js
packages/expression-parser/src/index.js
packages/meditrak-app/app/authentication/actions.js
packages/web-frontend/src/components/View/ChartWrapper/CartesianChart.js
packages/web-frontend/src/components/View/ChartWrapper/Tooltip.js
packages/web-frontend/src/utils/formatters.js
scripts/bash/getInternalDependencies.sh
tupaia-packages.code-workspace
yarn.lock

1578-do-not-reload-report test

---

packages/reports/package.json
scripts/bash/backendStartDev.sh

- Modified backendStartDev to allow starting ts server

1384 Fix yarn `start-dev` when src is typescript

---

packages/web-config-server/src/apiV1/view.js
packages/web-frontend/src/actions.js
packages/web-frontend/src/components/DateRangePicker/DatePickerDialog.js
packages/web-frontend/src/components/DateRangePicker/DateRangePicker.js
packages/web-frontend/src/components/DateRangePicker/constants.js
packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialog.js
packages/web-frontend/src/sagas.js
packages/web-frontend/src/tests/components/dateRangePicker.test.js
packages/web-frontend/src/tests/utils/periodGranularities.test.js
packages/web-frontend/src/utils/periodGranularities.js

Fix https://github.com/beyondessential/tupaia-backlog/issues/1578

1578: Do not reload date range report

---

packages/psss/src/containers/Tables/CountriesTable.js
packages/psss/src/containers/Tables/CountrySummaryTable.js
packages/psss/src/containers/Tables/CountryTable.js
packages/psss/src/containers/Tables/SiteSummaryTable.js
packages/psss/src/containers/Tables/constants.js

- Fix table alignments
---
See [the issue](https://github.com/beyondessential/tupaia-backlog/issues/1414)

fix psss table alignment issue

---

packages/data-broker/src/__tests__/services/weather/WeatherService.test.js
packages/data-broker/src/services/weather/WeatherService.js
packages/database/src/migrations/20201008010413-AddLaosEocHistoricMapOverlays-modifies-data.js
packages/database/src/migrations/20201009010413-AddLaosEocForecastMapOverlays-modifies-data.js
packages/web-frontend/.storybook/main.js
packages/web-frontend/.storybook/preview-head.html
packages/web-frontend/src/components/DateRangePicker/DateRangePicker.js
packages/web-frontend/src/components/View/constants.js
packages/web-frontend/src/containers/MeasureBar/Control.js
packages/web-frontend/src/tests/components/dateRangePicker.test.js
packages/web-frontend/src/utils/formatters.js
packages/web-frontend/stories/map/map.stories.js
packages/web-frontend/stories/map/marker.stories.js

- Add Laos EOC map overlays for forecast data
- Change WeatherService to always require start/end dates (and so make sure that forecast weather requests that specify start/end dates are handled correctly)
---
https://github.com/beyondessential/tupaia-backlog/issues/1295#issuecomment-705946095

1295 laos eoc forecast weather map overlays

---

packages/database/package.json
packages/database/src/migrations/20201012010424-AddLaosEocWeatherDashboards-modifies-data.js
packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialogContent.js
yarn.lock

- Add historic and forecast dashboards for Laos EOC
- Add limits to dashboard reports
- Add lodash to database package
---
See https://github.com/beyondessential/tupaia-backlog/issues/1199#issuecomment-706813336
---
replaces #1476

1199 1298 laos eoc

---

packages/database/src/migrations/20201014220808-AddLaosEocAggregateForecastMapOverlays-modifies-data.js
packages/web-config-server/src/apiV1/measureBuilders/DataPerOrgUnitBuilder.js
packages/web-config-server/src/apiV1/measureBuilders/sumPerOrgUnit.js
packages/web-frontend/src/containers/MeasureBar/Control.js
packages/web-frontend/src/containers/MeasureBar/index.js

- Add aggregate forecast map overlays
- Fix: data not being returned when aggregated
- Update measure builder to take data element from query
- Allow disable date picker in map overlays
---

1297 laos eoc aggregated map overlays

---

packages/database/src/migrations/20201014220808-AddLaosEocAggregateForecastMapOverlays-modifies-data.js
packages/database/src/migrations/20201123002611-AddNZToPSSSProject-modifies-data.js
packages/web-config-server/src/apiV1/measureBuilders/DataPerOrgUnitBuilder.js
packages/web-config-server/src/apiV1/measureBuilders/sumPerOrgUnit.js
packages/web-frontend/src/containers/MeasureBar/Control.js
packages/web-frontend/src/containers/MeasureBar/index.js

Merging dev into feature branch

Merging dev into feature branch

---

packages/database/src/migrations/20201117053359-AddPsssWoWIncreaseIndicators-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/1338

1338: Add PSSS WoW increase indicators

---

packages/database/src/migrations/20201123061122-AddConfirmedWeeklyDataReportForPSSS-modifies-data.js
packages/report-server/src/__tests__/reportBuilder/functions.test.ts
packages/report-server/src/__tests__/reportBuilder/transform/aggregate.test.ts
packages/report-server/src/__tests__/reportBuilder/transform/transform.fixtures.ts
packages/report-server/src/reportBuilder/reportBuilder.ts
packages/report-server/src/reportBuilder/transform/aliases/aggregateAliases.ts
packages/report-server/src/reportBuilder/transform/aliases/index.ts
packages/report-server/src/reportBuilder/transform/aliases/keyValueByFieldAliases.ts
packages/report-server/src/reportBuilder/transform/aliases/periodConversionAliases.ts
packages/report-server/src/reportBuilder/transform/functions/aggregate/aggregations.ts
packages/report-server/src/routes/fetchReport.ts
packages/report-server/src/types.ts

Added `Confirmed Weekly Report` Report

1409: PSSS Confirmed Weekly Report

---

packages/web-frontend/src/screens/mobile/RegionScreen/index.js

- Fix org unit children not showing in mobile

1521 Fix org unit children not showing in mobile

---

packages/database/src/migrations/20201125021221-AddPsssAlertThresholdIndicators-modifies-data.js
tupaia-packages.code-workspace

https://github.com/beyondessential/tupaia-backlog/issues/1339
https://github.com/beyondessential/tupaia-backlog/issues/1340

1338, 1339: Add PSSS Alert Threshold indicators

---

packages/meditrak-server/src/routes/importSurveyResponses/assertCanImportSurveyResponses.js
packages/meditrak-server/src/routes/postChanges.js
packages/meditrak-server/src/routes/surveyResponse.js

- Added permissions checking to POST surveyResponse and postChanges endpoints

1023 Permission Checking: Submit survey responses

---

packages/aggregator/src/__tests__/analytics/aggregateAnalytics/aggregations/offsetPeriod.test.js
packages/aggregator/src/analytics/aggregateAnalytics/aggregations/offsetPeriod.js

@rohan-bes adding you as a reviewer as you reviewed the original PR

Fix getDateRangeForOffsetPeriod

---

packages/web-frontend/src/sagas.js

from https://github.com/beyondessential/tupaia/pull/1719 as hotfix

HOTFIX: redirect to project page on login explore

---

packages/web-frontend/src/sagas.js

Co-authored-by: nick <nickw@ourcomunity.com.au>
https://github.com/beyondessential/tupaia/pull/1722

master back into dev

---

packages/devops/Set up server.md
packages/meditrak-app/README.md
packages/web-frontend/src/sagas.js

1361-add-title-and-export-date-to-exported-chart test

---

packages/database/src/migrations/20201126060032-AddUnconfirmedWeeklyDataReportForPSSS-modifies-data.js

1410: Added PSSS Unconfirmed Weeky Report

---

packages/devops/scripts/ci/utils.sh
packages/devops/scripts/ci/validateBranchName.sh

Addresses https://github.com/beyondessential/tupaia-backlog/issues/1539

1539: Update max branch name length validation

---

packages/web-frontend/src/actions.js
packages/web-frontend/src/components/View/MatrixWrapper/MatrixWrapper.js
packages/web-frontend/src/containers/DrillDownOverlay/index.js
packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialog.js
packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialogContent.js
packages/web-frontend/src/containers/EnlargedDialog/index.js
packages/web-frontend/src/historyNavigation/constants.js
packages/web-frontend/src/historyNavigation/historyMiddleware.js
packages/web-frontend/src/historyNavigation/historyNavigation.js
packages/web-frontend/src/historyNavigation/index.js
packages/web-frontend/src/historyNavigation/utils.js
packages/web-frontend/src/reducers.js
packages/web-frontend/src/sagas.js
packages/web-frontend/src/screens/desktop/RootScreen/index.js
packages/web-frontend/src/screens/mobile/RootScreen/index.js
packages/web-frontend/src/selectors/dashboardSelectors.js
packages/web-frontend/src/selectors/index.js
packages/web-frontend/src/utils/getUniqueViewId.js
packages/web-frontend/src/utils/index.js
packages/web-frontend/src/utils/periodGranularities.js

Reverts beyondessential/tupaia#1614

Revert "1421 refactor enlarged dialog"

---

packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/routes/GETDashboardReports/assertDashboardReportsPermissions.js
packages/meditrak-server/src/routes/GETHandler/helpers.js
packages/meditrak-server/src/routes/GETSurveyScreenComponents/assertSurveyScreenComponentPermissions.js
packages/meditrak-server/src/routes/accessRequests/assertAccessRequestPermissions.js
packages/meditrak-server/src/routes/userEntityPermissions/GETUserEntityPermissions.js
packages/meditrak-server/src/routes/userEntityPermissions/assertUserEntityPermissionPermissions.js
packages/meditrak-server/src/routes/utilities/index.js
packages/meditrak-server/src/routes/utilities/mergeFilter.js

- Fixup column handling to use resource/record conversion
- Add missing endpoint for user/id/userEntityPermission
- Fully justify table names in permission filters

Bugfixes: GET User Permissions

---

packages/devops/scripts/ci/validateBranchName.sh

A slight refactoring - functionality should stay the same, but I believe this uses a bit more accurate definitions

1539: Update validation logic

---

packages/meditrak-server/src/routes/exportSurveys/cellBuilders/AutocompleteConfigCellBuilder.js
packages/meditrak-server/src/routes/exportSurveys/cellBuilders/KeyValueCellBuilder.js

Addresses https://github.com/beyondessential/tupaia-backlog/issues/1723

1723: Hotfix export issue for surveys with an autocomplete field

---

packages/meditrak-server/src/routes/exportSurveys/cellBuilders/KeyValueCellBuilder.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/TableOfDataValuesWithCalc.js

Includes the following hotfixes (already approved):
* https://github.com/beyondessential/tupaia/pull/1768
* https://github.com/beyondessential/tupaia/pull/1772

Hotfix release 66

---

packages/report-server/src/aggregator/Aggregator.ts
packages/report-server/src/reportBuilder/fetch/functions/dataElement.ts
packages/report-server/src/reportBuilder/fetch/functions/dataGroup.ts
packages/report-server/src/types.ts

These params are required to do aggregation correctly for some aggregation types

Reworked URL params for fetchReport to accept startDate/endDate

---

packages/meditrak-app/app/Meditrak.js
packages/meditrak-app/app/assessment/DumbSurveyScreen.js
packages/meditrak-app/app/assessment/SurveysMenu.js
packages/meditrak-app/app/assessment/SurveysMenuScreen.js
packages/meditrak-app/app/changePassword/ChangePasswordPage.js
packages/meditrak-app/app/country/RequestCountryAccessPage.js
packages/meditrak-app/app/database/RealmExplorer.js
packages/meditrak-app/app/home/HomeScreen.js
packages/meditrak-app/app/navigation/HeaderLeftButton.js
packages/meditrak-app/app/navigation/Navigator.js
packages/meditrak-app/app/sync/SyncPage.js
packages/meditrak-app/app/sync/syncMigrations.js
packages/meditrak-app/app/user/CreateUserPage.js
packages/meditrak-app/app/web/WebBrowserContainer.js
packages/meditrak-app/app/widgets/InvisiblableView.js
packages/meditrak-app/app/widgets/KeyboardSpacer.js
yarn.lock

1696: Upgrade react-navigation 2

---

packages/psss/src/api/queries/useUpcomingReport.js
packages/psss/src/components/DateToolbar/DateToolbar.js
packages/psss/src/routes/PageRoutes.js
packages/psss/src/routes/PrivateRoute.js
packages/psss/src/store/auth.js

- Fix toolbar disabled state
- Fix auth refresh state
- Fix upcoming date calculation for due today
- Remove demo land

1632 fix bugs

---

packages/meditrak-app/app/navigation/Navigator.js
packages/meditrak-app/app/navigation/actions.js

- Implement new transition animation for react-navigation-stack 4.x

1696: Implement new transition for react-navigation-stack 4.x

---

packages/meditrak-server/src/routes/exportSurveyResponses.js

[1756: Hotfix missing Date column](https://github.com/beyondessential/tupaia-backlog/issues/1756)
Change fixed row count to dynamic

Change fixed row count to dynamic

---

packages/admin-panel/src/pages/resources/DataSourcesPage.js
packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/routes/CRUDHandler/CRUDHandler.js
packages/meditrak-server/src/routes/CreateHandler/BESAdminCreateHandler.js
packages/meditrak-server/src/routes/CreateHandler/TupaiaAdminCreateHandler.js
packages/meditrak-server/src/routes/CreateHandler/index.js
packages/meditrak-server/src/routes/DeleteHandler/BESAdminDeleteHandler.js
packages/meditrak-server/src/routes/DeleteHandler/TupaiaAdminDeleteHandler.js
packages/meditrak-server/src/routes/DeleteHandler/index.js
packages/meditrak-server/src/routes/EditHandler/BESAdminEditHandler.js
packages/meditrak-server/src/routes/EditHandler/TupaiaAdminEditHandler.js
packages/meditrak-server/src/routes/EditHandler/index.js
packages/meditrak-server/src/routes/GETDataSources.js
packages/meditrak-server/src/routes/GETEntities.js
packages/meditrak-server/src/routes/GETHandler/BESAdminGETHandler.js
packages/meditrak-server/src/routes/GETHandler/TupaiaAdminGETHandler.js
packages/meditrak-server/src/routes/GETHandler/index.js
packages/meditrak-server/src/routes/GETOptions.js
packages/meditrak-server/src/routes/index.js
packages/meditrak-server/src/routes/surveyResponses/GETSurveyResponses.js

https://github.com/beyondessential/tupaia-backlog/issues/1135
- Add simple CRUDHandlers to gate permissions to remaining endpoints
- Add get via parent handling to endpoints required by admin panel

1646 permissions integration

---

packages/meditrak-app/app/database/types/Response.js

- Fixes for bugs found when smoke test

1696: Upgrade react-native fixes

---

packages/psss-server/examples.http
packages/psss-server/src/app/addRoutesToApp.ts
packages/psss-server/src/routes/index.ts
packages/psss-server/src/routes/reports/ConfirmCountryWeeklyReportRoute.ts
packages/psss-server/src/routes/reports/FetchConfirmedCountryWeeklyReportRoute.ts
packages/psss-server/src/routes/reports/FetchConfirmedWeeklyReportRoute.ts
packages/psss-server/src/routes/reports/FetchCountryWeeklyReportRoute.ts
packages/psss-server/src/routes/reports/index.ts

Renamed psss-server endpoint handlers to be a bit more clear in their function

Renamed psss-server endpoint handlers

---

packages/meditrak-app/app/navigation/Navigator.js

- Disable transition animation in Welcome/Home screens

1696 Fix transition animation meditrak-app

---

packages/psss/src/api/queries/useSingleWeeklyReport.js
packages/psss/src/components/Table/CellComponents/PercentageChangeCell.js
packages/psss/src/store/auth.js

- Added percentage change value to country report table
---
See issue

1664 add percentage change value

---

packages/devops/scripts/deployment/checkoutLatest.sh
packages/devops/scripts/deployment/deployPackages.sh
packages/devops/scripts/deployment/startup.sh

Issue: https://github.com/beyondessential/tupaia-backlog/issues/1694

Check out latest code before deploying packages

---

packages/meditrak-app/README.md
packages/meditrak-app/ios/Podfile
packages/meditrak-app/ios/Podfile.lock
packages/meditrak-app/ios/TupaiaMediTrak.xcodeproj/project.pbxproj
packages/meditrak-app/ios/TupaiaMediTrak.xcodeproj/xcshareddata/xcschemes/TupaiaMediTrak.xcscheme
packages/meditrak-app/ios/TupaiaMediTrak/Base.lproj/LaunchScreen.xib
packages/meditrak-app/ios/TupaiaMediTrak/Info.plist
packages/meditrak-app/package.json

Get iOS app building
Mostly trial and error and looking up StackOverflow answers, so pretty hard to review!

1696 get app building on ios

---

packages/meditrak-app/app/api/TupaiaApi.js
packages/meditrak-app/app/assessment/specificQuestions/Instruction.js
packages/meditrak-app/app/home/HomeScreen.js
packages/meditrak-app/app/widgets/TupaiaHeaderLogo.js
packages/meditrak-app/app/widgets/index.js
packages/meditrak-server/src/routes/changePassword.js

- https://github.com/beyondessential/tupaia-backlog/issues/1779
- https://github.com/beyondessential/tupaia-backlog/issues/1696#issuecomment-742204885
- Aligned Tupaia Header Logo to the left in Home Screen
- Fixed an issue that users cannot change password using meditrak-app

1696: Meditrak app small fixes

---

packages/meditrak-app/app/assessment/DumbSurveyScreen.js
packages/meditrak-app/app/navigation/HeaderLeftButton.js
packages/meditrak-app/app/navigation/Navigator.js
packages/meditrak-app/app/sync/SyncPage.js

1696 fix ios x button

---

packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/routes/GETClinics.js
packages/meditrak-server/src/routes/GETCountries.js
packages/meditrak-server/src/routes/GETEntities.js
packages/meditrak-server/src/routes/GETGeographicalAreas.js
packages/meditrak-server/src/routes/index.js

- Add GETHandlers for /facilities /countries and /geographicalAreas
- Update GETHandler for /entities

Add endpoint permissions handlers for various get endpoints

---

packages/indicators/src/builders/buildArithmetic/buildArithmetic.ts
packages/indicators/src/builders/buildArithmetic/config/aggregation.ts
packages/indicators/src/builders/buildArithmetic/config/expand.ts
packages/indicators/src/builders/buildArithmetic/config/helpers.ts
packages/indicators/src/builders/buildArithmetic/config/index.ts
packages/indicators/src/builders/buildArithmetic/config/types.ts
packages/indicators/src/builders/buildArithmetic/config/validate.ts
packages/indicators/src/builders/buildArithmetic/index.ts

Towards https://github.com/beyondessential/tupaia-backlog/issues/1763, Part 1/3
This is a pure refactoring, mainly file restructuring and moving a few things around. I did this because I was planning to add new config-related functionality, but after https://github.com/beyondessential/tupaia-backlog/issues/1763#issuecomment-742864036 this will most probably not be needed (new functionality won't be in the config level). Still, I think the following refactoring is valuable

1763: Restructure arithmetic config utils (1/3)

---

packages/database/src/migrations/20201213223856-AddCanonicalTypesToSamoaCovid-modifies-data.js

- Add canonical types to covid_samoa project

Add canonical types to covid_samoa project

---

packages/database/src/migrations/20201213223856-AddCanonicalTypesToSamoaCovid-modifies-data.js
packages/database/src/migrations/20201214000845-ChangeDotMatrixViewSchema-modifies-data.js
packages/database/src/migrations/20201214000945-AddLegendsToUNFPAMatricies-modifies-data.js
packages/meditrak-app/app/assessment/specificQuestions/DateQuestion.js
packages/web-frontend/src/components/View/MatrixWrapper/components/FooterRow.js
packages/web-frontend/src/components/View/MatrixWrapper/components/Matrix.js
packages/web-frontend/src/components/View/MatrixWrapper/styles/getStyles.js
packages/web-frontend/src/components/View/propTypes.js
packages/web-frontend/src/utils/color.js
packages/web-frontend/stories/chart/matrix.stories.js

797-convert-covid-data-internal test

---

packages/meditrak-server/src/routes/exportSurveyResponses.js
packages/web-config-server/src/export/ExportSurveyResponsesHandler.js

* implement suggestion from review
- Example
---

implement suggestions from review (#1802)

---

packages/meditrak-server/src/dataAccessors/createUser.js

@Klaus-S found this issue while testing permissions - has existed for a long time!

Add default initial country as Demo Land when creating a user

---

packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/database/models/Option.js
packages/meditrak-server/src/database/models/OptionSet.js
packages/meditrak-server/src/database/models/Question.js
packages/meditrak-server/src/routes/index.js
packages/meditrak-server/src/routes/optionSets/DeleteOptionSets.js
packages/meditrak-server/src/routes/optionSets/EditOptionSets.js
packages/meditrak-server/src/routes/optionSets/GETOptionSets.js
packages/meditrak-server/src/routes/optionSets/assertOptionSetPermissions.js
packages/meditrak-server/src/routes/optionSets/index.js
packages/meditrak-server/src/routes/options/DeleteOptions.js
packages/meditrak-server/src/routes/options/EditOptions.js
packages/meditrak-server/src/routes/options/GETOptions.js
packages/meditrak-server/src/routes/options/assertOptionPermissions.js
packages/meditrak-server/src/routes/options/index.js
packages/meditrak-server/src/routes/questions/DeleteQuestions.js
packages/meditrak-server/src/routes/questions/EditQuestions.js
packages/meditrak-server/src/routes/questions/GETQuestions.js
packages/meditrak-server/src/routes/questions/assertQuestionPermissions.js
packages/meditrak-server/src/routes/questions/index.js
packages/meditrak-server/src/routes/surveys/assertSurveyPermissions.js
packages/meditrak-server/src/routes/surveys/index.js

- Added EditHandlers and DeleteHandlers for /questions /options /optionSets

1139: Permissions - Update/Delete Questions etc.

---

packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/routes/GETDashboardGroups/index.js
packages/meditrak-server/src/routes/dashboardGroups/DeleteDashboardGroups.js
packages/meditrak-server/src/routes/dashboardGroups/EditDashboardGroups.js
packages/meditrak-server/src/routes/dashboardGroups/GETDashboardGroups.js
packages/meditrak-server/src/routes/dashboardGroups/assertDashboardGroupsPermissions.js
packages/meditrak-server/src/routes/dashboardGroups/index.js
packages/meditrak-server/src/routes/dashboardReports/DeleteDashboardReports.js
packages/meditrak-server/src/routes/dashboardReports/EditDashboardReports.js
packages/meditrak-server/src/routes/dashboardReports/GETDashboardReports.js
packages/meditrak-server/src/routes/dashboardReports/assertDashboardReportsPermissions.js
packages/meditrak-server/src/routes/dashboardReports/index.js
packages/meditrak-server/src/routes/index.js
packages/meditrak-server/src/routes/mapOverlays/DeleteMapOverlays.js
packages/meditrak-server/src/routes/mapOverlays/EditMapOverlays.js
packages/meditrak-server/src/routes/mapOverlays/GETMapOverlays.js
packages/meditrak-server/src/routes/mapOverlays/assertMapOverlaysPermissions.js
packages/meditrak-server/src/routes/mapOverlays/index.js
packages/meditrak-server/src/routes/utilities/hasTupaiaAdminAccessToEntityForVisualisation.js
packages/meditrak-server/src/routes/utilities/index.js

- Added EditHandlers and DeleteHandlers for /dashboardGroups /dashboardReports and /mapOverlays

Add Edit and Delete routes for visualisation endpoints

---

packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/routes/GETProjects.js
packages/meditrak-server/src/routes/index.js

1140: Permissions - GET Projects

---

packages/database/src/migrations/20201216050328-AddCovidSamoaAgeByFlightMatrix-modifies-data.js
packages/database/src/utilities/index.js
packages/database/src/utilities/migration.js
packages/web-config-server/src/apiV1/dataBuilders/index.js
packages/web-config-server/src/apiV1/dataBuilders/modules/covid-samoa/flight/Flight.js
packages/web-config-server/src/apiV1/dataBuilders/modules/covid-samoa/flight/flightAgeRanges.js
packages/web-config-server/src/apiV1/dataBuilders/modules/covid-samoa/flight/index.js
packages/web-config-server/src/apiV1/dataBuilders/modules/covid-samoa/index.js
packages/web-config-server/src/apiV1/dataBuilders/modules/covid-samoa/valueAndPercentageByAgeByFlightDate.js
packages/web-config-server/src/export/excelFormatters/formatMatrixDataForExcel.js
packages/web-config-server/src/tests/apiV1/dataBuilders/modules/covid-samoa/flight/Flight.test.js
packages/web-config-server/src/tests/apiV1/dataBuilders/modules/covid-samoa/flight/flightAgeRanges.test.js
packages/web-frontend/src/components/View/MatrixWrapper/MatrixWrapper.js
packages/web-frontend/src/components/View/constants.js
packages/web-frontend/src/utils/formatters.js

- Add number and percentage formatter
- Allow matricies to have row and column value formatters
- Add Flight class for covid samoa
- Add valueAndPercentageByAgeByFlightDate for covid samoa
- Add Covid Samoa age by flight matrix
---
https://github.com/beyondessential/tupaia-backlog/issues/1437#issuecomment-757581610

1437 Covid Samoa age by flight matrix

---

packages/admin-panel/src/importExport/ImportModal.js

- connect ImportModal to redux store
- dispatch data change and success actions which trigger a refresh of the data fetching table after import success

Bug Fix: Admin Panel Imports

---

packages/web-frontend/src/constants/mapbox.js

- Add new thumbnail and map url as an option to tilesets
Note: the actual tileset does not show up on web front end unless the population key is added in admin panel
---

1214 laos eoc population tileset

---

packages/web-frontend/src/components/View/MatrixWrapper/MatrixWrapper.js

- Fix undefined error in matrix rendering

Fix undefined error in matrix rendering

---

packages/web-frontend/package.json
packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialog.js
packages/web-frontend/src/sagas.js
packages/web-frontend/src/utils/getBrowserTimeZone.js
packages/web-frontend/src/utils/index.js

- This reverts commit 7b40781b856d841e3597c87f4778b61ad1ec8c81.

Revert "1798: Use @tupaia/utils in web-frontend (#1899)"

---

packages/database/src/migrations/20210118040638-AddFetpProject-modifies-data.js

Migration to add Project and dashbaord groups for FEPT

AddFetpProject

---

packages/database/src/migrations/20201123014943-IntegrateInconsistentAnswersForHotelNames-modifies-data.js

[1444: Dashboard: Quarantine sites by flight (COVID-19)](https://github.com/beyondessential/tupaia-backlog/issues/1444)
Reassign correct hotel names to the quarantine site names of inconsistent answers

Assign correct hotel names to make them consistent

---

packages/meditrak-server/src/routes/surveyScreenComponents/EditSurveyScreenComponents.js

- Really just copy pasted the old code into the new handler. Double checked the permissions between questions and surveyScreenComponents and anyone who has access to edit the ssc would also have access to edit the attached question, so I did not add any further checks.

Port old surveyScreenComponent edit handling to new system

---

packages/meditrak-app/ios/TupaiaMediTrak/Info.plist
packages/meditrak-app/package.json

Bump version to 1.9.110

---

packages/psss/src/components/EditableTable.js
packages/psss/src/containers/Panels/WeeklyReportsPanel.js
packages/psss/src/containers/Tables/CountryReportTable.js
packages/ui-components/src/components/LoadingContainer.js
packages/ui-components/src/components/Table/TableMessageProvider.js
packages/ui-components/stories/tables/table.stories.js

- Add alerts to table component and table loading component
- Display table errors in psss
---
See issue

1413 psss handle table error state

---

packages/database/src/migrations/20210125010541-ResyncDelayedSubmissionsAfterRelease70-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/885
https://github.com/beyondessential/tupaia-backlog/issues/2143

885-2143: Hotfix missing HP05 and SCRF data

---

packages/database/src/migrations/20210125033426-MigrateFijiSurveyDataElementsFromDHISToTupaia-modifies-data.js

- Migrate fiji data elements to internal

Migrate fiji data elements to internal

---

packages/web-frontend/src/sagas.js

Original issue: https://github.com/beyondessential/tupaia-backlog/issues/1789
- Remove permission check on dashboard fetch
---

remove permission check from dashboard fetch

---

packages/database/src/migrations/20210125051145-AddGeneralDashboardToPalau-modifies-data.js
packages/web-config-server/src/authSession/publicAccess.js

Added 1 new dashboard report and made the Palau entity publicly accessible.

2127 make Palau public and add dashboard group

---

packages/meditrak-server/src/app/addRoutesToApp.js
packages/meditrak-server/src/routes/GETClinics.js
packages/meditrak-server/src/routes/GETCountries.js
packages/meditrak-server/src/routes/GETDataSources.js
packages/meditrak-server/src/routes/GETDisasters.js
packages/meditrak-server/src/routes/GETEntities.js
packages/meditrak-server/src/routes/GETGeographicalAreas.js
packages/meditrak-server/src/routes/GETHandler/GETHandler.js
packages/meditrak-server/src/routes/GETProjects.js
packages/meditrak-server/src/routes/GETSurveyGroups/GETSurveyGroups.js
packages/meditrak-server/src/routes/accessRequests/GETAccessRequests.js
packages/meditrak-server/src/routes/answers/GETAnswers.js
packages/meditrak-server/src/routes/dashboardGroups/GETDashboardGroups.js
packages/meditrak-server/src/routes/dashboardReports/GETDashboardReports.js
packages/meditrak-server/src/routes/editUser.js
packages/meditrak-server/src/routes/getUser.js
packages/meditrak-server/src/routes/index.js
packages/meditrak-server/src/routes/mapOverlays/GETMapOverlays.js
packages/meditrak-server/src/routes/options/GETOptions.js
packages/meditrak-server/src/routes/surveyResponses/GETSurveyResponses.js
packages/meditrak-server/src/routes/surveyScreenComponents/GETSurveyScreenComponents.js
packages/meditrak-server/src/routes/surveys/GETSurveys.js
packages/meditrak-server/src/routes/userAccounts/GETUserAccounts.js
packages/meditrak-server/src/routes/userEntityPermissions/GETUserEntityPermissions.js

- Restructure GETHandlers so SQL filtering applies to both the record fetching and the record count
- Fixup /me endpoints to work with CRUDHandlers
- Allow BES admin to edit projects
- Change default join type for access requests

Permissions bugfixes 1647

---

packages/database/src/migrations/20210107004358-AddSwapColorForLegendInLaoSchool-modifies-data.js
packages/web-frontend/src/components/Marker/index.js
packages/web-frontend/src/components/Marker/markerColors.js
packages/web-frontend/src/constants/constants.js
packages/web-frontend/src/tests/components/Marker/markerColors.test.js

1419-swap-colours-in-legend-laos-schools
- Example
---

1419 swap colours in legend laos schools (#1868)

---

packages/meditrak-server/src/routes/importStriveLabResults/surveys.json

I've also double checked to make sure these are the questions that are currently in the system for these surveys.

Add new surveys to strive importer

---

packages/database/src/migrations/20210125061447-AddK13PCRResultsBarGraph-modifies-data.js
packages/meditrak-server/src/routes/importStriveLabResults/surveys.json

Original PR: https://github.com/beyondessential/tupaia/pull/1967

Change branch name

---

packages/database/src/migrations/20210129022440-AddFacilityTypeOverlayForFiji-modifies-data.js
packages/database/src/migrations/20210201230429-MoveServiceTypeOverlayGroupToTheTop-modifies-data.js
packages/web-config-server/src/apiV1/measureBuilders/valueForOrgGroup.js
packages/web-config-server/src/apiV1/utils/findAccessibleGroupedMapOverlays.js

- Added operational facilities overlay for Fiji
- Moved Services Provided group to the top to make the new `Operational Facilities` the default overlay when hitting Fiji

2176: Added operational facilities overlay for Fiji

---

packages/database/src/migrations/20210126013657-AddK13C580YPositiveMapOverlay-modifies-data.js

Addresses: https://github.com/beyondessential/tupaia-backlog/issues/1404
New branch / PR because the old one had a capital in the name and was failing tests
Old PR here: https://github.com/beyondessential/tupaia/pull/1968

1404 strive lab overlay

---

packages/database/src/migrations/20210126013657-AddK13C580YPositiveMapOverlay-modifies-data.js
packages/database/src/migrations/20210129022440-AddFacilityTypeOverlayForFiji-modifies-data.js
packages/database/src/migrations/20210201230429-MoveServiceTypeOverlayGroupToTheTop-modifies-data.js
packages/web-config-server/src/apiV1/measureBuilders/valueForOrgGroup.js
packages/web-config-server/src/apiV1/utils/findAccessibleGroupedMapOverlays.js

kstst-2198-2196

---

packages/aggregator/src/analytics/aggregateAnalytics/aggregations/entityAggregations.js
packages/aggregator/src/analytics/aggregateAnalytics/aggregations/getFinalValuePerPeriod.js
packages/database/src/migrations/20210124055714-ConvertDhisSurveysIntoTupaia-modifies-data.js
packages/database/src/migrations/20210124063304-ConvertSurveyRawDataDownloadToCustomDataDownload-modifies-data.js
packages/database/src/migrations/20210124073946-FixUNFPAPercentagesOfFacilitiesOfferingServicesReports-modifies-data.js
packages/web-config-server/src/apiV1/dataBuilders/generic/comparison/index.js
packages/web-config-server/src/apiV1/dataBuilders/generic/comparison/valuesPerPeriodByOrgUnit.js
packages/web-config-server/src/apiV1/dataBuilders/generic/percentage/percentagesPerPeriod.js
packages/web-config-server/src/apiV1/dataBuilders/generic/sum/sumPerSeries.js
packages/web-config-server/src/export/ExportSurveyDataHandler.js

- Added Custom Export for UNFPA
- Convert UNFPA surveys from dhis to tupaia
- Fixed up a few incorrect vizes

1322: Added Custom Export for UNFPA

---

packages/database/src/migrations/20210201051217-SyncLaosEocEntitiesWithLaosSchools-modifies-data.js

- Fix lat/lon of a city
- Copy districts and sub_districts from laos_schools
---

1526 import org units

---

packages/database/package.json
packages/database/src/TupaiaDatabase.js
packages/database/src/modelClasses/Entity.js
packages/database/src/utilities/runDatabaseFunctionInBatches.js
yarn.lock

- Increase the max batch size after testing that 14000 Laos schools have no problems
---

Use a bigger batch size for fetching ancestors

---

packages/database/src/migrations/20210205000427-AddLaosEocPocDashboard-modifies-data.js
packages/dhis-api/src/authenticateWithDhis.js
packages/utils/src/dhis.js
packages/web-config-server/src/apiV1/dataBuilders/generic/count/countEventsPerPeriodByDataValue2.js
packages/web-config-server/src/apiV1/dataBuilders/generic/count/index.js

- Add network config to be able to connect to Laos DHIS
- Add code to id mappings needed for this dashboard
- Create new data builder
- Add dashboard
---
```
LAO-PEOPLES-DEMOCRATIC-REPUBLIC_DHIS_CLIENT_ID=
LAO-PEOPLES-DEMOCRATIC-REPUBLIC_DHIS_CLIENT_SECRET=
LAO-PEOPLES-DEMOCRATIC-REPUBLIC_DHIS_USERNAME=
LAO-PEOPLES-DEMOCRATIC-REPUBLIC_DHIS_PASSWORD=
LAO-PEOPLES-DEMOCRATIC-REPUBLIC_DHIS_API_URL=https://dhis2.world/laohmis
LAO-PEOPLES-DEMOCRATIC-REPUBLIC_DHIS_AUTH_TOKEN_HOST=https://dhis2.world/
LAO-PEOPLES-DEMOCRATIC-REPUBLIC_DHIS_AUTH_TOKEN_PATH=/laohmis/uaa/oauth/token
```
// fill out missing from lastpass

Laos EOC proof of concept dashboard

---

packages/database/src/TupaiaDatabase.js

See comment https://github.com/beyondessential/tupaia-backlog/issues/545#issuecomment-775485193

545 Validate against sql injection in comparisonType

---

packages/database/src/migrations/20210125025423-ChangePermissionInSamoaToCovid19Senior-modifies-data.js

[2168 - Review 'COVID19 Senior' permissions on closed cards](https://github.com/beyondessential/tupaia-backlog/issues/2168)
- Migration

2168 Review 'COVID19 Senior' permissions on closed cards

---

packages/database/src/migrations/20210127064624-MedicalCertificateLegendColorChange-modifies-data.js
packages/web-config-server/src/apiV1/dataBuilders/generic/sum/sumPerMetric.js

[1468 - CD Medical Certificate: Legend colour change](https://github.com/beyondessential/tupaia-backlog/issues/1468)
- Migration 
- For grouping by options in bar chart, add new config `valueKeyToOption` to assign return value to an option key. 
e.g.: `[{value: 24, dataElementCode: 'CD77'}] `to `[{Visa: 24, dataElementCode: 'CD77'}]`

1468 legend colour change

---

packages/database/src/TupaiaDatabase.js
packages/database/src/migrations/20210125025423-ChangePermissionInSamoaToCovid19Senior-modifies-data.js
packages/database/src/migrations/20210125042225-SamoaCovidSurveyHierarchyUpdate-modifies-data.js
packages/database/src/migrations/20210126234710-HeatmapHomeVillageOfQuarantinePassengers-modifies-data.js
packages/database/src/migrations/20210127064624-MedicalCertificateLegendColorChange-modifies-data.js
packages/web-config-server/src/apiV1/dataBuilders/generic/sum/sumPerMetric.js

2165-support-binary-labels test

---

packages/meditrak-server/src/routes/importSurveyResponses/importSurveyResponses.js

1149 survey response import uses data time

---

packages/data-broker/src/__tests__/services/dhis/DhisInputSchemeResolvingApiProxy.test.js
packages/data-broker/src/services/dhis/DhisInputSchemeResolvingApiProxy.js

- Remove special handling code for missing data elements now that all data elements must be registered in tupaia

[needs rebase once other card merged] Cleanup: remove special handling of missing data elements

---

packages/database/src/migrations/20210211041322-AddSubFacilityEntityType-modifies-schema.js
packages/database/src/modelClasses/Entity.js

- Add sub_facility entity type

2226: Add sub_facility entity type

---

packages/database/src/testUtilities/buildAndInsertSurveys.js
packages/meditrak-server/src/routes/GETHandler/helpers.js
packages/meditrak-server/src/routes/answers/GETAnswers.js
packages/meditrak-server/src/routes/answers/assertAnswerPermissions.js

- Add joins when requesting answers via survey requests
- Sort answers by screen number and component number

Fixup sorting answers when requesting via survey response

---

packages/database/src/migrations/20210212033659-AddMissingLaosGeographicalAreas-modifies-data.js
packages/database/src/migrations/20210215023211-FixLaosEntityHierarchy-modifies-data.js
packages/meditrak-server/src/routes/importEntities/getOrCreateParentEntity.js

- Add migration to clean up geographical_area for laos
- Entity importer can now import facilities at all levels
- Fix entity hierarchy for laos_eoc

2239 add geo data for laos

---

packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/TableConfig.js
packages/web-config-server/src/tests/apiV1/dataBuilders/generic/comparison/actualMonthlyValuesVsIdeal.test.js
packages/web-config-server/src/tests/apiV1/dataBuilders/generic/percentage/percentagesByNominatedPairs.test.js
packages/web-frontend/cypress/e2e/dashboardReports.spec.js
packages/web-frontend/cypress/scripts/generateDashboardReportConfig.js
packages/web-frontend/cypress/support/utils.js

https://github.com/beyondessential/tupaia-backlog/issues/1536

1536: Make e2e test snapshots more robust

---

packages/database/src/modelClasses/Entity.js

Add tracked entity type comment

---

packages/database/src/modelClasses/Entity.js

Meging dev into feature branch

Meging dev into feature branch

---

packages/lesmis/package.json
yarn.lock

Fix the dev psss app crashing due to different react and material ui versions

set lesmis package versions to the same as psss

---

packages/indicators/src/AnalyticsRepository.ts
packages/indicators/src/Builder/ArithmeticBuilder/ArithmeticBuilder.ts
packages/indicators/src/Builder/ArithmeticBuilder/config/aggregation.ts
packages/indicators/src/Builder/Builder.ts
packages/indicators/src/Builder/utils.ts
packages/indicators/src/IndicatorApi.ts
packages/indicators/src/__tests__/Builder/ArithmeticBuilder/ArithmeticBuilder.test.ts
packages/indicators/src/__tests__/Builder/ArithmeticBuilder/testGetAggregationListsByElement.ts
packages/indicators/src/getAggregationListsForAnalyticsFetch.ts
packages/indicators/src/mergeAggregationListsMaps.ts
packages/indicators/src/types.ts

https://github.com/beyondessential/tupaia-backlog/issues/1799
This PR addresses all comments in 
https://github.com/beyondessential/tupaia/pull/2071#pullrequestreview-591625439. Hopefully this makes changes a bit easier to review, if not feel free to merge straight into the base branch and review there!

1799: Simplify indicator aggregation handling

---

packages/data-broker/src/__tests__/services/dhis/DhisService/testPull/testPullAnalytics.js
packages/data-broker/src/services/dhis/DhisService.js

- Fix pullAnalyticsFromEventsForApi not passing org unit code

Fix pullAnalyticsFromEventsForApi not passing org unit code

---

packages/data-broker/src/services/dhis/getDhisApiInstance.js
packages/dhis-api/src/DhisApi.js
packages/meditrak-server/src/dhis/getDhisApiInstance.js
packages/utils/src/dhis.js
packages/web-config-server/src/dhis/getDhisApiInstance.js

- Throw error in dhis api if we attempt to push data for laos dhis.

2343: Prevent dhisApi from pushing changes to Laos DHIS2 server

---

packages/admin-panel/src/pages/resources/EntitiesPage.js
packages/meditrak-server/src/routes/importEntities/importEntities.js
packages/meditrak-server/src/routes/importEntities/updateCountryEntities.js

- Added option disable push entity to dhis2 server when importing new entities in Admin Panel
https://github.com/beyondessential/tupaia-backlog/issues/2301#issuecomment-786368352

2301: Added option disable push entity to dhis2 when importing new entities in Admin Panel

---

README.md

hotfix add space to make a new build

---

README.md
packages/database/src/migrations/20201203010928-StockStatusForNonMsupplyContriesInFacilityLevel-modifies-data.js
packages/database/src/utilities/migration.js
packages/meditrak-app/README.md
packages/web-config-server/package.json
packages/web-config-server/src/apiV1/dataBuilders/constants.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/TableOfDataValuesWithCalc.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers/addSummaryToTable.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers/buildBaseRowsForOrgUnit.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers/getValuesByCell.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfCalculatedValues.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfDataValues.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfPercentagesOfValueCounts.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfValuesForOrgUnits.js
packages/web-config-server/src/apiV1/dataBuilders/helpers/calculateOperationForAnalytics.js
yarn.lock

2304-pg-public-sb-dbgstest

---

README.md
packages/database/src/migrations/20201203010928-StockStatusForNonMsupplyContriesInFacilityLevel-modifies-data.js
packages/database/src/utilities/migration.js
packages/meditrak-app/README.md
packages/meditrak-server/package.json
packages/meditrak-server/src/routes/exportSurveyResponses/exportSurveyResponses.js
packages/web-config-server/package.json
packages/web-config-server/src/apiV1/dataBuilders/constants.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/TableOfDataValuesWithCalc.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers/addSummaryToTable.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers/buildBaseRowsForOrgUnit.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers/getValuesByCell.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfCalculatedValues.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfDataValues.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfPercentagesOfValueCounts.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfValuesForOrgUnits.js
packages/web-config-server/src/apiV1/dataBuilders/helpers/calculateOperationForAnalytics.js
yarn.lock

2353-flip-legend-color-fetptest

---

packages/indicators/src/Builder/AnalyticArithmeticBuilder/AnalyticArithmeticBuilder.ts
packages/indicators/src/Builder/AnalyticArithmeticBuilder/config/aggregation.ts
packages/indicators/src/Builder/AnalyticArithmeticBuilder/config/validate.ts
packages/indicators/src/Builder/Builder.ts
packages/indicators/src/Builder/EventCheckConditionsBuilder/EventCheckConditionsBuilder.ts
packages/indicators/src/Builder/EventCheckConditionsBuilder/config/validate.ts
packages/indicators/src/Builder/builders.ts
packages/indicators/src/Builder/helpers.ts
packages/indicators/src/IndicatorApi.ts
packages/indicators/src/__tests__/__integration/fixtures/analyticArithmeticFixtures.ts
packages/indicators/src/__tests__/__integration/fixtures/eventCheckConditionsFixtures.ts
packages/indicators/src/__tests__/__integration/integration.test.ts
packages/indicators/src/types.ts

* https://github.com/beyondessential/tupaia-backlog/issues/1378
* https://github.com/beyondessential/tupaia-backlog/issues/1799
* Applied the style decisions from our discussion with @rohan-bes on https://github.com/beyondessential/tupaia-backlog/issues/1710#issuecomment-789284956
* * Fixed some linting issues

1799: Use updated TS style guide

---

README.md
packages/database/src/migrations/20201203010928-StockStatusForNonMsupplyContriesInFacilityLevel-modifies-data.js
packages/database/src/migrations/20210225033329-RemoveLaosOxygenConcentratorsProject-modifies-data.js
packages/database/src/utilities/migration.js
packages/meditrak-app/README.md
packages/meditrak-server/package.json
packages/meditrak-server/src/routes/exportSurveyResponses/exportSurveyResponses.js
packages/web-config-server/package.json
packages/web-config-server/src/apiV1/dataBuilders/constants.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/TableOfDataValuesWithCalc.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers/addSummaryToTable.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers/buildBaseRowsForOrgUnit.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers/getValuesByCell.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfCalculatedValues.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfDataValues.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfPercentagesOfValueCounts.js
packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfValuesForOrgUnits.js
packages/web-config-server/src/apiV1/dataBuilders/helpers/calculateOperationForAnalytics.js
yarn.lock

2328-welcome-screen-tagline test

---

README.md
packages/database/src/migrations/20210225033329-RemoveLaosOxygenConcentratorsProject-modifies-data.js
packages/meditrak-app/README.md
packages/meditrak-server/package.json
packages/meditrak-server/src/routes/exportSurveyResponses/exportSurveyResponses.js

2088-download-testpng-fetp

---

packages/database/src/migrations/20210211051517-RenameArithmeticIndicators-modifies-data.js

- Renamed arithmetic param builders

1378: Renamed arithmetic param builders

---

packages/database/src/migrations/20210301123426-AddFetpDashboardsToSolomonIs-modifies-data.js
packages/database/src/migrations/20210303020040-removeStriveMapOverlaysFromExplore-modifies-data.js
packages/web-config-server/src/apiV1/organisationUnit.js
packages/web-config-server/src/apiV1/projects.js
packages/web-config-server/src/authSession/publicAccess.js
packages/web-config-server/src/models/Entity.js
packages/web-config-server/src/tests/geoJson.test.js
packages/web-config-server/src/utils/geoJson.js
packages/web-frontend/src/containers/Dashboard/index.js
packages/web-frontend/src/projects/sagas.js
packages/web-frontend/src/reducers/mapReducers.js
packages/web-frontend/src/selectors/index.js
packages/web-frontend/src/selectors/orgUnitSelectors.js
packages/web-frontend/src/selectors/projectSelectors.js
packages/web-frontend/src/tests/selectors/projectSelectors.test.js

Comparing dev into feature branch

Comparing dev into feature branch

---

packages/web-frontend/public/index.html
packages/web-frontend/src/containers/OverlayDiv/components/LandingPage/index.js
packages/web-frontend/src/containers/OverlayDiv/components/ProjectLandingPage/index.js
packages/web-frontend/src/containers/OverlayDiv/components/RequestProjectAccessDialog.js

- Changed Tupaia Welcome screens (login, project landing, project request) tag line:
"Data aggregation, analysis, and visualisation for the most remote settings in the world"

New welcome screen tagline

---

packages/meditrak-app/ios/TupaiaMediTrak/Info.plist
packages/meditrak-app/package.json

- Bump meditrak-app version to 1.10.111

Bump meditrak-app version to 1.10.111

---

packages/database/src/tests/testData/testDataDump.sql

Update test data dump

---

packages/web-config-server/src/apiV1/dataBuilders/generic/compose/composeData.js

Hot fix laos dashboards crash

---

.eslintrc
packages/web-frontend/cypress.json
packages/web-frontend/cypress/e2e/dashboardReports.spec.js

https://github.com/beyondessential/tupaia-backlog/issues/1537

1537: e2e tests should throw for empty reports

---

codeship-steps.yml
full-testable-package.Dockerfile
packages/devops/scripts/ci/validateBranchName.sh
packages/lesmis-server/src/__tests__/example.test.ts

- add codeship step
- add test stub
---

add code ship step and test stub

---

packages/lesmis-server/src/index.ts

- Current lesmis server port 8040 is duplicated with psss-server port

Change lesmis port

---

packages/database/src/migrations/20210311002222-AddDefaultValueForDailyCasesInPSSSWeeklyIndicators-modifies-data.js

- Added default values for daily cases data

2444: Added default values for daily cases data

---

packages/ui-components/src/components/Map/TileLayer.js
packages/ui-components/src/components/Map/TilePicker/TileButton.js
packages/ui-components/src/components/Map/TilePicker/TileControl.js
packages/ui-components/src/components/Map/TilePicker/TilePicker.js
packages/ui-components/src/components/Map/TilePicker/constants.js
packages/ui-components/src/components/Map/TilePicker/index.js
packages/ui-components/src/components/Map/TilePicker/keyFrames.js
packages/ui-components/stories/map/tilePicker.stories.js

- add Tile Picker component
Note: the TilePicker Component is pretty much copy and pasted from web front end with some name changes.
---

2153-map-overlay-components-part-2

---

packages/database/src/migrations/20210309020032-MalariaMapOverlaysLaosEOC-modifies-data.js
packages/database/src/migrations/20210309230008-MalariaDataSourceLaosEOC-modifies-data.js
packages/database/src/utilities/migration.js

[2369 - Malaria Cases by Sub District](https://github.com/beyondessential/tupaia-backlog/issues/2369)
[2371 - Malaria Deaths by Sub District](https://github.com/beyondessential/tupaia-backlog/issues/2371)
[2370 - Malaria Cases by Facility](https://github.com/beyondessential/tupaia-backlog/issues/2370)
[2372 - Malaria Deaths by Facility](https://github.com/beyondessential/tupaia-backlog/issues/2372)

Malaria map overlay

---

packages/database/src/migrations/20210310053755-DengueMapOverlaysLaosEOC-modifies-data.js
packages/database/src/migrations/20210310053808-DengueDataSourceLaosEOC-modifies-data.js

[2381: Dengue Deaths by Sub-District](https://github.com/beyondessential/tupaia-backlog/issues/2381)
[2382: Dengue Deaths by Facility](https://github.com/beyondessential/tupaia-backlog/issues/2382)
[2383: Dengue Cases by Sub-District](https://github.com/beyondessential/tupaia-backlog/issues/2383)
[2380: Dengue Cases by Facility](https://github.com/beyondessential/tupaia-backlog/issues/2380)
[2368: Dengue Cases: severe v other](https://github.com/beyondessential/tupaia-backlog/issues/2368)

Dengue map overlays

---

packages/data-broker/src/services/dhis/DhisInputSchemeResolvingApiProxy.js

See comment https://github.com/beyondessential/tupaia-backlog/issues/1718#issuecomment-797235161

Hotfix read property of undefined

---

packages/database/src/migrations/20210315001552-AddDataSourceMeaslesDeathCasesLaosEOC-modifies-data.js
packages/database/src/migrations/20210315001650-AddMapOverlayMeaslesDeathCasesLaosEOC-modifies-data.js

@IgorNadj  - new PR with shortened branch name
see: https://github.com/beyondessential/tupaia/pull/2227#issuecomment-798995749
[2376 - Measles Cases by Sub District](https://github.com/beyondessential/tupaia-backlog/issues/2376)
[2375 - Measles Deaths by Sub District](https://github.com/beyondessential/tupaia-backlog/issues/2375)
[2373 - Measles Cases by Facility](https://github.com/beyondessential/tupaia-backlog/issues/2373)
[2374 - Measles Deaths by Facility](https://github.com/beyondessential/tupaia-backlog/issues/2374)
Also see - [2366 ](https://github.com/beyondessential/tupaia-backlog/issues/2366)for related Malaria Group Overlay work 
---

2375  measles overlays shorter branch name

---

packages/dhis-api/src/buildAnalyticsQuery.js

Hotfix for https://github.com/beyondessential/tupaia-backlog/issues/1718#issuecomment-799025309

hotfix - Fix dhis query without dx

---

packages/database/src/migrations/20210312113926-AddLaosEOCMalariaStockAvailabilityByFacilityOverlay-modifies-data.js
packages/database/src/migrations/20210312214059-UpdateLaosSchoolsFunctioningTVSateliteOverlayConfig-modifies-data.js
packages/web-config-server/src/apiV1/measureBuilders/checkMultiConditionsByOrgUnit.js

- Added Malaria stock availability overlays

2378: Malaria stock availability overlay

---

packages/database/src/migrations/20210314024746-AddLaosEOCMalariaCriticalItemAvailabilityOverTimeDashboard-modifies-data.js
packages/database/src/migrations/20210314054551-AddLaosEOCMalariaCriticalItemAvailabilitySingleViewDashboard-modifies-data.js
packages/web-config-server/src/apiV1/dataBuilders/generic/percentage/percentagesOfValueCounts.js
packages/web-config-server/src/apiV1/dataBuilders/helpers/index.js
packages/web-config-server/src/apiV1/dataBuilders/helpers/multiplyValues.js

- Added Malaria Critical Item Availability dashboards

2367: Added Malaria Critical Item Availability dashboards

---

packages/database/src/migrations/20210316013933-DeleteFijiEntities-modifies-data.js

Addresses: https://github.com/beyondessential/tupaia-backlog/issues/2484

2484 hotfix delete fiji entities

---

packages/data-broker/src/services/dhis/DhisInputSchemeResolvingApiProxy.js

Hotfix bind params too long [direct apply to feature branch]

---

packages/data-broker/src/services/dhis/DhisInputSchemeResolvingApiProxy.js

Hotfix bind params too long

---

packages/data-broker/src/services/dhis/DhisInputSchemeResolvingApiProxy.js

Merge master into dev after hotfix #2252

Merge master into dev after hotfix 

---

packages/database/src/migrations/20210317015957-HideNoDataInBubbleMapLaoEoc-modifies-data.js

- change map overlays config `hideByDefault: {'0, null': true}` to `hideByDefault: {'null': true}`

hide no data in bubble map

---

packages/web-config-server/src/apiV1/utils/fetchIndicatorValues/fetchAggregatedAnalyticsByDhisIds.js

2361: fixed broken dashboard

---

packages/database/src/migrations/20210317053313-UpdateLaosEOCMalariaStockAvailabilityByFacilityOverlay-modifies-data.js
packages/database/src/migrations/20210317054627-AddDateSelectorForMeaslesVaccineStockAvailabilityByFacilityOverlay-modifies-data.js

Fixed some overlay issues in laos eoc

Fixed some overlay issues in laos eoc

---

packages/admin-panel/src/importExport/ImportModal.js

- Clear file name after canceling the import modal

Hotfix: Import Modal Regression

---

packages/database/src/migrations/20210323045613-LaosEocRemoveUnpermittedFacilities-modifies-data.js

- migration to remove Laos EOC facilities without access permission

Remove unpermitted Laos Eoc Facilities

---

packages/database/src/migrations/20210323045613-LaosEocRemoveUnpermittedFacilities-modifies-data.js

branched from master for  #2278

[Hotfix]remove unpermitted Laos Eoc Facilities

---

packages/admin-panel/src/importExport/ImportModal.js
packages/database/src/migrations/20210323045613-LaosEocRemoveUnpermittedFacilities-modifies-data.js

Hotfix: Merge master to dev

---

packages/admin-panel/src/editor/Editor.js
packages/admin-panel/src/pages/resources/SurveyResponsesPage.js
packages/admin-panel/src/widgets/InputField.js

- Pass a format through to the datetime-utc widget for parsing
- Revert previous change to date of data formatting on survey responses page

1149 widget parse formatted utc

---

packages/data-broker/src/services/dhis/DhisTranslator.js
packages/devops/scripts/ci/pullLatest.sh
packages/devops/scripts/deployment/checkoutLatest.sh
packages/meditrak-server/src/dhis/pushLatest.js
packages/web-frontend/cypress/e2eTests.md
tupaia-packages.code-workspace

Changes as per the commit history

Minor fixes

---

packages/database/src/migrations/20210324041508-AddSupplyChainFijiProject-modifies-data.js

Add Supply Chain Fiji Project

---

packages/database/src/migrations/20210324075314-AddEhealthNauruProject-modifies-data.js

Add eHealth Nauru Project

---

packages/database/src/migrations/20210325001804-AddCovidVaccineTrackingDashboardGroups-modifies-data.js

- migration to add dashboardGroups for covid vaccine tracking epic visuals.

Add covid vaccine tracking dashboard groups

---

packages/database/src/migrations/20210325014751-ChangeSupplyChainProjectBackgroundImage-modifies-data.js

- image changed from png to new jpg, doing as migration to merge with feature branch and avoid reupdating via admin panel serveral times.

Update sc fiji bgimage

---

packages/database/src/migrations/20210325030144-VaccineDoseTakenByDayVaccineTracking-modifies-data.js

[Number of people received 1st dose of COVID-19 vaccine by day #2559](https://github.com/beyondessential/tupaia-backlog/issues/2559)
[Number of people received 2nd dose of COVID-19 vaccine by day#2560
](https://github.com/beyondessential/tupaia-backlog/issues/2560)

vaccine dose taken by day

---

packages/database/src/migrations/20210326034445-AddCovidVaccineOverlays-modifies-data.js

- [2557](https://github.com/beyondessential/tupaia-backlog/issues/2557)
- [2558](https://github.com/beyondessential/tupaia-backlog/issues/2558)
https://github.com/beyondessential/tupaia-backlog/issues/2557#issuecomment-807954402

2557 Add map overlays for covid vaccine tracking

---

packages/database/src/migrations/20210329022054-AddCovidVaxTrackingVillageDose1-modifies-data.js

Connected ticket 2562 
Very* similar to [2563](https://github.com/beyondessential/tupaia/pull/2307)
- Added heatmap overlay 'Home village of people received 1st dose of COVID-19 vaccine'
---

2562 covid vac home vil d1

---

packages/database/src/migrations/20210329031216-ChangeScaleTypeOfMapOverlays-modifies-data.js
packages/web-frontend/src/utils/measures.js

https://github.com/beyondessential/tupaia-backlog/issues/2586#issuecomment-809061735

2586 no data change to grey

---

packages/database/src/migrations/20210329224807-AddCovidVaccineTotalDashboards-modifies-data.js

2557 covid vaccine total dashboards

---

packages/admin-panel/src/importExport/ImportModal.js

- Pass the extra query parameters (which contain the users timezone) into the upload function

Actually pass extra query parameters into upload function

---

packages/web-config-server/run_preaggregation.sh

https://github.com/beyondessential/tupaia-backlog/issues/2634

Use correct node version during preaggregation

---

packages/psss-server/src/connections/MeditrakConnection.ts

- Missed this because I only searched `*.js` files for references to `submission_time`
- This appears to be the last remaining reference to `submission_time`

Update PSSS to use data_time

---

packages/admin-panel/src/pages/resources/PermissionGroupsPage.js
packages/database/src/migrations/20210409060829-AddPsssTupaiaPermission-modifies-data.js
packages/database/src/migrations/20210409063837-AddPsssNumOfSentinelSitesDashboard-modifies-data.js
packages/web-config-server/src/apiV1/dataBuilders/generic/latestData/index.js
packages/web-config-server/src/apiV1/dataBuilders/generic/latestData/latestDataValue.js

- Minor: sort permission groups by name (Admin Panel)
- Add latestDataValue data builder
- Add PSSS Tupaia permission group
- Add num sentinel sites dashboard
https://github.com/beyondessential/tupaia-backlog/issues/1642#issuecomment-817406499

1642 psss vis num sentinel sites

---

packages/database/src/migrations/20210413001758-AddPsssVisCountryLevelDashboard2y-modifies-data.js
packages/web-frontend/src/components/View/ChartWrapper/CartesianChart.js

- Add PsssVisCountryLevelDashboard2y migration
- Limit percentage chart to 100%
---
https://github.com/beyondessential/tupaia-backlog/issues/1641#issuecomment-818342080

1641 psss vis country level dashboard 2y

---

packages/database/src/migrations/20210413043020-AddPsssCountryTrendDashboards-modifies-data.js

- Add PsssCountryTrendDashboards
---
https://github.com/beyondessential/tupaia-backlog/issues/1638#issuecomment-818443808

Add PsssCountryTrendDashboards

---

packages/database/src/migrations/20210413001758-AddPsssVisCountryLevelDashboard2y-modifies-data.js
packages/database/src/migrations/20210413043020-AddPsssCountryTrendDashboards-modifies-data.js

[2661: ISO Weeks support for dashboard reports](https://github.com/beyondessential/tupaia-backlog/issues/2661)
- We do support x Axis formatting in chart :)

support iso week

---

packages/ui-components/rollup.config.js

Fix wrong case in ui-components/rollup.config.js

fix-ui-components-rollup-typo

---

packages/database/src/migrations/20210415110921-UpdatePSSSWeeklyIndicatorsSupportSiteData-modifies-data.js

Added support for site level derived data in Total Cases indicators for PSSS

1337: Site level derived data in Total Cases indicators for PSSS

---

packages/database/src/migrations/20210414064857-DailyCasesTrendGraphPalau-modifies-data.js
packages/database/src/migrations/20210414064857-DailyCasesTrendGraphPalauCountryLevel-modifies-data.js
packages/database/src/migrations/20210416052750-DailyCasesTrendGrahphPalauFacilityLevel-modifies-data.js

[#2104](https://github.com/beyondessential/tupaia-backlog/issues/2104)
[#2105](https://github.com/beyondessential/tupaia-backlog/issues/2105)

daily case trend graph palau

---

packages/database/src/migrations/20210412055533-LaosEocEntitycleanUp-modifies-data.js

fix broken migration

---

packages/psss-server/examples.http
packages/psss-server/src/app/addRoutesToApp.ts
packages/psss-server/src/connections/EntityConnection.ts
packages/psss-server/src/routes/country/FetchCountries.ts
packages/psss-server/src/routes/country/FetchCountrySites.ts
packages/psss-server/src/routes/country/index.ts
packages/psss-server/src/routes/index.ts
packages/psss-server/src/routes/reports/FetchConfirmedWeeklyReportRoute.ts
packages/psss-server/src/types.ts

http://github.com/beyondessential/tupaia-backlog/issues/1501

1501: PSSS - GET site metadata

---

packages/utils/src/__tests__/array.test.js
packages/utils/src/array.js

This will be used in https://github.com/beyondessential/tupaia-backlog/issues/1369, but thought it should be good to get it in `dev` earlier (#1369 will be merged in the PSSS epic branch)

Add removeAt util

---

packages/meditrak-server/src/index.js
packages/web-config-server/src/index.js

To make sure that we are connected to the desired aggregation servers

Log aggregation url prefix on server start

---

packages/aggregator/src/Aggregator.js
packages/aggregator/src/analytics/aggregateAnalytics/adjustOptionsToAggregationList.js

The decision with this ticket is just to support fetching the PSSS Weekly Report and PSSS Weekly Cases when passing in the facility codes as orgUnitCodes. In order to support this a small change needs to be made to the entity aggregation logic to support aggregating to the requested entity level.

1411: Handled case where entity aggregation config returned no relations

---

packages/lesmis/src/api/queries/index.js
packages/lesmis/src/api/queries/useDashboardData.js
packages/lesmis/src/components/Tabs.js
packages/lesmis/src/constants/constants.js
packages/lesmis/src/views/DashboardReportTabView.js
packages/lesmis/src/views/DashboardView.js
packages/lesmis/src/views/MapView.js
packages/ui-components/src/components/Chart/CartesianChart.js
packages/ui-components/src/components/Chart/Legend.js
packages/ui-components/src/components/Chart/PieChart.js

This PR is for adding the dashboard groups to lesmis front end
- fetch dashboard data
- add dashboard group tabs
---

2538 lesmis dashboard reports part 2

---

packages/lesmis-server/src/app/createApp.ts
packages/lesmis-server/src/routes/DashboardRoute.ts
packages/lesmis-server/src/routes/index.ts
packages/lesmis/src/api/queries/index.js
packages/lesmis/src/api/queries/useDashboardData.js
packages/lesmis/src/components/Tabs.js
packages/lesmis/src/constants/constants.js
packages/lesmis/src/views/DashboardReportTabView.js
packages/lesmis/src/views/DashboardView.js
packages/lesmis/src/views/MapView.js
packages/ui-components/src/components/Chart/CartesianChart.js
packages/ui-components/src/components/Chart/Legend.js
packages/ui-components/src/components/Chart/PieChart.js

This is the lesmis server part of the Entity Dashboard Groups user story.
- add dashboard route to lesmis server
---

add dashboard route

---

packages/psss-server/src/connections/EntityConnection.ts
packages/psss-server/src/routes/country/FetchCountries.ts
packages/psss-server/src/routes/country/FetchCountrySites.ts
packages/psss-server/src/routes/reports/FetchCountryWeeklyReportRoute.ts

Addressing https://github.com/beyondessential/tupaia/pull/2436#discussion_r617990322 - let me know what you think!

Move specific API to EntityConnection

---

packages/lesmis/src/components/Tabs.js
packages/lesmis/src/views/DashboardReportTabView.js
packages/lesmis/src/views/DashboardView.js

- Restructure the tabs to be a dropdown
---
[See issue](https://github.com/beyondessential/tupaia-backlog/issues/2541)

2538 lesmis dashboard reports tab update

---

packages/database/src/migrations/20210419032448-MarkProgramIndicatorAsBorked-modifies-data.js
packages/web-config-server/src/apiV1/measureBuilders/sumPerOrgUnit.js
packages/web-config-server/src/apiV1/utils/fetchIndicatorValues/index.js
packages/web-config-server/src/apiV1/utils/fetchIndicatorValues/shouldUseFetchIndicatorValues.js
packages/web-config-server/src/apiV1/utils/index.js

2607 cleanup program indicator path

---

packages/lesmis/src/components/EntityPolygonLink.js
packages/lesmis/src/components/LocationHeader.js
packages/lesmis/src/components/Report.js
packages/lesmis/src/theme/theme.js
packages/lesmis/src/views/MapView.js
packages/ui-components/src/components/Chart/Chart.js
packages/ui-components/src/components/Chart/Table.js
packages/ui-components/src/components/Chart/index.js
packages/ui-components/src/components/Chart/utils.js
packages/ui-components/stories/chart/data/barChartViewContent.json
packages/ui-components/stories/chart/data/stackedBarChart.json
packages/ui-components/stories/chart/helpers.js
packages/ui-components/stories/chart/stackedBarChart.stories.js
packages/utils/src/index.js

- Add Table component to ui components
- Add Tables to lesmis
---
See issue

2688 table flippa

---

packages/lesmis-server/src/app/createApp.ts
packages/lesmis-server/src/connections/ReportConnection.ts
packages/lesmis-server/src/routes/ReportRoute.ts
packages/lesmis/src/api/queries/useVitalsData.js
packages/report-server/src/app/addRoutesToApp.ts
packages/report-server/src/routes/fetchReport.ts
packages/report-server/src/types.ts
packages/server-boilerplate/src/orchestrator/api/ApiBuilder.ts

- Allow report server to process report fetches from POST requests
- Allow lesmis server to forward to the report server using POST requests
- Send POST requests from lesmis

Report Server fetch via POST

---

packages/database/src/migrations/20210421001607-PsssPalauSyndromBubbleMapOverlay-modifies-data.js
packages/web-config-server/src/apiV1/measureData.js

[#2107](https://github.com/beyondessential/tupaia-backlog/issues/2107)
[#2108](https://github.com/beyondessential/tupaia-backlog/issues/2108)
- Support custom popup label (new config: `customLabel`)
- Migration for two map overlays

Psss syndrome map overlays

---

packages/database/src/migrations/20210428030104-DeleteSamoaCovidDashboardGroupFromExplore-modifies-data.js

Addresses: https://github.com/beyondessential/tupaia-backlog/issues/2651

2651 Delete dashboardGroup from Samoa

---

packages/lesmis/src/components/EntityMenu.js
packages/lesmis/src/components/ErrorBoundary.js
packages/lesmis/src/components/FetchLoader.js
packages/lesmis/src/utils/search.js
packages/lesmis/src/views/DashboardReportTabView.js
packages/ui-components/src/components/Inputs/Select.js
packages/utils/src/formatDataValueByType.js

- Add error boundary to dashboard reports
- Fix data formatting parsing for number types
- Add laos link to the top of the entity browse menu
- Fix search icon entity type mapping
- Fix dashboard group tab defaults
- Fix Dashboard super tab Select padding
---

2538 lesmis dashboard report fixes

---

packages/ui-components/.storybook/webpack.config.js
packages/ui-components/.storybook/yargsMock.js

Fixes storybook not working because it can't load yargs

Add mock for yargs to storybook build

---

packages/lesmis/src/components/MapOverlaysPanel/MapOverlaysPanel.js
packages/lesmis/src/components/MapOverlaysPanel/MapOverlaysPanelContainer.js

https://github.com/beyondessential/tupaia-backlog/issues/2751
Screenshot https://github.com/beyondessential/tupaia-backlog/issues/2751

2751 select period box sticks

---

packages/database/src/migrations/20210426204745-AddLaEocDengueCaseBarDistrict-modifies-data.js

- migration to add Laos EOC District (sub_district) level Dengue Cases bar report

2643 dengue bar district

---

packages/database/src/migrations/20210503024117-AddLaEocMapOverlayDengueCasesByWeekDistrict-modifies-data.js
packages/database/src/migrations/20210503055037-AddLaEocMapOverlayMalariaCasesByWeek-modifies-data.js
packages/database/src/migrations/20210503082425-AddLaEocMalariaCasesBarChart-modifies-data.js

- [2644](https://github.com/beyondessential/tupaia-backlog/issues/2644) Map Overlay: Weekly Dengue Cases by District
- [2645](https://github.com/beyondessential/tupaia-backlog/issues/2645) Map Overlay: Weekly Malaria Cases by Province 
- [2647](https://github.com/beyondessential/tupaia-backlog/issues/2647) Dashboard element: Malaria cases bar chart at district and province 
- migrations to add the above visuals
- copy of https://github.com/beyondessential/tupaia/pull/2492 rebased on new branch

Remaing Laos EOC visuals

---

packages/lesmis/src/api/queries/useEntitiesData.js
packages/lesmis/src/api/queries/useVitalsData.js
packages/lesmis/src/components/EntityVitalsItem.js
packages/lesmis/src/views/DashboardView.js

- Allow entity vital items to hyphenate if their content is too long
- Remove fake value in complete schools
- Add district/province name to vitals subsections
- Add unit `km` to distance to main road
- Add `School Type` to School dashboard
- Fetch entity attributes in react hook

BAT updates for entity vitals

---

packages/database/src/migrations/20210412210749-AddLesmisEntityVitalsReports-modifies-data.js
packages/lesmis/src/api/queries/useVitalsData.js
packages/lesmis/src/views/DashboardView.js

- Default value for sub district report
- Hard code country vitals

2501 bugfixes entity vitals

---

packages/database/src/migrations/20210503020203-RenameDashboardHeadings-modifies-data.js

- Rename dashboardGroups for LESMIS
- Add new empty dashboardGroups when necessary

2745 lesmis dashboard headings

---

packages/database/src/migrations/20210422030246-CreateUnknownEntitiesForSamoa-modifies-data.js

2606 add unknown entities to Samoa and exclude from explore (#2460)

---

packages/database/src/migrations/20210506052033-AddSamoaCovidPercentageVaccinatedMeasures-modifies-data.js

- Fix bug in samoa covid percentage map overlay

2655: Fix bug in samoa covid percentage map overlay

---

packages/database/src/migrations/20210506052033-AddSamoaCovidPercentageVaccinatedMeasures-modifies-data.js

2685-covid-samoa-percentage-reportstest

---

packages/database/src/migrations/20210512224458-LaEocLaRemoveDeletedFacility-modifies-data.js

- remove a Laos EOC facility from Tupaia that has been deleted on Laos EOC DHIS server

[Hotfix] Laos EOC remove deleted facility

---

packages/database/src/migrations/20210512114642-UpdatePSSSTotalSitesReportedIndicator-modifies-data.js
packages/database/src/migrations/20210512115557-AddPSSSWeeklyDataPerSyndromeReports-modifies-data.js
packages/database/src/migrations/20210513065305-AddPSSSConfirmedWeeklyDataPerSyndromeReports-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/1517
https://github.com/beyondessential/tupaia-backlog/issues/1518
- Added reports for alert details panel psss
- Reports that fetch data for Alert details panel
Report for country level confirmed data: `PSSS_${syndrome}_Confirmed_Weekly_Report`
Request URL: `{{URL}}/fetchReport/PSSS_DIA_Confirmed_Weekly_Report?period=2021W15&hierarchy=psss&organisationUnitCodes=PW`
```
{
"results": [
{
"percentageChange": -0.3333333333333333,
"period": "2021W15",
"organisationUnit": "PW"
}
],
}
```
Report for sentinel site level unconfirmed data: `PSSS_${syndrome}_Weekly_Report`
Request URL: `{{URL}}/fetchReport/PSSS_DLI_Weekly_Report?period=2021W17&hierarchy=psss&organisationUnitCodes=PW_AngaurCHC`
```
{
"results": [
{
"weeklyCases": 6, …
```

1517 1518: PSSS Reports for Alert details panel

---

packages/admin-panel/src/editor/EditModal.js
packages/admin-panel/src/pages/resources/EntitiesPage.js
packages/admin-panel/src/pages/resources/PermissionGroupsPage.js

- Remove hello text
---
see issue

remove hello text

---

packages/database/src/migrations/20210513065305-AddPSSSConfirmedWeeklyDataPerSyndromeReports-modifies-data.js

Update reports for new UI

---

packages/database/src/migrations/20210415062117-DataSourceCodeCleanUpLaosEoc-modifies-data.js

Fix [#2552](https://github.com/beyondessential/tupaia-backlog/issues/2552)

Fix data source clean up pr

---

packages/database/src/migrations/20210520024548-LaEocAddSubDistrictDataSources-modifies-data.js

Add data_service_entity entries for Laos EOC Districts (sub_district)

Add data-service-entity entries for Laos EOC districts

---

packages/report-server/src/routes/fetchReport.ts

PSSS fix merge

---

packages/psss/src/containers/ProfileButton.js

https://github.com/beyondessential/tupaia-backlog/issues/1117

1117: PSSS - Manage profile

---

packages/lesmis/src/api/queries/useMapOverlayReportData.js
packages/lesmis/src/components/MapOverlaysPanel/MapOverlayGroup.js
packages/lesmis/src/components/MapOverlaysPanel/MapOverlaysPanel.js

- add map overlay deep linking
---

2683 map overlay deep linking

---

packages/lesmis-server/src/constants.ts
packages/lesmis/src/constants/constants.js
packages/lesmis/src/views/MapView.js
packages/ui-components/src/components/Map/LeafletStyles.js
packages/ui-components/src/components/Map/Legend/Legend.js
packages/ui-components/src/components/Map/Legend/LegendEntry.js
packages/ui-components/src/components/Map/Legend/MarkerLegend.js
packages/ui-components/src/components/Map/MapContainer.js
packages/ui-components/src/components/Map/Markers/PopupMarker.js
packages/ui-components/src/components/Map/Markers/markerIcons.js
packages/ui-components/src/components/Map/TileLayer.js
packages/ui-components/src/components/Map/TilePicker/TileButton.js
packages/ui-components/src/components/Map/TilePicker/TileControl.js
packages/ui-components/src/components/Map/TilePicker/TilePicker.js
packages/ui-components/src/components/Map/index.js
packages/ui-components/src/components/Map/utils/markerFormats.js

The scope was initially to fix support for multi-measure in the map components and in lesmis. I did quite a bit of testing and found a bug with the legend for radius map overlays which was crashing the app. Once I fixed this the multi-measure map overlays worked as expected.
While testing I took the change to add support for light theme to the map components.
- fix radius legend item bug
- add support for light theme to map components
---
see issue

2680 multi measure map overlays

---

packages/psss/src/components/AffectedSitesTab.js

- Similar to country level, the key is not what the report returns

Fix alert sentinel site cases

---

packages/psss/src/api/queries/useWeeklyReportForAlert.js

Addresses https://github.com/beyondessential/tupaia-backlog/issues/2851#issuecomment-848371292 and https://github.com/beyondessential/tupaia-backlog/issues/2851#issuecomment-848372128

PSSS: Fix alert panel item order

---

packages/psss/src/components/Table/CellComponents/ArchivedAlertMenuCell.js
packages/psss/src/containers/Modals/ArchiveAlertModal.js
packages/psss/src/containers/Modals/ConfirmModal.js
packages/psss/src/containers/Modals/CreateOutbreakModal.js
packages/psss/src/containers/Modals/DeleteAlertModal.js
packages/psss/src/containers/Modals/RestoreArchivedAlertModal.js
packages/psss/src/containers/Modals/SuccessModal.js
packages/psss/src/containers/Panels/AlertsPanel.js
packages/psss/src/containers/Tables/ArchiveTable.js
packages/ui-components/src/components/ActionsMenu.js

https://github.com/beyondessential/tupaia-backlog/issues/2838#issuecomment-848457933
- Fixed small bugs when deleting/restoring alerts

Fix small bug when deleting alerts

---

packages/psss-server/src/connections/ReportConnection.ts
packages/psss/src/containers/Tables/SiteSummaryTable.js

https://github.com/beyondessential/tupaia-backlog/issues/2855#issuecomment-850016829

PSSS - Fix no sites error

---

packages/data-api/package.json
packages/data-api/scripts/dropAnalyticsTableIndexes.sql
packages/data-api/scripts/fastRefreshAnalyticsTable.sh
packages/data-api/scripts/fullRefreshAnalyticsTable.sh
packages/data-api/scripts/refreshAnalyticsTable.sh

Drops indexes, runs a full refresh of analytics, then recreates indexes

Add utility script for running analytics full refresh

---

packages/web-config-server/src/apiV1/dataBuilders/generic/dataDownload/rawDataValues.js

- Fixed a bug that Laos school Raw Data Download does not return values for some fields

2890: Fixed raw data download bug

---

packages/devops/configs/servers.conf
packages/lesmis/src/api/api.js

https://github.com/beyondessential/tupaia-backlog/issues/2833
Completing items in https://github.com/beyondessential/tupaia-backlog/issues/2833#issuecomment-849966659

Point LESMIS to same domain for api

---

packages/report-server/src/reportBuilder/fetch/functions/dataGroup.ts
packages/report-server/src/reportBuilder/fetch/functions/helpers/validators.ts

no issue
we want to fetch multiple dataGroups in report-server, ultimately we would want Aggregator to handle that.

fetchEvents() to handle multiple data groups in report server

---

packages/database/src/migrations/20210603231415-FixCOVIDVaccineFijiEntityDataSourceTypes-modifies-data.js
packages/database/src/migrations/20210603231515-FixCOVIDVaccineNauruEntityDataSourceTypes-modifies-data.js
packages/database/src/migrations/20210604004937-AddNewNationalLevelCovidTrackingByGenderDashboard-modifies-data.js
packages/database/src/migrations/20210604010622-AddTotalNumberOfPeopleReceive1stDoseCovidVaccineView-modifies-data.js
packages/database/src/migrations/20210604010722-AddTotalNumberOfPeopleReceive2ndDoseCovidVaccineView-modifies-data.js
packages/database/src/migrations/20210604015355-DeleteDuplicatedCovid19FijiDashboardGroup-modifies-data.js

- Fixed COVID-19 Fiji dashboards

2922: Fix COVID-19 Fiji dashboards

---

packages/database/src/migrations/20210604004448-CovidSamoaVaccineDeleteResponses-modifies-data.js

Will be tested on feature branch then become HOTFIX.

HOTFIX: delete all COVIDVac_WS survey responses

---

packages/database/src/migrations/20210602065620-AddFijiCOVIDVaccinatedRegionOverlays-modifies-data.js
packages/database/src/migrations/20210603023401-AddFijiCOVIDVaccinePercentageOfPopulationVaccinatedMapOverlays-modifies-data.js
packages/database/src/migrations/20210603231415-FixCOVIDVaccineFijiEntityDataSourceTypes-modifies-data.js
packages/database/src/migrations/20210603231515-FixCOVIDVaccineNauruEntityDataSourceTypes-modifies-data.js
packages/database/src/migrations/20210604004937-AddNewNationalLevelCovidTrackingByGenderDashboard-modifies-data.js
packages/database/src/migrations/20210604010622-AddTotalNumberOfPeopleReceive1stDoseCovidVaccineView-modifies-data.js
packages/database/src/migrations/20210604010722-AddTotalNumberOfPeopleReceive2ndDoseCovidVaccineView-modifies-data.js
packages/database/src/migrations/20210610005659-DeleteCovid19FJFacilityOverlays-modifies-data.js
packages/database/src/migrations/20210610013423-RemoveCovid19ByGenderReportFromDashboardGroup-modifies-data.js

- Datasource level is changed from facility to sub_district. So I'm updating the vizes to reflect that

2929: Change COVID 19 visuals data source level

---

packages/lesmis/src/views/PageView.js

@enunan noticed that the FQS page is crashing in production, this fixes that issue

[hot fix] Update PageHeader to use new breadcrumbs prop

---

packages/database/src/migrations/20210615042534-AddFijiCovidPercentageEligiableDashboards-modifies-data.js
packages/database/src/migrations/20210615060723-CreateSubDistrictFijiVaccinationDoseDashboardReports-modifies-data.js
packages/database/src/migrations/20210615064531-ReorderCovidFJSubDistrictDashboardReports-modifies-data.js

- Fixed sub district dashboards

2929: Fixed sub district dashboards

---

packages/database/src/migrations/20210607020237-AddIndicatorsForAuFlutracking-modifies-data.js
packages/database/src/migrations/20210610060144-AddFluTrackerLGAPercentNonFirstNationsILI-modifies-data.js

[#2879](https://github.com/beyondessential/tupaia-backlog/issues/2879)
- Add two indicators

2879 create flutracker phase two indicators

---

packages/report-server/examples.http

I was looking for one to get started building reports, so thought I might as well save this for future devs
It's based reasonably closely on the [slab doc](https://beyond-essential.slab.com/posts/reporting-package-154s5c5l) so that there's some consistency when learning how to use the reporting package

Add report test config example

---

packages/database/src/migrations/20210622234149-LESMISStudentCountToStackedBar-modifies-data.js

This is branched from `2963-schools-by-education-level` because I needed to use the translate function added by that PR
- Add migration for students by gender stacked bar with GPI
See attached ticket

2850: Add migration for students by gender stacked bar with GPI

---

packages/database/src/migrations/20210623024537-AddChildrenOverAgeLESMIS-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/2968
District level only for now, as per https://github.com/beyondessential/tupaia-backlog/issues/2968#issuecomment-866473967
Screenshot https://github.com/beyondessential/tupaia-backlog/issues/2968#issuecomment-866487801

2968: Children over age for grade, district level

---

packages/database/src/migrations/20210623041504-AddNERGERLESMIS-modifies-data.js

- https://github.com/beyondessential/tupaia-backlog/issues/2973
- https://github.com/beyondessential/tupaia-backlog/issues/2974

2973 2974: NER and GER reports for country, province, and district

---

packages/database/src/migrations/20210623032946-AddDropoutRateByGrade-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/2969
[Screenshot](https://github.com/beyondessential/tupaia-backlog/issues/2969#issuecomment-866504099)

2969: Dropout rate by grade, district level

---

packages/database/src/migrations/20210607020237-AddIndicatorsForAuFlutracking-modifies-data.js
packages/database/src/migrations/20210610060144-AddFluTrackerLGAPercentNonFirstNationsILI-modifies-data.js
packages/database/src/migrations/20210615035418-DropVillagesFromLESMIS-modifies-data.js
packages/lesmis-server/src/app/createApp.ts
packages/lesmis-server/src/connections/MeditrakConnection.ts
packages/lesmis-server/src/routes/UpdateUserEntityPermissionRoute.ts
packages/lesmis-server/src/routes/index.ts
packages/lesmis/src/api/mutations/useUpdateUserEntityPermission.js
packages/lesmis/src/api/queries/useVitalsData.js
packages/lesmis/src/components/DataGrid/DataGrid.js
packages/lesmis/src/components/DataGrid/NoDataRow.js
packages/lesmis/src/components/DataGrid/UserPermissionsCell.js
packages/lesmis/src/components/DataGrid/index.js
packages/lesmis/src/components/PageHeader.js
packages/lesmis/src/constants/constants.js
packages/lesmis/src/utils/search.js
packages/lesmis/src/views/DashboardView.js
packages/lesmis/src/views/PageView.js
packages/lesmis/src/views/UsersView.js
packages/report-server/examples.http
packages/server-boilerplate/src/orchestrator/api/ApiBuilder.ts

- [2845](https://github.com/beyondessential/tupaia-backlog/issues/2845) LESMIS Editing User Permissions
- [No issue](https://github.com/beyondessential/tupaia/pull/2661) FQS links open in new tab
- [No issue](https://github.com/beyondessential/tupaia/pull/2690) Add report test config example
- [2876](https://github.com/beyondessential/tupaia-backlog/issues/2876) Remove villages from LESMIS hierarchy
- [2879](https://github.com/beyondessential/tupaia-backlog/issues/2879) Create flutracker phase two indicators
- [No issue](https://github.com/beyondessential/tupaia/pull/2717) Fixed up pg-mv-fast-refresh module version

Release v2021-25.0 (Due 25/06/2021)

---

packages/database/src/migrations/20210624211254-AddChildrenOverAgeLESMIS-modifies-data.js
packages/lesmis/src/views/DashboardView.js

Same as https://github.com/beyondessential/tupaia/pull/2703, but added under international SDGs instead of the district profile
(reverted earlier PR last night so that the feature deployment wouldn't have that migration on it after it cloned at midnight, see https://github.com/beyondessential/tupaia/pull/2696/commits/cfd8fce2d0da02e595a9b9da9b8c44cdab283e7b)
https://github.com/beyondessential/tupaia-backlog/issues/2968
District level only for now, as per https://github.com/beyondessential/tupaia-backlog/issues/2968#issuecomment-866473967
Screenshot https://github.com/beyondessential/tupaia-backlog/issues/2968#issuecomment-866487801

2968: Add children over age for grade

---

packages/utils/src/formatDataValueByType.js

Fixes https://github.com/beyondessential/tupaia-backlog/issues/2973#issuecomment-867981984

Use 'numeral' rather than truncate function with floating point math issues

---

packages/database/src/migrations/20210622010643-UnfpaMonthly3MethodsBug-modifies-data.js
packages/ui-components/src/components/Chart/parseChartConfig.js
packages/web-frontend/src/components/View/ChartWrapper/parseChartConfig.js

[#2962](https://github.com/beyondessential/tupaia-backlog/issues/2962) SI and FSM are same colour in UNFPA Regional view
- fix sorting lengend
- add colour for undefined countries

2962 fix unfpa charts legend color

---

packages/database/src/migrations/20210627233338-LESMISDropObsoleteDashboardItem-modifies-data.js

Drop obsolete student gender pie graph

---

packages/ui-components/src/components/Chart/Table.js

- add support for column value types in the table flippa
---
See issue above

2974 add support for column value types in the table flippa

---

packages/database/src/migrations/20210628030723-AddNumberTeachersByEducationLevel-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/3024
Screenshot [here](https://github.com/beyondessential/tupaia-backlog/issues/3024)

3024: Teachers by education level at district level

---

packages/database/src/migrations/20210628035506-AddNumberSchoolsPublicPrivateESSDP-modifies-data.js
packages/lesmis/src/views/DashboardView.js

https://github.com/beyondessential/tupaia-backlog/issues/3026
Screenshot [here](https://github.com/beyondessential/tupaia-backlog/issues/3026#issuecomment-869350645)

3026: Add number of schools ESSDP visuals

---

packages/database/src/migrations/20210628030105-LESMISStudentsByEthnicity-modifies-data.js

- Migration
Attached to ticket

3020 student by ethnicity

---

packages/database/src/migrations/20210629001252-AddCohortSurvivalRatesLESMIS-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/2972
Screenshot [here](https://github.com/beyondessential/tupaia-backlog/issues/2972#issuecomment-870134329)

2972: Add cohort survival rates visuals at district

---

packages/database/src/migrations/20210628231433-AddRepetitionRateLESMIS-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/2970#issuecomment-870128100
Screenshot [here](https://github.com/beyondessential/tupaia-backlog/issues/2970#issuecomment-870128100)

2970: Add repetition rate visuals at district

---

packages/database/src/migrations/20210628230622-LESMISAgeOfGrade1Entrance-modifies-data.js

Add age of grade 1 entrance visual

---

packages/database/src/migrations/20210629014029-AddNumberClassesPublicSchoolsLESMIS-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/3028
[Screenshot](https://github.com/beyondessential/tupaia-backlog/issues/3028#issuecomment-870170888)

3028: Add number of classes in public schools

---

packages/database/src/migrations/20210629022811-FixTypoInTitles-modifies-data.js

https://github.com/beyondessential/tupaia-backlog/issues/2972#issuecomment-870166575

Fix typo in cohort rate title

---

packages/database/src/migrations/20210629011450-LESMISCompleteAndIncompleteSchools-modifies-data.js

- No change to utils
Attached to ticket

3025: Add stacked bar for complete/incomplete schools

---

packages/lesmis/src/components/DashboardReportModal.js
packages/lesmis/src/components/YearSelector.js
packages/lesmis/src/views/DashboardView.js
packages/ui-components/src/components/DateRangePicker/DateRangePicker.js

- add loading state to year selector
- don't clear year state when changing dashboard tabs
---

Lesmis date picker fixes

---

packages/utils/src/formatDataValueByType.js

Fixing issues with decimals showing up unnecessarily in axis labels etc.
See e.g. https://beyondessential.slack.com/archives/C01MAA3NKM1/p1625121332117800
Fixing issue introduced in https://github.com/beyondessential/tupaia/pull/2720/files

Truncate whole numbers

---

packages/web-frontend/src/components/View/ChartWrapper.js

Fix overflow last available data

---

packages/lesmis/src/components/Chart.js
packages/lesmis/src/components/DashboardReport.js
packages/lesmis/src/components/YearSelector.js

- Remove loading indicator from year selector
- Add background fetching indicator
---
see issue

3016 lesmis chart loading states

---

packages/database/src/migrations/20210705232257-DropDeprecatedDashboardReportAndDashboardGroupTables-modifies-schema.js

Renamed migration to schema

---

packages/database/src/migrations/20210621034818-FixSbAtLeastOneStaffMemberTrained-modifies-data.js

[#2913](https://github.com/beyondessential/tupaia-backlog/issues/2913)
Previous PR: https://github.com/beyondessential/tupaia/pull/2692
This 2913 ticket is already merged, but needs to update to use new db dashboard structure.

Use legacy-report in 2692 changes

---

packages/database/src/migrations/20210705014650-AddNumberOfECETeachersVis-modifies-data.js

- Migration for visual, util functions unchanged from other uses
Attached to ticket

Add number of ECE Teachers visual

---

packages/report-server/src/__tests__/reportBuilder/functions.test.ts
packages/report-server/src/reportBuilder/functions/math.ts

Reverted changes to 'sum' function in report-server until they are safe to merge

---

packages/web-frontend/cypress/README.md
packages/web-frontend/cypress/config/dashboardReportUrls/covidau.json
packages/web-frontend/cypress/config/dashboardReportUrls/default.json
packages/web-frontend/cypress/e2e/dashboardReports.spec.js
packages/web-frontend/cypress/scripts/generateConfig/VisualisationFilter.js
packages/web-frontend/cypress/scripts/generateConfig/generateReportConfig.js

- Update e2e tests to fit new dashboard structure

3138: Update e2e tests new dashboard structure

---

packages/web-frontend/public/index.html

Screenshot: https://github.com/beyondessential/tupaia-backlog/issues/3156#issuecomment-876907443

Add raygun crash reporting

---

packages/web-frontend/cypress/config/dashboardReportUrls/default.json
packages/web-frontend/cypress/config/dashboardReportUrls/lesmis.json

-  adding Lesmis visuals to E2E config

3000: E2E lesmis config 

---

packages/lesmis-server/src/session/attachSession.ts
packages/lesmis/src/components/ErrorBoundary.js
packages/lesmis/src/components/MapOverlaysPanel/MapOverlaysPanel.js
packages/lesmis/src/views/DashboardReportTabView.js
packages/lesmis/src/views/DashboardView.js
packages/server-boilerplate/src/orchestrator/routes/middleware.ts

- clear session cookie from browser if the server can't find it in the db (in lesmis-server and server-boilerplate)
- add some error boundaries to lesmis to stop whole app crashing if there is a js error
- handle no data better in lesmis dashboard tab component
I also investigated psss and it is already handling the case of no session record in the db well by logging the user out completely.
---

Handle missing user sessions

---

packages/web-frontend/src/actions.js
packages/web-frontend/src/components/mobile/Dashboard/index.js
packages/web-frontend/src/components/mobile/ExpandableList/index.js
packages/web-frontend/src/containers/OverlayDiv/components/ProjectPage/index.js
packages/web-frontend/src/containers/OverlayDiv/index.js
packages/web-frontend/src/containers/mobile/SearchOverlay/index.js
packages/web-frontend/src/reducers.js
packages/web-frontend/src/screens/mobile/RegionScreen/index.js
packages/web-frontend/src/styles/index.js

- [3088](https://app.zenhub.com/workspaces/active-sprints-5eea9d3de8519e0019186490/issues/beyondessential/tupaia-backlog/3088) Fix Search
- [3171](https://app.zenhub.com/workspaces/active-sprints-5eea9d3de8519e0019186490/issues/beyondessential/tupaia-backlog/3171) Hide mini-map
- [3170](https://app.zenhub.com/workspaces/active-sprints-5eea9d3de8519e0019186490/issues/beyondessential/tupaia-backlog/3170) Open dashboard by default
- [3086](https://app.zenhub.com/workspaces/active-sprints-5eea9d3de8519e0019186490/issues/beyondessential/tupaia-backlog/3086) Improve project selection
---
See issue tickets

Tupaia mobile quick wins

---

packages/devops/scripts/ci/deployFrontend.sh

https://github.com/beyondessential/tupaia-backlog/issues/3143
I'm not at all confident this will help, but it's possible that it will so worth a try.

3143: Keep ssh connection alive during front end builds

---

packages/meditrak-server/src/routes/importEntities/assertCanImportEntities.js
packages/meditrak-server/src/routes/importEntities/importEntities.js
packages/meditrak-server/src/routes/importEntities/updateCountryEntities.js
packages/meditrak-server/src/tests/routes/importEntities/assertCanImportEntities.test.js
packages/utils/src/getCountryCode.js

https://github.com/beyondessential/tupaia-backlog/issues/3179

3179: Use explicit list of unofficial country names

---

packages/devops/scripts/ci/deployBackend.sh
packages/devops/scripts/ci/pullLatest.sh
packages/devops/scripts/ci/runMigrations.sh

Identical to the change here, just added for migrations as well: https://github.com/beyondessential/tupaia/pull/2824

3143: Added keep alive during running migrations

---

packages/database/src/migrations/20210719025659-AddFluTrackerFirstNationWithIliMapOverlay-modifies-data.js

[#2760](https://github.com/beyondessential/tupaia-backlog/issues/2760)
A simple migration

2760 First Nation participants with Influenza covidau

---

scripts/node/validateTests.js

Fixes an issue introduced in https://github.com/beyondessential/tupaia/pull/2844

Fix broken script

---

packages/database/src/migrations/20210719092820-UpdatePermissionGroupHierarchy-modifies-data.js

Update permission group hierarchy

---

packages/admin-panel-server/package.json
packages/admin-panel-server/src/app/createApp.ts
packages/admin-panel-server/src/connections/MeditrakConnection.ts
packages/admin-panel-server/src/connections/SessionHandlingApiConnection.ts
packages/admin-panel-server/src/connections/index.ts
packages/admin-panel-server/src/routes/UserRoute.ts
packages/admin-panel-server/src/routes/index.ts
yarn.lock

This is just a supporting PR for the upcoming [3102 viz builder fe scaffolding](https://github.com/beyondessential/tupaia/pull/2854).
- add user route to admin panel server
- add camelcase-keys package
---

add user route to admin panel server

---

packages/report-server/src/__tests__/reportBuilder/functions.test.ts
packages/report-server/src/__tests__/reportBuilder/transform/insert.test.ts
packages/report-server/src/reportBuilder/functions/basic.ts
packages/report-server/src/reportBuilder/functions/index.ts
packages/report-server/src/reportBuilder/transform/functions/index.ts
packages/report-server/src/reportBuilder/transform/functions/insert.ts
packages/report-server/src/reportBuilder/transform/functions/position.ts
packages/report-server/src/reportBuilder/transform/parser/TransformParser.ts

- Add an `insert` transform following a similar pattern to `select`
- Add unit tests for insert

3195 report server insert row function

---

e2e.Dockerfile
full-testable-package.Dockerfile
packages/database/src/migrations/20210719023634-CorrectNumberTeachersByEducationLevel-modifies-data.js
packages/database/src/migrations/20210722044503-FixDataSourceEntityTypeLesmisProvinceStudentDashboards-modifies-data.js

Release 2021 29-e2e test

---

packages/devops/scripts/lambda/utilities.py

Fix lambda scripts for aws api limit

---

e2e.Dockerfile
full-testable-package.Dockerfile
packages/database/src/migrations/20210722044503-FixDataSourceEntityTypeLesmisProvinceStudentDashboards-modifies-data.js

Merge release-2021-29 back into dev

---

packages/database/scripts/dumpDatabase.sh

Add suffix -ssh for updating dump database.
It has been tested locally.

add suffix -ssh for updating dump database script

---

packages/web-config-server/src/apiV1/dataBuilders/helpers/calculateOperationForAnalytics.js

fix broken matriz

---

packages/database/scripts/refreshDatabase.js

- Noticed this while trying to refresh my local

Fix bad quotes on db command

---

packages/utils/src/object.js
packages/web-config-server/src/apiV1/dataBuilders/DataPerPeriodBuilder.js
packages/web-config-server/src/apiV1/dataBuilders/generic/count/countValuesByDataElementGroup.js
packages/web-config-server/src/apiV1/dataBuilders/generic/percentage/percentagesOfValueCountsPerPeriod.js

https://linear.app/tupaia/issue/MEL-383/fix-flaky-reports

MEL-383: Fix flaky reports

---

packages/database/src/migrations/20210803070618-AddCovidSamoaHouseholdVaccinationStatusMapOverlays-modifies-data.js

@nick-beyondessential probably just gonna merge this PR straight into your branch to do testing there

SOL-281: Household Vaccination Status Map Overlay

---

packages/database/src/migrations/20210803083523-AddCovidSamoaSubDistrictVaccinationTrackingMapOverlays-modifies-data.js

SOL-292: Added SubDistrict map overlays for Covid Samoa

---

packages/database/src/migrations/20210705232632-AddECEGoalsDrillDowns-modifies-data.js
packages/database/src/migrations/20210708023241-LESMISListVisualSummaryReport-modifies-data.js

- Fix codes being dropped in report
- Remove `listConfig` field
- Attach ECE goal drill downs to dashboard

Backend fixes for list visual

---

packages/meditrak-server/src/dataAccessors/editSurvey.js
packages/meditrak-server/src/dataAccessors/index.js
packages/meditrak-server/src/dataAccessors/validateSurveyFields.js
packages/meditrak-server/src/routes/importSurveys/importSurveys.js
yarn.lock

Addresses https://linear.app/tupaia/issue/MEL-92#comment-26ffa86f

2729: Disallow period granularity for dhis surveys (MEL-92)

---

packages/kobo-api/src/KoBoApi.js

- Add a max number of kobo entries to fetch
- Fetch from kobo in batches

NZ-824: Update KoBoApi to fetch data in paginated chunks

---

packages/database/src/migrations/20210728004659-RenameAnswerForOneOptionFromQuestion-modifies-data.js
packages/web-frontend/cypress/config.json
packages/web-frontend/cypress/config/mapOverlayUrls/default.json
packages/web-frontend/cypress/config/mapOverlayUrls/fanafana.json

ksNZ019tst

---

packages/admin-panel/src/VizBuilderApp/components/PreviewSection.js
packages/ui-components/src/components/Chart/Table/Table.js
packages/ui-components/src/components/Chart/Table/getChartTableData.js
packages/ui-components/src/components/DataTable/DataTable.js
packages/ui-components/src/components/Map/Table/Table.js
packages/ui-components/src/components/Map/Table/getMapTableData.js

- Use raw data table for preview data in viz-builder

MEL-39: Use raw data table for viz-builder preview

---

packages/database/src/migrations/20210809034325-CreateLarvaeHabitatsEntityType-modifies-schema.js
packages/database/src/modelClasses/Entity.js

https://linear.app/tupaia/issue/SOL-39/create-new-entity-type-for-recording-mosquito-larvae-habitats
Add new entity type: larval-habitat

Create larval-habitat entity type

---

packages/database/src/migrations/20210809034325-CreateLarvaeHabitatsEntityType-modifies-schema.js
packages/database/src/modelClasses/Entity.js

Create feature branch sol 305

---

packages/devops/scripts/ci/validateBranchName.sh

Just adding a comment, as I have put 64 - 17 - 1 into my calculator about 5 times 😂. (Could also be useful for any new devs that join in the future)

Add comment to avoid calculation when checking max length

---

packages/database/src/analytics/MaterializedViewLogDatabaseModel.js
packages/database/src/testUtilities/upsertDummyRecord.js

Issue identified during work for [MEL-92](https://linear.app/tupaia/issue/MEL-92#comment-0b96ee1c), but was introduced earlier
Not sure if this should be a hotfix instead? Truth be told, I'd love to include this in tomorrow's release. I think it shouldn't push testing back, but let me know what you think

Fix survey schema invalidation

---

packages/report-server/src/__tests__/reportBuilder/transform/select.test.ts
packages/report-server/src/reportBuilder/transform/functions/select.ts

https://beyondessential.slack.com/archives/C02649511JM/p1628804173010000
- Exit select early if we're not returning a new row

Move where clause to beginning of select

---

packages/database/src/migrations/20210705232632-AddECEGoalsDrillDowns-modifies-data.js

NZ-62
- Update migration to include Male/Female/GPI lines in the drill down reports

Add Male/Female/GPI lines to lesmis ece list drill downs

---

packages/database/src/migrations/20210809040122-PmosIndicators-modifies-data.js

https://linear.app/tupaia/issue/SOL-311/build-indicators-for-pacmossi

Sol 311 build indicators for pmos

---

packages/database/src/migrations/20210813034157-SOL149DeleteFacility-modifies-data.js

- Deletes unwanted KI facility

SOL-149 delete unwanted facility

---

packages/database/src/migrations/20210809040122-PmosIndicators-modifies-data.js

Fix pacmoss indicators

---

packages/admin-panel/src/VizBuilderApp/api/queries/useReportPreview.js
packages/admin-panel/src/VizBuilderApp/components/PreviewSection.js
packages/ui-components/src/components/FetchLoader.js

- Address viz-builder prototype feedback

MEL-397: Address viz-builder prototype feedback

---

packages/admin-panel-server/src/viz-builder/dashboardVisualisation/DashboardVisualisationCombiner.ts
packages/admin-panel/src/VizBuilderApp/api/constants.js
packages/admin-panel/src/VizBuilderApp/api/queries/useReportPreview.js

- Fix edit existing viz small bugs

MEL-387: Fix edit existing viz small bugs

---

packages/database/src/migrations/20210819000200-AddGeneralDashboardsToNauruEHealth-modifies-data.js

I've only approached half of the ticket in this dev work here, basically I've cleaned up the permissions model and added the dashboards themselves. The second part of the ticket will be to manually add dashboard relations to turn on dashboards items via the admin panel, which can be a data task. I've discussed with Erin and she's both happy with this approach and is interested in how to do that herself.
- Cleaned up permissions model for Nauru eHealth

SOL-275: Added General and Clinical Dashboards to Nauru eHealth project

---

packages/admin-panel/package.json
packages/lesmis/package.json
packages/psss/package.json
packages/web-frontend/package.json

- Disable generate source maps to reduce build size

Disable generate source maps to reduce front end build size

---

packages/admin-panel-server/examples.http
packages/admin-panel-server/package.json
packages/admin-panel-server/src/app/createApp.ts
packages/admin-panel-server/src/routes/ExportDashboardVisualisationRoute.ts
packages/admin-panel-server/src/routes/index.ts
packages/admin-panel/src/VizBuilderApp/api/api.js
packages/admin-panel/src/VizBuilderApp/api/mutations/index.js
packages/admin-panel/src/VizBuilderApp/api/mutations/useExportVisualisation.js
packages/admin-panel/src/VizBuilderApp/components/ExportButton.js
packages/admin-panel/src/VizBuilderApp/components/Toolbar.js
packages/server-boilerplate/src/routes/Route.ts

MEL-13
New viz export: [My_New_Viz.zip](https://github.com/beyondessential/tupaia/files/7005241/My_New_Viz.zip)
Existing viz export: [LESMIS_num_schools_by_education_level.zip](https://github.com/beyondessential/tupaia/files/7005242/LESMIS_num_schools_by_education_level.zip)

MEL-13: Viz builder export

---

packages/database/src/migrations/20210810040153-FQSVisualsInLESMIS-modifies-data.js

Resolves NZ-65
This is branched from the list visual work because I figured it should be tested with the latest version of the list
- Migration to add visuals for FQS1 and FQS2
---
See attached ticket

NZ-65 LESMIS FQS Visuals

---

packages/entity-server/examples.http
packages/entity-server/src/routes/hierarchy/relationships/middleware.ts

Fix incorrect assertion that ancestor_filter:type must be defined

---

packages/entity-server/examples.http
packages/entity-server/src/routes/hierarchy/relationships/middleware.ts

add_psss_dashboard_reports update

---

packages/web-frontend/cypress/config/dashboardReportUrls/default.json
packages/web-frontend/cypress/config/mapOverlayUrls/default.json

Add psss dashboard reports

---

packages/meditrak-server/src/apiV2/export/exportSurveyResponses/exportResponsesToFile.js

Broke this during my hot fix earlier in the week https://github.com/beyondessential/tupaia/pull/3124
🤦 🤦 🤦

Hot fix not exporting first row of data

---

packages/meditrak-app/app/assessment/actions/submitSurvey.js
packages/meditrak-app/ios/TupaiaMediTrak/Info.plist
packages/meditrak-app/package.json

See https://beyondessential.slack.com/archives/C01JD93J4E6/p1630364369013300
This one will need some regression testing, to make sure e.g. leaving questions blank in a survey doesn't cause them to have the empty string submitted etc.

Hot fix 0's not getting saved

---

packages/database/src/migrations/20210831043801-AddEntitiesRelationToSamoaForPenfaaSamoa-modifies-data.js

https://linear.app/bes/issue/SOL-402/add-entities-for-samoa-ncd-screening-project
Already get approved but head needs to be changed from dev to master. Previous PR: https://github.com/beyondessential/tupaia/pull/3131

add entity relation for penfaa_samoa

---

packages/database/src/migrations/20210831004115-RemoveAndUpdateCovidSamoaVailoaPalauliEntities-modifies-data.js
packages/database/src/migrations/20210831043801-AddEntitiesRelationToSamoaForPenfaaSamoa-modifies-data.js
packages/database/src/migrations/20210831074805-AddSubDistrictParentsSamoa-modifies-data.js

- Remove WS_012_Vailoa_Palauli entity
- Update name of WS_012_Vailoa_Satupaitea

SOL-405: Hotfix - Remove WS_012_Vailoa_Palauli entity

---

packages/database/src/migrations/20210823032403-LESMISChildrenOverAgeForGradeVisual-modifies-data.js

Resolves NZ-54
- Students over age for grade in province/country

NZ-54 Overage for grade province/country visual

---

packages/web-frontend/public/index.html

- Add tracking code to index.html
- Remove hotjar tracking code

add ms clarity and remove hotjar

---

packages/admin-panel/src/pages/resources/DashboardItemsPage.js
packages/admin-panel/src/widgets/JsonInputField.js
packages/database/src/migrations/20210825230542-LESMISProvinceNationalDropOutRates-modifies-data.js
packages/lesmis/src/api/api.js
packages/meditrak-server/src/apiV2/dashboardItems/DeleteDashboardItem.js
packages/meditrak-server/src/tests/apiV2/dashboardItems/DeleteDashboardItems.test.js
packages/meditrak-server/src/tests/apiV2/dashboardItems/EditDashboardItems.test.js
packages/meditrak-server/src/tests/apiV2/dashboardItems/GETDashboardItems.test.js
packages/web-frontend/public/index.html

Sima create branch

---

packages/database/src/migrations/20210902055844-UpdateUNFPASbRawDataDownloadSurvey-modifies-data.js

Already approved in https://github.com/beyondessential/tupaia/pull/3149

[Hotfix] Update UNFPA Raw Data Download Survey for SB

---

packages/database/src/migrations/20210804054649-CovidSamoaReinstateHouseholdOverlay-modifies-data.js
packages/database/src/migrations/20210805035710-CovidSamoaAddHouseholdPointdata-modifies-data.js
packages/database/src/migrations/20210902055844-UpdateUNFPASbRawDataDownloadSurvey-modifies-data.js

Includes already approved hotfixes
Post Release Note: @nick-beyondessential to move household vaccine status overlay down in Covid Samoa group via admin panel so it is no longer default.

[Hotfix] Release v2021-35-1

---

packages/web-frontend/cypress/config/dashboardReportUrls/default.json
packages/web-frontend/cypress/config/mapOverlayUrls/default.json

update the new viz details to maintain E2E test coverage
- Example
---

update default json for E2E

---

packages/data-broker/src/services/dhis/DhisService.js
packages/report-server/src/aggregator/Aggregator.ts

MEL-482 Hack (in a feature-flag fashion) until we get the time to work on MEL-481. We need this to release Fanafana Immunisation vizes this week

MEL-482: Allow fetching non regional DHIS data in report-server

---

.eslintrc

See https://beyondessential.slack.com/archives/C02DKC9U1FU/p1630986969002500

Add api-client to packages using ts eslint config

---

packages/admin-panel/cypress/e2e/survey/surveyImport.spec.js
packages/admin-panel/cypress/support/actions/importSurvey.js
packages/admin-panel/cypress/support/actions/index.js
packages/admin-panel/cypress/support/actions/survey.js
packages/admin-panel/cypress/support/commands.js
packages/web-frontend/cypress/config.json
packages/web-frontend/cypress/config/dashboardReportUrls/default.json
yarn.lock

Import a survey and check it through search .
- Example
---

Sol 265 import new survey

---

packages/admin-panel-server/src/app/createApp.ts
packages/admin-panel-server/src/connections/MeditrakConnection.ts
packages/admin-panel-server/src/routes/ExportDashboardVisualisationRoute.ts
packages/admin-panel-server/src/routes/ImportDashboardVisualisationRoute.ts
packages/admin-panel-server/src/viz-builder/dashboardVisualisation/DashboardVisualisationExtractor.ts
packages/admin-panel-server/src/viz-builder/dashboardVisualisation/validators.ts
packages/admin-panel-server/src/viz-builder/types.ts
packages/admin-panel/src/api/TupaiaApi.js
packages/admin-panel/src/pages/resources/DashboardItemsPage.js
packages/database/src/TupaiaDatabase.js
packages/database/src/modelClasses/DashboardRelation.js
packages/meditrak-server/src/apiV2/GETHandler/helpers.js
packages/meditrak-server/src/apiV2/dashboardItems/assertDashboardItemsPermissions.js
packages/meditrak-server/src/apiV2/dashboardRelations/GETDashboardRelations.js
packages/meditrak-server/src/apiV2/dashboardRelations/assertDashboardRelationsPermissions.js
packages/meditrak-server/src/apiV2/dashboardRelations/index.js
packages/meditrak-server/src/apiV2/dashboardVisualisations/CreateDashboardVisualisation.js
packages/meditrak-server/src/apiV2/dashboards/assertDashboardsPermissions.js
packages/meditrak-server/src/apiV2/index.js
packages/meditrak-server/src/apiV2/legacyReports/assertLegacyReportsPermissions.js
packages/meditrak-server/src/tests/apiV2/GETDashboardRelations.test.js
packages/meditrak-server/src/tests/apiV2/GETLegacyReports.test.js
packages/meditrak-server/src/tests/apiV2/dashboardItems/GETDashboardItems.test.js
packages/meditrak-server/src/tests/testUtilities/dashboards/setupDashboardTestData.js
yarn.lock

MEL-454: Viz builder export improvements

---

packages/data-api/package.json
packages/data-api/scripts/fullRefreshAnalyticsTable.sh

Looks like this was accidentally broken in afbe089e445a98ee47081d018675086c2776e68f

Fix refresh table script

---

packages/meditrak-app/app/assessment/actions/submitSurvey.js
packages/meditrak-app/ios/TupaiaMediTrak/Info.plist
packages/meditrak-app/package.json
packages/meditrak-server/src/apiV2/postChanges.js
packages/meditrak-server/src/apiV2/utilities/translateObjectFields.js

Hot fix WAI-939: survey submissions with empty answers blocking sync

---

packages/devops/scripts/deployment/deployPackages.sh

WAI-940 Delete front end builds at start of startup script

---

packages/admin-panel/package.json
packages/web-frontend/package.json

React not happy with browser list settings in package.json.
- replaced browser settings to use defaults in admin front-end and web-front-end
---

add package.json browser list

---

packages/devops/scripts/deployment/deployPackages.sh

ks_NZ22_tst

---

packages/devops/scripts/deployment/deployPackages.sh

ks_WAI31_tst

---

packages/web-frontend/cypress/scripts/generateConfig/configSchema.js
packages/web-frontend/cypress/scripts/testE2e/testE2e.js

RN-52: Remove e2e build error in CI

---

packages/lesmis/src/components/Visuals/VisualHeader.js

Now that react-scripts is updated, linter errors such as this crash the front-end builds so this needs to be fixed asap.

Fix lesmis prop types

---

packages/admin-panel/src/importExport/ImportModal.js
packages/meditrak-server/src/apiV2/export/exportSurveyResponses/exportResponsesToFile.js
packages/meditrak-server/src/apiV2/import/importSurveyResponses/importSurveyResponses.js

WAI-94: Include answers to deleted questions in export

---

packages/expression-parser/src/expression-parser/ExpressionParser.js

MEL-485 Allow expression parser to use all mathjs functions

---

packages/expression-parser/src/expression-parser/ExpressionParser.js

This PR replaces https://github.com/beyondessential/tupaia/pull/3183 (branch name)

ME:-484 Remove default to zero for empty string

---

packages/database/src/migrations/20210914232504-UpdateUNFPAWsRawDataDownloadSurvey-modifies-data.js

~[NOT-435](https://linear.app/bes/issue/NOT-435/raw-data-download-for-samoa-unfpa)~ PHX-54

PHX-54: Update UNFPA Raw Data Download Survey for WS

---

packages/ui-components/src/components/ListVisual/ListVisual.js

Hotfix release 2021-37-1

---

packages/database/src/migrations/20210907111655-LESMISNonTargetDistricts-modifies-data.js
packages/database/src/migrations/20210907222655-LESMISPrimaryEducationCohortSurvivalRate-modifies-data.js

* WAI-41 Add attribute type to lesmis non-target districts
* WAI-41 Add primary education HLO1 list to country level with drilldown
* WAI-41 Update reports to new config style
* WAI-41 Remove using 'last' from report
* WAI-41 Change <= to <
* WAI-41 Change aggregations to PER_PERIOD_PER_ORG_GROUP
Co-authored-by: Klaus-S <69126149+Klaus-S@users.noreply.github.com>
- Example
---

Sima pulling in the latest dev

---

packages/devops/scripts/deployment/checkoutLatest.sh

[HOT FIX] WAI-952: Add remote tracking of correct branch, if it exists

---

packages/report-server/src/reportBuilder/transform/functions/mergeRows/getMergeStrategy.ts
packages/report-server/src/reportBuilder/transform/functions/mergeRows/mergeRows.ts

O(n^2) was causing noticable slowness for 50k+ rows

Performance fix for in-efficient code in mergeRows

---

scripts/bash/downloadEnvironmentVariables.sh

Will solve the fact that dev and feature deployments are not coming online

Fix startup script: don't use `exec` from cron job

---

packages/devops/scripts/lambda/createOrRestoreDeployment.py

ks_mapoverlays_test

---

packages/database/src/migrations/20210923024807-LESMISDropOutRateDistrictOverlay-modifies-data.js

wai-7: drop out rates in lesmis overlays
new migration
---

WAI-7: drop out rates in lesmis overlays

---

packages/ui-components/src/components/Map/Markers/MeasurePopup.js

- Fix regression in the map measure popups
---

Fix map pop ups

---

packages/data-broker/src/services/dhis/DhisService.js

RN-104 Fix duplicate fetch

---

packages/database/src/migrations/20210921051858-LESMISRepititionRatesDistrict-modifies-data.js

Added migration file for WAI-6 LESMIS repition rates 2021 district level
- Example
---

Wai-6 lesmis repetition rate district level

---

packages/database/src/migrations/20210923024807-LESMISDropOutRateDistrictOverlay-modifies-data.js

WAI-7: LESMIS drop out rates overlays
New migration file.
---

WAI-7: LESMIS drop out rates overlays

---

packages/database/src/migrations/20210913044208-LESMIS-GER-Map-Overlays-modifies-data.js
packages/database/src/migrations/20210921211920-LESMIS-GIR-map-overlays-modifies-data.js
packages/database/src/migrations/20210924030256-lesmis-number-of-students-overlays-modifies-data.js
packages/ui-components/src/components/Map/Markers/MeasurePopup.js

- add number of students overlays
---
See issue

Wai 18 number of students overlays

---

packages/ui-components/src/components/Map/Legend/LegendEntry.js
packages/ui-components/src/components/Map/PopupDataItemList.js
packages/web-frontend/src/sagas.js

Release 2021 38 - to trigger code ship

---

packages/ui-components/src/components/Map/AreaTooltip.js
packages/ui-components/src/components/Map/InteractivePolygon.js
packages/ui-components/src/components/Map/PopupDataItemList.js

- fix Transparent shaded polygons not showing
- update AreaTooltips to new format
---

Hotfix map components regresssion

---

packages/meditrak-app/android/app/build.gradle
packages/meditrak-app/android/app/src/main/AndroidManifest.xml
packages/meditrak-app/android/build.gradle

Was: https://github.com/beyondessential/tupaia/pull/3294

RN-108: Bumped gradle version in Andriod build to 4.0.1

---

packages/report-server/src/aggregator/Aggregator.ts

RN-120: Not detecting data services from FetchEvents in report-server
Add detectDataServices to fetchEvents, remove dataService property.
---

RN-120: Not detecting data services from FetchEvents in report-server 

---

packages/report-server/src/aggregator/Aggregator.ts

RN-121
The issue was that SUM_PREVIOUS_EACH_DAY only works if you provide a period. Report server was not providing a period, only start/end dates.

RN-121 Fix report server SUM_PREVIOUS_EACH_DAY aggregation returns slice

---

packages/web-frontend/src/screens/mobile/RegionScreen/index.js

https://beyondessential.slack.com/archives/C01MAA3NKM1/p1633310619027900

Fix tupaia mobile not showing page

---

packages/admin-panel-server/src/viz-builder/dashboardVisualisation/DashboardVisualisationExtractor.ts
packages/ui-components/src/components/Map/MarkerLayer.js
packages/web-frontend/src/screens/mobile/RegionScreen/index.js

Reverts beyondessential/tupaia#3329

Revert "Master"

---

packages/entity-server/src/__tests__/__integration__/EntityDescendantRoutes.test.ts
packages/entity-server/src/__tests__/__integration__/EntityRelationshipsRoutes.test.ts
packages/entity-server/src/__tests__/__integration__/EntityRelativesRoutes.test.ts
packages/entity-server/src/__tests__/__integration__/EntityRoutes.test.ts
packages/entity-server/src/routes/hierarchy/middleware/attachEntityContext.ts

RN-136: Fixed entity-server returning 403 when fetching for empty list of entities

---

packages/web-frontend/cypress/scripts/generateConfig/VisualisationFilter.js

Running the e2e script currently causes the following issue in our CI/CD:

Hotfix: Fix visualisation filter

---

packages/admin-panel/package.json
packages/admin-panel/rollup.config.js
scripts/bash/buildInternalDependencies.sh
scripts/bash/getInternalDependencies.sh

- add admin panel library to ci cd
---

Admin Panel Library Build

---

packages/lesmis/src/App.js
packages/lesmis/src/components/LocaleMenu.js
packages/lesmis/src/constants/locale.js

- Remember user settings for locale in local storage
- On App start load the locale and set the default url

Wai 935 save locale preference

---

packages/web-frontend/public/index.html

Turn off raygun for non-prod

---

packages/database/src/migrations/20211101040146-WAI-1021-TongaContactTracingVisual-modifies-data.js
packages/report-server/src/__tests__/reportBuilder/context/buildContext.test.ts
packages/report-server/src/reportBuilder/context/buildContext.ts
packages/report-server/src/reportBuilder/context/types.ts
packages/report-server/src/reportBuilder/transform/parser/functions/context.ts
packages/report-server/src/reportBuilder/transform/parser/functions/index.ts

- Add a new context function to convert from `id` to `code`
- Add matrix visual for contact tracing

Add Contact Tracing visual for Tonga COVID-19

---

packages/database/src/migrations/20211102023345-TongaContactTracingCustomRawDataDownload-modifies-data.js
packages/web-config-server/src/apiV1/dataBuilders/helpers/translateEventEntityIdsToNames.js

- Add migration for custom data download for Tonga Covid Contact Tracing
- Bugfix issue with multiple `entityIdToName` translations

WAI-1022 tonga covid raw data download

---

packages/meditrak-server/src/apiV2/import/importSurveyResponses/importSurveyResponses.js

Fixes an issue with import now that we're exporting entity questions as codes rather than ids

[HOT FIX]: Sanitize entity answers before they are imported

---

packages/database/src/migrations/20211102023345-TongaContactTracingCustomRawDataDownload-modifies-data.js
packages/meditrak-server/src/apiV2/import/importSurveyResponses/importSurveyResponses.js
packages/web-config-server/src/apiV1/dataBuilders/generic/dataDownload/rawDataValues.js
packages/web-config-server/src/apiV1/dataBuilders/helpers/translateEventEntityIdsToNames.js
packages/web-config-server/src/apiV1/utils/mergeTableDataOnKey.js

A couple of hotfixes that need to be released outside of our usual schedule

Release v2021-44-1

---

packages/web-frontend/src/containers/MapOverlayBar/Content.js
packages/web-frontend/src/containers/MapOverlayBar/Control.js
packages/web-frontend/src/containers/MapOverlayBar/TitleAndDatePicker.js
packages/web-frontend/src/styles/index.js

PHX-130
Loading skeleton component
https://linear.app/bes/issue/PHX-130#comment-4c6c2f91

Phx 130 loading component

---

packages/meditrak-app/android/app/src/main/AndroidManifest.xml
packages/meditrak-app/android/build.gradle
packages/meditrak-app/ios/TupaiaMediTrak/Info.plist
packages/meditrak-app/package.json

WAI-1031: Upgrade target sdk version

---

packages/devops/scripts/deployment/setupGoldMaster.sh
packages/devops/scripts/lambda/resources/startup.sh

WAI-963: Minor tweaks

---

packages/devops/scripts/ci/triggerRedeploy.sh
packages/devops/scripts/lambda/actions/redeploy_tupaia_server.py
packages/devops/scripts/lambda/actions/spin_up_dhis_deployment.py
packages/devops/scripts/lambda/actions/spin_up_tupaia_deployment.py
packages/devops/scripts/lambda/actions/swap_out_tupaia_server.py
packages/devops/scripts/lambda/helpers/creation.py
packages/devops/scripts/lambda/helpers/networking.py

WAI-963
Commit messages show the changes made, which are a mix of suggestions after Friday's presentation, and two commits making redploy via codeship more robust if the instance is stopped (found this because @billli0 was working at 10pm on a Sunday!!)

WAI-963: Presentation feedback improvements

---

packages/database/src/migrations/20211117221003-AddVillageParentsForCovidSamoaHierarchy-modifies-data.js

Think this one needs to be a hotfix since Samoa are doing a second lockdown tomorrow

RN-131: Add entity relations for some villages in Samoa for Covid Samoa project

---

packages/devops/scripts/lambda/actions/spin_up_tupaia_deployment.py
packages/devops/scripts/lambda/helpers/creation.py

Tested with a feature branch `spin_up_tupaia_deployment`, production release through CI.

Only add default Start/StopAtUTC tags for non-prod

---

packages/devops/scripts/ci/triggerRedeploy.sh
packages/devops/scripts/lambda/actions/redeploy_tupaia_server.py

Master to Dev

---

packages/lesmis/src/components/DashboardReport.js
packages/lesmis/src/components/DashboardReportModal.js
packages/lesmis/src/components/Visuals/Chart.js
packages/lesmis/src/translations/en.json
packages/lesmis/src/utils/useExportToPNG.js
packages/ui-components/src/components/Chart/BarChart.js
packages/ui-components/src/components/Chart/CartesianChart.js
packages/ui-components/src/components/Chart/Legend.js
packages/ui-components/src/components/Chart/LineChart.js
packages/ui-components/src/components/Chart/PieChart.js
packages/ui-components/src/components/Chart/VerticalTick.js
packages/ui-components/src/components/Chart/XAxis.js
packages/ui-components/src/components/Chart/YAxes.js
packages/ui-components/src/components/Chart/constants/propTypes.js
packages/ui-components/stories/chart/data/stackedBarChart.json
packages/utils/src/addExportDateAndOriginInExcelExportData.js
packages/web-config-server/src/export/excelFormatters/formatMatrixDataForExcel.js
packages/web-frontend/src/components/DialogTitleWrapper.js
packages/web-frontend/src/components/ExportDialog.js
packages/web-frontend/src/components/Flexbox.js
packages/web-frontend/src/components/View/ChartWrapper.js
packages/web-frontend/src/components/View/utils.js
packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialog.js
packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialogContent.js
packages/web-frontend/src/utils/exports.js

- add support for export options to ui-components
- refactor tupaia export modal
- add export options to tupaia
- add export options to lesmis
---
See Issue

WAI-1024 add export options

---

packages/database/src/migrations/20211123223023-DeleteAccidentalTestCountry-modifies-data.js

- https://linear.app/bes/issue/PHX-199/there-is-a-country-in-the-country-table-called-klaus-test
This migration removes an accidental country from the country table as per the above ticket

PHX-199 Delete Test Country

---

packages/database/src/migrations/20211125021151-ChangePermissionForPenFaa-modifies-data.js

Change permission name to drop apostrophe

---

packages/database/src/migrations/20211123053316-AddProjectPenFaaSamoa-modifies-data.js

PHX-165 PenFa'a Samoa project creation
Note: have not confirmed we need to exclude cases or other entity types in `frontendExcludedTypes`. If so we can easily add it later in admin-panel.

PHX-165 Insert PenFa'a Samoa project

---

packages/database/src/migrations/20211123053316-AddProjectPenFaaSamoa-modifies-data.js
packages/database/src/migrations/20211125021151-ChangePermissionForPenFaa-modifies-data.js
packages/devops/scripts/deployment/buildDeployablePackages.sh
packages/devops/scripts/deployment/setupGoldMaster.sh
packages/devops/scripts/lambda/actions/spin_up_tupaia_deployment.py
packages/devops/scripts/lambda/resources/startup.sh
packages/ui-components/src/components/Chart/Table/Table.js
packages/ui-components/src/components/Chart/Table/getChartTableData.js
yarn.lock

Sima Create Instance

---

packages/web-config-server/examples.http

Update web-config-server examples.http to use supported routes

---

packages/devops/scripts/ci/triggerRedeploy.sh
packages/devops/scripts/lambda/resources/startup.sh

WAI-1051: Fail when some part of the build errors

---

packages/ui-components/src/components/Chart/ReferenceLines.js
packages/ui-components/stories/chart/data/barChartViewContent.json

Requirement from PHX-168
Support fixed line in bar chart

Support fixed line in bar chart

---

packages/ui-components/src/components/DataTable/useDataTableExport.js

PHX-206
Bug caused by PHX-154 that `Header` have been modified as a function or string.

PHX-206 Get columns using header groups

---

packages/database/src/migrations/20211130040028-UpdateFacilityNamesSolomonIslands-modifies-data.js

MAUI-227 Change multiple Vura facility names in Solomon Islands
Migration file with updated values for two facility records in the entity table.

MAUI-227 Change multiple Vura facility names in Solomon Islands

---

packages/database/src/migrations/20211201052040-AddPhiPermissionGroup-modifies-data.js

PHX-166: Add permission group for PHI data in a project
Add new permission groups and update others to enable PHI data permissions.

phx-166-add-permission-group-for-phi

---

packages/admin-panel/src/VizBuilderApp/api/queries/index.js
packages/admin-panel/src/VizBuilderApp/api/queries/useSearchDataSources.js
packages/admin-panel/src/VizBuilderApp/components/DataLibrary/DataElementDataLibrary.js
packages/admin-panel/src/VizBuilderApp/components/DataLibrary/index.js
packages/admin-panel/src/VizBuilderApp/components/Panel.js
packages/admin-panel/src/utilities/index.js
packages/admin-panel/src/utilities/useDebounce.js
packages/ui-components/src/components/DataLibrary/DataLibrary.js
packages/ui-components/src/components/DataLibrary/DataTypeTabs.js
packages/ui-components/src/components/DataLibrary/InputField.js
packages/ui-components/src/components/DataLibrary/ResultsList.js
packages/ui-components/src/components/DataLibrary/SelectedDataList.js
packages/ui-components/src/components/DataLibrary/index.js
packages/ui-components/src/components/DataLibrary/options.js
packages/ui-components/src/index.js
packages/ui-components/stories/dataLibrary.stories.js

RN-150
- Add Data Library UI component
- Add data library to Fetch step in viz builder

RN-150 Data Library search filter transfer

---

packages/meditrak-app/appcenter-post-clone.sh

HOTFIX: Added --ignore-engines to post-clone script

---

packages/database/src/migrations/20211207002048-DropNotificationTriggerFromReportTable-modifies-schema.js
packages/database/src/runPostMigration.js

Dropped notification trigger from report table to allow saving large reports

RN-238: Fix error when trying to save a large viz

---

packages/database/src/migrations/20211209033916-SeparateFlutrackingAndCovid19Projects-modifies-data.js

MAUI-258: Separate FluTracking and COVID-19 into 2 Distinct Projects
-Add project
-update covidau name

MAUI-258: Separate FluTracking and COVID-19 into 2 Distinct Projects
