beyondessential/tupaia

packages/admin-panel/src/pages/resources/SocialFeedPage.js, packages/admin-panel/src/pages/resources/SurveyResponsesPage.js, packages/admin-panel/src/widgets/InputField.js, packages/ui-components/src/components/Inputs/DatePicker.js, packages/ui-components/src/components/Inputs/TextField.js
- Make the date picker and the dates in the admin-panel tables show local dates (this is essentially reverting the admin panel to existing behaviour)
This ensures that the dates are accurate and consistent across AdminPanel. ie when you set a Date and Time using the date-picker the same value shows up in the table. Also the date in the tables is the 100% correct date and is formatted to show the timezone information using +/- hours GMT. However the issue remains that it is formatted differently to other places on Tupaia.org which can cause confusion. 
I tried to incorporate the timezone from the recordData into the dates in the datePicker and table. There were a couple of problems with this approach though.
1. Cannot easily set a timeZone per instance of MaterialUI date-picker
2. FeedItem …
=> 925 admin panel date picker fixes

README.md, tupaia-packages.code-workspace
[No issue]
The status is for `master`, let me know if we should use `dev` instead. Next steps would be adding code coverage reports for individual packages (especially internal ones such as `data-broker`, `aggregator` etc)
It looks like this:
=> Add build status badge

packages/access-policy/package.json, packages/admin-panel/package.json, packages/aggregator/package.json, packages/auth/package.json, packages/data-api/package.json, packages/data-broker/package.json, packages/database/package.json, packages/devops/package.json, packages/dhis-api/package.json, packages/eslint-config-typescript/package.json, packages/export-chart-lambda/package.json, packages/meditrak-app/package.json, packages/meditrak-server/src/devops/CreateThumbnail/package.json, packages/psss/package.json, packages/ui-components/package.json, packages/utils/package.json, packages/web-config-server/package.json, packages/web-frontend/package.json
[No issue]
I had removed the `private` field when open sourcing our codebase. This was a wrong interpretation of the field: it actually refers to whether the package can be published in the npm registry, not whether it is "Open source".
We really only need this for `meditrak-app`, since the package must be `private` for the `workspaces.nohoist` field in `meditrak-app/package.json` to work. But I thought we should keep using `private` in all `package.json`, since we wouldn't want our monorepo ending up in npm anyway.
=> Reinstate private field

packages/meditrak-server/src/database/models/Option.js
Addresses: https://github.com/beyondessential/tupaia-backlog/issues/794
I'm sure theres a way to do this same functionality using `hasContent` (which I removed from this file) but I couldn't figure out how. This code works but I'm happy to do it a cleaner way if there's an obvious solution
=> 794 fix optionset import

packages/meditrak-app/ios/Podfile.lock, packages/meditrak-app/package.json, yarn.lock
Gets podfile and package.json in step, and applies the latest react-native patch
Required to get iOS simulator version running in dev
=> Update react native patch version

packages/database/package.json, yarn.lock
Required if we want to use `foreignKey` when creating tables through db-migrate, now we have upgraded to node 12
See https://github.com/db-migrate/node-db-migrate/issues/635
This only updates the underlying driver, so there are no changes to the db-migrate interface we deal with.
=> Update db-migrate postgres driver

packages/database/src/DatabaseModel.js, packages/database/src/TupaiaDatabase.js, packages/database/src/cachers/EntityHierarchyCacher.js, packages/database/src/migrations/20201002193222-AddEntityParentIdIndex-modifies-schema.js, packages/database/src/tests/cachers/EntityHierarchyCacher.fixtures.js, packages/database/src/tests/cachers/EntityHierarchyCacher.test.js, packages/database/src/utilities/runDatabaseFunctionInBatches.js, tupaia-packages.code-workspace
From ~18 minutes down to ~40 seconds for a full run
@kael89 I'm sorry about the number of times you've had to re-review this same section of code. My motivations here was that I realised that the cache invalidation logic for handling each individual case was becoming quite complex, and that if I could get the time for a full run down by enough, we could just re-run the full build whenever something changed, simplifying things greatly.
=> Speed up full build and cache

packages/web-frontend/src/components/DateRangePicker/DateRangePicker.js, packages/web-frontend/src/containers/MeasureBar/Control.js, packages/web-frontend/src/containers/MeasureBar/index.js
- Measures use correct default date
- Prevent set dates to the same dates (this prevents multiple requests)
=> 1374 fix default date is wrong in map overlays

packages/database/src/tests/scaffolding.test.js
The database package test fails sometimes but it will pass when rebuilding the test.
Add database close command after test finished. I rebuilt the tests twice to make sure it is solved. We can investigate if it happens again.
=> Fix database test issue

packages/auth/src/AccessPolicyBuilder.js, packages/auth/src/__tests__/AccessPolicyBuilder.test.js, packages/database/src/DatabaseChangeChannel.js, packages/database/src/DatabaseModel.js, packages/database/src/cachers/EntityHierarchyCacher.js, packages/database/src/migrations/20201008205444-IncludeOldRecordInChangeNotifications-modifies-schema.js, packages/database/src/modelClasses/Indicator.js, packages/database/src/tests/cachers/EntityHierarchyCacher.fixtures.js, packages/database/src/tests/cachers/EntityHierarchyCacher.test.js, packages/meditrak-server/src/database/models/AccessRequest.js, packages/meditrak-server/src/database/models/Answer.js, packages/meditrak-server/src/database/models/Question.js, packages/meditrak-server/src/database/models/Survey.js, packages/meditrak-server/src/database/models/SurveyResponse.js, packages/meditrak-server/src/database/models/UserEntityPermission.js, packages/meditrak-server/src/dhis/DhisChangeDetailGenerator.js, packages/meditrak-server/src/externalApiSync/SyncQueueChangesManipulator.js, packages/meditrak-server/src/tests/dhis/DhisChangeDetailGenerator.test.js
The commits, in order, achieve the following:
1. Added two tests to catch edge cases of modifying an entity relation record
2. Modified change notification to include `old_record` and `new_record` instead of just `record` (which was previously old for deletes and new for creates/updates)
3. Update every instance of `record` being used within a change to deal with either `old_record` or `new_record` (or both!) instead (plus deprecated `onChange` in favour of `notifiers`)
4. Get new edge case tests passing by handling old and new records in the hierarchy cacher
=> Add old record to change notifications

packages/meditrak-server/src/tests/scaffolding.test.js, packages/web-config-server/src/tests/scaffolding.test.js
[No issue] Attempting to solve our DB connectivity issues during test run. Hopefully this will solve them, but even if not it's something we should do anyway.
In fact, `mocha` is forgiving but the same tests under `jest` would just hang and never finish, as we've found out during the mocha-to-jest conversion project.
=> Close DB connections

packages/web-frontend/src/components/DateRangePicker/DateRangePicker.js, packages/web-frontend/src/containers/MeasureBar/Control.js, packages/web-frontend/src/containers/MeasureBar/index.js
(Reopening a PR that was accidentally closed https://github.com/beyondessential/tupaia/pull/1436)
- Measures use correct default date
- Prevent set dates to the same dates (this prevents multiple requests)
=> 1374 fix default date is wrong in map overlays (2)

packages/database/src/DatabaseModel.js, packages/database/src/migrations/20201009035426-AddImmutableTableTrigger-modifies-schema.js, packages/database/src/modelClasses/Entity.js, packages/database/src/runPostMigration.js
The soft cache was being correctly invalidated when an entity was modified, but some of the cached functions also depend on ancestor_descendant_relation. This adds invalidation when entity_relation changes, so that the soft cache doesn't end up with a stale version of the hierarchy.
=> Invalidate soft cache on change to entity relation

packages/web-frontend/cypress.env.example.json, packages/web-frontend/cypress/config/dashboardReports.example.jsonc, packages/web-frontend/cypress/config/orgUnitMap.json, packages/web-frontend/cypress/constants.js, packages/web-frontend/cypress/e2e/dashboardReports.spec.js, packages/web-frontend/cypress/scripts/generateConfig.js, packages/web-frontend/cypress/scripts/generateDashboardReportConfig.js, packages/web-frontend/cypress/support/actions.js, packages/web-frontend/cypress/support/helpers.js, packages/web-frontend/cypress/support/utils.js, packages/web-frontend/src/components/DropDownMenu.js, packages/web-frontend/src/containers/DashboardGroup/index.js, packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialogContent.js, packages/web-frontend/src/containers/OverlayDiv/components/ProjectPage/ProjectCard.js, scripts/node/Script.js, scripts/node/testAll.js, scripts/node/utilities.js, scripts/node/validateTests.js
[1420: Parameterise report e2e tests](https://github.com/beyondessential/tupaia-backlog/issues/1420) - only the first requirement (**organisation unit** parameters)
* Did a major refactor of the report snapshot capturing logic. Instead of using the UI to navigate to a report, we use a direct URL now.
**Pros:**
✔ Much easier testing logic!
✔ Works for all types of reports, both expandable and not
✔The url can be used to identify a specific test setup, since it contains most information about a report's selected parameters. Example: `/covidau/AU/COVID-19?report=COVID_AU_Total_Cases_Each_State_Per_Day`
**Cons:**
❌We loose the benefit of using a more realistic user path, which would be clicking around portal components to get to a report.
It then occurred to me: the scope of those tests are …
=> 1420: Parameterise report e2e tests

packages/devops/scripts/ci/deployBackend.sh, packages/devops/scripts/ci/deployFrontend.sh, packages/devops/scripts/ci/determineDeploymentUrl.sh, packages/devops/scripts/ci/pullLatest.sh, packages/devops/scripts/ci/runMigrations.sh, packages/devops/scripts/ci/setupTestDatabase.sh, packages/devops/scripts/ci/testBackend.sh, packages/devops/scripts/ci/testFrontend.sh, packages/devops/scripts/ci/testInternalDependencies.sh, packages/devops/scripts/ci/updateCiEnvVars.sh, packages/devops/scripts/ci/utils.sh, packages/devops/scripts/ci/validateBranchName.sh, packages/devops/scripts/ci/validateTests.sh, packages/devops/scripts/ci/waitForPostgres.sh, packages/devops/scripts/deployment/deployLatestRepositories.sh, packages/devops/scripts/deployment/startup.sh, packages/devops/scripts/utility/detectStage.sh, packages/devops/scripts/utility/renewSslCertificate.sh, packages/web-config-server/run_preaggregation.sh, scripts/bash/backendStartDev.sh, scripts/bash/buildInternalDependencies.sh, scripts/bash/dumpDb.sh, scripts/bash/storeDotEnvOnParameterStore.sh, scripts/bash/updateParameterStoreEnvVars.sh, scripts/bash/validate.sh, tupaia-packages.code-workspace
[No issue]
* Replaced `\e` with `\033` as an terminal escape character, since the latter doesn't work in MacOS
* Used the [shell-format](https://marketplace.visualstudio.com/items?itemName=foxundermoon.shell-format) VSCode extension to format existing shell scripts.
* Indented scripts to consistently use 4 spaces
=> Fix terminal color output for MacOS

packages/database/src/migrations/20201026223059-UpdateLinkOnFeedItems-modifies-data.js, packages/meditrak-server/src/social/feedScraper.js
[Update the link generation on social feed items](https://github.com/beyondessential/tupaia-backlog/issues/1429#issuecomment-716313917)
1. Update value with key `link` in `template_variables` in `feed_item` table, from legacy link format: `https:\\mobile.tupaia.org\facility\{faclitycode}` or `https:\\mobile.tupaia.org\country\{countrycode}`
to `https:\\mobile.tupaia.org\explore\{code}` 
2. Update the link generation in `meditrak-server`
=> 1429 update link generation and existed links data for feed items

packages/database/src/modelClasses/Entity.js, packages/meditrak-server/src/routes/exportSurveyResponses.js
Now outputs the empty survey response (i.e. info row labels) as well as the "no data" comment if there are no survey responses.
Also cleaned up the code in the immediate area a little, and fixed a bug where the survey responses were being exported in an indeterminate order.
=> Allow exporting empty survey response

packages/web-frontend/src/constants/mapbox.js
Now that the custom mapbox tile set styles have been moved from our personal test accounts to the sussol account, we need to update the config in the web-front end code to match.
---
=> update mapbox tileset config

packages/database/src/migrations/20201019011335-RemoveRedundantDataInFijiEntity-modifies-data.js
While this is updating a migration that has already been released, a strict no-no, in this case it's ok because we don't care about the change running on production. In production, the migration will be marked as already run, so the change will have no effect. In e2e test environments, it will run with the change, so those environments will be fixed.
=> Fix e2e migrations breaking: delete any survey responses attached to the entity being deleted

packages/web-frontend/src/utils/getFacilityThumbnailUrl.js
- Update the thumbnail url to use the dev thumbnails
Note: To make this change work, I first updated the aws lambda trigger for CreateThumbnail to pick up uploads to the `dev_uploads` folder
---
=> update dev thumbnails

packages/meditrak-server/src/devops/CreateThumbnail/CreateThumbnail.js, packages/meditrak-server/src/s3/uploadImage.js
The issue was actually a regression caused by a previous feature for uploading profile images. It looks like that change was never actually needed and always saving the image as a png works fine. I regression tested the profile image uploads and they still work after this change.
- Fix s3 image uploads file types
- Fix create thumbnail logging
---
=> fix image uploads

yarn.lock
I was getting an error running the web-frontend app and could not run the app. Strangely this issue was only happening for me. It is not 100% clear what the root cause of the issue is but re-installed webpack-dev-server has resolved it. Prior to doing this, I tried clearing all node_nodules and yarn cache and re-installing but that did not work.
Stack trace of the error prior to the fix:
- Re-installed webpack-dev-server in the web-frontend package
---
=> Fix fsevents dependency bug

packages/web-frontend/cypress/support/actions.js, packages/web-frontend/cypress/support/commands.js
I tested the login form and it no longer loads twice. I believe the changes I made to the App.js and login flow in the sagas fixed this ([1528](https://github.com/beyondessential/tupaia/pull/1528)). However it could have been something else that fixed it - I'm not 100% sure to be honest but the main thing is that it works. I removed the hack that was in place in the end-to-end tests and ran them and the login flow works as expected.
**Notes on End To End Testing**
Setting up and running the tests went really smoothly for me. It is awesome to see these tests in working - great work @kael89! On the dev branch the tests were failing after login but on the most up to date branch [1574](https://github.com/beyondessential/tupaia/pull/1574) the tests ran perfectly (I stopped the tests after …
=> 1358 fix login form renders twice

packages/database/src/migrations/20201026232410-DeleteEntityPublicHealthService-modifies-data.js
[Safely archive Public Health Service, Tonga](https://github.com/beyondessential/tupaia-backlog/issues/1397)
Here are the manual steps:
1. Delete the survey responses which belong to Public Health Service
2. Hard delete the datavalues for Public Health Service on DHIS2
3. Do migration to delete `Public Health Services` from the clinic and entity tables (this PR)
=> Delete Public Health Services Entity

packages/admin-panel/src/pages/resources/CountriesPage.js
Addresses: https://github.com/beyondessential/tupaia-backlog/issues/1399
Basically when you create a new country the modal says "Hello" (the default EditModal.js message) and this change fixes that happening here
=> 1399 remove hello from country modal

packages/meditrak-server/src/routes/accessRequests/EditAccessRequests.js, packages/meditrak-server/src/routes/accessRequests/GETAccessRequests.js, packages/meditrak-server/src/routes/accessRequests/assertAccessRequestPermissions.js, packages/meditrak-server/src/tests/routes/accessRequests/EditAccessRequests.test.js, packages/meditrak-server/src/tests/routes/accessRequests/GETAccessRequests.test.js
- Update add additional checks to prevent a user from self elevating their permissions
- Add unit tests for GET and Edit handlers
=> 1132: Add unit tests for /accessRequests endpoint

packages/meditrak-server/src/app/addRoutesToApp.js, packages/meditrak-server/src/routes/index.js, packages/meditrak-server/src/routes/userEntityPermissions/CreateUserEntityPermissions.js, packages/meditrak-server/src/routes/userEntityPermissions/EditUserEntityPermissions.js, packages/meditrak-server/src/routes/userEntityPermissions/GETUserEntityPermissions.js, packages/meditrak-server/src/routes/userEntityPermissions/assertUserEntityPermissionPermissions.js, packages/meditrak-server/src/routes/userEntityPermissions/index.js, packages/meditrak-server/src/tests/routes/userEntityPermissions/CreateUserEntityPermissions.test.js, packages/meditrak-server/src/tests/routes/userEntityPermissions/DeleteUserEntityPermissions.test.js, packages/meditrak-server/src/tests/routes/userEntityPermissions/EditUserEntityPermissions.test.js, packages/meditrak-server/src/tests/routes/userEntityPermissions/GETUserEntityPermissions.test.js
- Add CreateUserEntityPermissions.js
- Add unit tests for user entity permissions CRUD handling
=> 1132: Add create handler for /userEntityPermissions route

packages/devops/configs/servers.conf
We have been using http/1.1 by default. According to https://developers.google.com/web/tools/chrome-devtools/network/reference?utm_source=devtools#timing-explanation 
> There are already six TCP connections open for this origin, which is the limit. Applies to HTTP/1.0 and HTTP/1.1 only.
This moves us to http/2
Will need to be manually applied - there is no CI/CD set up for nginx settings.
=> Use http/2 protocol on all requests

packages/web-frontend/src/styles/index.js
[1365 - hover text difficult to read](https://github.com/beyondessential/tupaia-backlog/issues/1365)
- Add style for tooltip's transparent background
=> Add style for tooltip's transparent background

packages/web-frontend/src/components/View/ChartWrapper/ChartWrapper.js, packages/web-frontend/src/components/View/ChartWrapper/helpers.js, packages/web-frontend/src/components/View/ChartWrapper/parseChartConfig.js
https://github.com/beyondessential/tupaia-backlog/issues/1538
Ended up filtering all non-numeric data out in `ChartWrapper`. Logically, I can't think of a reason why there would be a use for non-numeric data, so this seems logical to me, and it can always be changed if needed.
=> 1538 no bar for no data

jest.config.base.json
Add a `jest.config.base.json` in root. It is resuable in sub pacakges while jest testing. 
If any pacakges need extension jest config, you can easily add a custom jest config under sub pacakge.
=> Add a base jest config in root

packages/indicators/src/__tests__/builders/buildArithmetic/buildArithmetic.test.ts, packages/indicators/src/__tests__/builders/helpers/helpers.test.ts, packages/indicators/src/builders/buildArithmetic.ts, packages/indicators/src/builders/helpers.ts, packages/indicators/src/types.ts, packages/utils/src/__tests__/validation/validatorFunctions.test.js, packages/utils/src/validation/validatorFunctions.js
[No issue]
This adds support for single strings to be specified as an indicator's `aggregation`, eg
```json
{
"formula": "MRDT_POS_CONSULT_WEEKLY / SSWT1001",
"aggregation": "FINAL_EACH_WEEK"
}
```
is equivalent to
```json
{
"formula": "MRDT_POS_CONSULT_WEEKLY / SSWT1001",
"aggregation": { "MRDT_POS_CONSULT_WEEKLY": "FINAL_EACH_WEEK", "SSWT1001": "FINAL_EACH_WEEK" }
}
```
=> Indicators - support string aggregation

packages/psss/src/components/ComingSoon.js, packages/psss/src/components/Layout.js, packages/psss/src/components/index.js, packages/psss/src/containers/Modals/ExportModal.js, packages/psss/src/containers/Panels/WeeklyReportsPanel.js, packages/psss/src/views/CountriesReportsView.js, packages/psss/src/views/Tabs/AlertsTabView.js, packages/psss/src/views/Tabs/ArchiveTabView.js, packages/psss/src/views/Tabs/EventBasedTabView.js, packages/psss/src/views/Tabs/OutbreaksTabView.js, packages/psss/src/views/Tabs/WeeklyCasesTabView.js
- Add coming soon message to export modals, alerts and outbreaks pages events based data page, sentinel case data
- Comment out the alerts summary cards from the sidebar. I initially added the coming soon message to them but it looked too messy.
---
See [the issue](https://github.com/beyondessential/tupaia-backlog/issues/1576) for screenshots
=> Add psss stubs

codeship-steps.yml
Until the startup process is updated, or `report-server` code is merged in production
=> Do not deploy report server

packages/database/src/migrations/20201123002611-AddNZToPSSSProject-modifies-data.js
Need to add the `NZ` org unit to the PSSS project hierarchy.
This branch should be merge **after** the data tasks to create the NZ country and import the NZ entity are performed as per https://github.com/beyondessential/tupaia-backlog/issues/1573#issuecomment-730865834
=> 1573: Add NZ to PSSS project hierarchy

packages/meditrak-server/src/routes/importSurveyResponses/importSurveyResponses.js, packages/meditrak-server/src/routes/index.js, packages/meditrak-server/src/routes/postChanges.js, packages/meditrak-server/src/routes/surveyResponse.js, packages/meditrak-server/src/tests/routeTests/importStriveLabResults.test.js, packages/meditrak-server/src/tests/routes.test.js, packages/meditrak-server/src/tests/routes/GETSurveys.test.js, packages/meditrak-server/src/tests/routes/accessRequests.test.js, packages/meditrak-server/src/tests/routes/importSurveys/importSurveys.test.js, packages/meditrak-server/src/tests/surveyResponse.test.js
- Pluralize endpoints in unit tests
- Add auth to unit tests
- Allow anyone to request country access
- Allow anyone to change their own password
---
=> Fixup unit tests on permissions epic

packages/psss/src/api/FakeApi.js, packages/psss/src/containers/Modals/CreateOutbreakModal.js, packages/psss/src/containers/Tables/CountriesTable.js, packages/psss/src/containers/Tables/CountrySummaryTable.js, packages/psss/src/containers/Tables/CountryTable.js, packages/psss/src/containers/Tables/SiteSummaryTable.js, packages/psss/src/containers/__tests__/fixtures/country.fixtures.json, packages/psss/src/containers/__tests__/fixtures/sites.fixtures.json, packages/psss/src/containers/__tests__/weeklyReportsPanel.test.js
The acronym for Dengue Like Illness was spelt incorrectly everywhere it was used so just fixing that.
=> Fix DLI spelling

packages/psss/src/api/FakeApi.js, packages/psss/src/api/requests/weeklyReports.js, packages/psss/src/containers/Panels/WeeklyReportsPanel.js, packages/psss/src/containers/Tables/CountryReportTable.js, packages/psss/src/containers/Tables/SiteSummaryTable.js
- Add sites meta data endpoint
- Only show sites sections if there is sites in the meta data and sites data
---
See screenshots in the issue
=> handle if there is no sites data

packages/admin-panel/src/importExport/ExportButton.js, packages/admin-panel/src/pages/resources/SurveyResponsesPage.js, packages/admin-panel/src/utilities/index.js, packages/meditrak-server/src/routes/exportSurveyResponses.js, packages/utils/src/getBrowserTimeZone.js, packages/utils/src/index.js, packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialog.js, packages/web-frontend/src/sagas.js, packages/web-frontend/src/utils/getBrowserTimeZone.js, packages/web-frontend/src/utils/index.js
- `timeZone` (from browser) query parameter was added into the export survey response meditrak-server endpoint for this ticket (https://github.com/beyondessential/tupaia/pull/1627). It was only done for web-frontend. We should also do it for admin-panel. So this PR is just for sending through timeZone from Admin-Panel when exporting. A default timeZone to fall back was also added to in the endpoint
=> 1740: Hotfix unable to export survey responses via the admin panel

packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/TableOfDataValuesWithCalc.js
https://github.com/beyondessential/tupaia-backlog/issues/1751
Don't return `{ data: [] }` when there is no data for a matrix, it requires the keys `columns` and `rows` instead. In this case, I went with not having a different code path for no data, which could cause a bit of regression, but seems a lot cleaner to me? What do you think?
Note: the affected matrix is the only one with this dataBuilder:
Screenshots on card
=> Handle no baseline data differently

packages/database/src/migrations/20201209001056-ChangePSSSReportsToUseLastPerPeriodPerOrgUnit-modifies-data.js, packages/report-server/src/reportBuilder/transform/aliases/aggregateAliases.ts, packages/report-server/src/reportBuilder/transform/aliases/index.ts
Was previously fetching the earliest submitted response, now fetches the latest one
=> Use lastPerPeriodPerOrgUnit aggregation in PSSS Reports

packages/psss-server/examples.http, packages/psss-server/src/app/addRoutesToApp.ts, packages/psss-server/src/connections/MeditrakConnection.ts, packages/psss-server/src/routes/index.ts, packages/psss-server/src/routes/reports/DeleteCountryWeeklyReportRoute.ts, packages/psss-server/src/routes/reports/SaveCountryWeeklyReportRoute.ts, packages/psss-server/src/routes/reports/SubmitConfirmedCountryWeeklyReportRoute.ts, packages/psss-server/src/routes/reports/SubmitCountryWeeklyReportRoute.ts, packages/psss-server/src/routes/reports/index.ts, packages/psss-server/src/utils/index.ts, packages/psss-server/src/utils/validate.ts
Added two new endpoints for update/create and delete for unconfirmed survey responses.
@tcaiger Let's define the format that the data is coming in from the front-end?
=> 1497: PSSS-Server: Submit and Delete Weekly Survey Responses

packages/database/src/migrations/20201209052048-EditWoWIndicatorsToGiveRelativeIncrease-modifies-data.js
Now the indicators will return correctly, eg:
{ AFR: 5 } => { AFR: 10 } = 100% increase
{ AFR: 10 } => { AFR: 5 } = 50% decrease
=> Edit WoW Indicators to return relative increase

packages/database/src/migrations/20201209232802-EditSiteAverageIndicatorsToSupportDivByZero-modifies-data.js
New formulas:
```
{
"formula": "PSSS_Confirmed_Sites_Reported == 0 ? 0 : PSSS_Confirmed_DLI_Cases / PSSS_Confirmed_Sites_Reported",
"aggregation": "FINAL_EACH_WEEK"
}
{
"formula": "PSSS_Total_Sites_Reported == 0 ? 0 : PSSS_DLI_Total_Cases / PSSS_Total_Sites_Reported",
"aggregation": "FINAL_EACH_WEEK"
}
```
=> Edit Site_Average indicators to handle div by 0

packages/psss/src/api/mutations.js, packages/psss/src/api/queries/useUpcomingReport.js, packages/psss/src/components/Table/CellComponents/PercentageChangeCell.js, packages/psss/src/components/Table/CellComponents/StatusCell.js, packages/psss/src/components/Table/CellComponents/index.js, packages/psss/src/containers/Tables/CountryReportTable.js, packages/psss/src/containers/Tables/CountryTable.js
- Handle saving weekly report data to the server
- Make status cell it's own component and add a resubmit button
=> 1664 psss save report endpoint

packages/psss/src/utils/countries.js
Pitcairn is not showing up properly in psss because the country code in the database is not the expected standard country code. This is a temporary fix to display the country name and country flag correctly and there is a [new card](https://github.com/beyondessential/tupaia-backlog/issues/1782) in the backlog for fixing the underlying issue.
---
=> Fix to display Pitcairn

packages/psss-server/src/models/PsssSession.ts
=> Use correct sign when comparing expiry time

packages/meditrak-server/src/database/models/UserReward.js
- Initially we only wanted to exclude Rohan since he imported a lot of PSSS survey responses. But then I can't think of any case that we want to have any internal tupaia users in Meditrak Leaderboard... So went with excluding all the internal tupaia users
=> 1781: Exclude all BES internal emails from Meditrak Leaderboard

packages/web-frontend/src/components/View/ChartWrapper/Tooltip.js
[1660 - Values on hover wrong for UNFPA visuals Q2 2020 onwards](https://github.com/beyondessential/tupaia-backlog/issues/1660)
If dashboard is a chart, always performs `.MultiValueTooltip()`. `.SingleValueTooltip()` couldn't show single value in chart's tooltip properly.
=> Show value if it is singled in chart tooltip

packages/meditrak-server/src/app/addRoutesToApp.js, packages/meditrak-server/src/tests/routes/exportSurveys/exportSurveys.test.js
https://github.com/beyondessential/tupaia-backlog/issues/998
- We already pluralised these in the admin panel but forgot to pluralise in the addRoutesToApp.js file
=> Pluralise export endpoints

packages/meditrak-server/src/routes/GETHandler/GETHandler.js, packages/meditrak-server/src/routes/GETHandler/helpers.js, packages/meditrak-server/src/routes/surveys/GETSurveys.js
- Add ability to define default joins for GETHandlers, override on GETSurveys to match behaviour on dev
=> Override default join for GETSurveys to use left outer

packages/meditrak-server/src/dataAccessors/addSurveyImage.js
=> If image already on S3, log error rather than blocking sync

packages/meditrak-server/src/routes/exportSurveyResponses/exportSurveyResponses.js, packages/meditrak-server/src/routes/exportSurveys/SurveyExporter.js, packages/meditrak-server/src/tests/routes/exportSurveys/exportSurveys.test.js
https://github.com/beyondessential/tupaia-backlog/issues/998
- Allow BES admin permissions to override export permissions checks
- Fixup unit tests to expect the admin the new error message
=> Permissions exports respect bes

.gitignore, packages/database/src/migrations/20210110220114-AddCovidSamoaDemoIndivQuarhealthCond-modifies-data.js, packages/database/src/utilities/migration.js, packages/web-config-server/src/apiV1/dataBuilders/modules/covid-samoa/flight/flightAgeRanges.js, packages/web-config-server/src/apiV1/dataBuilders/modules/covid-samoa/index.js, packages/web-config-server/src/apiV1/dataBuilders/modules/covid-samoa/valueAndPercentageByAgeByFlightDate.js, packages/web-config-server/src/apiV1/dataBuilders/modules/covid-samoa/valueAndPercentageByDataValueByFlightDate.js, packages/web-config-server/src/tests/apiV1/dataBuilders/modules/covid-samoa/flight/flightAgeRanges.test.js
- Generalise databuilder `ValueAndPercentageByAgeByFlightDate` as `ValueAndPercentageByDataValueByFlightDate` and extend the latter class by the former. 
- Create migration to add Covid Samoa Demographics of individuals in quarantine: Health Conditions report
- export migration delete utilities
- add getPassengersPerDataValue test
=> Add ValueAndPercentageByDataValueByFlightDate

packages/database/src/migrations/20210114125216-AddCovidSamoaClearanceDocuments-modifies-data.js
- migration to add dashboard report
=> add Covid Samoa Clearance Documents report

packages/devops/scripts/deployment/startup.sh
Couldn't find a setting for cloudwatch agent to avoid turning itself on every reboot, so instead this adds a step to the startup script to turn it off for feature instances.
Note that cloudwatch agent is also on for the aggregation servers, but we rarely make extra instances of them, so I think it's okay for those rare extra instances to report their metrics.
=> 2090 stop cloudwatch on startup

.gitignore, packages/database/src/migrations/20201117224102-DeleteUNFPAStaffTrainedLines-modifies-data.js, packages/database/src/migrations/20201117224832-AddUNFPAStaffTrainedMatrix-modifies-data.js, packages/database/src/migrations/20201123014943-IntegrateInconsistentAnswersForHotelNames-modifies-data.js, packages/database/src/migrations/20201204224102-DeleteUNFPAStaffTrainedLinesCountry-modifies-data.js, packages/database/src/migrations/20201204224832-AddUNFPAStaffTrainedMatrixCountry-modifies-data.js, packages/database/src/migrations/20210114131303-AddCovidSamoaQuarantineSiteByFlight-modifies-data.js, packages/devops/scripts/deployment/startup.sh, packages/expression-parser/src/expression-parser/ExpressionParser.js, packages/meditrak-app/ios/TupaiaMediTrak/Info.plist, packages/meditrak-app/package.json, packages/psss/src/components/EditableTable.js, packages/psss/src/containers/Panels/WeeklyReportsPanel.js, packages/psss/src/containers/Tables/CountryReportTable.js, packages/report-server/src/reportBuilder/transform/aliases/keyValueByFieldAliases.ts, packages/report-server/src/reportBuilder/transform/transform.ts, packages/ui-components/src/components/LoadingContainer.js, packages/ui-components/src/components/Table/TableMessageProvider.js, packages/ui-components/stories/tables/table.stories.js, packages/web-config-server/src/apiV1/dataBuilders/helpers/calculateOperationForAnalytics.js, packages/web-config-server/src/apiV1/dataBuilders/helpers/divideValues.js, packages/web-config-server/src/apiV1/dataBuilders/modules/covid-samoa/valueAndPercentageByDataValueByFlightDate.js, packages/web-frontend/src/historyNavigation/historyMiddleware.js, packages/web-frontend/src/sagas.js, packages/web-frontend/src/selectors/dashboardSelectors.js
* Add ValueAndPercentageByDataValueByFlightDate
ValueAndPercentageByAgeByFlightDate extends above
migration for samoa covid health conditions report
* refactor getPassengersPerAgeRange
remove duplicate code
add getPassengersPerDataValue test
* Add Covid Samoa Individual Sex Matrix
Modify getPassengersPerDataValue to specify compare value
add getPassengersPerDataValue test specified value
* add Covid Samoa Clearance Documents report
* Add Covid Samoa Quarantine site by flight report
allow $allValues row config valueAndPercentageByDataValueByFlightDate
* Assign correct hotel names to make them consistent (#1674)
* Add migration
* Remove duplicated hotel name
* Update answers when needed
* Limit data update to specific survey
* trim all sites
* format update trim query
Co-authored-by: nick …
=> Add Covid Samoa Quarantine site by flight report (#1891)

packages/database/src/modelClasses/Entity.js
Rather than storing the overhead of the models etc. in the cache, we should just store the data, and construct the model instances again when we need them.
This was revealed when testing redis, because the models are a circular structure (each model references the other models, which then reference the original and around it goes), which can't be serialised to JSON and stored in redis. Seems it's not just a benefit in making the cache serialisable, but also means we save about 65% less memory in the cache for the Laos entity hierarchy alone.
See https://docs.google.com/spreadsheets/d/1KoewibyIxEJjpcjataeKi5svspPi41gbcG0LUtwIHZk/edit#gid=1369222111 for memory usage data (second tab)
=> Reduce cache memory footprint

packages/meditrak-server/src/routes/importEntities/extractEntitiesByCountryName.js, packages/meditrak-server/src/routes/importEntities/getEntityObjectValidator.js, packages/meditrak-server/src/routes/importEntities/updateCountryEntities.js
- Allow import data service entity when importing entities in Admin Panel
=> 2230: Allow import data service entity when importing entities in Admin Panel

packages/meditrak-server/src/routes/importSurveyResponses/assertCanImportSurveyResponses.js
- When submitting a survey against a new entity, run the permissions check against the parent entity of the newly created entity
=> 2240 hotfix survey submit

packages/admin-panel/src/importExport/ImportModal.js
- Dispatch error state from import modal so `DataFetchingTable` knows to stop loading
=> Allow import modal to dispatch error state

packages/admin-panel/src/autocomplete/Autocomplete.js, packages/admin-panel/src/pages/resources/ProjectsPage.js, packages/database/src/migrations/20210224014424-AddConfigToProjects-modifies-schema.js, packages/database/src/modelClasses/Project.js, packages/web-config-server/src/apiV1/projects.js, packages/web-frontend/src/containers/Map/AreaTooltip.js, packages/web-frontend/src/containers/Map/ConnectedPolygon.js, packages/web-frontend/src/selectors/index.js, packages/web-frontend/src/selectors/projectSelectors.js, packages/web-frontend/src/tests/selectors/projectSelectors.test.js
- Replaced `tile_sets` column with `config` in the projects table
- Updated project selectors to use config for tile sets
-  Configure Regional Labels (tooltips) based on the config
---
See issue
=> 2190 project sticky region labels

packages/admin-panel/src/pages/resources/SurveyResponsesPage.js, packages/database/package.json, packages/database/src/TupaiaDatabase.js, yarn.lock
https://github.com/beyondessential/tupaia-backlog/issues/1149 towards point 3
When pulling dates out of the database, our node postgres driver converts them to JS dates. Annoyingly, this means they get parsed using the default logic of "if no timezone is provided, assume local time". The parsed date is then converted to UTC to be stored, because JS dates are just a UTC timestamp with some formatting on top. 
This behaviour messed me up for a while. The solution here stops that whole parsing behaviour, and just returns strings for timestamp columns, which I think keeps things more "expected", and might make your life easier @EMcQ-BES
=> 1149 keep timestamp values as strings

packages/database/src/migrations/20210222124639-UpdateLaosEntitiesPushMetadata-modifies-data.js, packages/database/src/migrations/20210222204800-UpdateEntityDhisIdToTrackEntityInstanceId-modifies-data.js, packages/database/src/modelClasses/Entity.js, packages/meditrak-server/src/dhis/DhisChangeValidator.js, packages/meditrak-server/src/dhis/pushers/data/event/EventBuilder.js, packages/meditrak-server/src/dhis/pushers/entity/TrackedEntityPusher.js, packages/meditrak-server/src/routes/importEntities/updateCountryEntities.js, packages/meditrak-server/src/tests/dhis/EventBuilder.fixtures.js, packages/meditrak-server/src/tests/dhis/pushers/entity/TrackedEntityPusher.test.js, packages/meditrak-server/src/tests/dhis/pushers/entity/helpers.js
- Added push flag to metadata column of entity to prevent pushing to DHIS2
- Changed dhis.id to dhis.trackedEntityId for clarity
=> 2263: Make sure entity updates are not pushed to Laos DHIS

packages/database/src/migrations/20210225033329-RemoveLaosOxygenConcentratorsProject-modifies-data.js
Addresses: https://github.com/beyondessential/tupaia-backlog/issues/2298#issuecomment-785467065
This migration assumes that all the survey responses associated with the Laos facilities being deleted have been backed up / deleted on the admin panel first (cos it's easier to do it this way)
- This hasn't happened yet but will happen before testing / releasing this migration
This migration essentially removes Laos from being accessible from Explore mode (and also removes some map overlay / dashboard report associations related to this) and deletes the old facilities from the oxygen concentrators project (as per the comment linked above)
=> 2298 remove Laos oxygen concentrators project

packages/devops/scripts/deployment/dumpE2eDataToS3.sh, packages/devops/scripts/deployment/restoreE2eDataFromS3.sh, packages/devops/scripts/deployment/startup.sh
https://github.com/beyondessential/tupaia-backlog/issues/2188
Manual steps required on release:
-[ ] Open `crontab -e` and add the following line, which will dump `survey_response` and `answer` to S3 every night at 12:30pm UTC (currently 11:30pm in Melb, 10:30pm after daylight savings):
```
30 12 * * * /home/ubuntu/tupaia/packages/devops/scripts/dumpE2eDataToS3.sh | while IFS= read -r line; do printf '\%s \%s\n' "$(date)" "$line"; done >> /home/ubuntu/logs/dump_e2e_data.txt
```
=> 2188 e2e instance data

packages/web-frontend/src/historyNavigation/utils.js
This is a hotfix but I think it needs to be tested before being released so I have made it from the dev branch and not the release branch.
- Fix user page urls
---
=> only load user page urls when no project is being loaded

packages/meditrak-server/src/routes/importEntities/getOrCreateParentEntity.js, packages/meditrak-server/src/routes/importEntities/updateCountryEntities.js
- remove contraint on parents having geographicalAreas recently added for country level facilities
=> Hotfix remove geograhicalArea import contraint

packages/database/src/migrations/20210311045832-AddLaosEOCMapOverlayGroup-modifies-data.js, packages/database/src/migrations/20210315001650-AddMapOverlayMeaslesDeathCasesLaosEOC-modifies-data.js, packages/database/src/migrations/20210317052741-MoveLonelyMapOverlay-modifies-data.js
https://github.com/beyondessential/tupaia-backlog/issues/2480
- Fix migration order, create map overlay group first
- Move lonely map overlay to its friends
Screenshot:
https://github.com/beyondessential/tupaia-backlog/issues/2480#issuecomment-800810022
=> 2480 move map overlay

packages/meditrak-server/src/routes/importEntities/getEntityMetadata.js, packages/meditrak-server/src/routes/importEntities/getOrCreateParentEntity.js, packages/meditrak-server/src/routes/importEntities/updateCountryEntities.js
- Allow disable syncing subdistrict and district when importing facilities. Addressing the bug found here: https://github.com/beyondessential/tupaia-backlog/issues/2301#issuecomment-799054228
=> 2301: Allow disable syncing subdistrict and district when importing facilities

packages/web-frontend/src/reducers.js
- When fetching data, clear the view contents (when a view has no content it displays the loading circle)
=> 2182: Display loading circle when clicking retry

packages/database/src/migrations/20210325123857-ExcludeIndividualsFromCovidSamoaFront-modifies-data.js, packages/web-config-server/src/apiV1/RouteHandler.js, packages/web-config-server/src/apiV1/organisationUnit.js, packages/web-config-server/src/apiV1/organisationUnitSearch.js
- Check for project config frontendExcludedTypes else use entity default list `entity.typesExcludedFromWebFrontend` as before.
- Add migration to individual to frontendExcludedTypes for Covid Samoa
=> Allow project config of frontend exclude types 

packages/admin-panel/src/pages/resources/SurveyResponsesPage.js, packages/meditrak-server/src/dataAccessors/updateOrCreateSurveyResponse.js, packages/meditrak-server/src/database/constants.js, packages/meditrak-server/src/database/index.js, packages/meditrak-server/src/routes/importSurveyResponses/importSurveyResponses.js, packages/meditrak-server/src/tests/routes/importSurveyResponses/testFunctionality.js
https://github.com/beyondessential/tupaia-backlog/issues/1149
https://github.com/beyondessential/tupaia-backlog/issues/717
- Add browser timezone to REST request when importing survey responses
- Create survey responses relative to the given timezone
- Set an imported survey responses start and end time to current time
=> Import Survey Responses relative to browser timezone

packages/data-api/scripts/createAnalyticsMaterializedView.sql, packages/data-api/src/TupaiaDataApi.js, packages/data-api/src/__tests__/TupaiaDataApi.fixtures.js, packages/data-api/src/fetchData.js, packages/indicators/src/__tests__/__integration/fixtures/helpers.ts, packages/meditrak-server/src/database/models/SurveyResponse.js
https://github.com/beyondessential/tupaia-backlog/issues/2100
`dev` now includes the new `data_time` field! For ease of reviewing, I created [2101-merge-dev-with-conflicts](2101-merge-dev-with-conflicts) as a helper branch. This is the same as [2101-analytics-table-materialized-view](https://github.com/beyondessential/tupaia/tree/2101-analytics-table-materialized-view), plus a simple [commit](https://github.com/beyondessential/tupaia/commit/808170035145a7d4de2286e81eb0a12a6aaa1e10) that merges `dev`. There is no conflict resolution in that commit, in an effort to expose them in this PR.
=> 2100: Use data_time field in analytics table

packages/meditrak-app/ios/TupaiaMediTrak/Info.plist, packages/meditrak-app/package.json
The timezone changes from https://github.com/beyondessential/tupaia-backlog/issues/1149 are big enough to warrant a version bump
=> Bump meditrak version to 1.11.112

packages/ui-components/src/index.js
Map components were split out into to their own bundle but the map directory was never removed from the main ui-components bundle. 
- Remove map components from main bundle.
---
=> fix-ui-components-build

packages/database/src/migrations/20210318031303-UseTupaiaServiceInStrive-modifies-data.js, packages/database/src/migrations/20210322030033-FixStriveAfterTupaiaServiceConversion-modifies-data.js, packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfEvents.js
https://github.com/beyondessential/tupaia-backlog/issues/2177
This PR depends on the following features for correct functionality:
1. [1149: Correct internal data fetching time constraints to respect timezone](https://github.com/beyondessential/tupaia-backlog/issues/1149)
2. [2101: Analytics table](https://github.com/beyondessential/tupaia-backlog/issues/2101)
3. [2100: Use data_time field in analytics table](https://github.com/beyondessential/tupaia-backlog/issues/2100)
4. support for empty `dataElementCodes` when fetching tupaia events
All the above are included in the base branch. 1 and 2 are currently under testing. 3 and 4 depend on 1 and 2 so they will be reviewed and tested after their dependencies pass testing.
One can still review this PR, since none of its prerequisites affect …
=> 2177: Use tupaia service in Strive

packages/meditrak-app/app/api/TupaiaApi.js, packages/utils/src/__tests__/request.test.js, packages/utils/src/request.js
If you make a lot of fetches in a row, the timeouts build up and consume memory. Better to clear them as soon as the fetch resolves.
I found this because it was causing out of memory errors in my similar implementation over on Tamanu Mobile, if I ran sync super fast. There's a remote possibility that this has been contributing to our out of memory errors on web-config-server. That's a much bigger memory environment, so it's most likely not a significant factor, but great to clean it up anyway.
=> Clean up timeouts after fetch resolves

packages/database/src/analytics/AnalyticsRefresher.js, packages/database/src/runPostMigration.js
Added logic to prevent installing the notificationt trigger on the analytics and log tables
=> 2678: Analytics table refresh is broken after running migrations if Tupaia User has Super User privileges

packages/database/src/runPostMigration.js, packages/devops/scripts/deployment/startup.sh
We should be able to  load the `restoreE2eDataFromS3` script from the deployed branch and not always from production
=> Hotfix: Check latest code before running scripts

packages/data-api/scripts/installMvRefreshModule.sh
When the script to install the mvrefresh module runs over a database with an existing install, it drops all the module functions and re-creates them.
This causes a cascading delete to the triggers on the source tables in the tupaia schema. We do not recreate those triggers when re-installing the analytics table, as we simply check if the log tables exist and skip if they do (they still exist, they are just missing their triggers). This leaves the source tables in a misconfigured state, where they will not update the log tables when they get changes.
Simplest fix I could come up with is just to check if the mvrefresh module already exists before installing, and skip the installation if it does.
=> Hotfix: Skip mvrefresh installation if already exists

packages/aggregator/src/Aggregator.js, packages/aggregator/src/analytics/aggregateAnalytics/adjustOptionsToAggregationList.js, packages/database/src/migrations/20210419225536-UpdatePSSSTotalSitesReportToUseSiteData-modifies-data.js
Added 2 new indicators to determine if a site has completed a Weekly Survey or a Daily Survey for a given week
Updated Total Cases indicator to preferentially use: 
- National recorded answer for Sites Reported
- Number of Sites that submitted a weekly survey
- Number of sites that completed a daily survey
Note: After adding these indicators the performance of PSSS has dropped substantially! (~15 seconds to load the Weekly Report in my local). Subsequent work must be done to improve performance but that's out of the scope for this PR.
=> 1336: Support deriving PSSS Total Sites indicator from number of reporting sites

packages/aggregator/src/__tests__/Aggregator/Aggregator.test.js, packages/aggregator/src/analytics/aggregateAnalytics/adjustOptionsToAggregationList.js, packages/web-config-server/src/apiV1/DataAggregatingRouteHandler.js
Fairly simple hack that allows for web-config-server entity aggregation and aggregator entity aggregation logic to co-exist. Assumption is that if constructor of Aggregator doesn't provide a session in the context, then they are responsible for creating their own entity aggregation options.
=> 2677: Added check for `session` when adjusting aggregation options

packages/data-api/scripts/createAnalyticsTableIndexes.sql
Altered events index on analytics table to perform well even if no data element code is specified
Arguably I should have created a migration to change this index on the existing analytics table, however that would require creating a mechanism for performing migrations as a user other than the tupaia user and that seemed rather out of scope (the analytics table is owned by the mvrefresh user)
=> 2714: Improve performance of 'PSSS_Total_Sites_Reported' indicator

scripts/bash/backendStartDev.sh, scripts/bash/buildInternalDependencies.sh, scripts/bash/getInternalDependencies.sh
https://github.com/beyondessential/tupaia-backlog/issues/1221
buildInternalDependencies now optionally takes in --packageJsonPath to indicate the package.json of the package to build internal dependencies of
=> 1221 Allow buildInternalDependencies to build only deps of a specific package

packages/lesmis/src/views/MapView.js
https://github.com/beyondessential/tupaia-backlog/issues/2746
I didn't entirely remove the min height because below a certain point it seems better to have the legend disappear than to have the map become unusable
See issue for what it looks like at 350px
=> 2746 legend too far down

packages/lesmis/src/api/queries/utils.js, packages/lesmis/src/components/YearSelector.js, packages/lesmis/src/constants/constants.js, packages/lesmis/src/views/DashboardReportTabView.js, packages/lesmis/src/views/MapView.js
- remove the all data option from dashboard and map overlay year selector
- set 2020 as the default year
=> Remove the all data options from the year selectors

packages/devops/scripts/lambda/createOrRestoreDeployment.py
Allows us to have feature branch deployments use different EC2 specs to production, which in turn means we can make production faster without the cost implications extending through feature deployments
Note that this is already deployed to production
=> Require InstanceType when creating new deployments via lambda

packages/devops/scripts/lambda/createOrRestoreDeployment.py, packages/devops/scripts/lambda/deleteDeployment.py
@tcaiger had the idea that we should make sure no one can accidentally delete production using lambda. I've attached the "Protected": "true" tags to the three key production EC2 instances, and already deployed the code in this PR to lambda
=> Allow a deployment to be "protected" from lambda

packages/meditrak-server/src/dataAccessors/updateOrCreateSurveyResponse.js, packages/meditrak-server/src/routes/importSurveyResponses/importSurveyResponses.js, packages/meditrak-server/src/routes/postChanges.js, packages/meditrak-server/src/routes/surveyResponses/DeleteSurveyResponses.js, packages/meditrak-server/src/tests/routes/importSurveyResponses/testPermissions.js, packages/psss-server/src/connections/ApiConnection.ts, packages/psss-server/src/connections/MeditrakConnection.ts, packages/psss/src/api/mutations.js, packages/psss/src/api/queries/useSingleWeeklyReport.js, packages/psss/src/containers/Panels/WeeklyReportsPanel.js, packages/utils/src/__tests__/stripTimezoneFromDate.test.js, packages/utils/src/index.js, packages/utils/src/stripTimezoneFromDate.js
See each commit for changes, summary:
- Add opt-in flag for survey response submissions that blocks the response and waits for analytics table rebuild
- Allow submit survey responses with a data_time without a tz
- Fix frontend query cache invalidation to properly refetch data after mutation
---
https://github.com/beyondessential/tupaia-backlog/issues/2663#issuecomment-841042918
=> 2663 async issues psss (2)

packages/lesmis/src/views/DashboardView.js
- Add a `validImage` state to `PhotoOrMap` component
- If image fails to load, invalidate the image
=> If a lesmis school image fails to load, default to mini-map

packages/psss/src/components/AffectedSitesTab.js
- There's data for total cases per week but it's not showing in the Alert Panel (screenshot here: https://github.com/beyondessential/tupaia-backlog/issues/2851#issuecomment-846803816). The report returns `weeklyCases` instead of `totalCases`. So this is to fix incorrect property key in Alert Panel
- I didn't fix this in another WIP branch and wanted to fix this early because Sepi is testing the Alert Panel
=> Fix incorrect property key in Alert Panel

packages/psss/src/containers/Tables/FakeEventBasedDataTable.js, packages/psss/src/containers/Tables/index.js, packages/psss/src/views/Tabs/EventBasedTabView.js
[No issue] The **Event-based Data** placeholder broke when I refactored the alerts table. After talking with @enunan , I confirmed that the fact that we show alerts in the blurred background is a coincidence. The actual data that will be shown when we implement this feature will not be directly related to alerts.
=> PSSS: Fix event data placeholder

packages/psss/src/api/queries/useCountrySitesWeeklyReport.js, packages/psss/src/api/queries/useSitesSingleWeeklyReport.js, packages/psss/src/containers/ProfileButton.js, packages/psss/src/containers/Tables/AlertsTable.js, packages/psss/src/containers/Tables/ArchiveTable.js, packages/psss/src/containers/Tables/SiteSummaryTable.js, packages/ui-components/src/components/Table/Table.js, packages/ui-components/src/components/Table/TableMessageProvider.js
Addresses a few existing UI issues
1. In a past commit I enabled the "Edit Profile" button, thinking that this was all that was left to implement https://github.com/beyondessential/tupaia-backlog/issues/1117. It seems that there is also back-end work that needs to be done. Since this was a nice-to-have for Phase 2, I'm reverting this change until the back-end is built (in a future phase)
2. The current UI was a bit inconsistent when displaying the sentinel site summary in the Weekly Report page:
* If there was at least one report submitted in the selected week, all sites were shown. Empty data are shown as `-`
* If there were no reports submitted, then **no** site was shown.
This PR changes this behaviour by always showing the sentinel site summary:
I discussed with @tcaiger and it seems …
=> PSSS: Minor UI fixes

packages/database/src/migrations/20210525072702-UpdatePSSSSyndromeThresholdCrossedIndicators-modifies-data.js
- As per Erin's request, we don't want to see alert for a single case. So I'm adding total_cases > 1 to all the threshold crossed indicators except for AFR (because AFR threshold crossed is just > 1)
=> 2853: Changed syndrome threshold crossed indicators

packages/psss/src/containers/Panels/WeeklyReportsPanel.js, packages/psss/src/containers/Tables/WeeklyReportTable/WeeklyReportTable.js
* Addresses https://github.com/beyondessential/tupaia-backlog/issues/2874
* It also implements a behaviour that is included in the mockup but escaped our attention... When country level data are being edited, the sentinel data section should be disabled, and an alert should be shown (see screenshot below)
=> 2874: PSSS - Fix edit sentinel site data

packages/lesmis-server/src/constants.ts, packages/lesmis/src/constants/constants.js
While testing the 2680 issue, the lesmis app was pointed at the `fanfana` project. That ticket is now testing passed so we need to revert the lesmis app to point to the lesmis project data.
=> revert constants to lesmis project

packages/database/src/analytics/AnalyticsRefresher.js, packages/database/src/tests/analytics/AnalyticsRefresher.test.js
I've listed this as a hot fix as it'd be great to get it into production to help make Juliana's job importing heaps of EMIS data easier, though we do still need to test it on its own deployment and see whether it will actually help with that
=> [Hot fix] Prevent multiple concurrent analytics refreshes

packages/web-config-server/src/authSession/authSession.js
Changes to the getAccessPolicyForUser function made now have it throw an error when `undefined` userId is passed in (ie. when no basic auth header is provided), now we need to catch that error
=> Added error handling around auth function in web-config-server

packages/lesmis/.gitignore
Build gets generated here on deployment instances so worth ignoring for when deving directly on a feature instance
=> Added 'served_build/*' to lesmis .gitignore

packages/data-api/package.json, packages/data-api/scripts/buildAnalyticsMaterializedView.sh, packages/data-api/scripts/createAnalyticsTableIndexes.sql, packages/data-api/scripts/dropAnalyticsMaterializedView.sh, packages/data-api/scripts/dropAnalyticsTableIndexes.sql, packages/data-api/scripts/fullRebuildAnalyticsMaterializedView.sh, packages/data-api/scripts/fullRefreshAnalyticsTable.sh, packages/data-api/scripts/uninstallMvRefreshModule.sh
The core issue at play here is that the `owner` of the analytics table must be the `mvrefresh` role, however only a table `owner` or a `superuser` can add/remove indexes on a table in Postgres. 
There could have been a few ways to address this (open a connection as that `mvrefresh` user, temporarily grant `superuser` to the `tupaia` user, etc.) however I felt the most solid going forward would be to add a function to the `mvrefresh` module that allows us to add/remove indexes. Since the `tupaia` user has full access to the functions in that module, it can use these functions to add/remove indexes from the analytics table 👍 
Updated pg-mv-fast-refresh and analytics table build scripts
- New version pg-mv-fast-refresh version has functions that allow the tupaia user to add/remove indexes …
=> 2961: Allow creating/removing indexes on Analytics Table as the Tupaia database user

packages/admin-panel/src/importExport/ImportModal.js, packages/admin-panel/src/pages/resources/SurveyResponsesPage.js, packages/data-broker/src/__tests__/services/weather/WeatherService.stubs.js, packages/database/src/DatabaseModel.js, packages/database/src/tests/modelClasses/DataSource.test.js, packages/meditrak-server/src/routes/importSurveyResponses/SurveyResponseUpdatePersistor.js, packages/meditrak-server/src/routes/importSurveyResponses/getFailureMessage.js, packages/meditrak-server/src/routes/importSurveyResponses/importSurveyResponses.js, packages/meditrak-server/src/routes/importSurveyResponses/setupEmailResponseTimeout.js, packages/meditrak-server/src/routes/requestCountryAccess.js, packages/meditrak-server/src/routes/requestPasswordReset.js, packages/meditrak-server/src/routes/utilities/excel.js, packages/meditrak-server/src/routes/utilities/index.js, packages/meditrak-server/src/utilities/sendEmail.js, packages/utils/src/respond.js
https://github.com/beyondessential/tupaia-backlog/issues/2931
- If you upload a file that takes 10 seconds or less to process, there is no change
- If you upload a file that takes more than 10 seconds, it will continue in the background and email the user when done
- The admin panel will show a message in the modal indicating that the user will be emailed (see screenshot in issue)
- The email will contain any validation messages or db update failures
Changes are separated into four commits:
1. Separating out the db processing from parsing and validation, and making inserts and deletes happen in bulk batches
2. A minor fix to the inconsistent indentation we have across our Tupaia emails, semi-related to the emails sent in the next commit
3. Add a pattern for responding via email if an …
=> 2931: Process survey response imports in the background, email when done

packages/meditrak-server/src/database/models/SurveyResponse.js, packages/meditrak-server/src/routes/importSurveyResponses/SurveyResponseUpdatePersistor.js
Fixes two issues found during investigation of a crash on import:
- Changes in `SurveyResponse.js` relate to https://github.com/beyondessential/tupaia-backlog/issues/2931#issuecomment-863602178
- Changes in `SurveyResponseUpdatePersistor.js` relate to https://github.com/beyondessential/tupaia-backlog/issues/2931#issuecomment-863593789
=> Hot fix import in background

packages/lesmis/src/views/PageView.js
This is just a suggestion - @enunan do you think the FQS links should open in a new tab or just replace the LESMIS page and stay on the same tab?
=> FQS links open in new tab

packages/lesmis/src/components/ChartTable.js, packages/ui-components/src/components/Chart/CartesianChart.js, packages/ui-components/src/components/Chart/Chart.js, packages/ui-components/src/components/Chart/Legend.js, packages/ui-components/src/components/Chart/PieChart.js, packages/ui-components/stories/chart/barChart.stories.js, packages/ui-components/stories/chart/composedChart.stories.js, packages/ui-components/stories/chart/lineChart.stories.js, packages/ui-components/stories/chart/pieChart.stories.js, packages/ui-components/stories/chart/stackedBarChart.stories.js
I have based the position and styling on a new prop called legendPosition. There are other options such as:
- using the theme type (light vs dark)
- adding a project prop (tupaia vs lesmis)
- adding a chartLayout or chartConfig prop
In the end I went with the legendPosition because it is more representative than the first 2 options and simpler than the third. It would be easy to refactor later to add something like chartLayout if needed.
- Add position and style legend based on legendPosition prop
- Added a tooltip to the legend buttons
---
see issue
=> add support for different legend positions

packages/database/src/migrations/20210623032946-AddDropoutRateByGrade-modifies-data.js, packages/database/src/migrations/20210623041504-AddNERGERLESMIS-modifies-data.js, packages/database/src/migrations/20210624211254-AddChildrenOverAgeLESMIS-modifies-data.js, packages/lesmis/src/views/DashboardView.js
A few tweaks to existing migrations:
- Set up percentages correctly
- Put dropout rate visuals under the correct dashboard
- Delete old (duplicate) dropout rate visuals
- Convert over age report to two time series reports 
Going to merge this straight in so these tweaks are included when the server gets started up for testing on Monday morning, but please review post-hoc @EMcQ-BES
=> Tweaks to existing LESMIS visuals

packages/lesmis/src/constants/page.js, packages/ui-components/src/components/Chart/XAxis.js, packages/ui-components/src/components/Chart/YAxes.js
- Fix chart label display color
- Fix label formatter to allow number formatting
- Tweak tick sizing
- Update about page text
---
see original issue
=> 3031 fix lesmis chart labels

packages/database/src/migrations/20210629002858-CorrectDropoutRatePercentageCalculation-modifies-data.js
When updating to percentages, I only updated "primary" and missed the "lower secondary" and "upper secondary" reports. This fixes that. Excuse the length of the migration for a tiny change, it's the fastest option
=> Correct dropout rate percentage calculation

packages/database/src/migrations/20210622234149-LESMISStudentCountToStackedBar-modifies-data.js, packages/database/src/migrations/20210628030723-AddNumberTeachersByEducationLevel-modifies-data.js, packages/ui-components/src/components/Chart/Tooltip.js
- https://github.com/beyondessential/tupaia-backlog/issues/3024
- https://github.com/beyondessential/tupaia-backlog/issues/2850
- Look up the labelType on the individual chartConfigs in a composed chart
- Update migrations to add metadata and labelTypes 
---
New screenshots attached to tickets
=> Allow composed graphs to specify individual labelTypes (and use those on GPI visuals)

packages/lesmis/src/components/YearSelector.js, packages/lesmis/src/views/DashboardView.js, packages/ui-components/src/components/DateRangePicker/DateRangePicker.js
- add loading state to year selector
- don't clear year state when changing dashboard tabs
---
=> Update lesmis year selector

packages/ui-components/src/components/Chart/Legend.js, packages/ui-components/src/components/Chart/PieChart.js
- Move handling of mobile legend labels to legend component so that the legend value doesn't display on tooltips on mobile
---
=> Fix mobile chart legend display

packages/web-config-server/src/apiV1/getUser.js, packages/web-config-server/src/apiV1/projects.js, packages/web-config-server/src/appServer/handlers/changePassword.js, packages/web-config-server/src/appServer/handlers/getCountryAccessList.js, packages/web-config-server/src/appServer/handlers/requestCountryAccess.js, packages/web-config-server/src/authSession/authSession.js
The issue was that checkAllowedUnauthRoutes logic was wrong, because it considered query string.
Requests for /api/v1/login?cacheBreaker=xyz would return false, and the control flow would fall to the public access policy.
Removing cacheBreaker made checkAllowedUnauthRoutes return true, which caused a higher up if block to execute, which caused an error where a userId was expected but undefined.
=> Fix login not working now that cacheBreaker removed

packages/data-broker/src/DataBroker.js
Found the memory leak in web-config-server
How the memory leaks:
- A request for a dashboard report comes in to web-config-server
- It requests the data from aggregator
- Aggregator spins up a new DataBroker instance
- The DataBroker instance spins up a new ModelRegistry (but reuses the TupaiaDatabase instance, so same db connection)
- The ModelRegistry adds notification handlers to listen for changes, in order to have cache invalidation and trigger side effects
- These notification handlers are callbacks back into each model, and the ModelRegistry as a whole
- The callbacks are retained by the long-lived TupaiaDatabase instance, and each captures a reference to the database model that made it
- The data is returned back through the pipeline, and DataBroker instance is shut down, but the …
=> Maintain long lived ModelRegistry in data-broker (fixes memory leak)

packages/ui-components/src/components/Chart/Legend.js, packages/ui-components/src/components/Chart/PieChart.js
- Move handling of mobile legend labels to legend component so that the legend value doesn't display on tooltips on mobile
---
=> 3107 fix pie chart tooltips

packages/admin-panel/src/pages/resources/UsersPage.js, packages/admin-panel/src/table/columnTypes/columnFilters.js
* pulled package.json from remote dev branch
* Added the 'Verified' column to the users table. This column indicate whether a user is verified, new (no verified) or a historical user who does not need verification
* Update package.json
Co-authored-by: Tom Caiger <caigertom@gmail.com>
=> 1486 add verified colum to users table in admin panel (#2709)

packages/web-frontend/src/screens/desktop/RootScreen/index.js
* pulled package.json from remote dev branch
* Loading spinner is now displaying behind popup window
* Update package.json
Co-authored-by: Tom Caiger <caigertom@gmail.com>
=> 2813 spinner behind modal new (#2708)

packages/meditrak-server/src/routes/exportSurveyResponses/exportSurveyResponses.js
No issue for this, but @julianam-w reported that the answers for survey responses stopped lining up if you deleted all answers from a survey response early in the import file.
=> Ensure answers line up with their survey response in exports

packages/database/src/migrations/20210713012631-AddPostcodeTypeToExplore-modifies-data.js, packages/database/src/migrations/20210713232632-ExcludePostcodesFromExploreSearch-modifies-data.js
- Add postcode type to explore canonical types in explore hierarchy
- Redefine covid_samoa districts so that explore remains canonical and 'undefined entities' show only in covid_samoa.
- hide postcodes from explore search bar
=> 3001 Add postcodes in explore

packages/web-frontend/cypress.json
Most of the reports in [default.json](https://github.com/beyondessential/tupaia/blob/dev/packages/web-frontend/cypress/config/dashboardReportUrls/default.json) load in 15secs. There are a couple that do not, which prevents us from testing them, but I am a bit hesitant to further increasing the timeout:
* It can act as a performance test (performance degradation can be caught earlier)
* Reports can timeout because they are slow, or because the url doesn't exist. The second scenario may happen because of invalid url configuration or bugs preventing the reports from loading. No reason to wait too long in those cases
Would like to get another opinion on that though. Another option would be using a very generous timeout for data correctness tests, and regularly run performance tests with a …
=> Increase request timeout

packages/devops/scripts/lambda/createOrRestoreDeployment.py
I noticed there were a heap of elastic block store volumes just hanging around. Turns out the instances we start have the behaviour for volumes "DeleteOnTermination" set to false by default. This changes that.
=> Ensure volumes are deleted on instance termination

packages/aggregator/src/connections/EntityConnection.js, packages/entity-server/examples.http, packages/entity-server/src/app/createApp.ts, packages/entity-server/src/routes/hierarchy/EntityDescendantsRoute.ts, packages/entity-server/src/routes/hierarchy/EntityRelativesRoute.ts, packages/entity-server/src/routes/hierarchy/MultiEntityDescendantsRoute.ts, packages/entity-server/src/routes/hierarchy/MultiEntityRelativesRoute.ts, packages/entity-server/src/routes/hierarchy/middleware/attachEntityContext.ts, packages/entity-server/src/routes/hierarchy/relationships/types.ts, packages/entity-server/src/routes/hierarchy/types.ts, packages/server-boilerplate/src/microService/api/ApiBuilder.ts
* 3032: Switch entity-server multi entity routes to POST instead of GET
* 3032: Fixed bug in EntityConnection in Aggregator where incorrect param was being used to filter dataSourceEntities
Co-authored-by: Bindu madhavi tammireddy <41365985+BinduMadhaviTammireddy@users.noreply.github.com>
- Example
---
=> 3032: Use POST for MultiEntity routes in Entity-Server  (#2823) test

e2e.Dockerfile, full-testable-package.Dockerfile
Bug introduced in https://github.com/beyondessential/tupaia/commit/a426843ca4127b3460597fc00ef8444a2f0a5daf. At that time I spun up a new EC2 instance and everything went fine, but now I believe this was just because of cached layers in the build.
I will wait for the build to pass to make sure that this works as intended
=> Release hotfix: add missing config file

packages/database/src/migrations/20210722044503-FixDataSourceEntityTypeLesmisProvinceStudentDashboards-modifies-data.js
Previous `dataSourceEntityType` was incorrect but it was still working due to bug in `EntityConnection` in `Aggregator`. Now that bug has been fixed, so this one must be too.
=> hotfix: Fixup dataSourceEntityType for a few lesmis reports

package.json, packages/database/scripts/dumpDatabase.sh, packages/devops/scripts/ci/validateBranchName.sh
After I recently move those scripts under the `packages/database` folder, the `dumpDatabase` script will download the dump file in that location.
The previous behaviour was downloading the dump in the monorepo root by default. This is also assumed by the `yarn refresh-database` script defined in the root `package.json`, which expects the dump to be in the root. This script re-instates the previous behaviour regarding dump default locations
=> Fix dump database script - dump location

packages/admin-panel/src/VizBuilderApp/App.js, packages/admin-panel/src/VizBuilderApp/components/MetadataForm.js, packages/admin-panel/src/VizBuilderApp/components/Panel.js, packages/admin-panel/src/VizBuilderApp/components/PreviewOptions.js, packages/admin-panel/src/VizBuilderApp/components/PreviewSection.js, packages/admin-panel/src/VizBuilderApp/components/SaveButton.js, packages/admin-panel/src/VizBuilderApp/components/Toolbar.js, packages/admin-panel/src/VizBuilderApp/vizBuilderConfigStore.js, packages/admin-panel/src/rootReducer.js
This is just a refactor to rename the store in the vizBuilder app to be `vizBuilderConfigStore` and change its api to expose `VizBuilderConfigProvider ` and `useVizBuilderConfig ` to signpost to developers the purpose of the store.
=> Rename viz builder store

codeship-services.yml, packages/database/src/migrations/20210715093133-AddMostRecentAggregationFunction-modifies-schema.js
Part of: https://github.com/beyondessential/tupaia/pull/2887
Can be merged independently
Here we're adding a new aggregation function to the database. In order to ensure the tests pass, I've also updated the docker image we use for the database during tests to be version 10 of postgres (the same as we use in deployment instances).
=> 3202: Added 'most_recent' aggregation function to the database

packages/web-frontend/cypress/config/dashboardReportUrls/default.json
Testing those reports came up during MEL-87, but I think it's worth adding in the default config as they are interesting cases
Urls (for your convenience)
* `/covid_samoa/WS/COVID-19 Samoa?overlay=Samoa_COVID_Isolation_Beds&report=Samoa_Covid_Demo_Health_Cons_Per_Flight`
* `/fanafana/TO_VHP/Health Promotion Unit Validation?&report=TO_HPU_Validation_HP_03&reportPeriod=1st_Aug_2020-31st_Aug_2020`
* `/fanafana/TO_KlongaHC/Reproductive Health Validation?report=TO_RH_Validation_MCH06&reportPeriod=1st_Mar_2021-31st_Mar_2021` => notice that a few births were of twins 👶 👶
=> Add e2e report urls

packages/lesmis/src/api/queries/useDashboardReportData.js
The dashboard report modal was firing off a request even though it wasn't open and there wasn't a date set yet (it needs to be on the page before it is open for the nice animation). Fix it by only making a dashboard report request if there is a valid start and end date.
---
=> NZ-19: Fix Lesmis Dashboard Loading More Than Once

packages/database/src/DatabaseModel.js, packages/database/src/changeHandlers/SurveyResponseOutdater.js, packages/database/src/utilities/isMarkedChange.js, packages/meditrak-server/src/dataAccessors/validateSurveyFields.js, packages/meditrak-server/src/database/models/Survey.js
@edmofro Eventually I decided to follow your advice and disallow updating the reporting period for surveys that have responses against them.
Some of our surveys already have ~ 90,000 responses. As we have discussed, updating them all at once breaks `meditrak-server` and/or the database. I tried batching the changes and adding delays between each batch: this is successful but not robust, since
* Only relatively small batches are guaranteed to not stress the system (eg 1000 responses/minute). Bigger batches often work, but in combination with analytic updates that are triggered at the same time, we cannot guarantee the stability of the system. I guess a more robust solution would be using a db-based queue
* We can assume that people will not change period granularities often
* We can still …
=> 2729: Fixes (MEL-92)

packages/database/src/migrations/20210705232632-AddECEGoalsDrillDowns-modifies-data.js, packages/database/src/migrations/20210708023241-LESMISListVisualSummaryReport-modifies-data.js
NZ-62
- Change reports and indicators to use `FINAL_EACH_YEAR` instead of `MOST_RECENT` so they actually show historical data
- Compare target and actual values at the same scale
=> Bugfix: Historical data in list visual

packages/meditrak-server/src/kobo/startSyncWithKoBo.js
=> Bugfix: Check value of kobo disable var, not just existence

full-testable-package.Dockerfile
NZ-916
- Ony copy package.json of all packages at the start, rather than other files within each folder, so that the yarn install result can be cached and will only rerun when there are changes within package.json's
- Only copy src directories of internal dependencies before build internal dependencies step, so that if a non internal dependency has code changes it doesn't invalidate the built internal dependency cache
- Alphabetise order of commands
=> NZ-916: Improve docker container caching ability

packages/entity-server/src/routes/hierarchy/EntityDescendantsRoute.ts, packages/entity-server/src/routes/hierarchy/MultiEntityDescendantsRoute.ts
entity-server endpoint: entities getDescendants() always return root entities. 
treat `includeRootEntity` param in URL as string in entity server
=> Treat includeRootEntity param in URL as string in entity server

packages/admin-panel/package.json, packages/lesmis/package.json, packages/psss/package.json, packages/web-frontend/package.json
- Disable generate source maps to reduce build size.
- Sandbox environment here: http://chris-dev-clone.tupaia.org
- Can confirm that source maps are not generated in sandbox environment:
- I haven't checked how much size were reduced in front end builds without generating sourcemaps, but the build was deployed fine without failing here:
https://app.codeship.com/projects/70159bc0-0dac-0138-fdcb-260b82737f4e/builds/9477e7a1-cba7-4024-afbb-5490d03c82f2?component=step_deploy-all_deploy-frontends_deploy-psss
- Tested on sandbox deployment, and the front ends (tupaia, admin-panel, psss, lesmis,...) were working fine
=> Disable generate source maps to reduce build size

packages/admin-panel/src/pages/resources/EntitiesPage.js, packages/meditrak-server/src/routes/importEntities/importEntities.js, packages/meditrak-server/src/routes/importEntities/populateCoordinatesForCountry.js
- We use entities with no location data like "Unknown Island" in Samoa to record some data
- Importing/updating children of these entities is impossible via the admin panel because of the error that was being thrown because these entities don't have location data
- This change allows entities like "Unknown Island" to continue to have no location data and for us to be able to import/update children of this entity in the admin panel
=> MEL-412 allow entity import with no location

packages/report-server/src/routes/TestReportRoute.ts
Had a couple options of how we could enforce permissions here:
1. Give access to all org units for users with 'BES Admin' access
2. Give access to org units if user has 'BES Data Admin' access to that org unit
It seems that generally in Admin Panel we allow users to do operations if they have 'BES Admin' access to any country. However, for viewing data in our applications, we restrict it per org unit, and the highest org unit level permission you can be given is 'BES Data Admin'. For this reason, I felt it was more appropriate to go with the second option.
=> MEL-449: Added BES Data Admin permission restrictions on /testReport endpoint

packages/database/src/ModelRegistry.js, packages/database/src/testUtilities/getTestDatabase.js, packages/meditrak-server/src/index.js, packages/meditrak-server/src/tests/testUtilities/database/getModels.js
I noticed a secondary (non release-blocking) issue while debugging the meditrak-app sync issue this morning: migrations adding indicators were throwing uncaught errors that showed they were trying to create two data sources for each indicator added.
The reason for this is that `IndicatorModel` has a change handler that creates a data source whenever a new one is added. This model is defined centrally, and imported wherever a `ModelRegistry` is created. When Tupaia is running, model registries are created all over the place - even if you're just running meditrak-server, two will be created (one by data-broker).
This PR stops all those extra model registries from calling the models' notifiers.
=> Only run change side effects in meditrak-server database

packages/meditrak-server/src/apiV2/export/exportSurveyResponses/exportResponsesToFile.js
SOL-395
Hot fix as it is breaking downloads in prod
My changes for long running exports had not properly filtered out non-exported answers, which was causing a bug as it didn't know where on the spreadsheet it should go.
=> SOL-395: Filter out answers for non-exported questions

packages/admin-panel/src/widgets/JsonInputField.js
- Fix label z-index issue. I do not fully understand why but the legend is getting positioned behind other layers and position relative brings it into the right pane. I tested on chroms, firefox and safari and works as expected.
---
See issue
=> Fix boolean label within JsonInputField

packages/admin-panel/src/pages/resources/DashboardItemsPage.js, packages/meditrak-server/src/apiV2/dashboardItems/DeleteDashboardItem.js, packages/meditrak-server/src/tests/apiV2/dashboardItems/DeleteDashboardItems.test.js, packages/meditrak-server/src/tests/apiV2/dashboardItems/EditDashboardItems.test.js, packages/meditrak-server/src/tests/apiV2/dashboardItems/GETDashboardItems.test.js
Will also delete the associated report
[ ] - Release task: @rohan-bes Delete the Palau PSSS dashboard items that were deprecated by: SOL-398
=> SOL-400: Add ability to delete dashboardItems from admin panel

packages/admin-panel-server/examples.http, packages/admin-panel-server/package.json, packages/admin-panel-server/src/@types/express/index.d.ts, packages/admin-panel-server/src/app/createApp.ts, packages/admin-panel-server/src/connections/MeditrakConnection.ts, packages/admin-panel-server/src/index.ts, packages/admin-panel-server/src/models/index.ts, packages/admin-panel-server/src/routes/ExportDashboardVisualisationRoute.ts, packages/admin-panel-server/src/routes/FetchDashboardVisualisationRoute.ts, packages/admin-panel-server/src/routes/FetchHierarchyEntitiesRoute.ts, packages/admin-panel-server/src/routes/FetchReportPreviewDataRoute.ts, packages/admin-panel-server/src/routes/ImportDashboardVisualisationRoute.ts, packages/admin-panel-server/src/routes/SaveDashboardVisualisationRoute.ts, packages/admin-panel-server/src/routes/index.ts, packages/admin-panel-server/src/utils/hasBESAdminAccess.ts, packages/admin-panel-server/src/utils/hasTupaiaAdminPanelAccess.ts, packages/admin-panel-server/src/viz-builder/dashboardVisualisation/DashboardVisualisationCombiner.ts, packages/admin-panel-server/src/viz-builder/dashboardVisualisation/DashboardVisualisationExtractor.ts, packages/admin-panel-server/src/viz-builder/dashboardVisualisation/validators.ts, packages/admin-panel-server/src/viz-builder/index.ts, packages/admin-panel-server/src/viz-builder/types.ts, packages/admin-panel/src/authentication/reducer.js, packages/lesmis-server/src/utils/accessPolicy.ts, packages/meditrak-server/src/permissions/assertions.js, packages/report-server/package.json, packages/server-boilerplate/src/orchestrator/routes/LoginRoute.ts, packages/utils/src/filesystem.js
The main change here was a bit of a refactor to the `DashboardExtractor` logic. It's been switched to just directly using `yup` validators, rather than a wrapper class, as the validators actually provide really nice typescript integrations.
- Added @types/express/index.d.ts
- Added explicit defintions for routes
- Refactored validators
- Fixed up examples.http
=> MEL-453: admin-panel-server typescript cleanups

packages/report-server/src/__tests__/reportBuilder/transform/aggregate.test.ts, packages/report-server/src/reportBuilder/transform/functions/aggregate/aggregations.ts
Throws an error is there's more than 1 value per group
=> Added 'single' aggregation function to report-server

packages/database/src/migrations/20210902055844-UpdateUNFPASbRawDataDownloadSurvey-modifies-data.js
Addresses https://beyondessential.slack.com/archives/GAK5V0HHQ/p1630556369013300
Config is generally copied from the existing `UNFPA_Raw_Data_Reproductive_Health_Facility` report, then changed the survey code and name to use the SB-specific version of the `RHFSC` survey: `RHFSCSI`.
Edit: I also updated the existing `UNFPA_Raw_Data_Reproductive_Health_Facility` report, since we temporarily enabled both `RHFSC` and `RHFSCSI` there, but we only really need the first (which is the original config)
=> Hotfix: Update UNFPA Raw Data Download Survey for SB

packages/database/src/migrations/20210804054649-CovidSamoaReinstateHouseholdOverlay-modifies-data.js, packages/database/src/migrations/20210805035710-CovidSamoaAddHouseholdPointdata-modifies-data.js
Hotfix
- Unvaccinated households down to 3k which is acceptable to reinstate the household overlay while a better performance enhancement goes through usual test cycle.
- Re-add point data correcting original import mistake
Also includes https://github.com/beyondessential/tupaia/pull/3149
=> [HotFix] Fix covid-samoa household overlay

packages/devops/scripts/deployment/startup.sh
In https://linear.app/bes/issue/WAI-930#comment-09e03aa1 we experienced an issue where all appeared fine with the feature instance, but that was because it was serving the previously built production code. This means the startup script would exit early rather than getting to the part where nginx fires up and makes it look like it's finished successfully
=> Startup script should exit if any command fails

packages/utils/src/errors.js
=> Add stacktrace to logged errors

packages/ui-components/src/components/Map/Markers/MeasurePopup.js, packages/ui-components/src/components/Map/PopupDataItemList.js, packages/ui-components/src/components/Map/index.js, packages/web-frontend/src/components/Marker/PopupMarker.js, packages/web-frontend/src/containers/Map/AreaTooltip.js
SOL-711 Support specifying `hideFromPopup` for different values in area tooltips (hover). 
config:
>  "values": [
{
"value": null,
"hideFromPopup": true
}
]
Use the same logic in `PopupMarker` for rendering the list and hideFromPopup.
=> Support hide from popup in tooltips

packages/devops/scripts/deployment/deployPackages.sh
https://github.com/beyondessential/tupaia/pull/3192 introduced a great new environment banner, but because we have two build paths (one through CI/CD, the other on server startup), the same env var needs to be applied to the other place
=> Add environment variable to front end builds on startup

.eslintrc
Front-end builds are currently failing due to not being able to resolve the eslintc react-native package (or something like that).
Since the new flow involves new builds deleting the existing builds directories, this means that Tupaia ends up 'Under Maintenance' each time a new build comes in. 
This is a short term hack to get builds working again.
We need to follow up by:
1. Fixing up the eslint dependencies
2. Ensure that if building the frontend packages fails, the build fails and we don't deploy over the existing build
=> Hack to get front-end builds running again

packages/admin-panel/src/VizBuilderApp/components/PreviewSection.js
This just transforms all values to primitives, otherwise the table will error, I took a look at the react table docs (which is where this is eventually rendered) and they say that accessor can only return a primitive value. I hope this is ok to slip in, as it will only ever matter when val is an object or a function, where previously it would give an unhelpful error `Something went wrong`
=> PHX-45 Allow displaying objects in vizbuilder

packages/api-client/package.json
Is causing CI build to fail now that we are stricter about this. This is a workaround, proper fix incoming which fixes the type errors.
=> Allow api-client build errors

packages/devops/Set up server.md, packages/meditrak-server/src/apiV2/export/getExportPathForUser.js, packages/meditrak-server/src/apiV2/import/index.js, packages/meditrak-server/src/utilities/getTempDirectory.js, packages/meditrak-server/src/utilities/index.js
- WAI-950
- Uploads and exports are written to the temporary folder defined by the OS
Note that on most systems this means they will be deleted on restart, so I've also tweaked the instructions for setting up a new EC2 instance to preserve them for 20 days
=> WAI-950: Write temporary files to system tmp directory

packages/devops/scripts/ci/pushBuilds.sh
- WAI-951
Use a specific `incoming_builds` folder, suffixed with the CI build timestamp. There is still the opportunity for clashes, if they both hit the specific bit of the push that moves the unzipped folder over the top of the `tupaia` at the same time. That's a relatively fast step though (I'd say a second or two), whereas the entire `Push builds` step takes around 10 minutes, so it will greatly minimise the chance of conflicts causing issues
=> WAI-951: Minimise likelihood of concurrent builds conflicting

packages/devops/scripts/deployment/deployPackages.sh
The startup script is now running a stricter mode, where any failures of internal steps will fail the whole script. On startup, there are generally no processes running, so `pm2 delete all` throws a non zero exit code. This ignores that.
=> Ignore non-zero status codes from pm2 delete all

packages/meditrak-server/src/devops/getIsProductionEnvironment.js, packages/web-config-server/src/utils/getIsProductionEnvironment.js
The test suite will bail early if it gets run in a "production environment". Now that we're pulling the appropriate .env files for the current branch in CI/CD, builds to `master` get the production environment variables, so the tests can't run, even on the build machine. This tweaks what is considered a "production environment" to exclude when we are inside a CI/CD process on codeship.
See [this failed build](https://app.codeship.com/projects/70159bc0-0dac-0138-fdcb-260b82737f4e/builds/e3edb781-ba9f-489c-9881-5fc419e97803?component=step_Validate_and_test_Test_Test_meditrak-server) for context
=> [HOT FIX]: Don't consider CI build time a production environment

packages/ui-components/src/components/Map/Legend/SpectrumLegend.js, packages/ui-components/src/components/Map/__tests__/markerColors.test.js, packages/ui-components/src/components/Map/constants/colors.js, packages/ui-components/src/components/Map/constants/constants.js, packages/ui-components/src/components/Map/utils/markerColors.js
- Add new GPI Spectrum type
This is quite a specific type but considered common enough to have its own type. We did look into making it more generic but we deemed that substantially harder to implement.
---
See issue
=> Add support for GPI map overlays

packages/database/src/migrations/20210921183003-remove-laos-schools-map-overlay-modifies-data.js
Remove old laos schools map overalys to make way for the new ones as part of this cycle of new overlays. I didn't remove all the old ones as they might be good to have for future reference. They can always be deleted later on when they get replaced.
---
=> remove old laos schools map overalays

packages/database/src/DatabaseModel.js, packages/database/src/TupaiaDatabase.js
https://github.com/beyondessential/tupaia/pull/3273 is failing tests because of an issue inserting test data into the db. The problem is that knex doesn't handle json/jsonb columns where the root of the object is an array, see https://knexjs.org/#Schema-json
=> Sanitize jsonb arrays

packages/report-server/src/__tests__/reportBuilder/output/output.test.ts, packages/report-server/src/reportBuilder/output/functions/matrix/matrix.ts, packages/report-server/src/reportBuilder/output/functions/matrix/matrixBuilder.ts, packages/report-server/src/reportBuilder/output/functions/matrix/types.ts, packages/report-server/src/reportBuilder/output/output.ts
Just a small refactor here to use `yup` object validation over our original hand crafted version. Will be using these changes later down the line when adding functionality for: https://linear.app/bes/issue/RN-28/date-selector-shows-latest-data-by-default
=> Switched output over to using yup validation for report-server output step

packages/ui-components/src/components/Map/PopupDataItemList.js
https://beyondessential.slack.com/archives/C01MAA3NKM1/p1632719896018900
Issue in tupaia-release 
Previously `showNoDataLabel` is used for lesmis and tupaia separately, but now they can use the same code.
=> Fix not showing no data label

packages/auth/package.json, yarn.lock
WAI-956
Changes:
- Use a common `lodash` version across all dependencies. To do this, I combined lines in the `yarn.lock` file where `lodash` was being unnecessarily resolved using different versions, despite all dependents accepting any version within the same minor. This saved the majority of time, the reason being that it was having to copy across the (rather bloated) lodash library into every dependency that used it. Now, just one version is installed in the root `node_modules`, which is then utilised everywhere else. This is the default behaviour `yarn` uses to hoist nested dependencies, but it will only hoist one version, so when there are many being resolved, you end up with a lot of duplication.
- Changed legacy @beyondessential/tupaia-access-policy so that it doesn't …
=> WAI-956: Reduce feature branch deployment time by 30 minutes

packages/lesmis/src/api/queries/useMapOverlayReportData.js
There are 2 commits on this PR. The first one is a simple refactor which I did as part of debugging the issue. The second one is the actual fix.
Always get measureData for the whole country so that the displayed area has a color relative to the rest of the country.
---
See WAI-5 Issue
=> WAI-5: Fix lesmis map spectrum colors

packages/database/src/changeHandlers/AnalyticsRefresher.js, packages/database/src/tests/changeHandlers/AnalyticsRefresher.test.js
Due to the performance improvements in the latest pg-mv-fast-refresh version, I think we can try allowing the auto refresh behaviour when any source table changes. Previously we were refraining from refreshing some of the more sensitive tables as it seemed to have poor performance and we didn't want to refresh in the middle of a large import (entities for instance). Now that the behaviour seems fast across all tables, we can try always auto refreshing. The benefit of this is that changes will be integrated faster and more reliably, and large log table backlogs are less likely to build up.
- Bump pg-mv-fast-refresh version to include performance improvements
- Now we can try refresh if any of the source tables change
---
=> RN-82: Auto refresh analytics when any source table changes

packages/ui-components/src/components/Map/MarkerLayer.js
Fix issue with shaded polygons where colors don't update. Issue caused by upgrade to new version of react-leaflet. It turns out there is a different prop for colors if it needs to be mutable.
---
=> hotfix-lesmis-shaded-polygons

packages/admin-panel/src/VizBuilderApp/api/queries/useLocations.js
Bug occurred due to attempting to fetch available locations before selecting a hierarchy.
- Added handler for when project is undefined
---
=> RN-124: Fix error that appears in console when opening viz-builder

packages/admin-panel-server/src/routes/SaveDashboardVisualisationRoute.ts, packages/admin-panel-server/src/viz-builder/dashboardVisualisation/DashboardVisualisationExtractor.ts
https://linear.app/bes/issue/RN-126/vizbuilder-save-error-invalid-content-for-field-legacy
=> Hoftix: Fix new viz save

packages/report-server/src/__tests__/reportBuilder/context/buildContext.test.ts, packages/report-server/src/__tests__/reportBuilder/transform/parser/functions.test.ts, packages/report-server/src/aggregator/Aggregator.ts, packages/report-server/src/reportBuilder/context/buildContext.ts, packages/report-server/src/reportBuilder/context/extractContextProps.ts, packages/report-server/src/reportBuilder/context/index.ts, packages/report-server/src/reportBuilder/context/types.ts, packages/report-server/src/reportBuilder/transform/index.ts, packages/report-server/src/reportBuilder/transform/parser/TransformParser.ts, packages/report-server/src/reportBuilder/transform/parser/functions/context.ts, packages/report-server/src/reportBuilder/transform/parser/functions/index.ts, packages/report-server/src/reportBuilder/transform/parser/index.ts, packages/report-server/src/reportBuilder/transform/transform.ts
Basically just importing the `dataElementCodeToName` from the analytics fetch into the context, and then using a function to reference it from there. I thought about allowing users to directly reference the `metadata` object in the transform itself, and I think that could still have merit, but this method is cleaner and easier for users to work with 👍 
Note: only works with fetch analytics for now. If we want to add support when using fetch events I'd recommend we support that by returning metadata from fetch events also
A couple of cleanups in this PR as well, hopefully they aren't too distracting.
=> RN-125: Add 'dataElementCodeToName' function to report-server transforms

packages/web-frontend/src/components/mobile/FilterSelect/index.js
- Swap `id` in FilterSelect to refer to `code` instead, since that's what's being passed by the map overlays now
=> Swap id for code in FilterSelect

packages/admin-panel/src/pages/resources/DashboardItemsPage.js, packages/lesmis/src/routes/AdminPanelRoutes.js, packages/lesmis/src/views/AdminPanel/DashboardItemsView.js, packages/lesmis/src/views/AdminPanel/SurveyResponsesView.js
Fixes bug found in testing where dashboard item import and export don't work in lesmis admin panel
See testing comment: https://linear.app/bes/issue/WAI-1001#comment-c76db317
- Remove import and export buttons from Dashboard Items page because they are handled by admin-panel-server and not meditrak-server
---
=> remove-dashboard-item-import-export

packages/meditrak-server/src/apiV2/export/exportSurveyResponses/exportResponsesToFile.js, packages/meditrak-server/src/dataAccessors/findAnswersInSurveyResponse.js
Issue: https://linear.app/bes/issue/WAI-1020/export-answers-to-entity-questions-as-codes-rather-than-ids
This exports Entity answers as the Entity code instead of the Entity id
=> wai-1020 export code instead of id for entities

packages/dhis-api/src/DhisApi.js
This PR changes the default lookback period from 600 days to 3650 days (e.g. 10 years). The reason for this is that we have data on DHIS2 that is older than 600 days now and for databuilders where the default lookback period is used the data doesn't fetch
=> wai-1018 update dhisApi default lookback period

packages/database/src/modelClasses/AncestorDescendantRelation.js, packages/database/src/modelClasses/Entity.js, packages/entity-server/src/routes/hierarchy/format/formatEntityForResponse.ts, packages/web-config-server/src/apiV1/organisationUnit.js
This isn't an exhaustive investigation/fix by any means, but addresses a few low hanging fruit.
It seems that memory consumption when loading the /organisationUnits route in a project with a large hierarchy can be very high. During this process the memory usage of the web-config-server can spike to over 1GB. Initially the memory seemed to be leaking as it stayed high and grew on each subsequent request, but it turns out that was just the Node garbage collection not cleaning things up as yet. 
Overall to stop such issues in the future we probably need to tune our max memory limits for the various servers to something more safe given the total RAM of the feature instances is only 4GB.
Actual fixes here:
1. Pushed the filtering for unique entities in Entity.js inside the cached function. …
=> RN-196: Few fixes for heavy memory usage when fetching /organisationUnits

packages/meditrak-app/ios/TupaiaMediTrak/Info.plist, packages/meditrak-app/package.json
- Bump meditrak app version number before publishing an app release
=> Bump version to 1.11.115

packages/database/src/DatabaseChangeChannel.js
If the database instance and server instance are started at the same time, sometimes the pm2 processes will start up before the database is available. This means the servers will be a little more patient before giving up
=> WAI-963: Wait a full minute for the database to become available

packages/devops/scripts/lambda/actions/backup_instances.py, packages/devops/scripts/lambda/actions/redeploy_tupaia_server.py, packages/devops/scripts/lambda/actions/refresh_cloned_instances.py, packages/devops/scripts/lambda/actions/spin_up_dhis_deployment.py, packages/devops/scripts/lambda/actions/spin_up_tupaia_deployment.py, packages/devops/scripts/lambda/actions/swap_out_tupaia_server.py, packages/devops/scripts/lambda/actions/tear_down_dhis_deployment.py, packages/devops/scripts/lambda/actions/tear_down_tupaia_deployment.py, packages/devops/scripts/lambda/helpers/clone.py, packages/devops/scripts/lambda/helpers/create_from_image.py, packages/devops/scripts/lambda/helpers/creation.py, packages/devops/scripts/lambda/helpers/networking.py, packages/devops/scripts/lambda/helpers/teardown.py
WAI-963 (already released, these are tweaks only)
Commit names show the changes. The main change is the final commit, which adds a "DeploymentType" tag on instances, gateways, etc. so that we can distinguish between tupaia, regional-dhis2, and tonga-dhis2 deployments. Currently there are some that share a DeploymentName (e.g. dev, e2e) so you can unintentionally tear down instances you don't mean to.
=> WAI-963: Additional tweaks

packages/devops/scripts/ci/triggerRedeploy.sh, packages/devops/scripts/lambda/actions/redeploy_tupaia_server.py
Now that we have four deployments all connected to the master branch, the lambda redeploy function was taking longer than the default AWS CLI timeout. The AWS CLI then kicks into "helpful" retry attempts, which resulted in multiple deployments coming online for production, e2e, viz-testing and viz-sandbox.
This change:
- Increases the AWS CLI timeout to match lambda's 15 min max execution time
- Turns off the retry attempt behaviour, lest it try to be helpful again in future
=> [HOT FIX] Avoid multiple redeploy attempts

packages/web-frontend/public/index.html
- Use REACT_APP_DEPLOYMENT_NAME value to only run analytics on live deployments
---
=> wai-352: Restrict analytics to production

packages/database/src/migrations/20211124053026-AddMapOverlayGroupForNcd-modifies-data.js
No issue
That's the only overlay group we need for project `pen fa'a`. Since it is just an overlay group, I assume that we can put no testing required label.
=> Add map overlay group for project pen fa'a

packages/devops/scripts/ci/triggerRedeploy.sh, packages/devops/scripts/lambda/actions/spin_up_tupaia_deployment.py, packages/devops/scripts/lambda/helpers/networking.py
WAI-963 (already released)
If someone pushes to a branch out of hours, the redeploy will fail, but the build will still go green. This is because when the servers try to start up, the db instance will be sleeping. This change doesn't actually make it work (if we want to fix this properly, we should wait until the RDS transition is complete), but does mean that if the deployment is stopped, codeship won't trigger a redeploy, but will mark the build as failed so the dev knows to retry it during office hours.
=> WAI-963: Fail build when committing to a deployed branch out of hours

packages/devops/scripts/deployment/buildDeployablePackages.sh, packages/devops/scripts/deployment/setupGoldMaster.sh, packages/devops/scripts/lambda/actions/spin_up_tupaia_deployment.py, packages/devops/scripts/lambda/resources/startup.sh, yarn.lock
Deployments have been failing because:
- The `yarn.lock` file in dev is out of date with the actual dependencies required
- At the end of `yarn install` during startup, yarn tries to update that `yarn.lock` to reflect the current status
- The `tupaia` repo is owned by the root user on the gold master
This PR fixes all three of those issues, as well as two unrelated nits that I came across during debugging.
=> Fix yarn install during deployment

packages/admin-panel/src/autocomplete/Autocomplete.js, packages/admin-panel/src/autocomplete/actions.js, packages/admin-panel/src/pages/resources/AccessRequestsPage.js, packages/admin-panel/src/pages/resources/PermissionsPage.js, packages/admin-panel/src/widgets/InputField/registerInputFields.js
Was caused by a build up of queries against the entity table, which is huge and possibly poorly indexed, so the queries were taking a long time to return. Filtering by country is both a UX improvement, and means the query returns very quickly.
-  Only show countries when granting access requests or permissions
=> WAI-1054: Fix timeouts when processing access requests

packages/devops/scripts/lambda/resources/startup.sh
Currently we don't see the error message if the deployment fails, which can make debugging tricky.
-  Added `&` to pipe to log stderr as well as stdout (https://www.gnu.org/software/bash/manual/bash.html#Pipelines)
=> RN-221: Log deployment errors to deployment.log file

packages/database/src/migrations/20211201223600-DeleteCovid19SurveillanceDashbaord-modifies-data.js
PHX-148: Delete Empty Dashboard Group "COVID 19 Surveillance"
- delete record from dashboard table
=> phx-148-delete-dashboard-covid19-surveil

packages/admin-panel/src/VizBuilderApp/components/PreviewOptions.js
Not sure how long this has been broken hehe 😅 Basically due incorrectly treating the string input as an object we were never actually searching for values (however the `Autocomplete` component automatically searches through it's known data so it had the appearance of searching...)
=> RN-226: Fixed error where location search wasn't working as intended

packages/devops/scripts/lambda/resources/startup.sh
WAI-1083
- Allow cron job to write to the logs folder, which was write protected and preventing the script from running
- Fix date handling in cron job output pipeline, which was being evaluated early 
- Store cron job under ubuntu user so it is easier to find, and not running as root
- Use same PATH as regular bash scripts so `yarn` is available, etc.
=> WAI-1083: Fix preaggregations not running overnight

packages/ui-components/src/components/Chart/CartesianChart.js
- Trigger re-render on bar charts so that the layout is calculated correctly everytime
---
=> Fix bar chart legend overlap

packages/web-frontend/src/reducers.js, packages/web-frontend/src/sagas.js, packages/web-frontend/src/selectors/index.js, packages/web-frontend/src/selectors/mapOverlaySelectors.js, packages/web-frontend/src/utils/mapOverlays.js
PHX-231
- sagas cannot perform a fetch using latest date that updated by reducer. I believe it is designed for a reason. So we need to use the latest date from `UPDATE_MAP_OVERLAY_CONFIG` action.
- `selectMapOverlayGroupByCode ` -> `updatedMapOverlayHierarchyConfig` and it becomes a recursive function to add map overlay config for updated date.
- Example
---
=> PHX-231 Can't change date in map overlay

packages/dhis-api/src/DhisApi.js
Issue: https://linear.app/bes/issue/NOT-903/dhis2-data-sets-no-longer-completing-automatically
Basically this PR makes it so that data submitted against data sets is "completed" automatically when the data syncs to DHIS2
- "Completed" basically just means added to the `completedatasetregistration` table
For context - this used to happen automatically but stopped working in mid December (coincidentally right after we patched DHIS2 as mentioned in the issue linked above). This PR seems to make it work again
=> NOT-903 fix dataset autocompletion

packages/database/src/migrations/20220119005332-UpdateTongaCovidPermissions-modifies-data.js
MAUI-267: Tonga using permission groups COVID-19 and COVID-19 Senior which are in COVID-19 Samoa's permission hierarchy
- One migration to change parent of 'COVID-19 Senior' permission group to Fanafana Ola Admin
=> MAUI-267: Update Tonga Covid Permission Group

packages/meditrak-server/src/dataAccessors/editSurvey.js
RN-253
Reason: `service_type` plays a role in survey update validation. While we only want to change the survey code in admin panel, it doesn't have `service_type` in updated field from front end.
Change: Add `service_type` from `dataGroup` if `service_type` is not set.
=> Unable to edit survey code on certain surveys

packages/meditrak-server/src/apiV2/questions/GETQuestions.js, packages/meditrak-server/src/apiV2/questions/assertQuestionPermissions.js
- add filter for questions based on survey permission group and country access
---
=> WAITP-990: add question permission filter

packages/web-frontend/src/components/View/View.js, packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialogContent.js, packages/web-frontend/src/containers/MapOverlayBar/LastUpdated.js
RN-250
`moment.js` is not able to import date with format 'yyyymm', thus we need to use our customised translate function `periodToMoment` in front end.
=> Display latest overlay date in a format

packages/web-config-server/README.md, packages/web-frontend/src/components/View/SingleDownloadLinkWrapper.js
MAUI-367
[This hot fix](https://github.com/beyondessential/tupaia-backlog/issues/3208) worked for standard raw data downloads, but not for latest data downloads. This PR brings the same strategy of fetching against the correct URL for web-config-server to latest data downloads.
=> MAUI-367: Fully qualify URL for latest data downloads

packages/meditrak-server/src/social/getLeaderboard.js
Issue: https://linear.app/bes/issue/RN-344/remove-tamanu-server-user-from-meditrak-leaderboard
This (in theory) removes Tamanu Server from the MediTrak leaderboard. I haven't tested it locally but I feel confident it will work
=> rn-344 remove tamanu server from meditrak leaderboard

packages/admin-panel/src/VizBuilderApp/api/queries/index.js, packages/admin-panel/src/VizBuilderApp/api/queries/useSearchAggregationOptions.js, packages/admin-panel/src/VizBuilderApp/api/queries/useSearchDataSources.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/AggregationDataLibrary.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/DataElementDataLibrary.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/index.js, packages/admin-panel/src/VizBuilderApp/components/Panel.js, packages/ui-components/src/components/DataLibrary/DataLibrary.js, packages/ui-components/src/components/DataLibrary/options.js, packages/ui-components/stories/dataLibrary.stories.js
RN-347 
1. Enable aggregate tab to use transfer
2. Extend `useSearchDataSources` to fetch `aggregationTypes` from `report-server` 
3. Add a tooltip to show description when hover on result list
https://linear.app/bes/issue/RN-347#comment-232e5cf7
=> RN-347 enable aggregate tab to use transfer

packages/meditrak-server/src/apiV2/export/exportSurveyResponses/exportResponsesToFile.js
MAUI-390
During a disaster, users are likely more interested in data that relates to the most recent time period rather than the data that was most recently submitted. This changes the raw data download to sort by date of data rather than the time the survey was completed, and fixes a mismatch between the export and the visual, reported **Issue 2** in MAUI-390
=> MAUI-390: Base the latest responses on data time rather than end time

packages/database/src/migrations/20220208004345-RemoveApostropheFromAustralianEntityCode-modifies-data.js
MAUI-419: Remove apostrophe from Australian entity
- Add migration to remove an apostrophe from the entity named "Break O'Day"
=> MAUI-419: Remove apostrophe from Australian entity

packages/indicators/src/Builder/helpers.ts
[Issue from slack](https://beyondessential.slack.com/archives/C02HES8HFQF/p1644452399914279)
We were doing an `arrray.push` over a large number of values. It will put a large amount of number (number > ~135000) as function arguments on the stack, which will cause maximum call stack size exceeded error.
Using spread `...` can fix this.
=> Fix maximum call stack size exceeded with array.push

packages/devops/scripts/lambda/helpers/teardown.py
WAITP-1106
- Use boto3's paginator (and undocumented `build_full_result` feature) to get all route53 entries when checking which are appropriate to delete, so we don't just get the first page and miss the ones we're after
- Only delete subdomains via dns if the instance is tagged as having them (which the app server isn't - didn't realise this was buggy because we've never actually been deleting route53 entries due to the pagination issue!)
=> WAITP-1106: Properly delete route53 entries on teardown

packages/admin-panel/src/pages/resources/PermissionsPage.js
WAITP-1104
Handling the creation of permissions in bulk added some very helpful functionality, but broke editing a single record. This reinstates editing a single record.
=> WAITP-1104: Fix single record editing on permissions page

packages/meditrak-app/appcenter-post-clone.sh
RN-229
This will allow us to load node version from `root/.nvmrc`, instead of using app center default node version for `appcenter-post-clone` step.
https://appcenter.ms/orgs/Beyond-Essential/apps/Tupaia-MediTrak-Android/build/branches/test-app-center/builds/901
=> RN-229 Workaround to override the v8 alias

packages/admin-panel/src/pages/resources/PermissionsPage.js, packages/database/.babelrc, packages/database/.babelrc.js, packages/database/package.json, packages/database/src/getDbMigrator.js, packages/database/src/index.js, packages/database/src/migrate.js, packages/database/src/migrations/20220210214956-UpdateCovid19SamoaVisualisationPermissions-modifies-data.js, packages/database/src/migrations/20220210235957-UnfpaMarshallIslandsAddFacilities-modifies-data.js, packages/database/src/migrations/20220218050602-AddCovidKiribatiProject-modifies-data.js, packages/devops/scripts/deployment/startBackEnds.sh, packages/devops/scripts/lambda/actions/redeploy_tupaia_server.py, packages/devops/scripts/lambda/helpers/teardown.py, packages/indicators/src/Builder/helpers.ts, packages/meditrak-app/appcenter-post-clone.sh, packages/meditrak-server/src/index.js, packages/web-config-server/src/export/excelFormatters/formatMatrixDataForExcel.js, scripts/bash/buildInternalDependencies.sh
MAUI-429: Create project Covid-19 Kiribati
- No issue: Fix maximum call stack size exceeded with array.push
- RN-335 Fix COVID-19 Samoa visualisation permission issues
- WAITP-1105 and WAITP-1103: Include category headers when exporting matrix to excel
- WAITP-1104: Fix single record editing on permissions page
- RN-301: Add new Marshall Island facilities to UNFPA
- RN-229 Work around to override the v8 alias (#3678)
- WAITP-1106: Properly delete route53 entries on teardown
- WAITP-1107: Copy over StartAt/StopAt tags when redeploying
- WAI-1070: Migrate database when meditrak-server starts via pm2
=> Release 2022-7

packages/database/package.json
In today's release, we changed to running migrations within the meditrak-server process when it starts up. Subsequently, we deployed the first migration since that change as a hot-fix, and it met an edge case: json files were not included in the `dist` folder that meditrak-server reads migrations from. 
See https://beyondessential.slack.com/archives/CT0KTFSHZ/p1645492338632989?thread_ts=1645491301.510779&cid=CT0KTFSHZ
=> [Hot fix]: Include json migrationData files in babel output directory

packages/devops/scripts/lambda/actions/start_tagged_databases.py, packages/devops/scripts/lambda/actions/stop_tagged_databases.py, packages/devops/scripts/lambda/helpers/rds.py, packages/devops/scripts/lambda/lambda_function.py
Added deployment scripts to stop and start RDS instances based on the `StartAtUTC` and `StopAtUTC` tags.
Will add EventBridge configurations to trigger these automatically
=> RN-368: Added overnight shutdown for RDS

packages/database/src/migrations/20220223052221-DeleteInvalidKiribatiEntities-modifies-data.js
Issue [MAUI-530](https://linear.app/bes/issue/MAUI-530):
(cherry-picked commits from previous PR: https://github.com/beyondessential/tupaia/pull/3715)
Changes:
Create database migration that will:
Remove invalid district and sub_district entity records
Reassign a valid parent id to an orphan facility entity
=> MAUI-530: Remove invalid Kiribati entities

packages/database/src/DatabaseChangeChannel.js, packages/database/src/TupaiaDatabase.js
Remove db change channel timeout to fix issue of db being down for ~10 minutes for the overnight sync.
Have tested on my local:
1. start servers with db down and wait 4 minutes (previous timeout), then start db 
2. start servers with db up, take db down for 4 minutes, then start db
...it reconnects and everything seems to work fine.
Not sure what the other implications of this change are.
=> Remove db change channel timeout

packages/admin-panel-server/src/app/createApp.ts, packages/admin-panel-server/src/connections/ReportConnection.ts, packages/admin-panel-server/src/routes/FetchReportSchemasRoute.ts, packages/admin-panel-server/src/routes/index.ts, packages/report-server/examples.http, packages/report-server/src/app/createApp.ts, packages/report-server/src/reportBuilder/transform/functions/excludeColumns.ts, packages/report-server/src/reportBuilder/transform/functions/excludeRows.ts, packages/report-server/src/reportBuilder/transform/functions/index.ts, packages/report-server/src/reportBuilder/transform/functions/insertColumns.ts, packages/report-server/src/reportBuilder/transform/functions/insertRows.ts, packages/report-server/src/reportBuilder/transform/functions/mergeRows/index.ts, packages/report-server/src/reportBuilder/transform/functions/mergeRows/mergeRows.ts, packages/report-server/src/reportBuilder/transform/functions/sortRows.ts, packages/report-server/src/reportBuilder/transform/functions/transformValidators.ts, packages/report-server/src/reportBuilder/transform/functions/updateColumns.ts, packages/report-server/src/routes/FetchTransformSchemaRoute.ts, packages/report-server/src/routes/index.ts, packages/report-server/src/types.ts, packages/utils/src/__tests__/validation/DescribableLazy.test.js, packages/utils/src/validation/DescribableLazy.js, packages/utils/src/validation/yup.js
Part of RN-161
Slightly different approach from discussed with @IgorNadj . We can actually expose the type objects that are used by `yup.js`, which is a constant object.
=> RN-161 Fetch transform schema endpoints

packages/report-server/src/__tests__/reportBuilder/query/QueryBuilder.test.ts, packages/report-server/src/reportBuilder/query/buildPeriodParams.ts
Currently in `report-server`, `offset` config in `fetch's startDate` will be applied on `endDate` instead of `startDate`.
1. I've checked we are lucky to have only one visual at the moment(`PG_Strive_PNG_Prev_7_Days_Reported_Cases`) to use this config, and it didn't break anything after the changes.
2. From `periodGranularities.test.js` we can tell that it always put start date and end date in query, so there is no way we have a `null` start date.
3. It will be also consistent to the frontend offset config `defaultTimePeriod`:
>    {
start: { unit: 'day', offset: -1 },
end: { unit: 'day', offset: 3 },
}
=> offset from start date instead of end date

packages/web-frontend/package.json, scripts/bash/getDeployablePackages.sh
…(#3751)
* Switched from building frontend modules in serial rather than parallel
* Re-ordered how server packages are built so that dependencies resolve correctly
- admin-panel-server depends on report-server, so it must be build first
- Example
---
=> Sima Create Instance

packages/report-server/examples.http, packages/report-server/src/app/createApp.ts
The issue here is that the `next()` function was never being called when the middleware was appended to the request. As a result requests were never actually being handled.
=> Hotfix: Release 2022-9 - Fix report-server not responding to requests

packages/psss-server/package.json, packages/server-boilerplate/src/orchestrator/auth/AuthConnection.ts
This was a very strange issue and tbh I still don't quite understand why this was happening.
Whenever we attempted to login to PSSS, we'd send across an auth header of `Basic dW5kZWZpbmVkOnVuZGVmaW5lZA==` which decodes to username and password as `undefined`. This would fail to authenticate and the user couldn't log in.
The auth header is meant to be defined by 2 .env vars:
`MEDITRAK_API_CLIENT_NAME` and `MEDITRAK_API_CLIENT_PASSWORD`
Both of these .env vars are present in the PSSS .env file, with correct values. PSSS is loading its .env vars _**exactly**_ the same as how lesmis does. When logging out the .env vars with a console log they had the correct values.
So I'm pretty stumped, but applying these changes fixed the issue:
1. Correctly listing `dotenv` in psss-server's `package.json` …
=> Hotfix: Release 2022-9 - Fixed login failing on PSSS due to poorly loaded .env vars

package.json, packages/devops/ci/e2e.Dockerfile, packages/devops/ci/tupaia-ci-cd.Dockerfile, packages/meditrak-app/appcenter-post-clone.sh
Cypress installation requires postinstall hook to run
This fixes cypress being installed correctly. ~But it also removes the convenience behaviour for local development of rebuilding internal dependancies after running yarn install.~
=> Fix cypress not found when running e2e

packages/auth/src/AccessPolicyBuilder.js, packages/auth/src/__tests__/AccessPolicyBuilder.test.js
This is a pretty obvious problem when you look at it. We always cache the first time we try to build the access policy for a user, however if that fails for any reason (eg. database connection timeout) we keep that cached result. That can be seen happening here: https://beyondessential.slack.com/archives/C01JD93J4E6/p1646349708959339
This seems to be a fairly general case problem. In the past, we've made a conscious effort to try and cache promises rather than results (in order to avoid many requests for the same expensive resource). However the natural downside of doing that is that we don't know if the promise resolves successfully or not...
Happy to chat with the reviewer and decide if this should be fixed in other areas (namely `DatabaseModel.js`)
=> RN-396: Remove failed access policies  from the cache if they fail to build

packages/admin-panel/src/authentication/LoginForm.js, packages/admin-panel/src/authentication/reducer.js, packages/admin-panel/src/authentication/selectors.js
- RN-258
Although the ticket says to use a loading spinner, our common ui-component Button uses the "Loading..." text, so I've gone with that here too. That keeps the interface consistent with PSSS, LESMIS, etc.
=> RN-258: Show loading state on admin panel login

packages/meditrak-server/src/apiV2/import/importSurveyResponses/assertCanImportSurveyResponses.js, packages/meditrak-server/src/tests/apiV2/postChanges.test.js
- RN-411
When using Tupaia for recording lab results, you create a `case` entity in the "C19 Test Registration" survey, and then submit a "C19 Test Result" survey against that same case. If both the registration and the result sync up to the server in the same batch of changes, the permissions check for the result will fail, because the `case` won't have been created until the "C19 Test Registration" is fully processed. This PR fixes that, allowing the permissions check for the "C19 Test Result" response to use the case created in the registration response, before it has been saved to the db.
=> RN-411: Use new entity as primary entity in same sync batch

packages/web-frontend/src/components/ControlBar.js, packages/web-frontend/src/components/SearchBarItem.js, packages/web-frontend/src/containers/SearchBar/index.js, packages/web-frontend/src/containers/mobile/EntityHierarchy.js, packages/web-frontend/src/styles/index.js
I noticed that the change to a full black entity hierarchy looked a bit wrong on desktop, so this changes it to have a more subtle background.
=> RN-387: Improve entity hierarchy desktop styles

packages/devops/scripts/lambda/actions/redeploy_tupaia_server.py, packages/devops/scripts/lambda/actions/spin_up_tupaia_deployment.py, packages/devops/scripts/lambda/helpers/create_from_image.py
This not only meant that if we deleted old images, we couldn't redeploy to servers based on those images, but _we weren't actually including the latest security patches on production_ 🤦
=> Use the latest image, even on redeploy

packages/devops/scripts/ci/validateBranchName.sh
Underline in branch name will fail to tear down an instance.
=> Add underline as invalid chars in branch name

packages/meditrak-server/src/apiV2/import/importDataSources/createDataSources.js
Issue #:
RN-419
Changes:
Currently we block the update if code existed. If we can update the existing date elements in bulks, we can reuse the data elements for lesmis in the datalake and the existing reports.
=> Update fields if data element existed

packages/lesmis-server/locales/lo.json
The translatable route uses . and : as delimiters of the transition object key and so they don't work in actual translation string keys. There is no easy fix for the delimiters working in the translations but a simple work around is to just remove them from the delimiters translation config keys. The end result is the 100% correct translation.
=> WAITM-1111: Fix missing lesmis translation

packages/meditrak-app/app/assessment/DumbQuestion.js, packages/meditrak-app/app/assessment/DumbSurveyScreen.js, packages/meditrak-app/app/assessment/QuestionScreen.js, packages/meditrak-app/app/assessment/SurveyScreen.js, packages/meditrak-app/app/entityMenu/EntityList.js
This is an attempt to fix _**known_issue_1**_ recorded [here](https://linear.app/bes/issue/RN-439#comment-1fe72a8a)
Honestly I'm on the fence about whether this is worth merging. It feels kinda heavy handed and over complicated for solving one minor UX interaction, so I'm interested in the reviewers thoughts.
The current behaviour is that if the entity question is the last one on a screen, when you click to focus it, the results of your search will be entirely hidden by the keyboard
The change here makes the question scroll nearly to the top of the screen, allowing at least one result to be seen (on the screen size I'm emulating anyway) 
This comes at the expense of a large amount of whitespace that can be scrolled into view at the bottom of the screen. I don't think that's a major deal …
=> RN-439: Scroll question to top on focus

packages/meditrak-app/app/assessment/actions/actions.js, packages/meditrak-app/app/assessment/specificQuestions/EntityQuestion.js, packages/meditrak-app/app/database/types/Entity.js, packages/meditrak-app/app/database/types/User.js, packages/meditrak-app/app/entityMenu/EntityList.js, packages/meditrak-app/app/entityMenu/actions.js, packages/meditrak-app/app/entityMenu/reducer.js
RN-466
Most of the time spent loading the entities from the db was in running a permissions check. After optimising that permissions check, I realised we actually didn't need it at all!
I would recommend looking at commit 7d4a6e0 on its own before reviewing this as a whole - that's the (very simple) meat and potatoes of the PR. The rest is just nice-to-have simplifications (mainly renaming filteredEntities to entities, because I always found it confusing that the full list of entities handed to the search component was called filteredEntities)
=> RN-466: Meditrak entity load performance improvement

packages/devops/scripts/lambda/resources/startup.sh
Run the `git ls-remote` command as the `ubuntu` user, as the `ssm-agent` user doesn't have access to the `.git` file that describes the directory as a git repo.
=> Fixed deployment failing when checking if branch exists

packages/meditrak-app/app/assessment/actions/actions.js, packages/meditrak-app/app/assessment/actions/submitSurvey.js, packages/meditrak-app/app/assessment/helpers.js, packages/meditrak-app/app/assessment/reducer.js, packages/meditrak-app/app/assessment/specificQuestions/EntityQuestion.js, packages/meditrak-app/app/entityMenu/EntityList.js, packages/meditrak-app/app/entityMenu/actions.js, packages/meditrak-app/app/entityMenu/reducer.js
Fixes the awkward UX Sima mentions [here](https://linear.app/bes/issue/RN-439#comment-e61bc161)
- Show a list of recently used entities, rather than pre-selecting the last used entity when starting a new survey
See the screenshot [here](https://linear.app/bes/issue/RN-439#comment-a332a845)
=> RN-439: Show recently used entities in entity selection questions

packages/devops/scripts/deployment/startBackEnds.sh
Currently there's just 1 report-server instance, and since node is single threaded, it's a pretty major bottleneck when loading multiple vizes. Usually most of the work is being done in the database which is async, but the transforms are sync, which means that each viz can only be handled one by one.
By running in pm2's cluster mode we can parallelize up to 7 vizes at once, which greatly improves throughput for dashboard with multiple slow vizes.
Current (fork mode):
- min: 46ms
- max: 90.18s
- avg: 33.67s
Cluster mode:
- min: 45ms
- max: 16.73s
- avg: 4.59s
=> MAUI-754: Run report-server in cluster mode

packages/expression-parser/package.json, packages/expression-parser/src/__tests__/expression-parser/ExpressionParser.test.js, packages/expression-parser/src/expression-parser/ExpressionParser.js, packages/expression-parser/src/expression-parser/customFunctions.js, packages/expression-parser/src/expression-parser/customNamespaces.js
RN-447
- `date-fns` has been used in other places in codebase, it would be great to have it for data transforming. 
- Use `date-fns` to manipulate date in transform, there are plenty handy functions that we can use: https://date-fns.org/docs/Getting-Started
- For calculating age 
-- Before:
`age = string(floor((date($currentDate.substring(0,10)).getTime() - date(string($DOB).substring(0,10)).getTime())/(1000 * 3600 * 24* 365)))`
-- Now:
`age = dateUtils().differenceInYears(date($currentDate), date($DOB))`
---
=> Use date-fns to manipulate date in transform

packages/lesmis/src/constants/constants.js
Requested by @enunan in slack: https://beyondessential.slack.com/archives/C02E8F08CAU/p1650596299491969
- Swap default date to hard `2021` instead of the current year
=> Swap default lesmis date to 2021

packages/api-client/package.json, packages/api-client/src/TupaiaApiClient.ts, packages/api-client/src/connections/AuthApi.ts, packages/api-client/src/connections/index.ts, packages/api-client/src/constants.ts, packages/api-client/src/index.ts, packages/devops/scripts/ci/validateBranchName.sh, packages/devops/scripts/lambda/helpers/create_from_image.py, packages/entity-server/package.json, packages/entity-server/src/routes/hierarchy/types.ts, packages/entity-server/src/types.ts, packages/meditrak-app-server/examples.http, packages/meditrak-app-server/package.json, packages/meditrak-app-server/src/@types/express/index.d.ts, packages/meditrak-app-server/src/app/createApp.ts, packages/meditrak-app-server/src/routes/AuthRoute.ts, packages/meditrak-app-server/src/routes/index.ts, packages/meditrak-app-server/src/types.ts, packages/report-server/package.json, packages/tsutils/src/index.ts, packages/tsutils/src/types.ts
Added `AuthRoute` to `meditrak-app-server`. First by adding an `AuthApi` to the `api-client` so that we didn't need to explicitly request from the the `central-server`. I like this move, as we've been wondering about moving the auth logic into its own server, and by wrapping it in the `api-client` like this it will make the refactor simpler.
After that we just had to add the `api-client` to the request context in the `meditrak-app-server` and then implement a simple route class that uses it.
=> RN-493: Add AuthRoute to meditrak-app-server

packages/database/src/migrations/20220513032539-ReinstateMissingEntityAnswersC19TestRegistration-modifies-data.js
RN-511
Note that this migration does take 3 - 4 minutes to run on a standard feature branch, but I feel that's acceptable.
=> [Hot fix] RN-511: Reinstate entity answers for C19 test registration responses

packages/api-client/src/connections/CentralApi.ts, packages/meditrak-app-server/examples.http, packages/meditrak-app-server/src/app/createApp.ts, packages/meditrak-app-server/src/routes/RegisterUserRoute.ts, packages/meditrak-app-server/src/routes/index.ts
Pretty simple route here, just pass user details through to `CentralApi` to register the user
=> RN-498: Add RegisterUser route to meditrak-app-server

packages/central-server/src/apiV2/import/importEntities/updateCountryEntities.js, packages/database/src/modelClasses/Entity.js
See https://beyondessential.slack.com/archives/C02HES8HFQF/p1652822478304789 (first commit) and https://beyondessential.slack.com/archives/C011G5L1J12/p1652820293767959?thread_ts=1647919038.678739&cid=C011G5L1J12 (second commit)
- Fix missed text change from local_gov -> local_government
- Skip facility record creation if it doesn't have a valid geographical_area parent. `facility` aka `clinic` is a bit of a legacy thing, and is only maintained for people using older versions of MediTrak, meaning that most new `facility` type entities won't need a corresponding entry in the `facility`/`clinic` table
=> Hot fix importing facilities

packages/database/src/runPostMigration.js
Once the migrations have run we do an analytics refresh. This can sometimes take a long time, and it's a bit unclear what's taking so long. Just added a simple log message to indicate that the analytics are being refreshed
=> Added logging around refresh after migrations

packages/meditrak-app/app/assessment/specificQuestions/AutocompleteQuestion.js, packages/meditrak-app/app/widgets/Autocomplete/Autocomplete.js
RN-458
A UX change was required here, as we can only have either the autocomplete results _or_ the surrounding screen scrollable. 
See [here](https://linear.app/bes/issue/RN-458#comment-19a2299a) for a description with screenshots, but in brief:
- The autocomplete will now start "closed"
- Pressing the "down" arrow on the right, or just tapping in the searchbox will open the full set of options
- If you start typing, it filters the options and replaces the open/close arrow with a clear button
- Whenever the full list of options is open, it will be scrollable (but the screen around won't be)
- If you select an option or click the "up" button on the right, it will close and hand scroll control back to the surrounding screen
=> RN-458: Take scroll control when autocomplete in use

packages/database/src/migrations/20220531030730-RerunMigrationToReinstateMissingEntityAnswersC19TestRegistration-modifies-data.js
This is a copy of [this migration](https://github.com/beyondessential/tupaia/pull/3912) so we can run it again to clean up new data that came in after that initial migration had been run
=> Rerun existing migration for new data

packages/database/src/TupaiaDatabase.js
Switched to using [whereNotExists](http://knexjs.org/guide/query-builder.html#wherenotexists) ensure we don't create a record that already exists. Best practice as described here: https://stackoverflow.com/questions/4069718/postgres-insert-if-does-not-exist-already/13342031#13342031
Another option could have been use to use Postgres's `ON CONFLICT` clause (https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-upsert/) however that requires database constraints to be applied to work (something we might wanna consider for the future...)
=> RN-536: Modified DatabaseModel.findOrCreate to be atomic

scripts/bash/getDeployablePackages.sh
This should fix an issue where the Gold Master EC2 Image building process is failing with the following error: 
```
src/viz-builder/types.ts(6,30): error TS2307: Cannot find module '@tupaia/report-server' or its corresponding type declarations.
```
i.e., the report server has not had its types built at the point the admin panel is being built
There's one thing that's confusing me though - the image building process _does_ sometimes succeed (see the screenshot below). Can the reviewer understand why that might be? I would've thought if this was the issue it would deterministically fail?
=> Build admin-panel-server last

packages/database/src/migrations/20220616025825-DeleteCovidMinisterViewDashboard-modifies-data.js
- Remove any dashboard relations with the COVID19 Minister View dashboard
- Remove the dashboard record from the 'dashboard' table
=> MAUI-858: Delete COVID19 Minister dashboard

packages/admin-panel-server/src/app/createApp.ts, packages/central-server/src/apiV2/middleware/logApiRequest.js, packages/central-server/src/database/models/index.js, packages/database/src/migrations/20220614225441-AddLoggingForAllServicesApiRequestLog-modifies-schema.js, packages/database/src/modelClasses/ApiRequestLog.js, packages/database/src/modelClasses/index.js, packages/entity-server/src/app/createApp.ts, packages/lesmis-server/src/app/createApp.ts, packages/meditrak-app-server/src/app/createApp.ts, packages/psss-server/src/app/createApp.ts, packages/report-server/src/app/createApp.ts, packages/server-boilerplate/README.md, packages/server-boilerplate/src/microService/@types/express/index.d.ts, packages/server-boilerplate/src/microService/api/ApiBuilder.ts, packages/server-boilerplate/src/microService/utils/index.ts, packages/server-boilerplate/src/microService/utils/logApiRequest.ts, packages/server-boilerplate/src/orchestrator/@types/express/index.d.ts, packages/server-boilerplate/src/orchestrator/api/ApiBuilder.ts, packages/server-boilerplate/src/orchestrator/models/Session.ts, packages/server-boilerplate/src/orchestrator/utils/index.ts, packages/server-boilerplate/src/orchestrator/utils/logApiRequest.ts, packages/server-boilerplate/src/types.ts
Currently we just log the requests for the `central-server` to the `api_request_log` table. This table can be quite useful when debugging issues with meditrak-app. However, once we've moved the routes out to the `meditrak-app-server` we'll lose the logs. So this ticket to get logging happening for that server, and it proved easy enough to add support for all our other apis built off `server-boilerplate` as well.
=> RN-557: Add logging in api_request_log table for all apis

packages/database/src/DatabaseModel.js, packages/database/src/ModelRegistry.js, packages/database/src/analytics/MaterializedViewLogDatabaseModel.js, packages/meditrak-app-server/examples.http, packages/meditrak-app-server/jest.setup.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/CountChangesRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/PullChangesRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/upsertDummyQuestion.ts, packages/meditrak-app-server/src/app/createApp.ts, packages/meditrak-app-server/src/routes/index.ts, packages/meditrak-app-server/src/routes/sync/PullChangesRoute.ts, packages/meditrak-app-server/src/routes/sync/index.ts
Part 3 of 4.
In this PR we're adding the `PullChangesRoute`, which the meditrak-app calls to get the actual changes. Mostly unit tests this route itself was pretty simple and almost entirely copied from [central-server](https://github.com/beyondessential/tupaia/blob/973ac52ae0381ad668e7f417f664ee7fb63b2927/packages/central-server/src/apiV2/getChanges.js)
=> RN-501: Move sync logic to meditrak-app-server (PullChangesRoute)

packages/data-lake-api/src/DataLakeAnalyticsFetchQuery.ts
When we first wrote this code the data-lake didn't have a `value_type` column, so we just assumed all data was numeric. Now it has such a column, so we should respect it.
=> Allow pulling non-numeric data from the data-lake

packages/database/src/migrations/20220623233124-AddHouseholdsToEntityHierarchyCanonicalTypes-modifies-data.js
Issue: [RN-568](https://linear.app/bes/issue/RN-568/submitting-an-eh01-survey-response-breaks-the-sync-queue)
This is a hotfix to fix the issue where submitting EH01 survey responses would break the sync queue 
It seems like putting `household` into the `canonical_types` of the `entity_hierarchy` for the Palau project fixes it
=> Hotfix RN-568 - fix issue with sync queue breaking

packages/lesmis/src/translations/en.json, packages/lesmis/src/translations/lo.json, packages/lesmis/src/views/VitalsView.js
Pretty simple issue here. We added a translation for the word `Population` during this release, and the `I18n` library is set up to translate all fields of a report that it knows a translation for. 
It does feel a bit awkward to translate the key we're using on the frontend, as typically keys aren't translated in these kinds of scenarios. But given that this part of the UI is rendered from data coming from a report it seems acceptable to me.
Quite a small change here, mainly just whitespace, changes.
=> Hotfix: Switched to using translated key for 'Population' in lesmis vitals

packages/central-server/src/apiV2/utilities/translateExpression.js, packages/central-server/src/tests/apiV2/export/exportSurveys/configCellBuilders/configCellBuilders.test.js, packages/central-server/src/tests/apiV2/export/exportSurveys/configCellBuilders/fixtures/common.js
Full explanation of this issue outlined [in the ticket](https://linear.app/bes/issue/RN-527#comment-58c49107). Went with the simple fix here of just ensuring that we don't accidentally replace substrings within the question codes. A more structured re-write of this logic might be possible if we break down the expression tree, but I don't know how it build it up again using mathjs...
=> RN-527: Fix arithmetic questions not including all variables in expression

packages/ui-components/src/components/Map/__tests__/markerFormats.test.js, packages/web-frontend/src/utils/index.js, packages/web-frontend/src/utils/measures.js
Add a unit test to describe how dynamic coloured radius works.
=> No issue: Add a unit test for get measure display info

packages/web-frontend/src/containers/mobile/Dashboard.js
- As in `FilterSelect` we assign `item.code` to `ListItem` key instead of using `item.id`
=> hot-fix: Change dashboard list item id to code

packages/database/package.json, packages/database/scripts/migrateCreate.sh
Fixes error `Unbound variable "MIGRATION_NAME"` when running `yarn migrate-create`
Move commands into a bash script.
Not sure why this fixes it, some difference between yarn v1 and v3.
=> Fix migrate create

packages/devops/scripts/deployment/buildDeployablePackages.sh
Found while testing rn-403-clean-up-data-services. If it fixes that feature branch deployment, we can consider it ready for release to master.
=> Hotfix: force install internal deps

packages/lesmis/src/constants/constants.js
- Update default year in Lesmis constant to '2022'
=> MAUI-978: Return default date in LESMIS to 2022

packages/web-config-server/src/app.js, packages/web-config-server/src/utils/index.js, packages/web-config-server/src/utils/logApiRequest.js
Just added logging of api requests to the web-config-server app.
=> Add logging of web-config-server requests to the api_request_log table

packages/lesmis/src/components/DashboardExportModal/DashboardExportModal.js, packages/lesmis/src/views/ExportView.js
https://linear.app/bes/issue/RN-476#comment-5192a9d2
=> Fix unable to view loading circular progress

packages/meditrak-app/appcenter-pre-build.sh
Followed the advice in [this issue](https://github.com/realm/realm-js/issues/4740) in the Realm project. It's a bit of a simplistic solution, the issue's only a day old, so maybe we can keep and eye on it and see if it gets fixed by the Realm team more effectively?
=> RN-597: Explicitly install ndk 21.0.6113669 in appcenter-pre-build.sh

packages/devops/configs/servers.conf
`pdf-export-server` did not get routed in route 53.
=> Fix pdf-export-server deployment error

packages/devops/scripts/deployment/setupGoldMaster.sh, packages/lesmis-server/src/routes/PDFExportRoute.ts
pdf export is broken in `lesmis.la`
=> hotfix: Add lesmis la is valid url to pdf exporter

packages/admin-panel-server/package.json, packages/central-server/package.json, packages/entity-server/package.json, packages/lesmis-server/package.json, packages/meditrak-app-server/package.json, packages/pdf-export-server/package.json, packages/psss-server/package.json, packages/psss/package.json, packages/report-server/package.json, packages/web-config-server/package.json
According to [yarn 3 docs](https://yarnpkg.com/advanced/lifecycle-scripts) 
>In particular, we intentionally don't support arbitrary pre and post hooks for user-defined scripts (such as prestart). This behavior, inherited from npm, caused scripts to be implicit rather than explicit, obfuscating the execution flow. It also led to surprising executions with yarn serve also running yarn preserve.
=> Removed 'pre' scripts from package.json as yarn3 doesn't support them

packages/database/src/migrations/20220718043838-UnfpaAddMHFacilityRelations-modifies-data.js
Simple migration to add missing facility relations for Marshal Islands in UNFPA
---
=> UNFPA MH add missing facility relations

package.json, packages/meditrak-app/.yarnrc.yml, packages/meditrak-app/package.json, yarn.lock
https://beyondessential.slack.com/archives/D01A1LRAG9W/p1657848268725059
This was causing issues with running meditrak-app locally. You would need to `yarn install` inside packages/meditrak-app to get packages to show up in packages/meditrak-app/node_modules, otherwise the local build would fail. After this fix a single `yarn install` at root level is all that is needed again.
--
Fix: .yarnrc.yml method does not work, using package.json method instead
see https://yarnpkg.com/configuration/yarnrc#nmHoistingLimits
--
Passing appcenter build: https://appcenter.ms/orgs/Beyond-Essential/apps/Tupaia-MediTrak-Android/build/branches/fix-meditrak-app-hoisting/builds/1256
=> Fix meditrak-app hoisting config

packages/web-config-server/src/index.js
Not too sure why this suddenly became an issue. But this error has cropped up a few times in the past, and it seems the way we're referencing the port here isn't particularly safe.
Switched to using the standard way we do it on other servers.
=> Hotfix: Reference port safely when starting web-config-server

packages/ui-components/.babelrc.js
We currently see a lot of this warning when building ui-components:
```
[ui-components] Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
[ui-components] The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
[ui-components]         ["@babel/plugin-proposal-private-methods", { "loose": true }]
[ui-components] to the "plugins" section of your Babel config.
```
So I followed the recommendation to silence the …
=> Silence noisy warning when building @tupaia/ui-components

packages/database/src/migrations/20220810013153-UpdateAllNonRegionalDhisInstanceConfigDataElementsAndGroups-modifies-data.js
- Add migration to update null values to country server for dhisInstanceCode in data_element and data_group tables.
=> RN-558: Specify DHIS Server Explicit

packages/web-frontend/src/sagas/index.js
The issue was that editing the search bar never triggered a search request. Fixed missing export of `watchSearchBar` sagas, now they trigger a request properly again.
=> (Hotfix) RN-617: Fix broken Entity Searchbar

packages/web-frontend/src/sagas/watchOrgUnit/watchOrgUnitChangeAndFetchDashboard.js
We preset the default dashboard for every project in `project` table. Tupaia frontend will use it as the default dashboard when clicking into a project. 
The issue is when default dashboard is renamed in `dashboard_group` table, and we didn't update it in `project` table, frontend will not set `dashboard` code in URL, because it is 'not found'. Example: Project `Strive PNG`.
Everything works fine, the only effect is the 'incomplete' URL will cause issue for dashboard PDF export. 
I feel it would be better to change the default dashboard to a dashboard id as a foreign key in `project` table.
=> Set default dashboard to the first from list

packages/central-server/src/apiV2/utilities/meditrakSync/permissionsBasedMeditrakSyncQuery.js, packages/central-server/src/database/createPermissionsBasedMeditrakSyncQueue.js, packages/central-server/src/tests/apiV2/changes/getChangesMetadata.test.js, packages/central-server/src/tests/apiV2/changes/permissionsBasedSync.fixtures.js
Meditrak treats a survey with no countryIds as being available in all countries. Previously we were not syncing those surveys, so they did not show up in the app.
Personally I find the convention of no countryIds representing all countryIds a bit confusing... I won't change it as part of this PR but I'd prefer if we switched to a wild-card of sorts
=> Hotfix: Not all surveys showing up in meditrak-app

packages/lesmis-server/src/routes/PDFExportRoute.ts, packages/utils/src/convertToCDNHost.js, packages/utils/src/index.js, packages/web-config-server/src/export/PDFExportHandler.js
CDN does not forward CDN host to origin, which causes PDF export failed.
Add `.cdn` to host.
=> hotfix: Add .cdn to host domain

packages/lesmis-server/src/routes/PDFExportRoute.ts
No CDN for lesmis-server, we don't need to add `.cdn` to the host. This PR will simply revert previous changes.
=> hotfix: typescript validation error

packages/devops/scripts/deployment/startBackEnds.sh
Replaces #4124 for branch name
--
PR to add logging to initial dump file. Adds some logs so we can tell next time if the issue was caused at deployment time or after
https://beyondessential.slack.com/archives/CT0KTFSHZ/p1661729468357769
Tested by deploying this feature branch:
=> Log pm2 dump file on deployment

packages/database/src/migrations/20220901042432-AddFacilitiesPenfaa-modifies-data.js
- Add facilities to penfaa project
---
https://linear.app/bes/issue/MAUI-1205#comment-be5a6e22
=> MAUI-1205 Add facilities to penfaa project

packages/ui-components/src/components/Table/Table.js, packages/ui-components/src/components/Table/TablePaginator.js
I mistakenly assumed that `null` props would be overridden by child default props  🤦 
Fix is to ensure valid value for `rowsPerPageOptions` is passed to TablePaginator
=> Hotfix: Fix broken PSSS Countries tab

yarn.lock
That warning is really annoying...
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
=> [No issue]: Upgraded caniuse-lite

packages/admin-panel-server/src/__tests__/viz-builder/dashboardVisualisation/DashboardVisualisationExtractor.test.ts, packages/admin-panel-server/src/viz-builder/dashboardVisualisation/DashboardVisualisationExtractor.ts, packages/admin-panel-server/src/viz-builder/dashboardVisualisation/combineDashboardVisualisation.ts, packages/admin-panel-server/src/viz-builder/mapOverlayVisualisation/combineMapOverlayVisualisation.ts, packages/admin-panel-server/src/viz-builder/reportConfigValidator.ts, packages/admin-panel-server/src/viz-builder/types.ts, packages/admin-panel-server/src/viz-builder/utils.ts, packages/admin-panel-server/src/viz-builder/validators.ts, packages/admin-panel/src/VizBuilderApp/components/Panel.js, packages/admin-panel/src/VizBuilderApp/context/VizConfig.js, packages/report-server/examples.http, packages/report-server/src/__tests__/reportBuilder/customReport/testCustomReport.test.ts, packages/report-server/src/reportBuilder/configValidator.ts, packages/report-server/src/reportBuilder/customReports/index.ts, packages/report-server/src/reportBuilder/customReports/testCustomReport.ts, packages/report-server/src/reportBuilder/output/functions/outputBuilders.ts, packages/report-server/src/reportBuilder/reportBuilder.ts, packages/report-server/src/types.ts, packages/tsutils/src/types.ts
There often come times where we need to rush out a viz, and the demands to get it to work are too tricky for the viz builder at the moment.
The 'Custom Report' is an option to just handcraft a single JS function that pulls and transforms all the data we need. I prefer this option over using the legacy databuilders for a few reason:
1. We will probably always need some capacity for this, so it's worthwhile to manage it in a non-legacy way
2. The legacy pattern really blurs the line between what should be config, and what should be code. This however is very clear. Either use the viz-builder transform configs, or just code. I think that makes it simpler to understand and reverse engineer these custom reports when we need to
3. They're in typescript which makes them a lot easier to work …
=> RN-484: Add ability for defining 'custom reports' in the report-server 

packages/data-broker/src/__tests__/services/dhis/DhisService.stubs.js, packages/data-broker/src/__tests__/services/dhis/DhisService.test.js, packages/data-broker/src/__tests__/services/dhis/getDhisApi.test.js, packages/data-broker/src/services/dhis/DhisService.js, packages/data-broker/src/services/dhis/getDhisApi.js, packages/report-server/src/aggregator/ReportServerAggregator.ts, packages/utils/src/legacyDhis.js
- Always use the dhisInstanceCode marked against the DE/DG when pulling via data-broker
Note: this PR is based on rn-625-disable-1-many-mapping, therefore once both are in, there will be no cases* where we use entity based resolution to figure out which DHIS instance to pull from. To do 625 cleanly, we also need to do this.
* in data-broker... After these changes, there will still be parts of the codebase which rely on entity config for this, e.g. the dhis sync logic, which will be migrated over in a future PR.
=> RN-265 Always use dhis instance code on data element / group

packages/web-frontend/package.json, packages/web-frontend/src/tests/components/dateRangePicker.test.js, yarn.lock
I experienced the rarest intermittent [test failure](https://app.codeship.com/projects/70159bc0-0dac-0138-fdcb-260b82737f4e/builds/021f612f-6e14-40c7-9d9f-8beace5d0120?component=step_Validate_and_test_Test_Test_batch_2_Test_internal-dependencies) (date rolled over in the very short time between this test starting and asserting)
I swear to never again have this test fail due to date not being mocked!
=> [no-issue]: Fixed intermittent failure in dateRangePicker.test.js

packages/report-server/src/__tests__/reportBuilder/context/buildContext.test.ts, packages/report-server/src/__tests__/reportBuilder/transform/parser/parser.test.ts, packages/report-server/src/reportBuilder/context/buildContext.ts, packages/report-server/src/reportBuilder/context/types.ts, packages/report-server/src/reportBuilder/query/buildOrganisationUnitParams.ts, packages/report-server/src/reportBuilder/reportBuilder.ts, packages/report-server/src/reportBuilder/transform/parser/TransformParser.ts
I've wanted this feature for a while, as there are occasional cases where it'd be really handy to reference the original request parameters of the viz.
I see this as also paving the way for being able to have vizes take additional parameters (eg. A control to filter by Drug Type) which would be really cool.
It's also a pre-requisite for moving 'fetch' into the transform steps, which we want to have in place prior to moving on with the Data Tables epic
=> RN-601: Added ability to reference query parameters in viz-builder expressions

packages/central-server/src/tests/apiV2/changes/getChanges.test.js, packages/meditrak-app-server/src/__tests__/__integration__/sync/CountChangesRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/PullChangesRoute.test.ts
Since the change to making the ChangeHandlers run in a transaction, these sync queue related tests have all become a bit more flaky (eg. [here](https://app.codeship.com/projects/70159bc0-0dac-0138-fdcb-260b82737f4e/builds/70d3bcf9-099a-4fcf-8b4c-2837bda2b179?component=step_Validate_and_test_Test_Test_batch_1_Test_meditrak-app-server), and [here](https://app.codeship.com/projects/70159bc0-0dac-0138-fdcb-260b82737f4e/builds/be447781-7152-4af8-b3c7-5083f9f1d3b9?component=step_Validate_and_test_Test_Test_batch_1_Test_central-server)). They have previously been relying purely on timing at points, which isn't really all that safe. I've added a bunch of `await database.waitForAllChangeHandlers();` calls in places where they seemed necessary, which should halt the test execution until the change …
=> [no-issue]: Reduce flakiness in sync queue related tests

packages/lesmis/src/components/DashboardExportModal/pages/DashboardReportPage.js, packages/lesmis/src/components/DashboardReport.js, packages/lesmis/src/components/FavouriteButton.js, packages/lesmis/src/components/Visuals/Chart.js, packages/lesmis/src/components/Visuals/ListVisual.js, packages/lesmis/src/components/Visuals/VisualHeader.js, packages/lesmis/src/components/YearLabel.js, packages/lesmis/src/utils/getExportableSubDashboards.js, packages/lesmis/src/utils/index.js, packages/lesmis/src/utils/useIsFavouriteDashboardSelected.js, packages/lesmis/src/views/DashboardItemsView.js, packages/lesmis/src/views/DashboardReportTabView.js, packages/lesmis/src/views/DashboardView.js, packages/lesmis/src/views/ExportView.js, packages/lesmis/src/views/FavouriteDashboardTabView.js, packages/lesmis/src/views/FavouriteDashboardView.js
RN-506
- Add year label ([UX design](https://linear.app/bes/issue/RN-506#comment-a7304173))
- In favourite dashboard, we want dashboard item to fetch data by default year only (no year selector). They either fetch data by year or fetch all data. To be able to do so we pass down `useYearSelector` instead of a fixed `year` from the top for generating `startDate` and `endDate`.     
- Fix [issue 4](https://linear.app/bes/issue/RN-506#comment-42fce320)
=> RN-506 add year label and fix issues

packages/central-server/src/database/meditrakSyncQueue/MeditrakSyncRecordUpdater.js, packages/meditrak-app-server/src/sync/SyncableChangeEnqueuer.ts
Add changes to the meditrak sync queue one by one to avoid updates being processed after deletes.
=> RN-661: Prevent dead records appearing in the Meditrak Sync Queue

packages/admin-panel/src/table/actions.js, packages/central-server/src/apiV2/surveyResponses/GETSurveyResponses.js, packages/database/src/migrations/20220920062403-AddEntityIdIndexOnSurveyResponseTable-modifies-schema.js
This page runs really slowly, and when a user navigates to it it hangs the UI for 10+ seconds.
Some basic improvements can get it loading fairly smoothly.
1. Add a debounce to the `DataFetchTable` so that it waits between inputs, currently we send an api request for every keystroke
2. Add a few indexes on the `survey_response_table`
3. Re-work how the `count()` works in the route so that it only joins the reference tables if needed
=> MAUI-1269: Improve performance of Survey Response page in Admin Panel

packages/admin-panel/src/VizBuilderApp/api/queries/useSearchDataSources.js, packages/admin-panel/src/utilities/convertSearchTermToFilter.js, packages/database/src/TupaiaDatabase.js
Actually felt it might be best to make this a global change in our database layer. 
In postgres, `_` is treated as a wildcard character when doing text like comparison. I don't think we make use of the feature at all, and instead it's just confusing when we actually want to search for a text string with an underscore. There is a workaround that the user can escape the underscore using `\_` but it's not very user friendly....
Happy to hear pushback from the reviewer if they feel we're obfuscating native postgres functionality?
=> RN-662: Support searching with underscore in the Admin Panel

packages/report-server/package.json, packages/report-server/src/__tests__/reportBuilder/transform/orderColumns.test.ts, packages/report-server/src/__tests__/reportBuilder/transform/transform.fixtures.ts, packages/report-server/src/reportBuilder/transform/functions/index.ts, packages/report-server/src/reportBuilder/transform/functions/orderColumns/index.ts, packages/report-server/src/reportBuilder/transform/functions/orderColumns/orderColumns.ts, packages/report-server/src/reportBuilder/transform/functions/orderColumns/sortByFunctions.ts, packages/report-server/src/reportBuilder/transform/parser/functions/utils.ts, packages/utils/src/period/period.js, yarn.lock
Part 3 of 3.
The final and core PR for this feature. The actual transform.
So the idea with this transform is to allow us to re-order the columns of the table. You can either do this explicitly by specifying the column names, or by using a pre-defined sort function.
eg.
Basic explicit re-order
```
[ 
{ name: 'Bo', age: 7, car: 'Subaru' },
{ name: 'Jo', age: 12, car: 'Ferrari' }
]
transform: orderColumns
order: ['car', 'name', 'age']
=>
[ 
{ car: 'Subaru', name: 'Bo', age: 7 },
{ car: 'Ferrari', name: 'Jo', age: 12 }
]
```
Explicit re-order with wildCard
```
[ 
{ name: 'Bo', age: 7, car: 'Subaru' },
{ name: 'Jo', age: 12, car: 'Ferrari' }
]
transform: orderColumns
order: ['*', 'age']
=>
[ 
{ name: 'Bo', car: 'Subaru', age: 7 },
{ name: 'Jo', car: 'Ferrari', age: 12 }
]
```
Re-order with …
=> RN-175: Add order columns transform (p3. order columns transform step)

packages/admin-panel-server/src/__tests__/viz-builder/dashboardVisualisation/DashboardVisualisationExtractor.test.ts, packages/admin-panel-server/src/viz-builder/dashboardVisualisation/DashboardVisualisationExtractor.ts, packages/admin-panel-server/src/viz-builder/mapOverlayVisualisation/MapOverlayVisualisationExtractor.ts, packages/admin-panel-server/src/viz-builder/utils/extractDataFromReport.ts, packages/admin-panel-server/src/viz-builder/utils/getVizOutputConfig.ts, packages/admin-panel-server/src/viz-builder/utils/index.ts, packages/admin-panel/src/VizBuilderApp/api/queries/useReportPreview.js, packages/admin-panel/src/VizBuilderApp/components/PreviewSection.js, packages/report-server/package.json, packages/report-server/src/__tests__/reportBuilder/output/default.test.ts, packages/report-server/src/__tests__/reportBuilder/output/rows.test.ts, packages/report-server/src/__tests__/reportBuilder/output/rowsAndColumns.test.ts, packages/report-server/src/__tests__/reportBuilder/transform/orderColumns.test.ts, packages/report-server/src/__tests__/reportBuilder/transform/transform.fixtures.ts, packages/report-server/src/reportBuilder/output/functions/outputBuilders.ts, packages/report-server/src/reportBuilder/output/functions/rows.ts, packages/report-server/src/reportBuilder/output/functions/rowsAndColumns.ts, packages/report-server/src/reportBuilder/transform/functions/index.ts, packages/report-server/src/reportBuilder/transform/functions/orderColumns/index.ts, packages/report-server/src/reportBuilder/transform/functions/orderColumns/orderColumns.ts, packages/report-server/src/reportBuilder/transform/functions/orderColumns/sortByFunctions.ts, packages/report-server/src/reportBuilder/transform/parser/functions/utils.ts, packages/utils/src/period/period.js, yarn.lock
Part 2 of 3.
This is a fairly simple PR to switch the viz-builder to respect the column order defined during the data transformation in the report-server.
In order to be backwards compatible, we need to return data as just a simple array of objects from the report-server by default. However, we'd like the viz-builder to know the column order for this array of objects. So I added a new `output` type (`rowsAndColumns`) which returns the rows (array of objects) and the ordered list of column names. Then just a few changes in the admin-panel-server to use this new output type when previewing the data-table.
=> RN-175: Add order columns transform (p2. respect the column order in the viz-builder)

packages/meditrak-app-server/src/__tests__/__integration__/sync/PullChangesRoute.test.ts
I've seen the tests fail when one of them times out, so this should reduce the likelihood of timeouts
=> Fixup for flaky meditrak-app-server tests

packages/admin-panel/src/pages/resources/EntitiesPage.js, packages/central-server/src/apiV2/DeleteHandler/DeleteHandler.js, packages/central-server/src/apiV2/entities/DeleteEntity.js, packages/central-server/src/apiV2/entities/DeleteEntityHandler.js, packages/central-server/src/apiV2/entities/GETEntities.js, packages/central-server/src/apiV2/entities/assertEntityPermissions.js, packages/central-server/src/apiV2/entities/index.js, packages/central-server/src/apiV2/index.js, packages/central-server/src/apiV2/surveyResponses/GETSurveyResponses.js
Allow deleting entities via the Admin Panel. Limitations:
- Cannot delete country or project entities
- Cannot delete entities which have lingering survey responses
- Cannot delete entities which have children
=> MAUI-1267: Allow deleting entities via the Admin Panel

packages/central-server/src/apiV2/utilities/meditrakSync/permissionsBasedMeditrakSyncQuery.js
World wasn't syncing sync technically no users have permissions for it. We should always sync it.
=> RN-689: Fix the world entity not syncing with permission based syncs

packages/report-server/src/__tests__/reportBuilder/transform/updateColumns.test.ts, packages/report-server/src/reportBuilder/transform/functions/insertColumns.ts, packages/report-server/src/reportBuilder/transform/functions/updateColumns.ts
This issue is a bit rare, but when we're using dynamic columns to override an existing column, the old values from the existing column are kept.
=> [no-issue]: Fix upserting dynamic columns

packages/report-server/src/reportBuilder/transform/aliases/entityMetadataAliases.ts
Fixed unexpected errors when performing 'insertNumberOfFacilities' alias transform on an empty table
=> [no-issue]: Fixed errors in UNFPA about missing 'organisationUnit' column

packages/data-table-server/examples.http, packages/data-table-server/package.json, packages/data-table-server/src/@types/express/index.d.ts, packages/data-table-server/src/__tests__/dataTableService/internal/AnalyticsDataTableService.test.ts, packages/data-table-server/src/__tests__/dataTableService/internal/EntitiesDataTableService.test.ts, packages/data-table-server/src/__tests__/dataTableService/internal/EntityRelationsDataTableService.test.ts, packages/data-table-server/src/__tests__/dataTableService/internal/EventsDataTableService.test.ts, packages/data-table-server/src/app/createApp.ts, packages/data-table-server/src/dataTableService/DataTableService.ts, packages/data-table-server/src/dataTableService/DataTableServiceBuilder.ts, packages/data-table-server/src/dataTableService/index.ts, packages/data-table-server/src/dataTableService/internal/AnalyticsDataTableService.ts, packages/data-table-server/src/dataTableService/internal/EntitiesDataTableService.ts, packages/data-table-server/src/dataTableService/internal/EntityRelationsDataTableService.ts, packages/data-table-server/src/dataTableService/internal/EventsDataTableService.ts, packages/data-table-server/src/dataTableService/internal/index.ts, packages/data-table-server/src/dataTableService/types.ts, packages/data-table-server/src/dataTableService/utils/index.ts, packages/data-table-server/src/dataTableService/utils/yupSchemaToDataTableParams.ts, packages/data-table-server/src/middleware/attachDataTableToContext.ts, packages/data-table-server/src/middleware/index.ts, packages/data-table-server/src/routes/Parameters.ts, packages/data-table-server/src/routes/index.ts, packages/database/src/migrations/20221006004520-AddEntityRelationsDataTable-modifies-data.js, packages/database/src/migrations/20221006010514-AddEntitiesDataTable-modifies-data.js, yarn.lock
We're adding 2 new data tables in the PR.
`entities` - fetches metadata for entities (useful for getting entity names from codes for instance)
`entity_relations` - fetches relations within an entity hierarchy (useful for entity aggregation)
Also adding the `Parameters` route for fetching the parameters required by a given data-table. It's not entirely needed, but there's been some rebasing shenanigans going on and I'd rather not have to create a separate PR for it 👍
=> RN-645: Add internal data tables for fetching entities and entity relations

packages/admin-panel/src/pages/resources/ExternalDatabaseConnectionsPage.js, packages/admin-panel/src/pages/resources/UsersPage.js, packages/admin-panel/src/pages/resources/index.js, packages/admin-panel/src/routes.js, packages/admin-panel/src/table/customCells/TestDatabaseConnectionCell.js, packages/admin-panel/src/table/customCells/index.js, packages/admin-panel/src/widgets/InputField/registerInputFields.js, packages/central-server/src/apiV2/externalDatabaseConnections/TestExternalDatabaseConnection.js, packages/central-server/src/apiV2/externalDatabaseConnections/index.js, packages/central-server/src/apiV2/index.js, packages/central-server/src/apiV2/utilities/constructNewRecordValidationRules.js, packages/database/src/migrations/20221001204123-AddExternalDatabaseConnectionTable-modifies-schema.js, packages/database/src/modelClasses/ExternalDatabaseConnection.js, packages/database/src/modelClasses/index.js, packages/database/src/types.js
Added a new concept, the 'External Database Connection' to Tupaia. These are required by SQL data tables, to control what database to pull from.
Fields:
- code: unique identifier code
- name: display name
- description: more detailed explanation of the connection
- permission_groups: which users can use this connection when creating SQL data tables
=> RN-675: Added 'External Database Connections' to Tupaia

packages/web-config-server/src/apiV1/dashboardItems.js, packages/web-config-server/src/apiV1/index.js, packages/web-frontend/package.json, packages/web-frontend/src/actions.js, packages/web-frontend/src/autocomplete/actions.js, packages/web-frontend/src/autocomplete/constants.js, packages/web-frontend/src/autocomplete/index.js, packages/web-frontend/src/autocomplete/reducers.js, packages/web-frontend/src/components/Autocomplete.js, packages/web-frontend/src/components/DashboardEditButton.js, packages/web-frontend/src/components/EditDashboardModal.js, packages/web-frontend/src/containers/Dashboard.js, packages/web-frontend/src/reducers.js, packages/web-frontend/src/sagas/handlers/fetchDashboardItemEditOptions.js, packages/web-frontend/src/sagas/handlers/index.js, packages/web-frontend/src/sagas/watchUser/watchFetchInitialData.js, packages/web-frontend/src/selectors/autocompleteSelectors.js, packages/web-frontend/src/selectors/dashboardSelectors.js, packages/web-frontend/src/selectors/index.js, packages/web-frontend/src/utils/convertSearchTermToFilter.js, packages/web-frontend/src/utils/createNestedReducer.js, packages/web-frontend/src/utils/createReducer.js, packages/web-frontend/src/utils/index.js, packages/web-frontend/src/utils/makeSubstitutionsInString.js, yarn.lock
- Add route in web-config-server for returning dashboard item edit options (id and code)
- Add redux actions, reducers, sagas for storing these items to state.
- Style edit button in dashboard.
- Add search bar for dashboard item in modal.
=> Add dashboard item edit options

packages/central-server/src/kobo/startSyncWithKoBo.js, packages/database/src/modelClasses/DataServiceSyncGroup.js
Flag all kobo sync groups as being in an IDLE sync state upon server startup
=> RN-708: Fix Kobo Sync Groups being stuck in a 'Syncing' state

packages/database/src/migrations/20221104002716-UnfpaPopulationTileSet-modifies-data.js, packages/web-frontend/src/constants/mapbox.js
MAUI-1045
- new tile for UNFPA population
=> Add unfpa population tile

packages/data-broker/src/services/superset/getSupersetApi.js, packages/database/src/migrations/20221111050217-AddSupersetInstances-modifies-data.js, packages/superset-api/package.json, packages/superset-api/src/SupersetApi.ts, yarn.lock
- Remove insecure flag, not needed any more, servers have valid certs now
- Swap out package `needle` for standard `node-fetch`
- Add new superset instances
=> RN-710 Add superset instances

packages/central-server/package.json, packages/central-server/src/apiV2/surveyResponse.js, packages/tsutils/package.json, packages/tsutils/src/__tests__/datetime.test.ts, packages/tsutils/src/datetime.ts, packages/tsutils/src/index.ts, packages/utils/src/datetime.js, packages/utils/src/index.js, tupaia-packages.code-workspace, yarn.lock
Just moving the utils in `datetime.js` to `@tupaia/tsutils`
I left a copy of `utcMoment` in `@tupaia/utils` because it's currently used in many places. Will move that later on
=> [no-issue]: Move datetime to tsutils

packages/admin-panel-server/src/app/createApp.ts, packages/admin-panel-server/src/routes/FetchEntityHierarchyTreeRoute.ts, packages/admin-panel-server/src/routes/index.ts, packages/api-client/src/connections/CentralApi.ts, packages/api-client/src/connections/EntityApi.ts, packages/central-server/src/apiV2/entityRelations/GETEntityRelations.js, packages/central-server/src/apiV2/entityRelations/index.js, packages/central-server/src/apiV2/index.js, packages/entity-server/src/__tests__/__integration__/fieldsAndFilters.test.ts, packages/entity-server/src/models/Entity.ts, packages/entity-server/src/models/index.ts, packages/entity-server/src/routes/hierarchy/middleware/filter.ts, packages/entity-server/src/types.ts, packages/utils/src/object.js
[OS-10](https://linear.app/bes/team/OSC/active) - just the backend in this PR
* Added a `GET /entityHierarchyTree` endpoint in `admin-panel-server`
* Automatically stringify `columns`,  `sort` in `central-server` requests done with `api-client`
* Add support for `<`, `<=`, `>`, `>=` comparators in `entity-server`
* Add support for filtering on `ancestor_descendant_relation.generational_distance` for entities fetched with `entity-server`
* Add `GET /entityRelations` endpoint in `central-server` (basic version, needs more work)
=> OSC-10: Admin panel entity hierarchy - Backend

packages/report-server/src/__tests__/reportBuilder/transform/mergeRows.test.ts, packages/report-server/src/__tests__/reportBuilder/transform/parser/parser.test.ts, packages/report-server/src/reportBuilder/transform/functions/mergeRows/mergeRows.ts
Just re-introducing some behaviour that got removed as part of RN-175.
Also scrapped the `where` clause support on `mergeRows`, as it's never been used and makes the code more complex than needed
=> RN-702: Re-instate excluding columns when using the 'exclude' merge function

packages/admin-panel/src/utilities/convertSearchTermToFilter.js
- Revert search term filtering to previous behaviour, without wild card symbol at start. This enables easy searching for short names.
=> MDEV-2: Revert Search Term Filter in Admin Panel

packages/tsutils/src/downloadPageAsPDF.ts
Move validDomains to .env, so that pdf download domain validation is not hard coded.
I've added the secret `VALID_DOMAINS="[domain] www.[domain]"` in LESMIS lastpass.
=> Move validDomains to .env

packages/api-client/src/MockTupaiaApiClient.ts, packages/api-client/src/TupaiaApiClient.ts, packages/api-client/src/connections/DataTableApi.ts, packages/api-client/src/connections/index.ts, packages/api-client/src/connections/mocks/MockDataTableApi.ts, packages/api-client/src/connections/mocks/index.ts, packages/api-client/src/constants.ts
Just adding the `dataTableApi` to the `TupaiaApiClient` to allow for using it from other micro-services.
=> [no-issue]: Added data-table-api to the tupaia api-client

packages/data-broker/src/services/dhis/pullers/AnalyticsPuller.ts
Spreading a long results to parameters list will cause oversize error, since the maximum size is 255
- Example
---
=> RN-743 Fix maximum call stack size in viz builder

packages/database/src/migrations/20230216141720-ConvertReportsToPullFromDataTables-modifies-schema.js
- Look for 'dataGroupCode' instead of 'dataGroup' in parameters to determine 'events' data table.
=> RN-782: dataTableCode Migration Checks Against Wrong Data Group Key

packages/admin-panel/src/VizBuilderApp/views/Main.js
The problem is that when there are lots of columns of data, the preview component flows way over and also breaks the json editor when toggled.
- Add min-width property equal to 0, which fixes data table content overflow problem.
=> Fix data table content overflow

packages/admin-panel/src/pages/resources/QuestionsPage.js, packages/central-server/src/apiV2/import/importSurveys/importSurveys.js, packages/central-server/src/dataAccessors/findQuestionsInSurvey.js
Allow users to specify the question hook when importing surveys and in the Admin Panel
=> MDEV-117: Allow users to specify a question's hook

packages/data-table-server/src/__tests__/dataTableService/services/AnalyticsDataTableService.test.ts, packages/data-table-server/src/__tests__/dataTableService/services/EventsDataTableService.test.ts, packages/data-table-server/src/dataTableService/services/AnalyticsDataTableService.ts, packages/data-table-server/src/dataTableService/services/EventsDataTableService.ts, packages/data-table-server/src/dataTableService/services/utils/getDefaultDates.ts, packages/data-table-server/src/dataTableService/services/utils/index.ts
RN-818
Restores previous default start date logic
See dev branch: https://github.com/beyondessential/tupaia/blob/dev/packages/report-server/src/reportBuilder/query/buildPeriodParams.ts#L47
=> RN-818 Diff default startdate

packages/central-server/src/apiV2/dashboardVisualisations/EditDashboardVisualisation.js, packages/central-server/src/permissions/assertions.js
Issue: https://beyondessential.slack.com/archives/C04QFLD87E3/p1678940272063209
Legacy report doesn't have permission group, it throws error in this permission check. It is only used in EditDashboardVisualisation handler, so I think it is safe not to test.
=> No issue: Accept permissionGroupName as undefined

packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts, packages/types/src/types/requests/data-table-server/DataTablePreviewRequest.ts
(no issue)
--
Fixes `Internal server error: API error 500: Internal server error: must NOT have additional properties` when fetching preview data
=> Fix request schema

.eslintrc, packages/data-broker/package.json, packages/data-broker/src/__tests__/services/dhis/translators/DhisTranslator.test.ts, packages/data-broker/src/services/dhis/pullers/DataElementsMetadataPuller.ts, packages/data-broker/src/services/dhis/translators/DhisTranslator.ts, packages/data-broker/src/services/dhis/translators/InboundAnalyticsTranslator.ts, packages/data-broker/src/services/dhis/translators/formatDataElementName.ts, packages/dhis-api/src/DhisApi.js, packages/entity-server/src/routes/hierarchy/format/formatEntityForResponse.ts, packages/entity-server/src/routes/hierarchy/middleware/attachEntityContext.ts, yarn.lock
Issues: 8, 9, 14, 16
Reworked fetchDataElementMetadata in DhisService to pull category option combos and combine with data element name. This is the behaviour of pulling data element metadata with fetchAnalytics, so keeping it consistent. Might have to do some regression on the `tableOfEvents` and `tableOfDataValues` legacy reports, but they seemed to still work fine when I took a look at them.
=> RN-783 [fix]: Fix data element names not being consistent when pulling from DHIS2

packages/report-server/src/aggregator/ReportServerAggregator.ts, packages/report-server/src/reportBuilder/output/functions/rawDataExport/rawDataExportBuilder.ts
When doing raw data download, it throws yup validation error with DHIS data group result because validation is too strict.
This needs to be a hot fix. Slack thread: https://beyondessential.slack.com/archives/C04QFLD87E3/p1680130358072369
=> Fix validation too strict on fetchDataGroup result

packages/database/src/modelClasses/index.js, packages/server-boilerplate/src/microService/@types/express/index.d.ts, packages/server-boilerplate/src/microService/auth/middleware.ts, packages/server-boilerplate/src/types.ts
This noisy error can be seen in the logs quite often, and is a real red herring at times. It's not a real error, just that our previous flow did a try/catch on a `LoggedError`, so the error always got logged even though it was being caught and swallowed.
Now we check if user is an api client before attempting to auth, so the error shouldn't appear unless it's meant to.
=> [no-issue]: Prevent noisy api client auth error in server-boilerplate

packages/data-broker/src/services/dhis/translators/DhisTranslator.ts, packages/data-broker/src/types/results.ts
Issue found in regression, https://beyondessential.slack.com/archives/C01MAA3NKM1/p1680664696247249
Basically options are missing so legacy report can't translate value to option name.
=> Add options back to metadata

packages/psss-server/src/connections/ReportConnection.ts
https://beyondessential.slack.com/archives/C01MAA3NKM1/p1680744749341159
report server doesn't support `period` param anymore after data table phase 1 
link to the original function: https://github.com/beyondessential/tupaia/blob/6bf947a131c2b00d9ea0c5c0a2df51a0bb854a5b/packages/report-server/src/reportBuilder/transform/functions/fetchData/query/buildPeriodParams.ts#L30
- Example
---
=> Convert week to date for period in psss

packages/database/src/modelClasses/ExternalDatabaseConnection.js
RN-851 
Checked that type `timestamp without timezone`, `Integer` work fine.
=> RN-851 Knex to handle numeric and bigInt type

packages/admin-panel/src/VizBuilderApp/components/DataLibrary/component/TransformSelectedOptionWithJsonEditor.js, packages/report-server/src/reportBuilder/transform/functions/index.ts, packages/report-server/src/reportBuilder/transform/functions/orderColumns/index.ts, packages/report-server/src/reportBuilder/transform/functions/orderColumns/orderColumns.ts, packages/report-server/src/routes/FetchTransformSchemaRoute.ts
Change made to allow passing in the yup validator default as part of the transform schema. `exitOnNoData` has a default of `true`
=> RN-854: Fixed 'exitOnNoData' defaulting to 'null' when creating a fetchData transform

packages/admin-panel/src/dataTables/components/PreviewFilters/filters/DatePicker.js
RN-850
This happens in SQL data table, and it really depends on user's machine. When adding a new date param and pick a date, some clients will set date in UTC format instead of local time zone, which makes it inconsistent when compare with data period.
=> RN-850 Date param use client local timezone

packages/central-server/src/apiV2/mapOverlays/DeleteMapOverlays.js
- Delete report entry from relevant model when deleting a map overlay
- Uses the same logic as the equivalent behaviour for dashboard items
=> WAITP-1146 Delete report alongside map overlay

packages/ui-components/src/components/DataTable/useDataTableExport.js
- Add 'number' check in the useTableExport hook function.
=> RN-832: Raw data exports treat numbers as text

packages/admin-panel-server/package.json, packages/admin-panel-server/src/viz-builder/types.ts, packages/devops/ci/tupaia-ci-cd.Dockerfile, packages/report-server/src/reportBuilder/reportBuilder.ts, packages/report-server/src/types.ts, packages/types/src/types/models-extra/index.ts, packages/types/src/types/models-extra/report.ts, packages/types/src/types/models.ts, yarn.lock
It is not necessary to run `yarn build:non-internal-dependencies` in testing service because non internal packages are not relied on others anymore.  
1. This will save us ~6 mins to build testing service
2. Easier to migrate to GHA 
Remove report-server dependency in admin-panel-server (tiny)
=> Remove build non internal dependencies in ci for testing service

packages/admin-panel/src/editor/EditModal.js, packages/admin-panel/src/editor/Editor.js, packages/admin-panel/src/editor/actions.js, packages/admin-panel/src/editor/constants.js, packages/admin-panel/src/pages/resources/ResourcePage.js, packages/admin-panel/src/utilities/getFields.js, packages/admin-panel/src/utilities/index.js, packages/ui-components/src/components/Inputs/InputGroup.js, packages/ui-components/src/components/Inputs/index.js, packages/ui-components/stories/inputs/inputGroup.stories.js
- Created a `ui-component` called `InputGroup` that displays a title, description, and an array of fields
- Updated `admin-panel` edit files to handle groups of fields. To maintain backwards compatibility, this is done by passing in an optional array of `sections` to the `ResourcePage` component. Each item in the array will have an array of field names, which must be defined as fields are currently, as well as an optional title and description. The `Editor` will group the fields accordingly. This seemed the simplest way to handle these without needing to refactor everything else? 
Note: if sections are defined together with fields that don't belong to a section, the sections will appear first, and then the standalone fields. 
Also note that designs are not set in stone, so some of the …
=> WAITP-1184 field grouping support for admin panel

packages/data-table-server/src/index.ts, packages/database/src/TupaiaDatabase.js, packages/database/src/modelClasses/ExternalDatabaseConnection.js
Replaces PRs #4503 and #4507
Discussed rolling back vs rolling forward. Went with a fix that rolls back everything but data-table-server using a conditional. This lets us release safely today and in clean up in the next few days.
Tested:
- data-tables still work ✅ (data coming back from data lake as numeric)
- [rolled back] big int converted to string as before in web-config server ✅ 
- [rolled back] dhis sync queue the count is coming back as a string, as before ✅
=> Hotfix: move extra pg flags to callable method

packages/admin-panel/src/pages/resources/CustomLandingPagesPage.js, packages/admin-panel/src/pages/resources/index.js, packages/admin-panel/src/widgets/InputField/InputField.js, packages/admin-panel/src/widgets/InputField/registerInputFields.js, packages/ui-components/src/components/Inputs/RadioGroup.js, packages/ui-components/src/components/Inputs/TextField.js
- Amend the `RadioGroup` component to handle `helperText` prop
- Update styling of `startAdornment` text in `TextField`
- Add `radio` and `checkbox` field types to `registerInputFields` for use in admin panel
- Add other props for validation and `placeholder` to `text` and `textarea` input types
- Create and configure the page for Custom landing pages 
- 
- The tab has not been added to `Projects` as yet, because there is another ticket for this
- The endpoint has not yet been created and the schema is not finalised, so some details may change, however these will be easy to update in `CustomLandingPagesPage.js`
=> Waitp 1191 admin panel config elements

packages/web-frontend/src/containers/OverlayDiv/components/LandingPage/index.js, packages/web-frontend/src/containers/OverlayDiv/components/ProjectPage/ProjectCardList.js, packages/web-frontend/src/containers/OverlayDiv/components/ProjectPage/index.js, packages/web-frontend/src/containers/OverlayDiv/components/RequestProjectAccessDialog.js, packages/web-frontend/src/containers/UserBar/index.js, packages/web-frontend/src/screens/LandingPage/LandingPage.js, packages/web-frontend/src/screens/LandingPage/index.js, packages/web-frontend/src/screens/LandingPage/useAuth.js, packages/web-frontend/src/screens/LandingPage/useCustomLandingPages.js, packages/web-frontend/src/screens/LandingPage/useNavigation.js, packages/web-frontend/src/screens/LandingPage/useProjects.js, packages/web-frontend/src/screens/desktop/RootScreen/MainPage.js, packages/web-frontend/src/screens/desktop/RootScreen/index.js
- Add mock Landing Page template (most of this doesn't need review) at top level of app
- Included an additional OverlayDiv in the landing page to re-use login form etc
- Refactored the project card logic into a re-usable ProjectCardList component
- Added utils for navigating to login and logout routes in redux for ease of integration with the existing app
- Hide View Projects from LoginForm and Request Dialogs when it is a custom landing page
I still have to update the login button to stop it re-directing to the explore project. I didn't do that in this PR as it is a bit tricky.
=> WAITP-1151: Custom landing pages login flow

packages/admin-panel/src/pages/resources/CustomLandingPagesPage.js, packages/admin-panel/src/routes.js
- Added route and tab to landing pages view
- Updated table columns on landing pages view to allow sorting of order, custom headers in columns, and a clickable link to the custom link
With fake data:
=> Waitp 1185 landing pages tab

packages/psss/package.json, packages/psss/src/AppProviders.js, packages/psss/src/api/mutations.js, packages/psss/src/api/queries/helpers/query.js, packages/psss/src/api/queries/useAlerts.js, packages/psss/src/api/queries/useSingleWeeklyReport.js, packages/psss/src/containers/Modals/ArchiveAlertModal.js, packages/psss/src/containers/Modals/DeleteAlertModal.js, packages/psss/src/containers/Modals/RestoreArchivedAlertModal.js, packages/psss/src/containers/Panels/WeeklyReportsPanel.js, packages/psss/src/containers/Tables/WeeklyReportTable/WeeklyReportTable.js, packages/psss/src/index.js, yarn.lock
As part of RN-736, the version of `react-query` used by PSSS was bumped from `2.25.2` to `3.19.0`.
There are a number of breaking changes between these versions that need to be addressed: https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-3
=> Hotfix: Update usage of react-query in PSSS after version bump

packages/admin-panel/src/pages/resources/CustomLandingPagesPage.js
- Update to only direct to dev or prod urls, since that's the reality of where these will be used, so as not to have anything weird happen with release branch urls
=> Waitp 1185 landing pages url

packages/web-frontend/src/screens/LandingPage/LandingPage.js, packages/web-frontend/src/screens/LandingPage/LandingPageFooter.js, packages/web-frontend/src/screens/LandingPage/MultiProjectLandingPage.js, packages/web-frontend/src/screens/LandingPage/SingleProjectLandingPage.js
- Restricted the height setting of the wrapper to single project view so that multi projects on mobile didn't overlap the footer
- Updated media queries to handle landscape mobile
- Updated names of fields to reflect casing of API return value
=> Waitp 1188 multi project landing page styling

packages/admin-panel/src/pages/ProfilePage.js, packages/admin-panel/src/widgets/InputField/registerInputFields.js, packages/central-server/src/apiV2/landingPages/CreateLandingPage.js, packages/central-server/src/apiV2/landingPages/EditLandingPage.js, packages/central-server/src/apiV2/projects/CreateProject.js, packages/central-server/src/apiV2/projects/EditProject.js, packages/central-server/src/apiV2/utilities/uploadImage.js, packages/central-server/src/tests/apiV2/utilities/uploadImage.test.js, packages/central-server/src/utilities/getStandardisedImageName.js, packages/psss/src/views/Tabs/ProfileTabView.js, packages/ui-components/src/components/Inputs/ImageUploadField.js, packages/ui-components/stories/inputs/imageUploadField.stories.js, packages/utils/src/s3/S3Client.js, packages/web-frontend/src/containers/TopBarLogo/index.js, packages/web-frontend/src/screens/LandingPage/LandingPage.js
- Added timestamp query string to URL of image in `ImageUpload` component to prevent browser caching incorrectly
- Added timestamp query string to URL of image in landing page background and logo images to prevent browser caching incorrectly
Note: this is in response to an issue identified during testing. There is a slight performance impact by doing this but this should be minor.
=> Waitp 1191 image upload caching

scripts/bash/downloadEnvironmentVariables.sh
Now that we have the LESMIS .env var files in lastpass there was a naming clash. So have to provide the full name.
=> [no-issue]: Fix downloadEnvironmentVariables.sh script

packages/central-server/src/kobo/startSyncWithKoBo.js
Pretty simple issue in the end. At some point `DataBroker.pull` started returning `undefined` if no data has been found.
No exactly sure why that changed, and arguably it should always return an array, but I don't wanna deal with that now.
=> RN-917: Fix KoBo sync error when no data is returned

packages/api-client/src/MockTupaiaApiClient.ts, packages/api-client/src/TupaiaApiClient.ts, packages/api-client/src/auth/SessionSwitchingAuthHandler.ts, packages/api-client/src/connections/ReportApi.ts, packages/api-client/src/connections/WebConfigApi.ts, packages/api-client/src/connections/index.ts, packages/api-client/src/connections/mocks/MockReportApi.ts, packages/api-client/src/connections/mocks/MockWebConfigApi.ts, packages/api-client/src/connections/mocks/index.ts, packages/api-client/src/constants.ts, packages/server-boilerplate/src/index.ts, packages/server-boilerplate/src/orchestrator/index.ts, packages/server-boilerplate/src/orchestrator/session/attachSession.ts, packages/server-boilerplate/src/orchestrator/session/index.ts, packages/tupaia-web-server/src/@types/express/index.d.ts, packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/tupaia-web-server/src/routes/ReportRoute.ts, packages/tupaia-web-server/src/routes/TempLogoutRoute.ts, packages/tupaia-web-server/src/routes/UserRoute.ts, packages/tupaia-web-server/src/routes/index.ts
- Adding `reports` route to `tupaia-web-server`
- Basic forwarder route
- Adding `dashboards` route
- Fetch dashboards and items based on the entity hierarchy of the project
- Adding `TempLogout` route
- Currently the frontend uses a `GET` for logout which doesn't play nice with the `server-boilerplate` logout functionality
=> WAITP-1255: Tupaia web server report and dashboard routes

packages/web-config-server/src/apiV1/landingPages.js, packages/web-config-server/src/apiV1/projects.js
- Exposed function from `projects` API in `web-config-server` to reuse this in landing pages
- Updated landing page logic to fetch the projects and use the same logic as `projects` API to return the array of projects with the landing page
=> WAITP-1216 Add project permissions to landing page projects in response

packages/database/src/modelClasses/Project.js, packages/web-config-server/src/apiV1/projects.js
- return `entity_hierarchy_id` with `getAllProjectDetails` response
- return default dashboard code with projects response in `web-config-server` (uses `dashboardGroupName` to find default dashboard if possible, otherwise returns the first dashboard code. If no dashboards can be found it returns 'General' - this is because this is what web-frontend does I believe, so I kept the same logic)
=> Waitp 1216 projects default dashboard response

packages/ui-chart-components/src/__tests__/parseChartConfig.test.ts, packages/ui-chart-components/src/utils/parseChartConfig.ts
- Updated tests to be correct types in `ui-chart-components`
- Updated `$all` to be optional in `parseChartConfig`, because the method itself handles when this is unset
- Updated `parseChartConfig` to not try and spread `name` string
=> Fix chart tests

packages/api-client/src/connections/CentralApi.ts, packages/api-client/src/connections/EntityApi.ts, packages/entity-server/src/__tests__/__integration__/fieldsAndFilters.test.ts, packages/entity-server/src/models/Entity.ts, packages/entity-server/src/models/index.ts, packages/entity-server/src/routes/hierarchy/middleware/filter.ts, packages/entity-server/src/types.ts, packages/types/src/utils/utils.ts, packages/utils/src/object.js
This is required for OSC-17. It's used in https://github.com/beyondessential/tupaia/pull/4353, but I'm looking to get this merged separately to avoid further conflicts.
This PR is almost the same as the already approved https://github.com/beyondessential/tupaia/pull/4352 (reviewed by @edmofro).  Changes are:
* Removed any functionality that is implemented in `dev` now (`central-server: GetEntityRelations`)
* Removed `admin-panel-server: FetchEntityHierarchyTreeRoute` as it won't be needed
* Conflicts with `dev` resolved
After that there should be one more PR and OSC-17 should be ready for testing!
---
**Testing notes:** this PR does touch filtering in `entity-server`, so it may need to be QAed. At the same time, `entity-serfver` has great test coverage. I'll leave the testing strategy to …
=> [no-issue]: Add generational_distance filter in entity-server

packages/server-boilerplate/src/orchestrator/session/attachSession.ts, packages/tupaia-web-server/src/routes/UserRoute.ts
- `server-boilerplate` already wraps middleware in a try/catch so the original method wasn't working as expected
- Rather than wrap the existing `attachSession` function and discarding the error, just write it a little WET but without the throws
=> Tupaia web server fixup attach session

packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/CountryAccessListRoute.ts, packages/tupaia-web-server/src/routes/index.ts, packages/tupaia-web/src/api/queries/useCountryAccessList.ts
- Updated `tupaia-web-server` to have `countryAccessList` endpoint
- Use endpoint in `tupaia-web` instead of test data
=> WAITP-1207 Add country access list endpoint

packages/admin-panel/package.json, packages/central-server/package.json, packages/utils/package.json, packages/web-frontend/package.json, yarn.lock
Bump versions of moment-timezone, parse-link-header and validator to the recommended versions.
I tested building all the packages and smoke tested the front end apps and everything seems fine.
=> WAITP-1269: Fix frontend package vulnerabilities

packages/tupaia-web-server/examples.http, packages/tupaia-web-server/src/routes/ReportRoute.ts, packages/tupaia-web/src/api/queries/useDashboards.ts, packages/tupaia-web/src/api/queries/useReport.ts, packages/tupaia-web/src/features/Chart.tsx, packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/DashboardItem/DashboardItem.tsx, packages/ui-chart-components/src/components/Axes/YAxes.tsx, packages/ui-chart-components/src/components/CartesianChart.tsx
- Minor styling change for no data display with charts
- Updated `ReportRoute` to return non-legacy reports in the correct format
- Added examples to `tupaia-web-server` for report fetching
- Updated `useReport` to be able to accept `startDate` and `endDate`
---
=> WAITP-1243 Bar charts

packages/api-client/src/connections/WebConfigApi.ts, packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/LegacyMapOverlayReportRoute.ts, packages/tupaia-web-server/src/routes/MapOverlaysRoute.ts, packages/tupaia-web/src/api/queries/useMapOverlayData.ts
- Pass mapOverlay param to query string params instead of report report route param in legacy map overlay report route 
- Handle when there are no map overlays for a project and entity on the map overlays route
=> WAITP-1268: Update map overlay route

packages/tupaia-web/src/api/queries/useEntities.ts, packages/tupaia-web/src/api/queries/useEntity.ts, packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Dashboard/StaticMap.tsx, packages/tupaia-web/src/features/EntitySearch/EntityMenu.tsx, packages/tupaia-web/src/features/EntitySearch/EntitySearch.tsx, packages/tupaia-web/src/features/Map/Map.tsx, packages/tupaia-web/src/features/Map/MapLegend/DesktopMapLegend.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/DesktopMapOverlaySelector.tsx, packages/tupaia-web/src/features/MapOverlays/MapOverlays.tsx, packages/tupaia-web/src/features/MapOverlays/PolygonLayer.tsx, packages/tupaia-web/src/types/types.d.ts
The context of this refactor is that in [waitp-1293-entity-route-better-filtering](https://github.com/beyondessential/tupaia/tree/waitp-1293-entity-route-better-filtering) the response from the entities api endpoint was refactored to return a flat list of entities and so the front end has to be refactored to match.
- Entity Menu
- Entity Polygons
=> WAITP-1293: Refactor tupaia-web for flat entities data

packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/EntitiesRoute.ts, packages/tupaia-web/src/api/queries/useEntities.ts, packages/tupaia-web/src/api/queries/useEntity.ts, packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Dashboard/StaticMap.tsx, packages/tupaia-web/src/features/EntitySearch/EntityMenu.tsx, packages/tupaia-web/src/features/EntitySearch/EntitySearch.tsx, packages/tupaia-web/src/features/Map/Map.tsx, packages/tupaia-web/src/features/Map/MapLegend/DesktopMapLegend.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/DesktopMapOverlaySelector.tsx, packages/tupaia-web/src/features/MapOverlays/MapOverlays.tsx, packages/tupaia-web/src/features/MapOverlays/PolygonLayer.tsx, packages/tupaia-web/src/types/types.d.ts
- `EntitiesRoute` now takes `projectCode` and does a lookup for `hierarchyName`
- Allow overwriting the default `generational_distance` filter easier
=> WAITP-1293 Update filtering on entities route

packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/EntityAncestorsRoute.ts, packages/tupaia-web-server/src/routes/index.ts
- Add `entityAncestors` route to `tupaia-web-server`
- Returns an array of entities in ascending hierarchy order `[parent, grandparent, great-grandparent]`
- This is the default return from `entity-server` so it's mostly just forwarding the request
=> WAITP-1298 Add EntityAncestors route

packages/aggregator/src/Aggregator.js, packages/aggregator/src/__tests__/Aggregator/Aggregator.test.js, packages/central-server/src/kobo/startSyncWithKoBo.js, packages/data-broker/src/DataBroker/DataBroker.ts, packages/data-broker/src/DataBroker/fetchDataSources.ts, packages/data-broker/src/DataBroker/index.ts, packages/data-broker/src/DataBroker/mergeAnalytics.ts, packages/data-broker/src/__tests__/DataBroker/DataBroker.fixtures.ts, packages/data-broker/src/__tests__/DataBroker/DataBroker.stubs.ts, packages/data-broker/src/__tests__/DataBroker/DataBroker.test.ts, packages/data-broker/src/__tests__/DataBroker/fetchDataSources.test.ts, packages/data-broker/src/__tests__/services/dhis/DhisService.test.ts, packages/data-broker/src/__tests__/testUtils/createInstances.ts
I've wanted to make this change for some time now... We're talking about years :smile: 
When we were writing `data-broker`, @edmofro had warned me that we shouldn't use the same API for different data sources (e.g. `pull()` for both analytics and events). Unfortunately, I didn't heed his warning back then - we were moving fast and all that. It is time to set things right!
This PR splits `DataBroker.pull()` in one API per pulled data source type:
* `pullAnalytics()`
* `pullEvents()`
* `pullSyncGroupResults`
Benefits:
* Fix an over-abstraction. Get rid of `this.mergers`, `this.fetchers` etc
* More sensible types
* Easier to see what's happening at the function level
* Can still reuse functionality when needed, as an implementation detail
The package has good coverage and most parts of the …
=> Split DataBroker.pull API per data source

packages/web-config-server/src/connections/ReportConnection.js
- Skip the token refresh if we're already using an auth header
- There's a separate handler for forwarding to central server that's still going to be an issue
=> WAITP-1286 Web config forward auth header to report server

packages/central-server/src/kobo/startSyncWithKoBo.js, packages/data-broker/src/DataBroker/DataBroker.ts, packages/data-broker/src/services/DataServiceResolver.ts
Bit of an unexpected bug here. Because we were spreading the sync group data source Db objects we were losing the `databaseType` getter.
Added a check for that since it's a bit of a hard bug to track down.
=> RN-932: Fix KoBo sync

packages/meditrak-app/.env.example, packages/meditrak-app/app/api/TupaiaApi.js, packages/meditrak-app/package.json
This fixes a problem where an empty CENTRAL_API_URL env var was causing the BASE_URL to resolve to '';
=> Fix meditrak api url resolution

packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/LegacyDashboardReportRoute.ts, packages/tupaia-web-server/src/routes/LegacyMapOverlayReportRoute.ts, packages/tupaia-web-server/src/routes/ReportRoute.ts
=> Fixup silly errors

packages/utils/jest-setup.js, packages/utils/jest.config.js, packages/utils/src/__tests__/period/periodGranularities.test.js, packages/web-frontend/config/jest/jest-setup.js, packages/web-frontend/jest.config.js, packages/web-frontend/package.json, packages/web-frontend/src/tests/testutil.js, packages/web-frontend/src/utils/formatDateForApi.js, yarn.lock
- Updates to moment-timezone meant that the timezone wasn't getting set correctly at the start of period granularity tests. Fixed by setting the timezone through jest config instead.
=> WAITP-1269: Fix front end tests config

packages/ui-chart-components/src/components/CartesianChart.tsx, packages/ui-chart-components/src/components/Charts/GaugeChart.tsx, packages/ui-chart-components/src/components/Charts/PieChart.tsx, packages/ui-chart-components/src/components/Reference/Legend.tsx, packages/ui-chart-components/src/utils/utils.ts
- Assume isMobile is false when exporting so that the exports don't include mobile styles
=> WAITP-1290: Fix Chart pdf export styles

packages/ui-components/src/components/DownloadFilesVisual.tsx, packages/ui-components/src/components/DownloadFilesVisual/index.js, packages/ui-components/src/components/index.ts, packages/ui-components/tsconfig.json, packages/web-frontend/src/components/View/DownloadFilesVisual.js
- Convert Download Files Component to TS
- Refactor slightly to match tupaia-web patterns
---
=> RN-931: Refactor download files component to TS

packages/tupaia-web/src/features/Matrix.tsx, packages/ui-components/src/components/Matrix/Matrix.tsx, packages/ui-components/src/components/Matrix/MatrixContext.ts, packages/ui-components/src/components/Matrix/MatrixRow.tsx
- Applied filter to matrix component when no date filter is present on the report
- Added param `disableExpand` to UI Matrix component to allow expand to be forced open, e.g. when a search filter is enabled
---
=> WAITP-1229 Search filter for matrix

packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/EntityRoute.ts, packages/tupaia-web-server/src/routes/index.ts
=> WAITP-1318 Add single entity request route

packages/tupaia-web/src/features/DashboardItem/DashboardItemContent.tsx, packages/tupaia-web/src/features/Matrix.tsx, packages/ui-components/src/components/Matrix/MatrixContext.ts, packages/ui-components/src/components/Matrix/MatrixHeader.tsx
- Added support for `rowHeaderColumnTitle` in `ui-components/Matrix`
- Moved the search bar to be passed in as `rowHeaderColumnTitle` prop
- Updated placeholder text to be `Search...`
---
=> Move search bar

.gitignore, packages/meditrak-app/android/app/src/main/AndroidManifest.xml
https://stackoverflow.com/questions/70333565/targeting-s-version-31-and-above-requires-that-an-explicit-value-for-android
=> [no-issue]: Fix missing android:exported="true" in AndroidManifest.xml

packages/tupaia-web/src/constants/constants.ts, packages/tupaia-web/src/features/Map/Map.tsx, packages/tupaia-web/src/features/Map/MapLegend/MapLegend.tsx, packages/tupaia-web/src/features/Map/MapLegend/MobileMapLegend.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/DesktopMapOverlaySelector.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapOverlayDatePicker.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapOverlayList.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapOverlaySelector.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapOverlaySelectorTitle.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MobileMapOverlaySelector.tsx, packages/tupaia-web/src/layout/TopBar/TopBar.tsx
- Added overlay library list, title, and datepicker to mobile overlay selector
- Styled mobile overlay selector
- Tweaked styling around map so that attribution is visible on mobile
---
=> Waitp 1288 mobile map overlay

packages/entity-server/src/routes/hierarchy/middleware/filter.ts
- When generating the permission filter, also allow for `country_code IS NULL`
=> WAITP-1340 Entity server don't filter out projects

packages/tupaia-web-server/package.json, packages/tupaia-web-server/src/routes/MapOverlaysRoute.ts, packages/types/src/schemas/schemas.ts, packages/types/src/types/requests/tupaia-web-server/MapOverlaysRequest.ts, yarn.lock
- Sort by `sort_order`, then by `name`
- Update dev dependencies to use `lodash.sortby`
- Add `sortOrder` to types
=> WAITP-1286 Fixup overlay sort

packages/api-client/src/connections/ApiConnection.ts
- When an API connection throws an error, don't just discard that error code
=> WAITP-1365 Maintain status codes in API connections

packages/entity-server/src/models/Entity.ts, packages/entity-server/src/routes/hierarchy/extendedFieldFunctions.ts, packages/tupaia-web-server/src/routes/EntitySearchRoute.ts
- Allow requesting a qualified name from entity server as an extended field
- Request qualified name by default in `tupaia-web-server` search route
=> WAITP-1289 Allow requesting qualified name from entity server

packages/tupaia-web/src/layout/TopBar/Logo.tsx
WAITP-1320: Custom Landing Page: Update organisation name style
- Changed font-size in tupaia-web/src/layout/TopBar/Logo.tsx on line 48
=> changed font-size commit

packages/tupaia-web/src/components/RouterButton.tsx, packages/tupaia-web/src/layout/ProjectCardList/ProjectCard.tsx, packages/tupaia-web/src/views/LandingPage/MultiProjectLandingPage.tsx, packages/tupaia-web/src/views/LandingPage/SingleProjectLandingPage.tsx
WAITP-1299 Custom landing page: Open link to project in new tab
- Added target to BaseLink component in tupaia-web/src/layout/ProjectCardList/ProjectCard.tsx line 133,
- Added target to ActionLink component in tupaia-web/src/views/LandingPage/SingleProjectLandingPage.tsx line 104
=> Waitp 1299 link to project new tab

packages/tupaia-web/src/api/queries/useCountryAccessList.ts, packages/tupaia-web/src/views/RequestProjectAccessModal/RequestProjectAccessModal.tsx
- Show request access form when some countries already have access, so long as the project does not yet have access granted
- Remove caching on country access list so that if the user goes bak to request access view, access is up to date.
=> Fix bug with request access form

packages/tupaia-web/src/api/queries/useMapOverlayReport.ts
- Only keep previous data for map overlay when query is enabled. Fixes issue where going back to an entity where there were no map overlays would keep the previous entity's data
=> Waitp 1222 point overlay fix

packages/tupaia-web/src/api/mutations/useRequestCountryAccess.ts
- Invalidate project query when project access is requested, so that projects is always up to date with access status
=> WAITP-1207: Invalidate queries when project access is requested

packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Dashboard/DashboardMenu.tsx
- Show minimap with default bounds when no dashboard (ie permission denied)
- Hide dashboard button when no dashboards available (permission denied)
---
=> Waitp-1287 dashboard minimap no data

packages/devops/configs/servers.conf
- Increase the `proxy_buffer_size` for `central-server`
- Default is usually `8k`, double it to `16k`
- This buffer is used for processing http headers when we proxy to the central-server
- `tupaia-web-server` is making some large requests that blow out the original buffer size
=> WAITP-1215 Increase proxy_buffer_size for central-server

packages/tupaia-web/src/api/queries/useEntity.ts, packages/tupaia-web/src/features/Map/Map.tsx, packages/tupaia-web/src/types/entity.d.ts, packages/ui-map-components/src/components/LeafletMap.tsx, packages/ui-map-components/src/components/Markers/MeasurePopup.tsx
- Updated useEntity query in tupaia-web to fetch point column. 
- Passed point and zoom from Map to leafletMap component.
- switched if statement priority from bounds to point so the map auto movement will always use setView instead of fitBounds if there is a point available.
=> WAITP-1397: Tupaia Maps - Auto-zoom out

packages/devops/configs/servers.conf
- Vite builds to dist instead of build and we need to updated the server config to match
---
=> WAITP-1283: Fix broken server config

packages/central-server/src/apiV2/mapOverlayGroupRelations/GETMapOverlayGroupRelations.js, packages/database/src/TupaiaDatabase.js, packages/database/src/modelClasses/MapOverlayGroupRelation.js, packages/database/src/modelClasses/index.js, packages/server-boilerplate/src/orchestrator/api/ApiBuilder.ts, packages/tupaia-web-server/src/@types/express/index.d.ts, packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/models/MapOverlayGroupRelation.ts, packages/tupaia-web-server/src/models/index.ts, packages/tupaia-web-server/src/routes/MapOverlaysRoute.ts, packages/tupaia-web-server/src/types.ts
- Remove some debug logs
- Allow `TupaiaDatabase.findRecursiveTree` to search for multiple ids at once
- Add a recursive parent search to `MapOverlayGroupRelationModel`
- Allow orchestration servers to attach models to req in `server-boilerplate`
- This isn't best practice, so generates a warning on startup
- Add model and modelRegistry types to `tupaia-web-server`
- Attach those to the default request type
- Update `MapOverlaysRoute` to fetch relations from the db directly
=> WAITP-1286 Use direct db access for MapOverlayRoute

packages/database/src/migrations/20230814030728-RemoveUnusedEntityBoundsData.js
- Added migration to remove all bounds records in the entity table where there is a point record
=> Waitp 1419 remove unused entity bounds data

packages/tupaia-web-server/src/routes/EntitySearchRoute.ts, packages/tupaia-web/src/features/EntitySearch/SearchResults.tsx
- Updated searchResults.tsx in tupaia-web to use qualified_name instead of name as this will show the ancestor entities as well as the target entity when searching.
=> WAITP-1210 Navigation: Entity navigation via search

packages/tupaia-web/src/features/EntitySearch/EntitySearch.tsx
- Updated expandSearchBar function in EntitySearch to an expanding only function rather than a toggle as this was causing the tab changing bug. Behaviour is now consistent with production.
=> WAITP-1201: Navigation: Entity navigation via search (issue 3)

packages/data-broker/.env.example
It says that its env variables are used in `data-broker` tests, but they're not
=> [no-issue]: Remove redudnant .env.example file

packages/data-broker/src/DataBroker/DataBroker.ts, packages/data-broker/src/__tests__/DataBroker/DataBroker.stubs.ts, packages/data-broker/src/__tests__/DataBroker/DataBroker.test.ts, packages/data-broker/src/__tests__/services/dhis/DhisService.test.ts, packages/data-broker/src/__tests__/services/dhis/pullers/DeprecatedEventsPuller.test.ts, packages/data-broker/src/__tests__/services/kobo/KoBoService.test.ts, packages/data-broker/src/__tests__/services/superset/SupersetService.test.ts, packages/data-broker/src/__tests__/services/tupaia/TupaiaService.test.ts, packages/data-broker/src/__tests__/services/weather/WeatherService.stubs.ts, packages/data-broker/src/__tests__/services/weather/WeatherService.test.ts, packages/data-broker/src/services/Service.ts, packages/data-broker/src/services/data-lake/DataLakeService.ts, packages/data-broker/src/services/dhis/DhisService.ts, packages/data-broker/src/services/dhis/pullers/AnalyticsPuller.ts, packages/data-broker/src/services/dhis/pullers/DeprecatedEventsPuller.ts, packages/data-broker/src/services/dhis/pullers/EventsPuller.ts, packages/data-broker/src/services/indicator/IndicatorService.ts, packages/data-broker/src/services/kobo/KoBoService.ts, packages/data-broker/src/services/superset/SupersetService.ts, packages/data-broker/src/services/tupaia/TupaiaService.ts, packages/data-broker/src/services/weather/WeatherService.ts, packages/data-broker/src/types/models.ts
This PR continues the work that started in https://github.com/beyondessential/tupaia/pull/4704 by splitting the pull API for `data-broker` services into `pullAnalytics()`, `pullEvents()`, `pullSyncGroupsResults()`
=> [no-issue]: Split pull API for data-broker Services

packages/entity-server/src/routes/hierarchy/EntitySearchRoute.ts
- Parameterize Entity Search Route so that the search string is escaped and sanitised.
=> WAITP-1210: Parameterize Entity Search Route

packages/tupaia-web/src/api/mutations/useExportDashboard.tsx, packages/tupaia-web/src/features/Dashboard/ExportDashboard.tsx, packages/ui-components/src/components/CheckboxList.tsx
Making this component generic allows us to override the base `ListItem` type when using the `CheckboxList`.
Just to address this comment thread: https://github.com/beyondessential/tupaia/pull/4848/files#r1296553278
=> RN-899: Make the CheckboxList component generic

packages/central-server/src/apiV2/mapOverlayGroupRelations/GETMapOverlayGroupRelations.js, packages/central-server/src/apiV2/projects/GETProjects.js
The regression was caused in WAITP-1310 so just marking it against that ticket. The change isn't deployed yet so no need for a hotfix.
=> WAITP-1301: Fix Get Projects Endpoint

packages/database/src/modelClasses/DashboardItem.js, packages/database/src/modelClasses/index.js, packages/tupaia-web-server/src/models/DashboardItems.ts, packages/tupaia-web-server/src/models/index.ts, packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/tupaia-web-server/src/types.ts, packages/tupaia-web/src/features/Visuals/NoAccessDashboard.tsx
- Update handling of no access routes in tupaia-web-server to match web-config-server
- Update no access dashboard to be correctly formatted and displayed
=> Waitp 1366 no access dashboards

packages/entity-server/src/app/createApp.ts, packages/entity-server/src/routes/hierarchy/middleware/attachEntityContext.ts, packages/entity-server/src/routes/hierarchy/middleware/index.ts
- Allow calculating and attaching the `filter` context to `req` in `entity-server` without a specific entity context
- This is only useful for the `entitySearch` route at the moment because searches happen within a hierarchy context, but may still require a filter applied
- Fixes the issue with `frontendExcludedTypes` not being correctly applied to entity search
=> WAITP-1210: Allow attaching filter context without entity context

packages/entity-server/src/__tests__/__integration__/EntitySearchRoute.test.ts, packages/entity-server/src/routes/hierarchy/EntitySearchRoute.ts
- Put entities that are higher in the hierarchy order higher in the search results
=> WAITP-1210 Sort entity searches with higher hierarchy entities first

packages/server-boilerplate/src/orchestrator/api/ApiBuilder.ts, packages/tupaia-web-server/src/routes/DashboardsRoute.ts
- Remove the spammy warning that I added
- Override default page size for dashboard requests
- Since we fetch data for all dashboards on an entity simultaneously, some of our entities have upwards of 20 different dashboards
- This results in more than 100 items/relations across those dashboards
We used a similar solution for `mapOverlays` that wound up not working because of the sheer volume of values in that case. Map overlay relations are in a hierarchy structure, which means for cases with a lot of layers the numbers blow up exponentially. Those requests were going above 400 records at points, which caused us issues. This is less likely to cause issues in dashboards since they're flat structured. Experimenting on my local, the larger sets of dashboards were giving ranges of 150-200. So …
=> WAITP-1243 Fixup missing dashboard items

packages/tupaia-web-server/src/routes/MapOverlaysRoute.ts
- Filter overlays before the relations fetch
- This way no relations will match and it won't get attached to the final return object
=> WAITP-1215 Filter out overlays with hideFromMenu set

packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Dashboard/DashboardMenu.tsx, packages/tupaia-web/src/features/Dashboard/ExpandButton.tsx, packages/tupaia-web/src/features/Dashboard/StaticMap.tsx, packages/tupaia-web/src/features/DashboardItem/DashboardInfoHover.tsx, packages/tupaia-web/src/features/DashboardItem/ExpandItemButton.tsx, packages/tupaia-web/src/features/Visuals/View/DataDownload.tsx, packages/tupaia-web/src/layout/ProjectCardList/ProjectCard.tsx, packages/tupaia-web/src/layout/TopBar/TopBar.tsx
- Remove red background test code
- Update dashboard and project card styles to match design
- Update Dashboard item more info action to match existing behaviour
---
Update dashboard colours and padding to match design 
Dashboard item more info hover on desktop
Dashboard item more info on mobile
=> WAITP-1242: Tupaia- web FE fixes

packages/central-server/src/apiV2/export/exportSurveys/cellBuilders/EntityConfigCellBuilder.js, packages/central-server/src/apiV2/import/importSurveys/ConfigImporter/processEntityConfig.js, packages/utils/src/errors.js
Couple issues here to address:
- We always set a value for `generateQrCode` and `allowScanQrCode` when it'd be better for us to default them instead
- There are functions that throw errors that extend from `LoggedError` in the frontend. Figured it'd be easier just to just check if `winston` is available in that exception.
=> hotfix: Fix error logging when importing surveys

packages/lesmis/src/routes/PageRoutes.jsx
Fixes this issue on the dev builds.
```
er-compatibility for more details.
\Tue Aug 29 00:43:59 UTC 2023 \✓ 11625 modules transformed.
\Tue Aug 29 00:44:00 UTC 2023 \Export "ExportModal" of module "../../node_modules/@tupaia/admin-panel/lib/importExport/ExportModal.js" was reexported through module "../../node_modules/@tupaia/admin-panel/lib/importExport/index.js" while both modules are dependencies of each otherand will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
\Tue Aug 29 00:44:00 UTC 2023 \Either change the import in "src/views/AdminPanel/components/getSurveyResponsesExportModal.jsx" to point directly to the exporting …
```
=> No-issue: fix lesmis build error

packages/api-client/src/connections/ApiConnection.ts, packages/server-boilerplate/src/orchestrator/api/ApiBuilder.ts, packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/ExportSurveyResponsesRoute.ts, packages/tupaia-web-server/src/routes/index.ts, packages/types/src/types/requests/tupaia-web-server/ExportSurveyResponsesRequest.ts, packages/types/src/types/requests/tupaia-web-server/index.ts
I initially intended to do multiple routes on this branch, but this change bloated a bit beyond initial scope
- Clean up some imports
- Add `ExportSurveyResponsesRoute`
- Add request type to `types` package
- Allow `ApiClient` to return non-json responses
=> WAITP-1239: Add export survey responses route to tupaia-web-server

packages/tupaia-web/src/features/Map/Map.tsx, packages/tupaia-web/src/features/Map/MapOverlays/DataVisualsLayer.tsx, packages/tupaia-web/src/features/Map/MapOverlays/InteractivePolygon.tsx, packages/tupaia-web/src/features/Map/MapOverlays/PolygonNavigationLayer.tsx
- Fix issue of zoom level being incorrect on selection of an entity
- Fix issue with polygon shades being wrong
- Fix issue with country outlines not showing on map
- Fix issue where child entities were not showing while map overlay report data was loading
=> WAITP-1221: Polygon overlay fixes

packages/tupaia-web-server/package.json
`tupaia-web-server` tests are failing in github actions because we don't correctly run the initial setup for the database, so the base `tupaia` user hasn't been created when it tries to run tests. Add the appropriate line to the `package.json`
=> Add setup-test command to tupaia-web-server

packages/admin-panel-server/package.json, packages/data-table-server/package.json, packages/database/package.json, packages/entity-server/package.json, packages/lesmis-server/package.json, packages/meditrak-app-server/package.json, packages/psss-server/package.json, packages/report-server/package.json, packages/server-boilerplate/package.json, packages/tupaia-web-server/package.json, yarn.lock
This allows us to use the same `winston` instance across all packages. Mainly useful when modifying the default transports when running tests in the root `jest.setup.js`.
=> no-issue: Set winston to ^3.3.3 everywhere

packages/datatrak-web/src/components/Button.tsx, packages/datatrak-web/src/components/TopProgressBar.tsx, packages/datatrak-web/src/features/Survey/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveyScreen.tsx, packages/datatrak-web/src/features/Survey/SurveySideMenu/SideMenuButton.tsx, packages/datatrak-web/src/features/Survey/SurveySideMenu/SurveySideMenu.tsx, packages/datatrak-web/src/features/Survey/SurveySideMenu/index.ts, packages/datatrak-web/src/theme/theme.ts, packages/ui-components/src/components/Inputs/RadioGroup.tsx
- Changed `SurveyContext` to use a reducer instead of state, now that we have more than 1 action
- Created survey contents menu and added to view
Note: I haven't included mobile styling here, as not sure of design yet
---
Closed  
Open
=> WAITP-1346: Survey contents menu

packages/devops/configs/servers.conf, packages/devops/scripts/deployment/setupGoldMaster.sh
- Fix `nging` typo
- Update h5bp to latest release
- Why are we using a version from 2017??
- I don't know if we want to upgrade to an inbetween version, but upgrading is necessary if we want to use `compression.conf`
=> No issue: Fixup servers conf

packages/database/package.json, packages/database/src/DatabaseChangeChannel.js, yarn.lock
Means that we don't get those annoying console logs during the tests.
Decided to bump to latest version while at it.
=> no-issue: Set winston as the logger for pg-pubsub

packages/tupaia-web-server/src/routes/EntitiesRoute.ts
- Prevents an issue where drop down arrows appear on entities without children in the entity search list
- We request two layers of entities at a time, and we only filter the first layer in this implementation
- If we wanted to filter all `child_codes` fields we'd need an additional fetch from `entity-server`, pull the filtered descendants of the entity list and the filter all `child_codes` fields by that list
- I implemented _that_ version of code in the first commit, then replaced it with this version, which uses less api requests
- But we the data from that version is more consistent, so we might still prefer it. This might be a tech design sort of discussion
=> WAITP-1211: Filter child_codes when fetching entities in tupaia-web-server

packages/tupaia-web-server/src/routes/ExportSurveyResponsesRoute.ts
- The filter argument was formatted incorrectly, causing an unfiltered request which was causing incorrect (but valid) data to be passed to the next step
=> WAITP-1242 Fixup headers on survey response export

packages/tupaia-web/src/api/queries/useReport.ts, packages/tupaia-web/src/features/EnlargedDashboardItem/utils/useEnlargedDashboardItem.ts
- Added `isExpanded` param to query for enlarged reports, so that reports get handled correctly. 
Note: BE piece of this is a separate PR
=> WAITP-1231: Handle isExpanded params for matrix report

packages/expression-parser/package.json, packages/expression-parser/src/expression-parser/ExpressionParser.js, packages/report-server/package.json, packages/report-server/src/reportBuilder/transform/parser/functions/math.ts, yarn.lock
```
> Task :app:bundleReleaseJsAndAssets
error While trying to resolve module `fraction.js` from file `/Users/runner/work/1/s/packages/expression-parser/node_modules/mathjs/lib/cjs/type/fraction/Fraction.js`, the package `/Users/runner/work/1/s/packages/expression-parser/node_modules/fraction.js/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/runner/work/1/s/packages/expression-parser/node_modules/fraction.js/fraction.cjs`. Indeed, none of these files exist:
```
See a broken [build](https://appcenter.ms/orgs/Beyond-Essential/apps/Tupaia-MediTrak-Android/build/branches/dev/builds/1882).
The issue is math.js had an unlocked dependency on fraction.js which upgraded and …
=> Fix appcenter build fail due to mathjs

packages/server-boilerplate/src/utils/forwardRequest.ts
- Catch errors in the forward request handler
- All default routes are wrapped in a similar catch and next handler
- This prevents an issue with crashing on failure to `getAuthHeader`
=> WAITP-1421 Catch errors in forward request handler

packages/central-server/src/apiV2/surveyResponse.js, packages/central-server/src/apiV2/surveyResponses/ResubmitSurveyResponse.js, packages/psss-server/package.json, packages/psss-server/src/connections/CentralConnection.ts, packages/psss-server/src/routes/alerts/ProcessAlertActionRoute.ts, packages/psss-server/src/routes/reports/ConfirmWeeklyReportRoute.ts, packages/psss-server/src/routes/reports/SaveWeeklyReportRoute.ts, yarn.lock
Previously PSSS has been using the `POST /changes` endpoint in the `central-server` for survey response submission. This endpoint really ought to just be used by meditrak, and will shortly be moved over to the `meditrak-app-server`.
So this change is just to switch PSSS over to the more appropriate `/surveyResponse` endpoints
=> RN-988: Switched PSSS survey response CRUD over to using /surveyResponse endpoint

packages/central-server/src/database/meditrakSyncQueue/MeditrakSyncRecordUpdater.js, packages/central-server/src/externalApiSync/ExternalApiSyncQueue.js, packages/database/src/migrations/20230915002216-DropMeditrakSyncQueueChangeTimeTrigger-modifies-schema.js, packages/meditrak-app-server/src/sync/MeditrakSyncRecordUpdater.ts
This change is primarily motivated by testing interests. Having the `change_time` being calculated by db trigger means it's really hard to accurately await for when the sync queues have been properly updated.
I guess the other motivation is to reduce complexity a little.
Having the database be responsible for this though is a more resilient approach, so happy to drop this if we feel the cons outweigh the pros.
@edmofro wouldn't mind getting your perspective on this 🙏
=> RN-664: Move calculation of change_time for sync queues into application logic

packages/tupaia-web-server/package.json, packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/tupaia-web-server/src/routes/MapOverlaysRoute.ts, yarn.lock
- Add a discrete step to sorting visuals to place `null` sort values last
=> WAITP-1287 Fixup ordering of nulls

packages/central-server/src/database/meditrakSyncQueue/MeditrakSyncRecordUpdater.js, packages/central-server/src/externalApiSync/ExternalApiSyncQueue.js, packages/meditrak-app-server/src/sync/MeditrakSyncRecordUpdater.ts, packages/tsutils/src/getSyncQueueChangeTime.ts, packages/tsutils/src/index.ts
In this release we are now calculating the sync queue `change_time` in the application. An issue was discovered in the release that there can be clashes with the way we calculate this `change_time`.
Fix this by:
1. Using the same function for determining the change time as we'd been using previously
2. Switch a couple instances of `Promise.all()` to explicit loops in order to preserve change order
=> no-issue: Fix broken sync queues

packages/devops/scripts/ci/validateNewMigrations.sh
This hot-fix updates the validateMigration CI script to ignore the process when the current branch is the same as origin (master).
=> hot-fix: skip migration validation on master

packages/tupaia-web/src/features/Map/MapOverlaysLayer/MarkerLayer.tsx, packages/tupaia-web/src/features/Map/MapOverlaysLayer/PolygonLayer.tsx, packages/tupaia-web/src/features/Map/utils/useMapOverlayMapData.ts
- Fixed issue where duplicated entities appeared on the map
- Fixed issue where hidden measures still appeared
- Fixed points appearing when the selected overlay is not a point type overlay
- Handle array type measure levels (likely to be deprecated later though)
=> WAITP-1221: Map overlay fixes

packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/tupaia-web/src/features/Dashboard/DashboardMenu.tsx, packages/tupaia-web/src/features/EntitySearch/SearchResults.tsx, packages/tupaia-web/src/features/Map/utils/useMapOverlayTableData.ts, packages/tupaia-web/src/features/Visuals/Matrix.tsx, packages/tupaia-web/src/features/Visuals/View/DownloadFiles.tsx, packages/tupaia-web/src/features/Visuals/View/SingleValue.tsx, packages/tupaia-web/src/features/Visuals/View/View.tsx
- Hide static text hover effect when enlargable
- Fix height of dashboard menu to allow for branch name banner
- Fix sort of dashboard items to use `name` instead of `code` after `sort_order`
- Don't display single value name if is not `multiSingleValue`
- Add disabled button state to download files viz
- Fix loading state of map overlay selector when there are no overlays for an entity
- Fix issue with missing table rows when only some table rows are grouped
- Fix issue with missing search result at end of list
=> WAITP-1287: Misc FE fixes

packages/datatrak-web/mocks/mockData/surveyScreenComponents.json, packages/datatrak-web/src/Routes.tsx, packages/datatrak-web/src/__tests__/survey.test.tsx, packages/datatrak-web/src/api/mutations/useSubmitSurvey.ts, packages/datatrak-web/src/api/queries/useSurveyScreenComponents.ts, packages/datatrak-web/src/features/Survey/Components/SurveyQuestion.tsx, packages/datatrak-web/src/features/Survey/Components/SurveyQuestionGroup.tsx, packages/datatrak-web/src/features/Survey/Components/SurveySideMenu/SurveySideMenu.tsx, packages/datatrak-web/src/features/Survey/Screens/SurveyReviewScreen.tsx, packages/datatrak-web/src/features/Survey/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveySideMenu/SurveySideMenu.tsx, packages/datatrak-web/src/features/Survey/index.ts, packages/datatrak-web/src/features/Survey/utils.ts, packages/datatrak-web/src/features/index.ts, packages/datatrak-web/src/types/surveys.ts, packages/types/src/schemas/schemas.ts, packages/types/src/types/requests/datatrak-web-server/SurveyScreenComponentsRequest.ts
- Added filtering to questions and screens based on visibility criteria
- Added ability to save values to formData when questions depend on answers being updated
- Removed logic around changing question numbers based on screens with only instructions, because the question numbers don't match the side menu numbers in this case
- Tidied up context methods to try make more readable
- Changed survey components to be an array of arrays in the FE so is easier to work with visibility
- Added logic to redirect the user to the first survey question if they attempt to access a survey screen that is not available
- Added logic to reset the survey questions that have changed to being invisible
=> WAITP-1416: Visibility criteria

packages/database/src/modelClasses/DashboardRelation.js, packages/database/src/modelClasses/index.js, packages/server-boilerplate/src/models/types.ts, packages/tupaia-web-server/package.json, packages/tupaia-web-server/src/__tests__/testUtilities/setup.ts, packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/app/middleware/attachAccessPolicy.ts, packages/tupaia-web-server/src/app/middleware/index.ts, packages/tupaia-web-server/src/models/DashboardRelation.ts, packages/tupaia-web-server/src/models/User.ts, packages/tupaia-web-server/src/models/index.ts, packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/tupaia-web-server/src/types.ts
- Allow fetching `dashboardRelations` from the db to skip permissions checking
- This is because we use the difference between `relations` and `items` to decide whether we show the "No access" or "No data" default dashboard
- Attach access policy to req object in `tupaia-web-server`
- Filter dashboard items by `accessPolicy`
- `central-server` checks you can access the item in _any_ of its countries, so we need a more specific check against the requested entity to make sure we're not showing you dashboard items that you can't access data for
=> WAITP-1366 Update dashboard permissions

packages/datatrak-web-server/src/routes/SurveyRoute.ts, packages/datatrak-web/src/components/Icons/RadioIcon.tsx, packages/datatrak-web/src/components/Icons/index.ts, packages/datatrak-web/src/features/Questions/AutocompleteQuestion.tsx, packages/datatrak-web/src/features/Questions/CheckboxQuestion.tsx, packages/datatrak-web/src/features/Questions/DateQuestion.tsx, packages/datatrak-web/src/features/Questions/DateTimeQuestion.tsx, packages/datatrak-web/src/features/Questions/EntityQuestion/EntityQuestion.tsx, packages/datatrak-web/src/features/Questions/EntityQuestion/SearchField.tsx, packages/datatrak-web/src/features/Questions/GeolocateQuestion/GeolocateQuestion.tsx, packages/datatrak-web/src/features/Questions/InstructionQuestion.tsx, packages/datatrak-web/src/features/Questions/QuestionHelperText.tsx, packages/datatrak-web/src/features/Questions/RadioQuestion.tsx, packages/datatrak-web/src/features/Questions/ReadOnlyQuestion.tsx, packages/datatrak-web/src/features/Questions/TextQuestion.tsx, packages/datatrak-web/src/features/Survey/Components/SurveyQuestionGroup.tsx, packages/datatrak-web/src/features/Survey/Screens/SurveyScreen.tsx, packages/datatrak-web/src/features/Survey/utils.ts, packages/datatrak-web/src/types/mui.d.ts, packages/types/src/types/requests/datatrak-web-server/SurveyRequest.ts, packages/ui-components/src/components/Inputs/Autocomplete.tsx
- Added support for option colours on radio inputs
- Added support and styling for question helper text
---
Helper texts
Radio input option colours
=> WAITP-1345:Core question updates

packages/database/src/migrations/20231012222503-DeleteLaosEOCAndCOVIDAuProjects-modifies-data.js
- Delete `laos_eoc` and `covidau` projects from db
I know we generally just do data migrations directly in the db these days, but this is pretty low priority and better kept as part of the rewrite branch I think.
=> WAITP-1448 Remove unused projects

packages/central-server/src/apiV2/surveyResponse.js
- Make **id** an optional field in the answers of survey questions in the central-server `surveyResponses` endpoint
In the saving of the survey response, it already handles the id being undefined but we are validating for an id in the surveyResponse questions.
This is the line where it handles the id not being set buildResponseRecord:
```
saveResponsestoDatabase.js line 73
...
return {
id: id || generateId(),
survey_id: surveyId,
user_id: user.id,
entity_id: entityId || entitiesByCode[entityCode].id,
data_time: dataTime,
start_time: startTime,
end_time: endTime,
timezone: timezone || getTimezoneNameFromTimestamp(timestamp),
assessor_name: user.fullName,
approval_status: approvalStatus,
};
=> WAITP-1349: Fix DataTrak survey submit

packages/devops/scripts/lambda/actions/delete_old_servers.py
Currently the DeleteAfter logic requires the check to run the same day as the DeleteAfter value.
If an instance is shut down overnight it can be missed by the deleter completely. This change just makes it consider all instances with DeleteAfter, not just those with a value of today.
Tested in `igor-test-deployment` lambda function.
=> Fix DeleteAfter

packages/central-server/src/database/models/User.js, packages/central-server/src/database/models/UserEntityPermission.js, packages/central-server/src/database/models/index.js
- Add ability to expire sessions for a user from `central-server`
- Trigger an expiry after a `user_entity_permission` change
This should only expire your access token for `tupaia_web`, once the `access_token` expires, the web session will automatically refresh using the `refresh_token` which means you get the updated `access_policy`
=> WAITP-1418 Permission revoking fixup

packages/admin-panel/src/pages/resources/SurveysPage.jsx, packages/central-server/src/apiV2/export/exportSurveys/cellBuilders/questionConfigCellBuilders/EntityConfigCellBuilder.js, packages/central-server/src/apiV2/import/importSurveys/ConfigImporter/processEntityConfig.js, packages/central-server/src/apiV2/import/importSurveys/Validator/ConfigValidator/EntityConfigValidator.js, packages/meditrak-app/app/entityMenu/EntityItem.js, packages/meditrak-app/app/entityMenu/EntityList.js
- Enable entity question config option `hideParentName` (workaround until projects are linked to surveys)
- Add option to set `hideParentName` in admin panel
---
=> MDEV-199: 'hideParentName' entity question config option

packages/tupaia-web/src/features/Visuals/View/DownloadFiles.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/Carousel.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/MultiPhotograph.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/MultiPhotographEnlarged.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/MultiPhotographPreview.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/index.ts, packages/tupaia-web/src/features/Visuals/View/View.tsx
- Added support `multiPhotograph` viz type in `tupaia-web`
- Fixed download files viz button styling to match the rest of the app
Note: I have just made it match in design to the current front-end, so there may be some design changes later, which is out of scope for this ticket
---
Carousel
Modal
Preview
=> WAITP-1241: Photo gallery

packages/types/generate-models.ts, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts
Reworked this one a bit: https://github.com/beyondessential/tupaia/pull/5098
Decided to add 2 more types for each table, Create and Update.
Create omits the `id` column.
Update has all columns be optional.
I also tested with setting all columns on the base type to required, since they will be still have `null` as an option if they are nullable. But that was a bit unweildy and felt like it was tying these types a bit too closely to their database implementation. Conceptually a nullable column is an optional field in almost all cases.
Also filtered out all the mvrefresh columns (eg. `m_row$`) from the type defs.
=> no-issue: Added <Model>Create and <Model>Update types

packages/datatrak-web-server/src/routes/SubmitSurvey/buildUpsertEntity.ts, packages/datatrak-web-server/src/routes/SubmitSurvey/processSurveyResponse.ts, packages/datatrak-web/src/features/Questions/EntityQuestion/utils.ts, packages/datatrak-web/src/features/Survey/SurveyContext/generateId.ts, packages/datatrak-web/src/features/Survey/SurveyContext/utils.ts, packages/types/src/schemas/schemas.ts, packages/types/src/types/index.ts, packages/types/src/types/models-extra/index.ts, packages/types/src/types/models-extra/survey/index.ts, packages/types/src/types/models-extra/survey/surveyScreenComponent.ts, packages/types/src/types/requests/datatrak-web-server/SurveyRequest.ts
@tcaiger and I paired on this and decided to move them into models-extra for now. Ideally we'd put them on the survey_screen_component model itself, but since the underlying config field is text for now, best to just define them separately.
=> no-issue: Move SurveyScreenComponent config types

packages/central-server/package.json, packages/central-server/src/apiV2/deleteAccount.js, packages/central-server/src/apiV2/middleware/emailAfterTimeout.js, packages/central-server/src/apiV2/requestCountryAccess.js, packages/central-server/src/apiV2/requestPasswordReset.js, packages/central-server/src/apiV2/utilities/emailVerification.js, packages/central-server/src/database/models/UserEntityPermission.js, packages/central-server/src/tests/scaffolding.test.js, packages/central-server/src/utilities/index.js, packages/server-utils/package.json, packages/server-utils/src/index.ts, packages/server-utils/src/sendEmail.ts, yarn.lock
We need to call this function from the `tupaia-web-server`, so migrating it over to `@tupaia/server-utils`
=> RN-1060: (task) Moved sendEmail to @tupaia/server-utils

packages/tupaia-web-server/package.json, packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/ExportDashboardRoute.ts, packages/tupaia-web-server/src/routes/index.ts, packages/tupaia-web/src/api/mutations/useExportDashboard.tsx, packages/types/src/types/requests/index.ts, packages/types/src/types/requests/tupaia-web-server/ExportDashboardRequest.ts, packages/types/src/types/requests/tupaia-web-server/index.ts, yarn.lock
Since we're adding custom functionality to this route as part of the email work, decided to port it over from web-config-server.
Also chose to rename the route from a generic `/pdf` to `/dashboards/:project/:entity/:dashboard/export`. Since this route is really just being used once, I feel it's nice if we capture the business case as part of the route interface.
=> RN-1060: (task) Added dashboards/:project/:entity/:dashboard/export route to tupaia-web-server

packages/devops/scripts/ci/validateBranchName.sh
- `api` is one of our suffixes. In some cases like `data-table-api` and `tupaia-web-api` we don't have an equivalent non `api` suffix so we don't catch invalid branch names
- e.g. `branch-data-table` would generate `branch-data-table-api` _and_ `branch-data-table-data-table-api` both of which match `*-data-table-api`
=> No issue: Update branch name validation script

packages/meditrak-app/app/assessment/QrCodeScreen.jsx, packages/meditrak-app/ios/Podfile.lock, packages/meditrak-app/ios/TupaiaMediTrak.xcodeproj/project.pbxproj, packages/meditrak-app/package.json, yarn.lock
As far as I can tell the only thing missing from Meditrak iOS that is in Meditrak Android was saving QR codes to camera roll.
Green build: https://appcenter.ms/orgs/Beyond-Essential/apps/Tupaia-MediTrak/build/branches/rn-963-meditrak-ios-features/builds/268
CI/CD issues will fixed in `bump-node-to-v16` branch
Screenshots in card.
=>  RN-963 Meditrak ios features

packages/tupaia-web/src/features/PDFExportDashboardItem/PDFExportDashboardItem.tsx
There was a bug causing whole dashboard export to always export a blank page in tupaia-web
=> no-issue: Fix whole dashboard export in tupaia-web

packages/tupaia-web-server/src/routes/MapOverlaysRoute.ts
When fetching map overlays from `central-server` we don't fetch in the context of an entity. So if a map overlay is available in both `DL` and `VU` for example, we will return it if you have appropriate permissions to either country. When we fetch for `tupaia-web-server` we want to filter specifically for the entity we're looking at.
- Add an additional permission filter for map overlays
---
=> WAITP-1224 Add an additional filter to MapOverlaysRoute

packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/EmailDashboardRoute.ts, packages/tupaia-web-server/src/routes/ExportDashboardRoute.ts, packages/tupaia-web-server/src/routes/index.ts, packages/tupaia-web-server/src/utils/downloadDashboardAsPdf.ts, packages/tupaia-web-server/src/utils/index.ts, packages/tupaia-web/src/api/mutations/index.ts, packages/tupaia-web/src/api/mutations/useEmailDashboard.tsx, packages/types/src/types/requests/index.ts, packages/types/src/types/requests/tupaia-web-server/EmailDashboardRequest.ts, packages/types/src/types/requests/tupaia-web-server/index.ts
Added endpoint to tupaia-web-server for emailing the dashboard export to all subscribed users in the mailing list.
There is a permissions check to ensure that the user requesting the email has appropriate permissions for that project.
=> RN-1060 (task): Added dashboards/:project/:entity/:dashboard/email route to tupaia-web-server

packages/admin-panel/src/pages/resources/SurveysPage.jsx, packages/admin-panel/src/widgets/InputField/registerInputFields.jsx, packages/central-server/src/apiV2/utilities/constructNewRecordValidationRules.js
- Add HTML validation settings for maxlength of text on survey name (no validation message will show until we have implemented inline validation messages)
- Add length validation for name when creating a survey in central-server
=> WAITP-1463: Cap survey name length at 50 characters

packages/datatrak-web/src/components/Tile.tsx, packages/datatrak-web/src/features/Leaderboard/Leaderboard.tsx, packages/datatrak-web/src/features/Leaderboard/LeaderboardTable.tsx, packages/datatrak-web/src/features/Leaderboard/UserRewardsSection.tsx, packages/datatrak-web/src/views/LandingPage/ActivityFeedSection/ActivityFeedMarkdownItem.tsx, packages/datatrak-web/src/views/LandingPage/RecentSurveysSection.tsx, packages/datatrak-web/src/views/LandingPage/SurveyResponsesSection.tsx
- Added loaders to dashboard sections (but not activity feed because is infinite scroll with own loader)
- Made leaderboard respond to height of viewport
---
13 inch laptop
15 inch laptop
Desktop
=> Responsive styling of dashboard leaderboard

packages/tupaia-web/src/features/Map/MapOverlaySelector/MobileMapOverlaySelector.tsx
- Use `dvh` instead of `vh` on mobile browser for height of overlay selector because of system specific infringements on the  useable viewport space on mobile devices
=> WAITP-1214: Fix height issue of overlay selector on mobile

packages/central-server/src/apiV2/surveys/GETSurveys.js, packages/datatrak-web-server/src/routes/SurveyRoute.ts, packages/datatrak-web/src/api/queries/useSurveys.ts
- `surveyQuestions` and `countryNames` are now optional and controlled by the `columns` query parameter
- They follow the same logic as any other column, they are included by default but filtered out if you are requesting specific columns only
=> WAITP-1496 Make questions optional in GETSurveys

packages/types/generate-schemas.ts, packages/types/src/schemas/schemas.ts, packages/types/src/utils/casing.ts
The camel-case keys type wasn't working correctly when being passed an array with nested objects. Reworked it to handle this, but as part of that had to change how we build the schemas to not include the util types. This is a win since we don't want schemas for those util types anyway.
=> no-issue: Fix camel case keys type

package.json, packages/admin-panel/package.json, packages/datatrak-web/package.json, packages/dhis-api/package.json, packages/e2e/package.json, packages/entity-server/src/routes/hierarchy/middleware/filter.ts, packages/indicators/src/Builder/AnalyticArithmeticBuilder/config/aggregation.ts, packages/lesmis/package.json, packages/meditrak-app/package.json, packages/report-server/src/reportBuilder/transform/transform.ts, packages/report-server/src/routes/FetchTransformSchemaRoute.ts, packages/tsutils/src/camelcaseKeys.ts, packages/tsutils/src/typeGuards.ts, packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web/package.json, packages/tupaia-web/stories/components/dateRangePicker.stories.tsx, packages/ui-chart-components/package.json, packages/ui-chart-components/src/components/Charts/PieChart.tsx, packages/ui-components/package.json, packages/ui-map-components/package.json, packages/web-config-server/package.json, packages/web-frontend/package.json, tupaia-packages.code-workspace, yarn.lock
It'd be good to get everything in the monorepo on the same version of typescript. Keeps things simpler.
=> no-issue: Bump monorepo to using TS 5.2.2 globally

packages/database/src/migrations/20231204032614-MakeEntityTypeNotNull-modifies-schema.js, packages/datatrak-web-server/src/__tests__/processSurveyResponse.test.ts, packages/datatrak-web/src/views/SurveySelectPage/SurveyCountrySelector.tsx, packages/datatrak-web/src/views/SurveySelectPage/SurveySelectPage.tsx, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts, packages/types/src/types/requests/datatrak-web-server/UserRequest.ts
The `type` column of the `entity` table being nullable makes typescript a bit more tricky in a few situations.
Having a `NULL` type is an invalid state, so ensuring this doesn't happen at the database level if useful.
=> no-issue: Make entity.type NOT NULL

packages/database/src/modelClasses/SurveyResponse.js, packages/datatrak-web/src/features/Leaderboard/LeaderboardTable.tsx, packages/datatrak-web/src/features/Leaderboard/UserRewardsSection.tsx, packages/datatrak-web/src/layout/UserMenu/MenuList.tsx, packages/datatrak-web/src/layout/UserMenu/UserInfo.tsx, packages/datatrak-web/src/views/AccountSettingsPage/DeleteAccountSection/UserDetails.tsx, packages/datatrak-web/src/views/LandingPage/SurveySelectSection.tsx, packages/tupaia-web/src/views/ForgotPasswordModal.tsx, packages/tupaia-web/src/views/LoginModal.tsx, packages/tupaia-web/src/views/ProjectsModal.tsx, packages/ui-components/src/features/Auth/ForgotPasswordForm.tsx, packages/ui-components/src/features/Auth/LoginForm.tsx, packages/ui-components/src/features/Auth/ResetPasswordForm/ResetPasswordSuccess.tsx, packages/web-frontend/src/containers/SearchBar/index.js
Various minor tweaks to Tupaia.org and DataTrak GUIs.
- Remove `background-color` hover effect on project button in navbar (at request of Felicity in internal communications).
- `getLeaderboard()` now returns `coconuts` count as a number, rather than a string. (Probably safe to assume this was the original intention anyway. This seems to be a quirk of Knex.js.)
- Fixed some misalignment in navbar.
- Correct some uses of “log in” vs “login” (ditto “log out” vs “logout”).
- More consistent casing (specifically sentence case) and punctuation in accordance with [Material UI style guide](https://m3.material.io/foundations/content-design/style-guide/ux-writing-best-practices).
- Non-breaking spaces between values and units.
- Refactor CSS styling of DataTrak leaderboard to improve readability. …
=> no-issue: Nitpicky GUI tweaks and tidy-ups

packages/datatrak-web/index.html
- Add Zendesk bot to datatrak when in production
---
Confirmation of mobile appearance
=> WAITP-1460: Add Zendesk bot to Datatrak Web

tupaia-packages.code-workspace
Added [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) and [Partial Diff](https://marketplace.visualstudio.com/items?itemName=ryu1kn.partial-diff) and as recommended extensions in the VS Code workspace file. Developer now prompted to install these when opening the monorepo as a workspace.
---
=> no-issue: Recommend REST Client & Partial Diff VSC extensions

packages/central-server/src/apiV2/changePassword.js, packages/datatrak-web/src/api/mutations/useResetPassword.ts, packages/datatrak-web/src/views/AccountSettingsPage/ChangePasswordSection/ChangePasswordForm.tsx
This PR is a small add-on to #5240. (Separate PR just to make reviewing easier.)
- When password change fails instead of simply saying “couldn’t update password”, show the server-supplied error message as a toast.
- Ditto with success message in API response.
---
=> WAITP-1467: Account Settings – Change Password 2 (Error Feedback)

packages/ui-components/package.json, packages/ui-components/src/components/HorizontalTree/ColumnFilter.jsx, packages/ui-components/stories/passwordStrengthBar.stories.js, yarn.lock
In this recent change (here) we removed react-scripts from the mono-repo. It turns out that storybook was relying on the babel-loader module that came with react-scripts and so storybook broke. This change is to explicitly add babel-loader to ui-components to fill the gap.
=> No Issue: Fix UI-Components Storybook

packages/admin-panel/src/pages/resources/DashboardMailingListsPage.jsx, packages/database/src/migrations/20231123022242-AddEmailAdminPermissionGroupsToDashboardMailingList-modifies-schema.js, packages/tsutils/src/typeGuards.ts, packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/tupaia-web-server/src/routes/EmailDashboardRoute.ts, packages/tupaia-web-server/src/routes/MapOverlaysRoute.ts, packages/tupaia-web/src/features/Dashboard/ExportDashboard/ExportSettings.tsx, packages/tupaia-web/src/features/Dashboard/ExportDashboard/MailingListButton.tsx, packages/types/src/schemas/schemas.ts, packages/types/src/types/models-extra/mapOverlay.ts, packages/types/src/types/models.ts, packages/types/src/types/requests/tupaia-web-server/DashboardsRequest.ts, packages/utils/src/object.js
Added a `email_admins_permission_groups` column to the `dashboard_mailing_list` table.
A user must have permissions to the country they're in to be able to see the Mailing list button and to send the email export.
=> RN-1073: Permissions for dashboard emailing

.github/PULL_REQUEST_TEMPLATE/release_template.md
Created a PR template for releases. After merging, this can (in theory) be invoked using https://github.com/beyondessential/tupaia/compare/master...dev?quick_pull=1&title=Release+20yy-w&labels=release&template=release_template.md, which will also automatically add the **release** tag.
If an open `master` ← `dev` PR already exists, GitHub will prompt you to view that one instead of creating a new one.
The [existing pull request template](https://github.com/beyondessential/tupaia/blob/dev/.github/pull_request_template.md) remains the default. Unfortunately, this needs to stay at the top level of the `./github` folder; moving it into the new `./github/PULL_REQUEST_TEMPLATE` folder makes it accessible only via a link with a `template` [query …
=> no-issue: PR template for releases

.eslintrc-js.json, package.json, packages/dhis-api/src/__tests__/DhisApi/helpers.js, packages/dhis-api/src/__tests__/DhisApi/testCodesToIds.js, packages/dhis-api/src/__tests__/DhisApi/testGetEventAnalytics.js, packages/dhis-api/src/__tests__/DhisApi/testGetEvents.js, packages/dhis-api/src/__tests__/DhisApi/testProgramCodeToId.js, packages/web-config-server/src/__tests__/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers.js, packages/web-config-server/src/__tests__/apiV1/measureBuilders/composePercentagePerOrgUnit.test.js, yarn.lock
I started migrating `central-server` from `mocha` to `jest`, and this is a prerequisite.
I also fixed an  `eslint` rule along the way
=> Bump jest-when to v3

package.json, packages/devops/configs/servers.conf, vite.config.js, yarn.lock
These changes reduce the amount of data transferred over the network on landing page from 10MB to 3MB
- Pre-compress JS files in vite build
- Configure NGINX to server zip JS files if they exist
- Add GZIP compression for json responses in NGINX config
---
=> WAITP-1527: GZIP JS files and json responses on tupaia and datatrak

packages/tupaia-web/src/components/FetchErrorAlert.tsx, packages/tupaia-web/src/components/index.ts, packages/tupaia-web/src/features/DashboardItem/DashboardItemContent.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapOverlayList.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapOverlaySelectorTitle.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MobileMapOverlaySelector.tsx, packages/tupaia-web/src/features/Map/MapOverlaysLayer/MapOverlaysLayer.tsx, packages/tupaia-web/src/features/Map/utils/useMapOverlayTableData.ts, packages/tupaia-web/src/utils/index.ts
- Show an error message and option to refetch when an error is caught for map overlay data\
- Don't show blank map overlay data when an error is caught
- Fix issue with map overlays reloading on open/close of the library
---
=> WAITP-1511: map overlay error handling

packages/datatrak-web/src/layout/UserMenu/MenuList.tsx
In medium and smaller size classes (where the hamburger menu appears as a drawer/sidebar) it would not dismiss when you clicked **Account settings**. This PR fixes that.
---
=> no-issue: Fix persistent DataTrak sidebar

packages/central-server/src/tests/apiV2/meditrakApp/permissionsBasedSync.fixtures.js, packages/central-server/src/tests/testUtilities/database/upsertRecord.js, packages/database/src/__tests__/changeHandlers/AnalyticsRefresher.fixtures.js, packages/database/src/migrations/20240108015220-UpdateSurveyProjectIdToBeNonNullable-modifies-schema.js, packages/database/src/testUtilities/buildAndInsertSurveys.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts
- Add migration to make survey project ID field not nullable
=> WAITP-1524: Make survey project_id field non-nullable

packages/datatrak-web/src/layout/UserMenu/MenuList.tsx
#5314 fixed the sidebar remaining after navigating to Account Settings, but introduced a new (worse!) fault where navigating to Account Settings from an in-progress survey becomes impossible because the confirmation modal to leave the survey is a child of the menu that #5314 programatically closed.
=> no-issue: Undo fix persistent DataTrak sidebar

packages/aggregator/global.d.ts, packages/aggregator/src/Aggregator.js, packages/aggregator/src/__tests__/Aggregator/Aggregator.test.js, packages/aggregator/src/__tests__/Aggregator/fixtures.js, packages/data-broker/.env.example, packages/data-broker/README.md, packages/data-broker/src/DataBroker/DataBroker.ts, packages/data-broker/src/__tests__/DataBroker/DataBroker.stubs.ts, packages/data-broker/src/__tests__/DataBroker/DataBroker.test.ts, packages/data-broker/src/services/Service.ts, packages/data-broker/src/types/results.ts
Splitting `DataBroker.pullMetadata` into two APIs, one for data elements and one for data group.
Splitting the Service APIs will be done in another PR
=> no-issue: Split DataBroker pullMetadata API per type

packages/admin-panel/src/autocomplete/ReduxAutocomplete.jsx, packages/admin-panel/src/widgets/InputField/registerInputFields.jsx
This makes it easier for users to add/remove from the existing selection rather than needing to remember it
=> no-issue: Set the initial selection of a multi-value autocomplete input

packages/tupaia-web/src/features/PDFExportDashboardItem/PDFExportDashboardItem.tsx, packages/tupaia-web/src/features/PDFExportDashboardItem/PDFExportHeader.tsx, packages/ui-components/src/__tests__/components/DateRangePicker/DateRangePicker.test.js, packages/ui-components/src/components/DateRangePicker/useDateRangePicker.tsx, packages/ui-components/src/components/PDFExportComponent.tsx, packages/web-frontend/src/tests/components/dateRangePicker.test.js
- PDF exports from Tupaia dashboard now show project logo that instead of the Tupaia logotype. (If no project logo is applicable and available, Tupaia logotype is shown as fallback.)
- Also refactored some the PDF layouts with some minor design tweaks.
While working on this one I found that the `px` values we use to define the A4 page sizes are incorrect, but correcting it will have ripple effects which I felt was too much to tack onto this PR.
=> RN-998: Logo on export

packages/datatrak-web/src/features/Questions/GeolocateQuestion/GeolocateQuestion.tsx, packages/datatrak-web/src/features/RequestProjectAccess/ProjectAccessForm.tsx, packages/datatrak-web/src/features/Survey/Components/SurveyReviewSection.tsx, packages/datatrak-web/src/theme/theme.ts, packages/datatrak-web/src/views/AccountSettingsPage/ChangePasswordSection/ChangePasswordForm.tsx
- Use `CssBaseline` overrides to set sensible defaults for `<fieldset>`, rather than repeating the same CSS code for every use.
- Set `img` to use block display by default. This one’s slightly more opinionated—happy to discuss/remove.
=> no-issue: Globally reset `<fieldset>` styling

packages/tsutils/src/typeGuards.ts
When `assertIsNotNullish` assertion fails, output whether it received `null` or `undefined`.
=> no-issue: More verbose `assertIsNotNullish` error message

packages/ui-chart-components/README.md, packages/ui-components/README.md, packages/ui-map-components/README.md
- `ui-map-components` README actually talked about `ui-chart-components`. Fixed.
- The updated READMEs referenced the wrong directory when describing where Storybooks looks. Fixed.
- Various minuscule quality-of-life and readability improvements.
=> no-issue: Update UI component package READMEs

packages/tupaia-web-server/src/routes/EmailDashboardRoute.ts
Switched to fetching entities from entity-server as central-server permission checking was incorrect for project entities.
=> hotfix: Fix whole dashboard export email

packages/data-broker/src/services/weather/WeatherService.ts
The current error is very unclear:
```
API error 500: Error in transform[1]: API error 500: Internal server error: Cannot read properties of null (reading 'coordinates')
```
=> no-issue: Improve error messaging in weather-api when the entity being fetched does not have a point recorded

scripts/bash/pm2startInline.sh
- Changed legacy `start-dev` instruction to `start-stack`
- Set parameters with underline (GitHub sanitises `<u>` so no inline preview 🥲) and verbatim commands in **`bold`**
---
Before:
After:
=> no-issue: Fix `start-stack` help text

packages/tupaia-web/src/layout/UserMenu/MenuList.tsx, packages/tupaia-web/src/layout/UserMenu/UserMenu.tsx
- Bump <kbd>Submit data</kbd> below <kbd>View projects</kbd> to un-break muscle memory
- Make external links (namely <kbd>Submit data</kbd> and <kbd>Help centre</kbd>) open in a new tab
The props for `BaseMenuItem` probably shouldn’t be any, but the typing around here is a little fragile. Would be nice if we could tighten things up at some point, but I decided against refactoring this time around.
=> RN-1171: Tweak Tupaia `UserMenu`

packages/datatrak-web/src/features/RequestProjectAccess/ProjectAccessForm.tsx
- In `ProjectAccessForm`, when the form state validity changes, the button spacing would jump around. This PR fixes that.
- Also some refactors, copied over from #5268: use CSS logical properties where appropriate and remove a redundant `<div>`
---
These screenshots show the **old** behaviour. Notice how the buttons are differently spaced in each screenshot.
=> no-issue: Fix minor button spacing jank

packages/types/src/types/models-extra/dashboard-item/charts/common.ts, packages/ui-chart-components/src/utils/getChartTableData.tsx
- Fix issue where no data in the table was being infinitely re-rendered due to not being memoized
=> Fix issue with non-memoized table data

packages/datatrak-web/src/layout/UserMenu/MenuList.tsx, packages/tupaia-web/src/layout/UserMenu/UserMenu.tsx
- Updated <kbd>Help centre</kbd> links to <kbd>Support centre</kbd>, which now point to Zendesk instead of Slab.
=> RN-1123: Update Tupaia Web support link

packages/meditrak-app/appcenter-post-clone.sh
Since #5123, the monorepo has used [the same version of Node](https://github.com/beyondessential/tupaia/blob/dev/.nvmrc) as `meditrak-app`, which makes this workaround redundant
- Removed workaround in `appcenter-post-clone.sh` which overwrote `.nvmrc` in monorepo root
=> no-issue: Remove MediTrak/nvm workaround 

packages/database/src/migrations/20240226202900-MigrateDisplayOnEntityConditionsToEntityAttributeFilters-modifies-data.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models-extra/dashboard-item/common.ts, packages/web-config-server/src/apiV1/dashboards.js
- Removed `displayOnEntityConditions` config from dashboard items types
- Updated `web-config-server` to not refer to `displayOnEntityConditions`
- Migrated any cases of `displayOnEntityConditions` to use `attributes_filters` on `dashboard_relation`
Note: the `type` for `displayOnEntityConditions` allowed for filters other than `attributes` filters, but there were no cases of these in the database so I ignored that option
=> RN-1157: Remove displayOnEntityConditions

packages/api-client/package.json, yarn.lock
- This PR addresses the #4282 Dependabot PR of **high** severity
- Major version number does not change, and indeed [qs’s changelog](https://github.com/ljharb/qs/blob/main/CHANGELOG.md) suggests there have been no breaking changes
=> RN-1112: Bump `qs` to 6.12.0

packages/central-server/src/tests/scaffolding.test.js, packages/central-server/src/tests/testUtilities/database/resetTestData.js, packages/data-broker/jest.setup.ts, packages/database/src/testUtilities/clearTestData.js, packages/database/src/testUtilities/index.js, packages/tupaia-web-server/package.json
- Removed old `clearTestData` util
- Updated `clearAllTestData` to be called `clearTestData`
- Updated `tupaia-web-server` to test with test db instead of real db
=> RN-1223: Update clearTestData to remove all test database data

packages/devops/scripts/deployment/setupGoldMaster.sh
We need to bump our base image to a newer version of ubuntu in order to run Node 20.
=> no-issue: Update setupGoldMaster.sh to correctly install on ubuntu 22+

packages/devops/scripts/deployment/buildDeployablePackages.sh, packages/devops/scripts/deployment/setupGoldMaster.sh, scripts/bash/downloadEnvironmentVariables.sh
Switch to pulling from bitwarden. We have to use `jq` to parse the responses from bitwarden cli since we can't filter the query.
=> RN-952: Switch to bitwarden for pulling .env vars

packages/utils/package.json, yarn.lock
- Was originally going to do this as part of ticket RN 1112, but but turns out #4665 already addressed the vulnerability (hence not linking the ticket)
- [validator’s changelog](https://github.com/validatorjs/validator.js/blob/master/CHANGELOG.md) has only had two releases since 13.7 and seems to have only minor improvements with no breaking changes, so may as well go ahead
=> no-issue: Bump `validator` to 13.11.0

packages/server-utils/package.json, packages/web-config-server/package.json, yarn.lock
This supersedes the #5488 Dependabot PR, which addresses [an alert of **critical** severity](https://github.com/beyondessential/tupaia/security/dependabot/36).
According to the [changelog](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md) `server-utils` should see only bug fixes.
`web-config-server` is coming from 4.6, so _may_ see a few more changes, but I didn’t see anything drastic in the [changelog](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md).
=> RN-1112: Bump `nodemailer` to ≥6.9.9

packages/meditrak-app/package.json, yarn.lock
This PR is identical to the #5490 Dependabot PR, which resolves [an alert of **moderate** severity](https://github.com/beyondessential/tupaia/security/dependabot/276).
The only reason for this PR because Dependabot’s feature branch names don’t pass our CI validation.
=> RN-1112: Bump `react-native-document-picker` to 9.1.1

packages/datatrak-web/src/api/queries/useActivityFeed.ts
#5508 renamed `useCurrentUser` to `useCurrentUserContext`, but I missed an import.
Not sure how it passed status checks in the PR, but this fixes that 😅
=> hotfix: Fix import in DataTrak test

tupaia-packages.code-workspace
Sets Prettier as the default formatter in the workspace, regardless of what your user settings are
We recommend _format on save_ in the repo setup instructions and in the README, so I thought about also enforcing it, but that felt a little too opinionated
=> no-issue: Set Prettier as default formatter in workspace

.github/workflows/cd.yaml, .github/workflows/ci.yaml, .github/workflows/e2e.yaml, tupaia-packages.code-workspace
We were getting warnings to upgrade these as node 16 is being deprecated
=> no-issue: Bump GHA versions to latest

packages/dhis-api/src/types.js
I think this got accidentally renamed as part of changing from `<model>Type` -> `<model>Record`
=> hotfix: Fixup broken dhis2 api endpoint for trackedEntityTypes

.gitattributes
Marks the `schemas.ts` file as generated, which makes GitHub not render its diff by default. (Not listing `yarn.lock` because GitHub already does this for the major package managers by default)
(Also marks Markdown files as documentation, which excludes it from the bar chart of the repo’s language makeup in GitHub’s sidebar)
=> no-issue: Don’t render schema diffs by default

packages/auth/src/__tests__/userAuth.test.js, packages/auth/src/userAuth.js, packages/meditrak-app-server/src/__tests__/__integration__/ChangePasswordRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/UserRewardsRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/socialFeed/SocialFeedRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/PushChangesRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/pullChanges/ChangesMetadataRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/pullChanges/CountChangesRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/pullChanges/PullChangesRoute.test.ts
- Removed refresh token from access token.
Note: After discussion with @rohan-bes it was agreed that apart from this change, our current approach for auth is fine.
=> fix(security): RN-1084: Remove refresh token from access token

.gitattributes
Marks `yarn.lock` as a generated file, making GitHub hide its diffs _by default_ when reviewing.
=> repo: mark lockfile as generated

packages/database/src/configureEnv.js, packages/server-utils/src/configureDotEnv.ts, packages/types/generate-models.ts
- Turns out the first var is used if there is double up. We want it to use the last var, and only use the package env file if it exists.
=> tweak(environment): RN-1225: Override with local env if exists

packages/admin-panel/package.json, packages/admin-panel/src/VizBuilderApp/components/PreviewOptions/DateRangeField.jsx, yarn.lock
We’ve had trouble with using helpers from **tsusils** in frontend packages, which crashes in remote deployments (but doesn’t affect devs locally).
Accidentally snuck one in #647 which is causing VizBuilder to immediately crash the entire Admin Panel. forcing a reload.
Fixes the issue described above by not using tsutils in admin-panel. Also removed the dependency for good measure (it was the only usage in the package).
=> fix(vizBuilder): vizBuilder crashes Admin Panel

packages/tsutils/src/datetime.ts
Just removed `^` and `$` from the regex pattern I was using to validate date parameters. Specifically, **it’s the `$` that breaks it**, but I cannot for the life of me see why 😕
Strictly speaking, this now allows anything that has a _substring_ in the `YYYY-MM-DD` format to pass validation, but these inputs aren’t ever hand-written anyway (as far as I know). Ultimately it would result in another error saying that the date is null (since the server would then fail to parse it)—just a slightly less helpful error message.
=> fix: `/report` endpoint date validation

packages/central-server/src/apiV2/middleware/handleError.js, packages/server-boilerplate/src/utils/handleError.ts, packages/utils/src/errors.js, packages/web-config-server/src/utils/handleError.js
It's very noisy and difficult to silence. I'll do a check to make sure we still get a useful error when routes fail, but aside from that I don't think the logging was really doing much for us (and had a lot of false positives).
=> tweak: Remove LoggedError class

packages/datatrak-web/src/features/Survey/Screens/SurveyScreen.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/reducer.ts
Now shows the `detail` field of a question on `SurveyScreen` under the existing heading.
---
=> fix(datatrakWeb): show question detail when first question is an instruction

packages/types/src/schemas/schemas.ts, packages/types/src/types/models-extra/dashboard-item/common.ts, packages/types/src/types/models-extra/mapOverlay.ts, packages/ui-map-components/src/utils/markerColors.ts
1. [dashboard item: reference.text should be supported](https://beyondessential.slack.com/archives/C02649511JM/p1715659292774199)
2. [spectrum map overlay: scaleColorScheme should not be mandatory](https://beyondessential.slack.com/archives/C02649511JM/p1715150587907049)
=> fix(vizBuilder): Fixed up a couple presentation config schema options

.github/workflows/ci.yaml
Occasionally `meditrak-app-server` tests might run for hours in GitHub Actions because Jest doesn’t exit properly. (Likely an async-related problem.)
This is a band-aid fix. If the error happens, CI will fail due to timeout—just manually rerun the test.
=> ci: fix never-ending `run_tests`

packages/admin-panel/src/table/DataFetchingTable/Cells.jsx, packages/admin-panel/src/table/DataFetchingTable/DataFetchingTable.jsx, packages/admin-panel/src/table/reducer.js
- Fixed issue where pagination changes caused infinite re-render on tables. Now manually sets page when filters, sorting etc change for table. This is because react-table has it's own table state and we also have pagination stored in the redux store.
- Fix stuck focus effect when table changes
- Reset table sorting when table is reinitialised
=> fix(adminPanel): Fix re-render issue on tables

packages/data-broker/src/__tests__/services/weather/WeatherService.stubs.ts, packages/database/src/DatabaseModel.js
Renamed `createTypeInstance` → `createRecordInstance`
=> tweak(database): fix straggling “type” symbol name to use “record”

packages/ui-chart-components/src/components/Reference/ChartTooltip.tsx, packages/ui-chart-components/src/utils/getChartTableData.tsx
@SimonCarryer found this issue when building vizes with where date picker and the X axis didn't have the same period granularity. In this case you can override the default formatting using `periodTickFormat` but that formatting wasn't being respected by the data table (or the hover tooltip).
=> fix(viz): Ensure that the `Date` column in the viz table is formatted the same as the X axis

packages/meditrak-app/app/assessment/selectors.jsx
Only instantiate the expression parsers once rather than for each evaluation. Almost all the changes are auto-formatting and whitespace.
=> fix(meditrak): RN-1316: Improve responsiveness when filling out a survey with lots of conditional or calculated questions

packages/meditrak-app/app/version/isBeta.jsx
The latest meditrak master build has the emulator base url as the banner:
Decided to just remove the default value since it's just for convenience anyway (devs can just use .env vars)
=> fix(meditrak): HOTFIX: Remove banner for production meditrak builds

packages/admin-panel/src/autocomplete/ReduxAutocomplete.jsx, packages/admin-panel/src/routes/projects/projects.js, packages/admin-panel/src/routes/surveys/optionSets.js, packages/admin-panel/src/routes/surveys/surveyResponses.js, packages/admin-panel/src/routes/surveys/surveys.js, packages/admin-panel/src/routes/users/accessRequests.js, packages/admin-panel/src/routes/users/users.jsx, packages/admin-panel/src/routes/visualisations/dashboardMailingLists.js, packages/admin-panel/src/routes/visualisations/dashboardRelations.js, packages/admin-panel/src/routes/visualisations/mapOverlays.jsx, packages/admin-panel/src/widgets/InputField/InputField.jsx, packages/admin-panel/src/widgets/InputField/JsonEditor.jsx, packages/admin-panel/src/widgets/InputField/registerInputFields.jsx, packages/ui-components/src/components/Inputs/ImageUploadField.tsx, packages/ui-components/src/components/Inputs/InputLabel.tsx, packages/ui-components/src/components/Inputs/RadioGroup.tsx, packages/ui-components/src/components/Inputs/TextField.tsx
- Change secondary labels to be tooltips
- Autogenerate min/max length validation text if values are set
---
=> tweak(adminPanel): RN-1187: Move secondary labels to tooltips

packages/central-server/src/apiV2/middleware/handleError.js, packages/server-boilerplate/src/utils/handleError.ts, packages/web-config-server/src/utils/handleError.js
Allows us to see the original stack trace which helps debugging
=> tweak(logging): Log original error in handleError middleware

packages/admin-panel/src/VizBuilderApp/components/DataLibrary/TransformDataLibrary.jsx
- Fixed issue where adding. removing, and reordering transforms in the viz builder causes duplicate IDs and buggy behaviours
=> fix(vizBuilder): Fix duplicate ID issue on viz builder transforms

packages/admin-panel/src/VizBuilderApp/api/queries/useEntities.js
- Fix issue where filter for entities was not stringified so didn't fetch last used entity
=> fix(vizBuilder): Fix pre-filling entities not working

packages/admin-panel/src/importExport/ImportModal.jsx, packages/lesmis/src/views/AdminPanel/routes/helpers/getImportConfigs.js
- Fix issue where file name was being reset incorrectly on admin panel import modal when closing and reopening the modal
=> fix(adminPanel): Stop no file message showing between import views

packages/datatrak-web/src/features/Survey/SurveyContext/utils.ts
- Fix issue where admin panel saves visibility criteria answers as strings, but we compare the absolute value. Changed to converting everything to a string to compare.
=> fix(datatrakWeb): NOTUP-710 Make visibility criteria comparisons convert to strings

packages/meditrak-app/ios/TupaiaMediTrak/Info.plist
Explicitly link to MediTrak app with `tupaiameditrak://` URL scheme
=> feat(meditrak): RN-1219: `tupaiameditrak://` URL scheme

packages/database/scripts/setupNewDatabase.sh
Some of these commands can print secrets in plaintext, which can be easily accidentally shared in screenshots or while screen sharing.
=> tweak(scripts): hide `setupNewDatabase.sh`’s executed commands

packages/devops/configs/nginx-template/servers.template.conf
Update nginx config to regularly update the cached ip address for the default frontend
=> fix(nginx): RN-1365: Fix occasional 504 Gateway Timeout errors

packages/central-server/src/apiV2/GETHandler/helpers.js, packages/central-server/src/apiV2/dashboardRelations/GETDashboardRelations.js
- In a recent change [here](https://github.com/beyondessential/tupaia/commit/18b4128b7bed133344ffacfaf07f186f71e35583) there was a change to how getDbQueryCriteria works in the api Getter class to include the custom column selectors which caused an error in the dashboard relations tab query. The custom selector for dashboard relations is used in an unknown number of places so it doesn't seem safe to edit the format of the custom selector. So I have opted to overwrite the getDBQueryCriteria method for GetDashboardRelations instead.
=> fix(adminPanel): Fix admin panel dashboard relations table

packages/admin-panel/src/routes/users/permissions.js
In the admin panel, permissions can be bulk created by selecting multiple entities when filling out the create permission group form. However when editing a permission group, the user is in the context of a single permission group so the ui should only allow for selecting one entity.
=> fix(adminPanel): RN-1190: Fix permissions editing

packages/admin-panel/src/routes/users/users.jsx, packages/admin-panel/src/table/DataFetchingTable/DataFetchingTable.jsx
**Fix Lesmis Admin Panel Crash**
The action label can be null if the translation for admin.action in lesmis is blank and this causes the Header field of the action column to be null which creates an error in react query. I have fixed it by simply moving the Action label fallback to account for null values.
An alternative fix which I considered was to change the translation util function in lesmis to return the translation key as a string rather than null but it seemed like too wide of a change for a release fix.
**Revert User Countries Field To Single Select**
Revert the User Countries field back to being a dropdown select rather than a checkbox multi select. The scope of the ticket was to update the multi select drop downs to be checkbox multi selects but this field was accidentally …
=> fix(lesmis): RN-1335: Fix DataFetchingTable Action Label

packages/admin-panel/src/table/DataFetchingTable/DataFetchingTable.jsx
- Fix tables not reloading on successful delete of data
=> fix(adminPanel): NOTUP-722: Refresh data on admin panel on successful delete

packages/admin-panel/src/table/DataFetchingTable/DataFetchingTable.jsx
- If no sorting is defined on the data fetching table, use the default sorting (another classic issue with redux I think)
=> fix(adminPanel): RN-1380: Use default sorting where applicable

packages/database/src/__tests__/changeHandlers/TaskCompletionHandler.test.js, packages/database/src/changeHandlers/TaskCompletionHandler.js, packages/database/src/migrations/20240715234341-AddTaskSurveyResponseId-modifies-schema.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts
- Added `survey_response_id` column to `task` table
- Updated task change handler to apply `survey_response_id` to completed task
=> feat(datatrakWeb): RN-1339: Link survey responses to tasks

packages/datatrak-web-server/src/routes/SingleSurveyResponseRoute.ts, packages/datatrak-web/src/features/Survey/SurveyContext/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/reducer.ts, packages/datatrak-web/src/features/Tasks/TasksTable/ActionButton.tsx, packages/datatrak-web/src/utils/index.ts, packages/datatrak-web/src/utils/usePrimaryEntityLocation.ts, packages/datatrak-web/src/views/SurveyResponsePage.tsx, packages/types/src/types/requests/datatrak-web-server/SingleSurveyResponseRequest.ts, packages/types/src/types/requests/datatrak-web-server/SurveyRequest.ts
- Add ability to set the primary entity in location state for a survey
- Set the primary entity on the Complete tasks action
- Fetch and include the primary entity on the survey response page 
---
=> feat(datatrak): RN-1314: Auto populate entity question

packages/admin-panel/src/routes/surveys/surveys.js, packages/central-server/src/apiV2/import/importSurveys/ConfigImporter/ConfigImporter.js, packages/central-server/src/apiV2/import/importSurveys/ConfigImporter/processUserConfig.js, packages/datatrak-web-server/src/app/createApp.ts, packages/datatrak-web-server/src/routes/PermissionGroupUsersRoute.ts, packages/datatrak-web-server/src/routes/index.ts, packages/datatrak-web-server/src/utils/getFilteredUsers.ts, packages/datatrak-web-server/src/utils/index.ts, packages/datatrak-web/src/__tests__/features/Questions/UserQuestion.test.tsx, packages/datatrak-web/src/api/queries/index.ts, packages/datatrak-web/src/api/queries/usePermissionGroupUsers.ts, packages/datatrak-web/src/components/Autocomplete.tsx, packages/datatrak-web/src/components/index.ts, packages/datatrak-web/src/features/Questions/AutocompleteQuestion.tsx, packages/datatrak-web/src/features/Questions/UserQuestion.tsx, packages/datatrak-web/src/features/Questions/index.ts, packages/datatrak-web/src/features/Survey/Components/SurveyQuestion.tsx, packages/datatrak-web/src/features/Tasks/AssigneeInput.tsx, packages/types/src/schemas/schemas.ts, packages/types/src/types/models-extra/survey/surveyScreenComponent.ts, packages/types/src/types/requests/datatrak-web-server/UsersRequest.ts, packages/types/src/types/requests/datatrak-web-server/index.ts, packages/types/src/types/requests/index.ts
- Added user question type to Datatrak Web
- Added `PermissionGroupUsers` route to `datatrak-web-server`
---
=> feat(datatrakWeb): RN-1362: Datatrak Web User question type

packages/central-server/src/apiV2/index.js, packages/central-server/src/apiV2/taskComments/CreateTaskComment.js, packages/central-server/src/apiV2/taskComments/index.js, packages/central-server/src/apiV2/tasks/EditTask.js, packages/central-server/src/tests/apiV2/taskComments/CreateTaskComment.test.js, packages/central-server/src/tests/apiV2/tasks/EditTask.test.js, packages/datatrak-web/src/api/mutations/index.ts, packages/datatrak-web/src/api/mutations/useCreateTaskComment.ts, packages/datatrak-web/src/api/mutations/useEditTask.ts, packages/datatrak-web/src/components/Icons/ArrowLeftIcon.tsx, packages/datatrak-web/src/components/Icons/index.ts, packages/datatrak-web/src/features/Tasks/CommentsCount.tsx, packages/datatrak-web/src/features/Tasks/TaskDetails/TaskComments.tsx, packages/datatrak-web/src/features/Tasks/TaskDetails/TaskDetails.tsx, packages/datatrak-web/src/features/Tasks/TaskTile.tsx, packages/datatrak-web/src/views/LandingPage/TasksSection.tsx, packages/datatrak-web/src/views/Tasks/TaskDetailsPage.tsx
- Updated styling of task details view to have separate save button for comments
- Added 'back' button to task details page, per the design
- Added link to task tiles on landing page
- Added endpoint for creating task comments via parent task `id`
- Changed handling of successful task save to not navigate back anymore, per discussion with Georgia and Felicity
---
=> tweak(datatrakWeb): RN-1331: Update to task details/comments

packages/tupaia-web/src/features/Dashboard/ExportDashboard/SelectVisualisations.tsx
- updated tool tip text to say to 'PDF export unavailable' instead of 'PDF export coming soon'
---
=> tweak(tupaiaWeb): RN-1394: Update tool tip for visualisation export

packages/meditrak-app/android/app/build.gradle, packages/meditrak-app/android/build.gradle, packages/meditrak-app/ios/TupaiaMediTrak.xcodeproj/project.pbxproj, packages/meditrak-app/package.json
Releasing [RN-1389 ](https://linear.app/bes/issue/RN-1389/bump-meditrak-target-android-version-to-14-api-level-34) to production since we're potentially skipping next release and this is time sensitive
Note that I don't think this was originally branched off `master` but I don't think it matters since it doesn't seem to contain any changes from `dev` that don't already exist on `master` (as far as I can tell)
=> tweak(meditrak): HOTFIX: Bump MediTrak target Android version to 14 (API level 34)

packages/central-server/src/dhis/DhisChangeValidator.js, packages/central-server/src/tests/dhis/DhisChangeValidator.test.js, packages/database/src/testUtilities/buildAndInsertSurveyResponses.js
- Updated `DHISChangeValidator` to create `delete` entries in `dhis_sync_queue` for outdated survey responses and their associated answers
=> tweak(adminPanel): RN-1274: Remove outdated survey responses and associated answers from DHIS via sync queue

packages/database/src/migrations/20240818212910-removeMapOverlayConfigFromPgNotify-modifies-schema.js
We often hit the max payload for pg notify when trying to edit map overlay records due to their large config even though none of the change handlers are interested in the changes to the config field. This change filters out the config field from the notifier updates.
=> fix(adminPanel): RN-1424: Fix max payload error when saving map overlay records

packages/api-client/src/connections/EntityApi.ts, packages/database/src/modelClasses/Entity.js, packages/datatrak-web-server/src/routes/EntityDescendantsRoute.ts, packages/datatrak-web/src/features/EntitySelector/EntitySelector.tsx, packages/entity-server/src/__tests__/__integration__/EntityDescendantRoutes.test.ts, packages/entity-server/src/routes/hierarchy/EntityDescendantsRoute.ts, packages/entity-server/src/routes/hierarchy/middleware/attachCommonEntityContext.ts, packages/entity-server/src/routes/hierarchy/types.ts, packages/server-boilerplate/src/models/Entity.ts, packages/types/src/types/requests/datatrak-web-server/EntityDescendantsRequest.ts
- Allow setting `pageSize` param for entity descendants
- Limit entity descendants in Datatrak to 100
Note: This is to fix an issue where if a survey's primary entity filter is type `household`, for example, it will load all results, which can be upwards of 10000 results. This was causing a performance issue
=> fix(datatrakWeb): Limit entity results to 100

packages/auth/package.json, packages/utils/package.json, yarn.lock
- Updated version of `jsonwebtoken` as per [dependabot PR](https://github.com/beyondessential/tupaia/pull/4290)
Changelog can be found [here](https://github.com/Keats/jsonwebtoken/blob/master/CHANGELOG.md)
=> deps(security): RN-1096: Update version of `jsonwebtoken`

packages/central-server/src/dhis/pushLatest.js, packages/central-server/src/dhis/pushers/entity/TrackedEntityPusher.js, packages/central-server/src/externalApiSync/ExternalApiSyncQueue.js
- On error getting tracked entity type, throw a more descriptive error
- Mark bad requests in db, and after 8 bad requests, mark record as dead letter
=> tweak(centralServer): RN-1351: Handle bad DHIS2 sync requests

packages/admin-panel/src/VizBuilderApp/api/mutations/useUploadTestData.js, packages/admin-panel/src/VizBuilderApp/api/queries/useMapOverlays.js, packages/admin-panel/src/VizBuilderApp/api/queries/useProjects.js, packages/admin-panel/src/api/mutations/useLogout.js, packages/lesmis/src/api/queries/useEntitiesData.js, packages/lesmis/src/api/queries/useUser.js
- updated some mutations and queries to meet react-query v4 syntax
=> fix(adminPanel): Miscellaneous Bug fixes (Tiny)

packages/datatrak-web/src/constants/url.ts, packages/datatrak-web/src/features/Survey/Components/SurveySideMenu/SurveySideMenu.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveyLayout.tsx, packages/datatrak-web/src/features/Tasks/TaskTile.tsx, packages/datatrak-web/src/features/Tasks/TasksTable/ActionButton.tsx, packages/datatrak-web/src/utils/index.ts, packages/datatrak-web/src/utils/useLocationState.ts, packages/datatrak-web/src/views/Tasks/TaskDetailsPage.tsx
Update autofilling entity when completing a task so that the entity code is stored in the url rather than in route state so that it persists across pages.
[Here](https://linear.app/bes/issue/RN-1314/create-link-between-complete-task-and-the-actual-survey#comment-a10fa181) is the original issue
=> fix(datatrak): RN-1314: Update autofilling entity when completing a task

packages/datatrak-web/src/features/Survey/SurveyContext/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/reducer.ts, packages/datatrak-web/src/features/Survey/SurveyContext/utils.ts, packages/datatrak-web/src/features/Survey/utils/useSurveyResponseWithForm.ts
- Make `initialiseFormData` not run on resubmit screens
- Make code generator values get created when in resubmit mode and no saved answer
=> fix(datatrakWeb): RN-1483: Fix issue with code gen replacing saved values on resubmit

packages/datatrak-web/src/views/LandingPage/LandingPage.tsx, packages/datatrak-web/src/views/LandingPage/RecentSurveysSection.tsx
- Shift layout on larger screens when less than 2 recent surveys
---
=> tweak(datatrakWeb): RN-1426: Shift activity feed upwards when less than 2 recent surveys

packages/admin-panel/src/importExport/ExportButton.jsx
This change was mistake since some downloads are json and some are xlsx. This PR is to rollback the change and then in the next PR I will explicitly set the file type with the file name for each of the downloads see https://github.com/beyondessential/tupaia/pull/5948
=> fix(adminPanel): RN-1496: Roll back download button change

packages/central-server/package.json, packages/central-server/src/createApp.js, packages/server-boilerplate/package.json, packages/server-boilerplate/src/connections/ApiConnection.ts, packages/server-boilerplate/src/orchestrator/api/ApiBuilder.ts, packages/server-boilerplate/src/orchestrator/auth/AuthConnection.ts, packages/server-boilerplate/src/orchestrator/routes/LoginRoute.ts
- Forward client ip address to central-server when logging in on orchestration servers
- Add a list of trusted proxies on orchestration and central servers to prevent spoofing of ip address
=> fix(auth): RN-1108: Securely read client ip for rate limiting

packages/central-server/src/database/meditrakSyncQueue/MeditrakSyncQueue.js, packages/database/src/changeHandlers/AnalyticsRefresher.js, packages/database/src/changeHandlers/ChangeHandler.js, packages/database/src/changeHandlers/TaskAssigneeEmailer.js, packages/database/src/changeHandlers/entityHierarchyCacher/EntityHierarchyCacher.js, packages/meditrak-app-server/src/sync/SyncableChangeEnqueuer.ts
- Fixed change handler processing logic to allow for change handlers to run in parallel
- Updated logging for change handlers
---
=> fix(centralServer): RN-1294: Allow parallelisation of change handlers

packages/types/src/schemas/schemas.ts, packages/types/src/types/models-extra/mapOverlay.ts, packages/ui-map-components/src/components/Table/getMapTableData.tsx, packages/ui-map-components/src/types/series.ts
This PR is to update the map overlay config to support hiding measures of data from the popup and map table
- fix type for hideFromPopup so that it can be set in the viz builder
- add support hideFromTable map overlay config
=> tweak(tupaiaWeb): RN-1370: Add support for hiding map overlay data from map overlay table

packages/data-api/src/utils.ts
When sum calculations are run on data for arithmetic questions, the values were not being cast to float and so were being concatenated instead of summed. Data for Arithmetic questions was intentionally not being casted because it used to be possible to have expressions as return values but since this is no longer possible, it is now safe to cast to float. The query below was run to confirm that all Arithmetic data are valid floats.
```
SELECT value
FROM analytics
WHERE type = 'Arithmetic'
AND value !~ '^[+-]?[0-9]*\.?[0-9]+([eE][+-]?[0-9]+)?$';
```
**Note: since this is a production hotfix I opted not to add additional casting in the aggregator sum functions as that would increase regression risk.**
=> fix(tupaiaWeb): RN-1512: Fix broken arithmetic visuals

packages/datatrak-web/src/views/AccountSettingsPage/RequestCountryAccessSection/RequestCountryAccessForm.tsx
- Replace form with message if user already has access to all the countries in the project
---
=> tweak(datatrak): RN-1451: DataTrak request country access form

packages/datatrak-web/src/features/MobileSelectList/ListItem.tsx, packages/datatrak-web/src/features/Survey/Components/CopySurveyUrlButton.tsx, packages/datatrak-web/src/features/Survey/Components/MobileSurveyHeader.tsx, packages/datatrak-web/src/features/Survey/Components/SurveySideMenu/SurveySideMenu.tsx, packages/datatrak-web/src/features/Survey/Screens/SurveyReviewScreen.tsx, packages/datatrak-web/src/layout/StickyMobileHeader.tsx, packages/datatrak-web/src/views/AccountSettingsPage/AccountSettingsPage.tsx, packages/datatrak-web/src/views/LandingPage/ActivityFeedSection/MobileActivityFeed.tsx, packages/datatrak-web/src/views/SurveySelectPage/MobileTemplate.tsx
Setting myself up to begin work on RN-1465, but spotted this opportunity for a more versatile interface for `<StickyMobileHeader>`
Instead of passing it a `title` prop (which shadows the standard `title` attribute that most HTML elements can take), now just takes children and renders them as the title
Semantically, this makes a touch more sense—especially as there are some cases where we were giving an icon to the `title` prop
Small readability bonus: shallower indents!
=> refactor(datatrak): update `<StickyMobileHeader>` interface

packages/admin-panel/src/VizBuilderApp/constants.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models-extra/dashboard-item/matricies.ts
There was a regression in the recent entity links feature caused by the schema for MatrixVizes in the admin panel being commented out. It looks like they were commented out because the schema was incorrect and was causing an error. I re-included the schema and updated it to match the config for the output columns and now it is working as expected.
=> fix(adminPanel): RN-1534: Fix matrix preview

packages/psss/src/containers/Modals/RestoreArchivedAlertModal.jsx
> [!NOTE]
> Supersedes #6035. That one had a bad branch name (sorry)
`<ConfirmModal>` no longer exists in **@tupaia/ui-components**; one straggling import needed to be updated.
=> fix(psss): broken import

scripts/bash/ansiControlSequences.sh, scripts/bash/downloadEnvironmentVariables.sh, scripts/bash/getDeployablePackages.sh, scripts/bash/getPackagesWithEnvFiles.sh
Found that the `downloadEnvironmentVariables.sh` script wasn’t working. #5568 previously made modifications to the script (though hasn't been merged)
I used that as a starting point to fix up the script
=> fix(scripts): fix `download-env-vars`

packages/datatrak-web/src/features/Tasks/TaskDetails/TaskDetails.tsx, packages/types/src/types/requests/datatrak-web-server/SingleSurveyResponseRequest.ts
Stored as a `TIMESTAMP WITH TIME ZONE` in the database, but it comes through to us as an ISO9075 string (without a time zone??)
This sorts out the type, but let me know if it breaks semantics
=> fix(datatrak): survey response type

scripts/bash/downloadEnvironmentVariables.sh
Currently we don't download the .env vars for packages, just the global ones
=> fix(ci): Fix script for downloading env vars for packages

packages/datatrak-web/src/api/queries/index.ts, packages/datatrak-web/src/api/queries/useProjectEntities.ts, packages/datatrak-web/src/features/CountrySelector/useUserCountries.ts, packages/datatrak-web/src/features/EntitySelector/EntitySelector.tsx, packages/datatrak-web/src/features/Tasks/CreateTaskModal/CreateTaskModal.tsx
Instead of picking `UseQueryOptions` one-by-one to pass through as separate parameters, now just bring the entire options object through
All existing behaviour preserved. A bit easier to set overrides in code now
Tightened up the typing, which should flow through quite well to the consumers
=> refactor(datatrak): RN-1543: clean up `useUserCountries` interface

packages/central-server/src/apiV2/authenticate/authenticate.js, packages/central-server/src/tests/apiV2/authenticate/authenticate.test.js, packages/central-server/src/utilities/createSupportTicket.js
Temporarily disables support alerts sent when logging in from a new location, following [this internal discussion](https://beyondessential.slack.com/archives/C01JD93J4E6/p1738634862196829)
Alerts are planned to be restored in RN-1526
=> tweak: disable login alerts

packages/central-server/src/utilities/createSupportTicket.js
In non-production environments, we want to send an email to `DEV_EMAIL_ADDRESS` instead of creating a support ticket
This is controlled by the `ZENDESK_NOTIFICATIONS_DISABLE` environment variable, but its naming doesn’t suggest that it completely short-circuits **central-server**’s `createSupportTicket` function
This means that in **dev** and feature branch deployments, `ZENDESK_NOTIFICATIONS_DISABLE` needs to be unset for email notifications to go through, and no ticket is created in Zendesk anyway
This PR flips the order in which the production-ness of an environment and the `ZENDESK_NOTIFICATIONS_DISABLE` value so that the variable does what it says on the label
**Non-production environments will continue to bypass creation of support tickets**
=> fix: `ZENDESK_NOTIFICATIONS_DISABLE` behaviour

packages/datatrak-web/src/features/EntitySelector/ResultsList.tsx, packages/datatrak-web/src/features/EntitySelector/SearchField.tsx, packages/datatrak-web/src/features/Questions/EntityQuestion.tsx, packages/ui-components/src/components/SelectList/ListItem.tsx, packages/ui-components/src/components/SelectList/SelectList.tsx
- Put back question detail label
- Change wording of "All entities" and "Recent entities"
- Fix borders
- Hide the question label if the Entity question is the only question on a screen
---
=> tweak(datatrakWeb): RN-1559: Update Entity Question UI

package.json, packages/meditrak-app/package.json, yarn.lock
Suppresses this warning:
```
➤ YN0002: │ tupaia@workspace:. doesn't provide prettier (pf4afa), requested by @beyondessential/eslint-config-jest
➤ YN0002: │ tupaia@workspace:. doesn't provide prettier (p7908a), requested by @beyondessential/eslint-config-js
➤ YN0002: │ tupaia@workspace:. doesn't provide prettier (pa4b33), requested by @beyondessential/eslint-config-ts
```
=> deps: correctly declare `prettier` peer dependency

packages/datatrak-web/src/views/LandingPage/SurveySelectSection.tsx
This PR exists just in case the design decision is made that we don’t want to balance text wrapping in the survey select section.
In other words, this PR is ready on standby for @avaek to merge, pending the design decision. Otherwise we’ll just close the PR later this week.
=> tweak(datatrak): RN-1453: restore “unbalanced” dashboard text

packages/ui-components/src/components/Inputs/TextField.tsx
=> fix(datatrak): RN-1585: text field colour contrast

packages/datatrak-web/src/features/EntitySelector/EntitySelector.tsx, packages/datatrak-web/src/features/EntitySelector/ResultsList.tsx, packages/ui-components/src/components/SelectList/SelectList.tsx
=> fix(datatrak): RN-1585: hide entity select list subtitles when redundant

packages/datatrak-web-server/src/routes/ExportSurveyResponseRoute.ts, packages/lesmis-server/src/routes/PDFExportRoute.ts, packages/server-utils/package.json, packages/server-utils/src/downloadPageAsPDF.ts, packages/tupaia-web-server/src/routes/EmailDashboardRoute.ts, packages/tupaia-web-server/src/utils/downloadDashboardAsPdf.ts, packages/types/src/types/requests/tupaia-web-server/ExportDashboardRequest.ts, packages/types/src/types/requests/tupaia-web-server/ExportMapOverlayRequest.ts, yarn.lock
v15 requires Rosetta or the `PUPPETEER_EXPERIMENTAL_CHROMIUM_MAC_ARM` environment variable to run on Apple Silicon
Update turned out straightforward enough, taking the opportunity rather than adding an immediately-outdated inline comment telling devs to install Rosetta
Had a squiz through their changeling for breaking changes since v15, and it seems like the only thing that affects us is the switch from Node’s `Buffer` type to the builtin `Uint8Array` type for browser compatibility
***
`Page.setCookie(...cookies: CookieParam[])` has also been deprecated in favour of `setCookie(...cookies: CookieData[])`, but it still works so leaving that for now
=> deps(serverUtils): RN-1407: bump puppeteer to support Apple Silicon

packages/datatrak-web/src/features/Questions/BinaryQuestion.tsx, packages/datatrak-web/src/utils/index.ts, packages/datatrak-web/src/utils/typeGuards.ts, packages/tsutils/src/typeGuards.ts
#6112 introduced a semantic check that an object is an array, but the code change wasn’t 100% equivalent
This PR fixes that
=> fix(datatrak): binary question with default options

.github/workflows/ci.yaml, packages/expression-parser/package.json, yarn.lock
Just build the regular dependencies (“regular” as in no dev dependencies) of each package when running tests, rather than all internal dependencies
Back-of-the-napkin calculation suggests this saves 40–50 GHA minutes in a full CI run
=> ci: avoid unnecessary builds with `yarn workspaces foreach`

packages/datatrak-web/src/components/Tile.tsx
Looks like a previous merge of **dev** into an epic branch went bad and we lost this fix.
Took the opportunity to refactor to use `grid` layout, as `flex` worked but wasn’t semantically appropriate anyway
=> fix(datatrak): RN-1619: text clipping in Dashboard tiles

packages/datatrak-web/index.html, packages/datatrak-web/public/.well-known/apple-app-site-association, packages/meditrak-app/ios/TupaiaMediTrak/TupaiaMediTrak.entitlements
Keeps `webcredentials` association so iOS knows to let people autofill login credentials in MediTrak with DataTrak credentials
=> tweak(datatrak): hide Smart App Banner, don’t open DataTrak links in MediTrak

packages/datatrak-web/src/api/queries/useProjectEntities.ts, packages/datatrak-web/src/api/queries/useSurveyResponse.ts
If no `useQueryOptions.enabled` value is explicitly is provided, the chain evaluates `undefined`, which is falsy
But `enabled` should default to true to preserve `useQuery`’s out-of-the-box behaviour
=> fix(datatrak): incorrect forwarding of `useQueryOptions.enabled` when no options provided

packages/datatrak-web/src/components/PageContainer.tsx, packages/datatrak-web/src/components/index.ts, packages/datatrak-web/src/layout/CentredLayout.tsx, packages/ui-components/src/components/SafeArea.tsx, packages/ui-components/src/components/index.ts
`<PageContainer>` was doing a similar job to the new `<SafeAreaColumn>`, but its use of `flex` and `position` was a bit heavy-handed. I often need to override it with `flex: initial; position: initial;`, polluting the cascade.
The idea behind this component is to dedupe instances of `max(env())`
I don’t have an elegant solution for `calc(env() + x)`, though, as `x` is more likely to change
=> tweak: reusable `<SafeArea>` component

packages/ui-components/src/components/SafeArea.tsx
Turns out **styled-components**, by design, doesn’t forward the `as` prop:
https://github.com/styled-components/styled-components/issues/1981#issuecomment-548860710
=> fix(uiComponents): forwarding of `as` prop to `<SafeArea>`

packages/datatrak-web/src/features/Questions/GeolocateQuestion/MapModal/Map.tsx, packages/datatrak-web/src/features/Questions/GeolocateQuestion/MapModal/MapModal.tsx, packages/datatrak-web/src/layout/BackgroundPageLayout.tsx, packages/datatrak-web/src/layout/TasksLayout.tsx, packages/datatrak-web/src/layout/UserMenu/DrawerMenu.tsx, packages/datatrak-web/src/views/LandingPage/ActivityFeedSection/MobileActivityFeed.tsx, packages/datatrak-web/src/views/OfflinePage.tsx, packages/datatrak-web/src/views/SurveyPage.tsx
`vh`, `vw`, `vb` and `vi` units have proven a bit problematic for browsers where the viewport size isn’t fixed, often behaving as their _large_ counterparts (`lvh`, `lvw`, `lvb` and `lvi`), which leads to unwanted overflow when we want an element to exactly fit the viewport.
The _dynamic_ version of these viewport units (same but with a `d` prefix) has been baseline since 2023; and is more appropriate in these cases.
This PR makes small semantic changes to prefer logical properties where appropriate, but is otherwise a pure refactor—no behavioural changes
***
This issue came out of testing for #6030 (see [this Linear thread](https://linear.app/bes/issue/RN-1528/welcome-screen-and-very-short-tutorial-for-datatrak#comment-51f95bf5)). I fixed the offending style in that PR, but this carries …
=> fix(datatrak): use dynamic viewport units

packages/central-server/src/apiV2/GETHandler/GETHandler.js, packages/central-server/src/apiV2/dashboardVisualisations/GETDashboardVisualisations.js, packages/central-server/src/apiV2/mapOverlayVisualisations/GETMapOverlayVisualisations.js, packages/central-server/src/apiV2/surveyResponses/GETSurveyResponses.js, packages/database/src/TupaiaDatabase.js
> [!TIP]
>  Review this PR [commit-by-commit](https://github.com/beyondessential/tupaia/pull/6204/commits). Either of the last *two* commits are a valid approach, and I’m 50–50 on which one should get the go-head. Would appreciate reviewers’ input here 🙏 
The Admin Panel performance fix introduced by #6178 put a time limit on all calls to `TupaiaDatabase.count()`, which wrought havoc on how the entity hierarchy is built.
After discussing with Rohan and Chris, we decided this abort behaviour should be moved up the stack to **@tupaia/central-server** or **@tupaia/admin-panel-server**. The latter forwards `GET /surveyResponse` requests (with the slow `COUNT`) to the former, so this PR makes the change in **@tupaia/central-server**.
Two approaches:
- timeout (like that in #6178); or
- a …
=> fix: RN-1638: entity hierarchy build

packages/datatrak-web/index.html
RN-1479 has actually already been released, but we disabled the web app in production
Arose from [this comment in RN-1479](https://linear.app/bes/issue/RN-1479/set-up-pwa-for-installation#comment-0de3f89c)
=> feat(datatrak): RN-1479: enable web app in production

packages/devops/scripts/deployment-common/setup.sh
Previous fix is fine for branches off **dev**, but it didn’t occur to me that **baseline-** branches are still affected
This change will need to be applied to AWS once passed review
=> fix: globally avoid Bitwarden CLI 2025.5.0

packages/tupaia-web/src/Routes.tsx, packages/tupaia-web/src/utils/useEntityLink.ts
`<Navigate>` was being called with a prop that changes under its feed hundreds of times, causing `history.replaceState()` to be called many times.
This was causing browsers to throttle or block calls.
=> fix(tupaiaWeb): RN-1716: browser history abuse

packages/central-server/src/apiV2/import/importSurveyResponses/assertCanImportSurveyResponses.js
Troubling, long-lived bug that is known to self-resolve (but not in a timely fashion).
=> tweak(centralServer): warn when `assertCanImportSurveyResponses` sees unexpected nullish value

packages/api-client/src/connections/CentralApi.ts, packages/api-client/src/connections/mocks/MockCentralApi.ts, packages/central-server/src/apiV2/dashboardItems/GETDashboardItems.js, packages/central-server/src/apiV2/index.js, packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/utils/src/errors.js
When tupaia-web-server `GET`s dashboard relations from central-server, it passes an array of IDs in its query parameters.
For our largest project, this is over 240 IDs, which makes the request URI longer than 8KB, causing nginx to respond with `414 Request-URI Too Large`.
Increasing `large_client_header_buffers` didn’t seem to work; and following discussion in Rapa Nui stand up (21 July 2025) we decided to use `POST` method in these scenarios.
**This code change should be fully backward-compatible.** I’ve updated the problematic handler in tupaia-web-server to use `POST`, but `GET` requests should still work as usual.
=> fix: support `POST /dashboardItems` to avoid long URIs

packages/auth/src/Authenticator.js, packages/central-server/src/apiV2/utilities/emailVerification.js, packages/central-server/src/database/models/User.js, packages/central-server/src/tests/apiV2/authenticate/authenticate.test.js, packages/central-server/src/tests/apiV2/import/importSurveyResponses/testPermissions.js, packages/central-server/src/tests/apiV2/requestPasswordReset.test.js, packages/database/src/__tests__/changeHandlers/AnalyticsRefresher.fixtures.js, packages/database/src/migrations/20250701000000-argon2-passwords-modifies-schema.js, packages/database/src/modelClasses/ApiClient.js, packages/database/src/modelClasses/User.js, packages/server-boilerplate/src/utils/initialiseApiClient.ts, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts, packages/utils/src/testUtilities/randomData.js
- Updates the migration from #5872 to immediately discard legacy hashes, not preserving them in `password_hash_old`
- Adds similar migration logic for API clients
- fixes last few unit tests broken by this stack
=> fix: RN-1309: migrate API clients to Argon2

packages/central-server/src/hooks/utilities.js
From this comment: https://github.com/beyondessential/tupaia/pull/6325#discussion_r2221176732
[`ST_GeomFromGeoJSON` docs](https://postgis.net/docs/ST_GeomFromGeoJSON.html) suggest it expects stringified numeric values, but current implementation just checks the input _is parseable_ and discards the parsed values.
=> fix(centralServer): make parser actually parse

packages/server-utils/src/email/templates/content/permissionGranted.html
- One line change which removes a redundant duplicate "for" in Tupaia permission granted email
=> fix(serverUtils): RN-1723: duplicate “for” in permissions email

packages/datatrak-web/src/api/queries/useDatabaseQuery.ts
After working with it a bit, I think defining `LocalContext` as a `Record<string, unknown>` caused more issues than it solved.
- I tried using generics so that consumers could declare a local context type, but since we attach the `GlobalContext` as well as TanStack’s `QueryFunctionContext`, we end up having to pass through heaps of type arguments which made devX a bit miserable.
- Just defaulting it to `{}` instead of `LocalContext`
- `useDatabase` query doesn’t need to know about the input param type in that much detail. It just needs to call it and know what the return type is. This code change maintains all that.
When defining query functions, we _can_ explicitly type its context parameter to extend this new `ContextualQueryFunctionContext`; but it will also happen through type …
=> tweak(datatrak): smarter default `TLocalContext` in `useDatabaseQuery` query function
