beyondessential/tupaia

packages/web-frontend/src/components/View/utils.js, packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialog.js
- Fix logic in getIsUsingDots for Matrix Tables
---
=> HotFix 1 for Release 2021-50

packages/admin-panel/src/editor/DataChangeAction.js, packages/admin-panel/src/editor/index.js, packages/admin-panel/src/library.js, packages/admin-panel/src/pages/resources/SurveyResponsesPage.js, packages/lesmis/src/components/ApproveButton.js, packages/lesmis/src/components/RejectButton.js
- Add a wrapper component in admin panel library for triggering page refreshes
- Update lesmis actions to trigger page after completed actions
---
=> WAI-990: Refresh data after lesmis admin panel actions

packages/database/src/migrations/20220105040520-AddIndividualToFanafanaEntityHierarchy-modifies-data.js
MAUI-269: Add "individual" to fanafana entity hierarchy
Migration to add individual to canonical hierarchy for fanafana project
=> MAUI-269: Add "individual" to fanafana entity hierarchy

packages/database/src/migrations/20211214050226-AddFlutrackingPostcodeMapOverlayGroup-modifies-data.js, packages/database/src/migrations/20220107050226-AddFlutrackingPostcodeMapOverlayGroup-modifies-data.js
MAUI-268: Create new map overlay groups for Flutracking project
Add entry in map_overlay and map_overlay_relation for new overlay group.
=> MAUI-268: Create new map overlay groups for Flutracking project

packages/database/src/migrations/20211115202946-LESMISESSDPDrillDown5Year40District-modifies-data.js, packages/database/src/migrations/20220105040520-AddIndividualToFanafanaEntityHierarchy-modifies-data.js, packages/database/src/migrations/20220107050226-AddFlutrackingPostcodeMapOverlayGroup-modifies-data.js, packages/devops/scripts/lambda/resources/startup.sh, packages/ui-components/src/components/Chart/CartesianChart.js, packages/web-frontend/src/actions.js, packages/web-frontend/src/containers/MapOverlayBar/MapOverlayBar.js, packages/web-frontend/src/containers/MapOverlayBar/TitleAndDatePicker.js, packages/web-frontend/src/reducers.js, packages/web-frontend/src/reducers/mapReducers.js, packages/web-frontend/src/sagas.js, packages/web-frontend/src/selectors/index.js, packages/web-frontend/src/selectors/mapOverlaySelectors.js, packages/web-frontend/src/utils/mapOverlays.js
=> ks880mrgfrmdev

packages/admin-panel/src/pages/resources/MapOverlayGroupsPage.js, packages/database/src/migrations/20220107061813-SetMapOverlayGroupCodeAsUniqueKey-modifies-schema.js, packages/meditrak-server/src/apiV2/index.js, packages/meditrak-server/src/apiV2/mapOverlayGroups/CreateMapOverlayGroups.js, packages/meditrak-server/src/apiV2/mapOverlayGroups/index.js, packages/meditrak-server/src/apiV2/utilities/constructNewRecordValidationRules.js, packages/meditrak-server/src/tests/apiV2/mapOverlayGroups/CreateMapOverlayGroups.test.js
RN-317
Basically just copy and paste from PR https://github.com/beyondessential/tupaia/pull/3048. Extra work is to set map overlay group code as a unique key in db.
=> Rn 317 allow creating a map overlay group

packages/database/src/migrations/20220117011411-CovidSamoaDeleteOutdatedResponses-modifies-data.js
* RN-328 Delete old Covid Samoa data (#3625)
=> Release 2022-2-1 (hotfix)

packages/devops/scripts/ci/triggerRedeploy.sh
=> RN-331: Extend deployment timeouts to ~4 hours

packages/ui-components/package.json, packages/ui-components/src/components/DataLibrary/DataLibrary.js, packages/ui-components/src/components/DataLibrary/ResultsList.js, packages/ui-components/src/components/DataLibrary/SelectedDataList.js, packages/ui-components/src/components/DataLibrary/constant.js, packages/ui-components/src/components/DataLibrary/options.js, yarn.lock
RN-153 Sort functionality 
Transfer lists in material ui cannot support drag and drop functionality. Found anothe tool [react-beautiful-dnd](https://www.npmjs.com/package/react-beautiful-dnd) that is very handy to achieve this requirement.
=> Use 'rbd' to achieve drag and drop functionality

packages/data-broker/src/DataBroker.js, packages/data-broker/src/__tests__/DataBroker/DataBroker.fixtures.js, packages/data-broker/src/__tests__/DataBroker/DataBroker.stubs.js, packages/meditrak-server/src/apiV2/dataElements/DeleteDataElements.js, packages/meditrak-server/src/apiV2/dataElements/EditDataElements.js, packages/meditrak-server/src/apiV2/dataElements/GETDataElements.js, packages/meditrak-server/src/apiV2/dataElements/assertDataElementPermissions.js, packages/meditrak-server/src/apiV2/dataGroups/DeleteDataGroups.js, packages/meditrak-server/src/apiV2/dataGroups/EditDataGroups.js, packages/meditrak-server/src/apiV2/dataGroups/GETDataGroups.js, packages/meditrak-server/src/apiV2/dataGroups/assertDataGroupPermissions.js, packages/meditrak-server/src/tests/apiV2/dataElements/DeleteDataElements.test.js, packages/meditrak-server/src/tests/apiV2/dataElements/EditDataElements.test.js, packages/meditrak-server/src/tests/apiV2/dataElements/GETDataElements.test.js, packages/meditrak-server/src/tests/apiV2/dataGroups/DeleteDataGroups.test.js, packages/meditrak-server/src/tests/apiV2/dataGroups/EditDataGroups.test.js, packages/meditrak-server/src/tests/apiV2/dataGroups/GETDataGroups.test.js, packages/web-config-server/src/apiV1/DataAggregatingRouteHandler.js
- Pass in an access policy when creating a data broker instance
- Check permissions before pulling data
- Update some unit tests to keep working
=> Wai-1049 Check data source permissions when pulling via data broker

packages/database/src/migrations/20220201052718-DeleteDuplicateSamoaSchoolEntities-modifies-data.js
MAUI-347 Delete duplicate Samoa school entities
- Migration deleting two school entities.
=> MAUI-347 Delete duplicate Samoa school entities

packages/devops/scripts/lambda/resources/startup.sh
Switched to checking out new branch using the `ubuntu` user so that any new files/folders in the branch will have the correct owner
=> RN-355: Fixed permissions issue when a branch has a new package

packages/database/src/migrations/20220201052718-DeleteDuplicateSamoaSchoolEntities-modifies-data.js
MAUI-347: delete duplicate samoa schools
- Delete child_id from entity_relation table
=> Maui 347 delete duplicate samoa schools

packages/database/src/migrations/20220122223251-PenFaaSamoaAddVillageSchoolEntityRelations.js, packages/database/src/migrations/20220201052718-DeleteDuplicateSamoaSchoolEntities-modifies-data.js, packages/database/src/migrations/migrationData/20220122223251-PenFaaSamoaAddVillageSchoolEntityRelations/PenFaa Samoa school entity relations.json, packages/devops/scripts/lambda/resources/startup.sh, packages/meditrak-server/src/apiV2/export/exportSurveyResponses/exportResponsesToFile.js
- MAUI-390: Base the latest responses on data time rather than end time
- MAUI-347: Delete duplicate Samoa school entities
- RN-219: Attach schools to villages for PenFaa Samoa.
- RN-355: Fixed permissions issue when a branch has a new package
=> Release-2022-5

packages/admin-panel/src/VizBuilderApp/api/queries/useSearchAggregationOptions.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/AggregationDataLibrary.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/DataElementDataLibrary.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/SelectedOptionWithJsonEditor.js, packages/admin-panel/src/VizBuilderApp/components/Panel.js, packages/ui-components/src/components/DataLibrary/DataLibrary.js, packages/ui-components/src/components/DataLibrary/SelectedDataList.js, packages/ui-components/src/components/DataLibrary/index.js, packages/ui-components/src/components/DataLibrary/options.js, packages/ui-components/src/components/JsonEditor/JsonEditor.js, packages/ui-components/stories/dataLibrary.stories.js, packages/ui-components/stories/jsonEditor.stories.js
RN-152
1. Refactor option component to be dynamic to fit JSON Editor in it.
2. JSON editor in drag down can be validated by aggregation schema.
- Example
---
=> RN-152 right side advanced transfer list item

packages/database/src/migrations/20220210042050-TestMigration-modifies-data.js
=> RN-195: Test if branch strategy and migrations work properly

packages/admin-panel/src/pages/resources/UsersPage.js
RN-319
https://linear.app/bes/issue/RN-319#comment-a80b024e
=> RN-319 Enable Tupaia user email verification via the admin panel

packages/devops/scripts/lambda/resources/startup.sh, packages/web-config-server/src/preaggregation/pushAggregateData.js
=> WAITP-1102: Ensure node is available to preaggregation process

packages/database/src/migrations/20220210214956-UpdateCovid19SamoaVisualisationPermissions-modifies-data.js
Co-authored-by: Sima-BES <87400368+Sima-BES@users.noreply.github.com>
- Example
---
=> rn-335 update permission groups for covid samoa visualisations (#3677)

packages/web-config-server/src/export/excelFormatters/formatMatrixDataForExcel.js
- WAITP-1103
In https://github.com/beyondessential/tupaia/pull/279 we updated matrixes to allow nested row categories, but we didn't add handling for this to the export to excel formatter. This PR handles those nested row categories during export to excel.
=> WAITP-1103: Include category headers for nested data when exporting

packages/devops/scripts/lambda/actions/redeploy_tupaia_server.py
=> WAITP-1107: Copy over StartAt/StopAt tags when redeploying

packages/admin-panel/src/VizBuilderApp/components/DataLibrary/AggregationDataLibrary.js, packages/ui-components/src/components/DataLibrary/DataLibrary.js, packages/ui-components/src/components/DataLibrary/SelectedDataHeader.js, packages/ui-components/src/components/DataLibrary/styles.js
=> RN-188: Broke out header into its own component SelectedDataHeader

packages/devops/scripts/lambda/actions/spin_up_tupaia_deployment.py, packages/devops/scripts/lambda/actions/tear_down_tupaia_deployment.py
Couple small bugs encountered when switching `dev` over to RDS yesterday
=> RN-371: Fixed bugs in deployment scripts that caused issues when creating/deleting tupaia instances that had associated dhis2 instances

packages/devops/scripts/lambda/helpers/creation.py
=> RN-195: Added deletion protection for prod RDS deployment

packages/devops/scripts/ci/triggerRedeploy.sh, packages/devops/scripts/lambda/helpers/secrets.py
=> RN-195: Switched redeploy back to using 'deployment' lambda

packages/database/src/migrations/20220222043511-UnfpaMarshallIslandsAddMissingFacility-modifies-data.js, packages/database/src/migrations/20220223024636-AddVillageToCovidKiribatiProjectHeirarchy-modifies-data.js
MAUI-430
Migration to database relating to COVID-19 Kiribati project:
- Remove facility from canonical hierarchy
- Add village to hierarchy
=> MAUI-430 Add village heirarchy project

packages/devops/scripts/lambda/actions/spin_up_tupaia_database.py, packages/devops/scripts/lambda/actions/spin_up_tupaia_deployment.py, packages/devops/scripts/lambda/helpers/utilities.py
See context [on slack](https://beyondessential.slack.com/archives/CT0KTFSHZ/p1645994719332819?thread_ts=1645994457.082069&cid=CT0KTFSHZ)
=> Start DB an hour earlier than server

packages/admin-panel/src/widgets/InputField/registerInputFields.js
WAITP-145
- Pass false as a value not a prop
=> WAITP-145 Fix json array editor

packages/admin-panel/src/widgets/InputField/registerInputFields.js
=> Sima  create instance

packages/database/scripts/dumpDatabase.sh
Few small improvements to the database dump script post the RDS changes.
- No longer requires password input
- Uses compression
- Shows loading spinner to indicate progress
=> RN-376: Updated database dump script

packages/web-frontend/package.json, scripts/bash/getDeployablePackages.sh
Building in parallel caused out of memory errors on feature instances
=> Switched to building frontend modules in serial rather than parallel

packages/database/src/migrations/20220303051055-AddPalauToPacmossiProject-modifies-data.js
Add Palau as country into the PacMossi project
- Add Palau as child to pacmossi in entity_relation table
=> MAUI-601: Add Palau to PacMossi project

packages/meditrak-server/src/apiV2/accessRequests/GETAccessRequests.js, packages/meditrak-server/src/apiV2/index.js, packages/meditrak-server/src/apiV2/userAccounts/GETUserAccounts.js
I probably shouldn't submit against other team's tickets but it was small and that's where Georgia made the ticket
- Move get via parent from `GETUserAccount` to `GETAccessRequest`
- Update route to use `GETAccessRequest`
=> RN-395 Swap incorrect parent/child relation

yarn.lock
```
Target browser changes:
- and_chr 93
+ and_chr 98
- and_ff 92
+ and_ff 96
- android 93
+ android 98
- chrome 93
- chrome 92
- chrome 91
+ chrome 99
+ chrome 98
+ chrome 97
+ chrome 96
- edge 93
- edge 92
+ edge 98
+ edge 97
- firefox 92
- firefox 90
+ firefox 97
+ firefox 96
- ios_saf 14.5-14.7
+ ios_saf 15.2-15.3
+ ios_saf 15.0-15.1
+ ios_saf 14.5-14.8
+ ios_saf 12.2-12.5
- opera 78
- opera 77
+ opera 83
+ opera 82
- safari 14
- safari 13.1
+ safari 15.2-15.3
+ safari 15.1
- samsung 14.0
- samsung 13.0
+ samsung 16.0
+ samsung 15.0
```
=> RN-402: Upgrade caniuse-lite

packages/admin-panel/src/VizBuilderApp/api/queries/index.js, packages/admin-panel/src/VizBuilderApp/api/queries/useSearchTransformSchemas.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/AggregationDataLibrary.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/DataElementDataLibrary.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/TransformDataLibrary.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/component/AggregateSelectedOptionWithJsonEditor.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/component/SelectedOptionWithJsonEditor.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/component/TransformSelectedOption.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/component/TransformSelectedOptionWithJsonEditor.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/component/index.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/index.js, packages/admin-panel/src/VizBuilderApp/components/Panel.js, packages/admin-panel/src/VizBuilderApp/context/VizConfig.js, packages/report-server/src/routes/FetchTransformSchemaRoute.ts, packages/report-server/src/types.ts, packages/ui-components/src/components/DataLibrary/DataLibrary.js, packages/ui-components/src/components/DataLibrary/SelectedDataHeader.js, packages/ui-components/src/components/DataLibrary/SelectedDataList.js, packages/ui-components/src/components/DataLibrary/index.js, packages/ui-components/src/components/DataLibrary/options.js, packages/ui-components/stories/dataLibrary.stories.js, packages/utils/src/__tests__/validation/DescribableLazy.test.js, packages/utils/src/validation/DescribableLazy.js
RN-161
1. Transfer tab 
2. Verify input by transform schema
3. Add `id` to each step (aggregate & transform) so that we can handle multiple selected option properly
=> RN-161 Transform schema and transform tab

packages/admin-panel/src/authentication/LoginForm.js, packages/admin-panel/src/authentication/reducer.js, packages/admin-panel/src/authentication/selectors.js, packages/admin-panel/src/pages/resources/DataSourcesPage.js, packages/database/src/modelClasses/DataElement.js, packages/meditrak-server/src/apiV2/import/importDataElements/createDataElements.js, packages/meditrak-server/src/apiV2/import/importDataElements/importDataElements.js, packages/meditrak-server/src/apiV2/import/importDataElements/index.js, packages/meditrak-server/src/apiV2/import/index.js
=> Merge from dev to wai-1045 permission update

packages/admin-panel-server/src/viz-builder/mapOverlayVisualisation/combineMapOverlayVisualisation.ts, packages/admin-panel/package.json, packages/lesmis/package.json, packages/psss/package.json, packages/web-frontend/package.json
Replaces https://github.com/beyondessential/tupaia/pull/3778
=> Fix viz export2

packages/admin-panel-server/src/viz-builder/mapOverlayVisualisation/combineMapOverlayVisualisation.ts, packages/admin-panel/package.json, packages/admin-panel/src/authentication/LoginForm.js, packages/admin-panel/src/authentication/reducer.js, packages/admin-panel/src/authentication/selectors.js, packages/admin-panel/src/pages/resources/DataSourcesPage.js, packages/database/src/modelClasses/DataSource.js, packages/lesmis/package.json, packages/meditrak-server/src/apiV2/import/importDataSources/createDataSources.js, packages/meditrak-server/src/apiV2/import/importDataSources/importDataSources.js, packages/meditrak-server/src/apiV2/import/importDataSources/index.js, packages/meditrak-server/src/apiV2/import/index.js, packages/psss/package.json, packages/ui-components/src/components/Chart/Table/getChartTableData.js, packages/ui-components/src/components/DataTable/DataTable.js, packages/web-frontend/package.json
=> merge latest dev into waitp-1045

packages/admin-panel-server/src/routes/dashboardVisualisations/ImportDashboardVisualisationRoute.ts, packages/admin-panel-server/src/viz-builder/dashboardVisualisation/types.ts, packages/admin-panel-server/src/viz-builder/dashboardVisualisation/validators.ts
- Re-insert nullable(true) for dashboards and dashboard relations validation
=> MAUI-635: Fix dashboard item import

packages/ui-components/src/components/Chart/LineChart.js
- Add `strokeDasharray` property from recharts api into Line component
- Add `dot` property from recharts api into Line component
=> MAUI-646: Add dash style to dashboard items

packages/web-frontend/src/components/ControlBar.js, packages/web-frontend/src/containers/SearchBar/index.js
While looking at the desktop styles, I noticed that the ControlBar was made in a generic way but is now only being used by the SearchBar, so there was room to simplify it.
=> RN-387: De-genericise ControlBar

packages/meditrak-server/src/apiV2/import/importDataSources/createDataSources.js
Same as PR [update-fields-if-data-element-is_existed](https://github.com/beyondessential/tupaia/pull/3798)
=> Update fields if data element existed

packages/utils/src/dhis.js
```
#PALAU_DHIS_API_URL=https://dhis2.palauhealth.org
#PALAU_DHIS_CLIENT_SECRET=""
#PALAU_DHIS_PASSWORD=""
PALAU_DHIS_API_URL=https://dev-dhis2.palauhealth.org
PALAU_DHIS_CLIENT_SECRET=""
PALAU_DHIS_PASSWORD=""
#PALAU_DHIS_API_URL=https://e2e-dhis2.palauhealth.org
#PALAU_DHIS_CLIENT_SECRET=""
#PALAU_DHIS_PASSWORD=""
```
=> RN-245 Add Palau DHIS server to server list

packages/web-frontend/src/components/View/SingleValueWrapper.js, packages/web-frontend/src/styles/index.js
Issue [MAUI-685](https://linear.app/bes/issue/MAUI-685)
=> refactor single value wrapper

packages/web-frontend/src/components/View/SingleValueWrapper.js, packages/web-frontend/src/styles/index.js
- Add use of config 'dataColor' for Single Value dashboard items, which changes the text color of the data.
=> MAUI-685: Change Single Value Data Colour

packages/ui-components/src/components/Chart/CartesianChart.js, packages/ui-components/src/components/Chart/Legend.js, packages/ui-components/src/components/Chart/PieChart.js, packages/web-frontend/src/components/ExportDialog.js, packages/web-frontend/src/components/View/ChartWrapper.js, packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialog.js, packages/web-frontend/src/containers/EnlargedDialog/EnlargedDialogContent.js
- Add preview to chart export
- Update layout so everything fits
https://linear.app/bes/issue/RN-408#comment-216d3f11
=> Rn 408 crowding of values exp

packages/meditrak-server/src/apiV2/import/importSurveyResponses/assertCanImportSurveyResponses.js, packages/meditrak-server/src/tests/apiV2/postChanges.test.js
WAITP-1112
Today's release had a change to a function that didn't update all callers of that function. This updates the caller that was missed
=> Hot fix WAITP-1112: Sync permissions check broken

packages/database/src/migrations/20220405032953-UpdateAnalyticsTableToHandleEntityTypeAnswer-modifies-schema.js
Changes:
- Add migration to update build_analytics_table to replace with entity type answer with name instead of id.
=> Maui 717 entity type answer to name

packages/meditrak-server/src/apiV2/import/importStriveLabResults/importStriveLabResults.js
- Throw upload error when database returns no result on entity id.
=> MAUI-743: Specify error row for lab import

packages/admin-panel/src/VizBuilderApp/components/DataLibrary/AggregationDataLibrary.js, packages/admin-panel/src/VizBuilderApp/components/DataLibrary/TransformDataLibrary.js, packages/admin-panel/src/VizBuilderApp/context/VizConfig.js
Copy of: https://github.com/beyondessential/tupaia/pull/3847
=> RN-464: Fix alias transforms not loading properly in viz-builder

packages/devops/scripts/lambda/helpers/teardown.py
=> RN-370 rout53 rds tear down in sync

packages/meditrak-app/README.md
To make it work I use `appcenter-gradle.properties` as `gradle.properties`, but I might be wrong.
=> Update readme in meditrak-app

packages/meditrak-app/ios/TupaiaMediTrak/Info.plist, packages/meditrak-app/package.json
Bump mobile MediTrak version to 1.11.119
=> Bump version to 1.11.119

packages/meditrak-app/app/assessment/actions/submitSurvey.js, packages/meditrak-app/ios/TupaiaMediTrak/Info.plist, packages/meditrak-app/package.json
Entity questions are not saving, in the current production release of MediTrak 😱 
Need to get this out the door quickly.
=> [Hot fix] Entity questions not saving

packages/database/src/migrations/20220515045038-AddEntityTypeLocalGov-modifies-schema.js, packages/database/src/migrations/20220516000532-AddProjectImpactHealth-modifies-data.js, packages/database/src/modelClasses/Entity.js
- Schema migration to add new entity type, 'local_gov' to ENUM (db) and Entity.js
- Data migration to add new project 'Impact Health'
=> Maui 781 add proj health impact

packages/database/src/migrations/20220518002531-AddFacilityEntitiesForImpactHealth-modifies-data.js, packages/database/src/migrations/migrationData/20220518002531-AddFacilityEntitiesForImpactHealth-modifies-data.js/entities.json
- Add migration to add facilities and entity relations.
=> Maui-797: Import Impact Health facilities (hot-fix)

packages/api-client/src/connections/CentralApi.ts, packages/central-server/src/apiV2/changePassword.js, packages/central-server/src/apiV2/getSocialFeed.js, packages/central-server/src/apiV2/getUserRewards.js, packages/meditrak-app-server/examples.http, packages/meditrak-app-server/src/app/createApp.ts, packages/meditrak-app-server/src/routes/ChangePasswordRoute.ts, packages/meditrak-app-server/src/routes/index.ts
Simple route that redirects to central-server via the CentralApi
=> RN-512: Add ChangePasswordRoute to meditrak-app-server

packages/database/src/migrations/20220520063938-ExcludeBetioFromCovidKiribatiProject-modifies-data.js, packages/database/src/migrations/migrationData/20220520063938-ExcludeBetioFromCovidKiribatiProject-modifies-data/kiribati-subdistrict.json
- Migration script to add entity relations for all sub districts except Betio against the covid_kiribati project hierarchy.
=> MAUI-550: Exclude Betio from COVID-19 Kiribati project

packages/expression-parser/src/__tests__/expression-parser/ExpressionParser.test.js, packages/expression-parser/src/expression-parser/ExpressionParser.js, packages/indicators/src/Builder/AnalyticArithmeticBuilder/AnalyticArithmeticBuilder.ts, packages/indicators/src/Builder/EventCheckConditionsBuilder/EventCheckConditionsBuilder.ts, packages/indicators/src/Builder/helpers.ts, packages/indicators/src/__tests__/Builder/AnalyticArithmeticBuilder/AnalyticArithmeticBuilder.fixtures.ts, packages/indicators/src/__tests__/Builder/AnalyticArithmeticBuilder/testBuildAnalytics.ts
=> Support string value in indicator

packages/database/src/testUtilities/buildAndInsertSurveyResponses.js, packages/meditrak-app-server/examples.http, packages/meditrak-app-server/package.json, packages/meditrak-app-server/src/__tests__/__integration__/ChangePasswordRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/RegisterUserRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/UserRewardsRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/fixtures.ts, packages/meditrak-app-server/src/app/createApp.ts, packages/meditrak-app-server/src/routes/UserRewardsRoute.ts
Just a couple of routes that missed having tests added amidst all the PRs. Also fixed a couple small bugs in the routes which is nice 😄
=> Add missing tests for meditrak-app-server

packages/database/src/migrations/20220524011100-AddProjectCovidSolomonIslands-modifies-data.js
- Add project, hierarchy and permissions for 'COVID-19 Solomon Islands'
=> MAUI-817:  Add Project 'COVID-19 Solomon Islands'

packages/database/src/migrations/20220523020255-AddEntityTypesMedicalAreaAndNursingZone-modifies-schema.js, packages/database/src/migrations/20220523032848-AddProjectMassDrugAdministration-modifies-data.js, packages/database/src/modelClasses/Entity.js
- Create new project in Fiji, 'Mass Drug Administration'
- Add new entity types, 'medical_area' and 'nursing_zone'
=> MAUI-688: Add Mass Drug Administration project

README.md
Last commit in dev has branch name validation error, this commit will make dev turn green.
=> Readme add a space

packages/database/scripts/dumpDatabase.sh
Show error if fails, spinner if works.
=> Db dump show error

packages/database/src/migrations/20220615053401-AddSamoaToPacMossiProject-modifies-data.js
- Add entity relation from project entity to Samoa country entity.
=> MAUI-977: Add Samoa to PacMOSSI project

packages/report-server/src/__tests__/reportBuilder/context/buildContext.test.ts, packages/report-server/src/__tests__/reportBuilder/transform/parser/functions.test.ts, packages/report-server/src/reportBuilder/context/buildContext.ts, packages/report-server/src/reportBuilder/context/types.ts, packages/report-server/src/reportBuilder/transform/parser/functions/context.ts, packages/report-server/src/reportBuilder/transform/parser/functions/index.ts
https://linear.app/bes/issue/RN-550#comment-dd56a0a7
=> RN-550 Add custom report fn orgUnitAttribute

packages/lesmis/src/constants/page.js, packages/lesmis/src/translations/en.json
- Update aboutText property in English translations file.
=> MAUI-342: Update LESMIS Landing Page

packages/database/src/migrations/20220615070630-UpdateEntityRelationsForSamatauVillageSamoa-modifies-data.js
- Update parent for Sanatau in Penfaa and Covid Samoa projects to 'Aiga I le Tai'
=> MAUI-793: Change parent for Samatau village

packages/admin-panel/src/pages/resources/DashboardsPage.js
- Add delete column with config in DashboardsPage component.
=> MAUI-870: Allow Deletion of Dashboards

packages/devops/configs/servers.conf
No issue, just noticed this during a manual release involving downtime
=> Use correct location for 404 page

packages/meditrak-app/app/database/schema.js, packages/meditrak-app/ios/TupaiaMediTrak/Info.plist, packages/meditrak-app/package.json
=> Hotfix bump version to refresh schema

packages/database/src/migrations/20220714065133-AddEntityImageHookToHouseholdQuestion-modifies-data.js
- Add migration script to update hook field to 'entityImage' for Palau project
=> MAUI-1057: Add entityImage hook to household question

packages/devops/scripts/deployment/setupGoldMaster.sh, packages/lesmis-server/package.json, packages/lesmis-server/src/routes/PDFExportRoute.ts, packages/lesmis/src/components/DashboardExportModal/DashboardExportModal.js, packages/lesmis/src/components/DashboardExportModal/components/EntityDetails.js, packages/lesmis/src/utils/export/useDashboardItemsExportToPDF.js, packages/lesmis/src/utils/getApiUrl.js, yarn.lock
- In lesmis, session cookie domain is targeting `lesmis-api.tupaia.org`, instead of `lesmis.tupaia.org`, changes will reflect that.
- Dependencies for puppeteer
=> Fix puppeteer not working on feature branch

packages/expression-parser/package.json, packages/expression-parser/src/expression-parser/customFunctions.js, yarn.lock
Upper first case for every word in one string.
=> Add upper first case function in vizbuilder

packages/devops/scripts/deployment/setupGoldMaster.sh, packages/pdf-export-server/src/routes/PDFExportRoute.ts
master and dev modified `PDFExportRoute.ts` at the same time. This PR will add back the previous code so that master can merge in without conflict.
There will be a second PR to update this file, after master merged in.
=> Resolve merge conflict from master part 1

packages/ui-components/package.json, packages/web-frontend/package.json, yarn.lock
Downgrade recharts version as before.
=> Fix lesmis cannot export as PNG file

packages/lesmis/src/constants/constants.js, packages/lesmis/src/constants/page.js, packages/lesmis/src/views/HomeView.js
- Created constants for phone number and website address (for single source)
=> MAUI-1087: Update LESMIS phone number

packages/database/src/migrations/20220804020223-DeletePalauEnviroHealthEntities-modifies-data.js
- Delete records for four entities in survey_response, entity_relation and entity tables.
=> MAUI-1067: Delete entities - Environmental Health

packages/database/src/migrations/20220802000352-ChangeCovidSamoaProjectName-modifies-data.js
- database migration, changing project entity name to 'Samoa Health'
=> MAUI-1064: Change project entity name

packages/meditrak-app/appcenter-pre-build.sh
=> Hotfix baseline android issue with RN-597

packages/ui-components/src/components/Chart/LineChart.js
=> RN-623: Hide dot when exporting line charts

packages/web-config-server/src/authSession/publicAccess.js
- Add TV to public countries list
=> MAUI-1190 Add TV to public countries list

packages/database/src/migrations/20220901060328-AddProjectTuvaluEhealth-modifies-data.js
- Add project Tuvalu eHealth
---
https://linear.app/bes/issue/MAUI-1076#comment-3d192911
=> MAUI-1076 Add project Tuvalu eHealth

packages/web-frontend/src/containers/Map/DataVisualsLayer/InteractivePolygonLayer.js
- Map overlay look deeper for polygon data
---
See description in https://linear.app/bes/issue/MAUI-1228/look-deeper-than-grandchild-when-rendering-interactive-polygons-for
=> (hotfix) MAUI-1228 Map overlay look deeper for polygon data

packages/database/src/migrations/20220908093833-DeletePermissionGroupDEehVectorSurveillance-modifies-data.js
- Migration to delete unused permission group, 'DEH Vector Surveillance'
=> RN-515: Delete unused permission group

packages/database/src/migrations/20220829032330-AddConstraintDataServiceConfig-modifies-schema.js
- A bug in a migration worked during testing because the data was different, failed on dev
=> RN-625 (2) Fix migration

packages/admin-panel-server/src/connections/ReportConnection.ts, packages/devops/scripts/deployment/startBackEnds.sh, packages/lesmis-server/src/connections/ReportConnection.ts
Just some small clean-ups I noticed needed doing when running `lesmis-server` recently
=> Lesmis server minor cleanups

packages/lesmis/src/components/DashboardReport.js, packages/lesmis/src/components/DashboardReportModal.js, packages/ui-components/stories/chart/listVisual.stories.js
- When viewing a list type visual, show a scrollbar (charts still need fixed 100% height because of how they render)
---
https://linear.app/bes/issue/MAUI-1105#comment-5882c2e6
=> MAUI-1105 lesmis modal scroll

packages/admin-panel/src/sync/SyncStatus.js
Felicity asked me to budge the sync message over just a tad to be further from the icon.
=> [no-issue]: Adjust padding on Sync message

packages/data-table-server/examples.http, packages/data-table-server/src/__tests__/dataTableService/internal/EventsDataTableService.test.ts, packages/data-table-server/src/dataTableService/internal/EventsDataTableService.ts, packages/data-table-server/src/dataTableService/internal/index.ts, packages/database/src/migrations/20220915060402-AddEventsDataTable-modifies-schema.js
Simple data-table for pulling events (much like the one for pulling analytics)
=> RN-652: Added events data-table

packages/data-broker/src/DataBroker.js, packages/data-broker/src/__tests__/DataBroker/DataBroker.test.js, packages/data-broker/src/__tests__/services/DataServiceResolver.stubs.js, packages/data-broker/src/__tests__/services/DataServiceResolver.test.js, packages/data-broker/src/services/DataServiceMapping.js, packages/data-broker/src/services/DataServiceResolver.js
=> (Hotfix) Fix kobo sync

packages/database/src/migrations/20220916024924-AddUnfpaFacilities-modifies-data.js
=> Add sub_district and district

packages/admin-panel/src/importExport/ImportModal.js, packages/admin-panel/src/pages/resources/SurveysPage.js, packages/central-server/src/apiV2/import/importSurveys/importSurveys.js, packages/central-server/src/dataAccessors/validateSurveyFields.js
---
https://linear.app/bes/issue/RN-666#comment-eae2a36d
=> RN-666 Specify dhisInstanceCode on survey import

packages/tsutils/src/PDFExporter.ts
Satisfy the pdf export request from `tupaia.org`
=> Add tupaia.org to pdf export valid domain list

packages/meditrak-app/app/assessment/specificQuestions/FreeTextQuestion.js
- Add multiline === true as prop to the FreeTextQuestion component.
=> RN-592: Add Multiline To FreeText Question Field

packages/web-frontend/src/containers/OverlayDiv/components/LandingPage/index.js
Broken when adding the View Projects button in the UserMenu
=> RN-665: Fix the login button in the project page project cards

packages/central-server/src/dataAccessors/editSurvey.js
=> RN-677 Fix DHIS Server validation

packages/admin-panel/src/common.js, packages/admin-panel/src/pages/resources/DataElementDataServicesPage.js, packages/admin-panel/src/pages/resources/DataSourcesPage.js, packages/admin-panel/src/pages/resources/PermissionsPage.js, packages/admin-panel/src/routes.js, packages/central-server/src/apiV2/import/importDataElementDataServices.js, packages/central-server/src/apiV2/import/importUserPermissions.js, packages/central-server/src/apiV2/import/index.js, packages/central-server/src/apiV2/index.js, packages/central-server/src/apiV2/utilities/constructNewRecordValidationRules.js, packages/central-server/src/database/models/DataElement.js, packages/central-server/src/social/feedScraper.js, packages/data-broker/src/services/superset/SupersetService.js, packages/database/src/migrations/20220916024924-AddUnfpaFacilities-modifies-data.js, packages/database/src/migrations/20220925225155-AddSupersetMappings-modifies-data.js, packages/superset-api/package.json, packages/superset-api/src/SupersetApi.ts, packages/web-config-server/src/apiV1/measureBuilders/valueForOrgGroup.js, yarn.lock
- RN-615 Create UNFPA Country
- RN-523 Create FPBS Country
- "Swap FW to FJ flag" (needed for regional map overlays)
- Register 2 new superset_instances for UNFPA project (mSupply)
- Allow superset to connect via proxy (for RN-651)
- RN-681 Admin panel for data-element-data-service mapping table
- RN-683 User permission import in admin panel
---
- See each individual card for screenshots
=> mSupply Setup

packages/meditrak-app/app/assessment/specificQuestions/FreeTextQuestion.js
This reverts commit e76d2da6098ed536cfd0604c6b78faab464d117f.
Discussed with @avaek , this commit has not testing passed.
=> Revert "RN-592: Add Multiline To FreeText Question Field (#4207)"

packages/lesmis/src/components/MainMenu.js
www.info.tupaia.org doesn't work anymore
=> [no-issue]: Fix broken powered by Tupaia link in LESMIS

packages/admin-panel/package.json, packages/admin-panel/src/pages/resources/EntitiesPage.js, yarn.lock
=> qr-code admin panel

packages/meditrak-app/app/user/CreateUserPage.js
Issue:[ RN-701](https://linear.app/bes/issue/RN-701/fix-terms-and-conditions-link-in-meditrak-app)
=> RN-701 Update terms and conditions URL

packages/database/src/migrations/20221102231839-AddNigeriaToTupaia-modifies-data.js, packages/web-config-server/src/authSession/publicAccess.js
=> MAUI-1261 Add Nigeria to tupaia

packages/admin-panel/src/App.js, packages/admin-panel/src/editor/BulkCreateButton.js, packages/admin-panel/src/editor/BulkEditButton.js, packages/admin-panel/src/editor/CreateButton.js, packages/admin-panel/src/editor/EditButton.js, packages/admin-panel/src/editor/EditModal.js, packages/admin-panel/src/editor/Editor.js, packages/admin-panel/src/importExport/ExportButton.js, packages/admin-panel/src/importExport/ExportModal.js, packages/admin-panel/src/importExport/ImportModal.js, packages/admin-panel/src/logsTable/LogsButton.js, packages/admin-panel/src/sync/SyncStatus.js, packages/admin-panel/src/table/ColumnFilter.js, packages/admin-panel/src/table/DataFetchingTable.js, packages/admin-panel/src/table/columnTypes/DeleteButton.js, packages/admin-panel/src/utilities/index.js, packages/admin-panel/src/utilities/labelToId.js, packages/admin-panel/src/widgets/InputField/JsonInputField.js, packages/admin-panel/src/widgets/InputField/registerInputFields.js, packages/ui-components/src/components/NavBar.js, packages/ui-components/src/components/Toolbar.js
=> RN-441 Add ids to admin panel

packages/database/src/migrations/20221110021119-AddFacilitiesPenfaa-modifies-data.js, packages/web-frontend/src/containers/Map/DataVisualsLayer/InteractivePolygonLayer.js
MAUI-1228 
Changes based on 'https://github.com/beyondessential/tupaia/pull/4145/files'
- Example
---
=> MAUI-1228 Map overlay look deeper for polygon data

packages/meditrak-app/appcenter-post-clone.sh, packages/meditrak-app/appcenter-pre-build.sh, packages/meditrak-app/package.json, yarn.lock
https://appcenter.ms/orgs/Beyond-Essential/apps/Tupaia-MediTrak-Android/build/branches/hotfix-meditrak-app-build/builds/1425
- Bump react-native version https://github.com/facebook/react-native/issues/35210
* Hide output spam
* Freeze lockfile
Thanks @rohan-bes ! 🏌️
=> Fix meditrak app build

packages/web-config-server/src/preaggregation/runPreaggregation.js
Grant pre-aggregators BES Admin permissions so that they can fetch required data
=> RN-712: Fix broken pre-aggregator permissions

packages/devops/scripts/deployment-vm-app/install.sh, packages/devops/scripts/deployment-vm-app/setup.sh, packages/devops/scripts/deployment-vm-db/setup.sh, packages/devops/scripts/manual/vm-app/deploy.sh, packages/devops/scripts/manual/vm-app/upload.sh, packages/devops/scripts/manual/vm-db/deploy.sh, packages/devops/scripts/manual/vm-db/upload.sh
Note: We cannot fully install dependencies because it took a bit of time to install a dependency due to low network speed, and it will break the pipe. Please see other notes in the changes.
=> Update lesmis on premise

packages/web-frontend/src/containers/OverlayDiv/components/ProjectLandingPage/index.js
https://linear.app/bes/issue/MAUI-1335#comment-6cbe0091
=> Background img cover the entire area of <div> and clips the excess

packages/lesmis/src/components/DashboardReport.js, packages/lesmis/src/components/DashboardReportModal.js, packages/lesmis/src/utils/index.js, packages/lesmis/src/utils/useStartAndEndDates.js, packages/lesmis/src/views/DashboardItemsView.js
- Update DashboardReport component to account for different date param inputs.
=> RN-678: Fix LESMIS dashboard date picker

packages/database/src/migrations/20230110023215-SolIslandsDeleteCovidProject-modifies-data.js
- Database migration to remove Solomon Islands Covid project.
=> MAUI-1446: Delete Sol Islands Covid project

packages/data-broker/src/__tests__/services/superset/SupersetService.stubs.js, packages/data-broker/src/__tests__/services/superset/SupersetService.test.js, packages/data-broker/src/services/superset/SupersetService.js
=> RN-721 Superset filter by org unit

packages/database/src/migrations/20230118223340-ChangeSupersetCountryCodeToFj-modifies-data.js
- Add migration to swap country code from FW to FJ for superset services in date_element_data_service table
=> MDEV-24: Update Superset Country Code to FJ

packages/admin-panel/src/dataTables/DataTableEditFields.js, packages/admin-panel/src/dataTables/config/SqlDataTableConfigEditFields.js, packages/admin-panel/src/dataTables/useDataTable.js, packages/ui-components/src/components/DataTable/PreviewFilters/PreviewFilters.js, packages/ui-components/src/components/DataTable/editing/ParameterList.js, packages/ui-components/src/components/Inputs/SQLQueryEditor.js, packages/ui-components/stories/dataTable.stories.js
=> Add data table components to admin panel

packages/tsutils/src/validation/ajv/getAjv.ts, packages/utils/src/validation/validatorFunctions.js
=> Revert adding second argument

packages/admin-panel/src/dataTables/DataTableEditFields.js, packages/admin-panel/src/editor/actions.js, packages/admin-panel/src/editor/reducer.js, packages/admin-panel/src/pages/resources/DataTablesPage.js, packages/central-server/src/apiV2/index.js, packages/central-server/src/apiV2/utilities/constructNewRecordValidationRules.js
=> RN-730 edit data table

packages/central-server/src/utilities/sendEmail.js
RN-758, LESMIS don't want to set email server. It throws error if it is not set.
=> RN-758: Do not send email if SMTP is not set

packages/web-frontend/public/index.html
Just added new tag for collection analytics via google's new analytics interface.
Most changes were made by prettier/eslint
=> MDEV-114: Add new GA4 code tags to tupaia.org

packages/data-table-server/src/dataTableService/services/utils/mapProjectEntitiesToCountries.ts, packages/report-server/examples.http
- Fix mapProjectToCountries function in data-table-server. The entity api call does not use the filter so was redundant.
- Update examples.http for test config request in report server.
=> No Issue  - Fix project to country mapping bug

packages/database/src/migrations/20230216140701-MoveFetchIntoTransformInReports-modifies-data.js
- Change 'dataElements' to 'dataElementCodes'
- Change 'dataGroups' to 'dataGroupCode'
- Change any aggregation element that is a string to an object.
=> RN-781: Update fetchData config migration with correct property names

packages/entity-server/src/routes/hierarchy/middleware/filter.ts, packages/entity-server/src/types.ts, packages/server-boilerplate/package.json, packages/server-boilerplate/src/models/types.ts, packages/tsutils/src/types.ts, yarn.lock
- Fix type error in server-boilerplate package, add ObjectLikeFields type.
=> NO-ISSUE: Fix ObjectLikeKeys type error, add ObjectLikeFields

packages/aggregator/src/Aggregator.js, packages/data-table-server/src/dataTableService/services/EventsDataTableService.ts
=> Fix: wrap aggregations into object (data-table-ph1)

packages/database/src/migrations/20230216140701-MoveFetchIntoTransformInReports-modifies-data.js
- Change the transform conversion to ensure that dataGroupCode is a string and not an array.
=> Update Migration: Convert Data Group Code To String

packages/data-broker/src/__tests__/services/dhis/translators/DhisTranslator.test.ts, packages/data-broker/src/services/dhis/pullers/DataElementsMetadataPuller.ts, packages/data-broker/src/services/dhis/translators/DhisTranslator.ts, packages/data-broker/src/types/results.ts
=> RN-787 Fix dhis data element metadata

packages/report-server/src/__tests__/reportBuilder/output/default.test.ts, packages/report-server/src/__tests__/reportBuilder/output/matrix.test.ts, packages/report-server/src/__tests__/reportBuilder/output/rawDataExport.test.ts, packages/report-server/src/__tests__/reportBuilder/output/rows.test.ts, packages/report-server/src/__tests__/reportBuilder/output/rowsAndColumns.test.ts, packages/report-server/src/__tests__/reportBuilder/transform/fetchData/getContext.ts, packages/report-server/src/reportBuilder/context/buildContext.ts, packages/report-server/src/reportBuilder/context/index.ts, packages/report-server/src/reportBuilder/context/types.ts, packages/report-server/src/reportBuilder/output/functions/rawDataExport/rawDataExport.ts, packages/report-server/src/reportBuilder/output/functions/rawDataExport/rawDataExportBuilder.ts, packages/report-server/src/reportBuilder/output/functions/rawDataExport/types.ts, packages/report-server/src/reportBuilder/output/output.ts, packages/report-server/src/reportBuilder/output/types.ts, packages/report-server/src/reportBuilder/reportBuilder.ts, packages/report-server/src/reportBuilder/transform/functions/fetchData/fetchData.ts
- Remove output context, which only impacted RawDataExport type output. 
- Remove outputContext reference in tests
=> RN-688: Remove Output Context

packages/admin-panel/src/dataTables/DataTableEditFields.js, packages/admin-panel/src/dataTables/query/index.js, packages/admin-panel/src/dataTables/query/useExternalDatabaseConnections.js, packages/admin-panel/src/pages/resources/ExternalDatabaseConnectionsPage.js, packages/central-server/src/apiV2/dataElements/assertDataElementPermissions.js, packages/central-server/src/apiV2/externalDatabaseConnections/GETExternalDatabaseConnections.js, packages/central-server/src/apiV2/externalDatabaseConnections/index.js, packages/central-server/src/apiV2/index.js, packages/central-server/src/apiV2/utilities/getPermissionListWithWildcard.js, packages/central-server/src/apiV2/utilities/index.js
RN-729 
[Issue A](https://linear.app/bes/issue/RN-729#comment-feab04ad)
[Issue 4](https://linear.app/bes/issue/RN-729#comment-cfab4b25)
[Issue 5](https://linear.app/bes/issue/RN-729#comment-a3c6a270)
=> Fix for RN-729 

packages/data-table-server/src/__tests__/dataTableService/services/DataElementMetaDataDataTableService.test.ts, packages/data-table-server/src/dataTableService/services/DataElementMetadataDataTableService.ts, packages/database/src/migrations/20230222233428-RewriteVizsUsedDataElementCodeToName-modifies-schema.js, packages/report-server/src/reportBuilder/transform/parser/TransformParser.ts
Fix RN-783 testing issues, see issue links on commit messages.
=> Set lookup even with no row

packages/admin-panel/src/VizBuilderApp/components/DataLibrary/AggregationDataLibrary.js, packages/admin-panel/src/VizBuilderApp/context/VizConfig.js
=> RN-817 Fix inline aggregations

packages/web-frontend/src/selectors/measureSelectors.js
=> RN-756 Set default value for measureLevel

packages/database/src/migrations/20230314005038-RewriteWishFijiBaselineVizesWithOrgUnitContext-modifies-data.js, packages/database/src/migrations/20230316041331-RewriteWishFijiMatrixReports-modifies-data.js, packages/database/src/migrations/20230316061147-RewriteWishFijiMatrixReportsWithMultiDataElements-modifies-data.js
- Migrations to rewrite WISH vizes that use orgUnit context functions
=> RN-809 Rewrite WISH Vizes

packages/admin-panel/src/dataTables/DataTableEditFields.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/DatePicker.js, packages/admin-panel/src/dataTables/query/useDataTablePreview.js, packages/admin-panel/src/dataTables/useParams.js, packages/admin-panel/src/dataTables/useSqlEditor.js, packages/data-table-server/src/__tests__/dataTableService/DataTableService.test.ts, packages/data-table-server/src/dataTableService/utils/dataTableParamsToYupSchema.ts
=> Fix some bugs for data tables found in demo

packages/database/src/migrations/20230222233428-RewriteVizsUsedDataElementCodeToName-modifies-schema.js, packages/report-server/src/reportBuilder/transform/functions/fetchData/createJoin.ts
https://linear.app/bes/issue/RN-783#comment-d4e45a7a
=> Fix issue-11 in rn-783

packages/report-server/src/reportBuilder/transform/functions/fetchData/fetchData.ts, packages/report-server/src/reportBuilder/transform/transform.ts
=> RN-826 Add exitOnNoData flag to fetchData

packages/database/src/migrations/20230222233428-RewriteVizsUsedDataElementCodeToName-modifies-schema.js
=> Add column sort to fix Palau matrix viz

packages/database/src/migrations/20230328002338-FixDateOffsetVizes-modifies-data.js
Now we use expressions to calculate date offsets. A bit more technical, but vastly more powerful, so worth it imo
=> Fixup broken date offset vizes

packages/database/src/migrations/20230316041331-RewriteWishFijiMatrixReports-modifies-data.js, packages/database/src/migrations/20230316061147-RewriteWishFijiMatrixReportsWithMultiDataElements-modifies-data.js
(NO-ISSUE)
- Fix issues relating to RN-809
=> Fix WISH Fiji Matrix transforms

packages/data-table-server/src/__tests__/dataTableService/services/EntityAttributesDataTableService.test.ts, packages/data-table-server/src/__tests__/dataTableService/services/fixtures.ts, packages/data-table-server/src/dataTableService/DataTableService.ts, packages/data-table-server/src/dataTableService/DataTableServiceBuilder.ts, packages/data-table-server/src/dataTableService/services/EntityAttributesDataTableService.ts, packages/data-table-server/src/dataTableService/services/index.ts, packages/data-table-server/src/models/Entity.ts, packages/data-table-server/src/models/index.ts, packages/data-table-server/src/types.ts, packages/database/src/migrations/20230321045049-AddEntityAttributesDataTableType-modifies-schema.js, packages/database/src/modelClasses/Entity.js, packages/report-server/src/__tests__/reportBuilder/transform/parser/functions.test.ts, packages/report-server/src/reportBuilder/transform/parser/functions/context.ts, packages/report-server/src/reportBuilder/transform/parser/functions/index.ts
=> RN-819 Convert additional reports

packages/report-server/src/aggregator/ReportServerAggregator.ts, packages/report-server/src/reportBuilder/output/functions/rawDataExport/rawDataExportBuilder.ts
=> master into dev

packages/admin-panel-server/src/routes/FetchReportPreviewDataRoute.ts, packages/admin-panel/src/VizBuilderApp/api/queries/useReportPreview.js, packages/admin-panel/src/VizBuilderApp/components/PreviewOptions.js, packages/admin-panel/src/VizBuilderApp/components/PreviewSection.js, packages/admin-panel/src/VizBuilderApp/context/VizConfig.js
Needed to do this to test the changes in https://github.com/beyondessential/tupaia/pull/4406
Such a simple feature, and it makes the viz-building experience so much better. So I feel it's worth it
=> RN-156: Added startDate and endDate selectors to the viz-builder

packages/web-frontend/public/index.html
=> MDEV-115 Remove legacy google analytics snippet

packages/admin-panel/src/VizBuilderApp/components/PreviewOptions.js
=> Allow to set startDate and endDate to be undefined in viz builder

packages/database/src/migrations/20230216140701-MoveFetchIntoTransformInReports-modifies-data.js
https://beyondessential.slack.com/archives/C01MAA3NKM1/p1680761067485949
=> Add exitOnNoData when splitting data groups

packages/admin-panel/src/dataTables/components/PreviewFilters/filters/ArrayField.js, packages/admin-panel/src/dataTables/components/editing/types.js
https://beyondessential.slack.com/archives/C02HES8HFQF/p1680767078051119
=> No issue: defaultValue in ArrayField should have a default value

packages/data-table-server/src/__tests__/dataTableService/DataTableService.test.ts, packages/data-table-server/src/dataTableService/utils/dataTableParamsToYupSchema.ts
We added a bunch of new parameter types, but never added validation logic on the server side to create yup validators for them.
=> RN-853: Fixed parameter validation for all parameter types

packages/admin-panel-server/src/routes/FetchReportPreviewDataRoute.ts
Nice to be able to simplify this logic.
=> RN-856: Allow fetching data without specifying the Project or Location fields in the viz-builder

packages/central-server/src/tests/apiV2/dashboardVisualisations/dashboardVisualisations.fixtures.js, packages/database/package.json, packages/database/src/__tests__/testData/testDataDump.sql, packages/database/src/migrations/20230413041856-FixupDropAnalyticsLogTablesFunction-modifies-schema.js, packages/database/src/migrations/migrationData/buildAnalyticsTableFunction/createDropAnalyticsLogTablesFunction.v1.js
Should fix recent intermittent test failures
Also fixed the broken drop_analytics_log_tables function
Also updated update-test-data script to point to db in .env file
=> [no-issue]: Update the test database schema file

packages/admin-panel/src/dataTables/DataTableEditFields.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/ArrayField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/BooleanField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/DataElementCodesField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/DataGroupCodeField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/DatePicker.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/HierarchyField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/NumberField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/OrganisationUnitCodesField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/TextField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/utils.js, packages/admin-panel/src/dataTables/components/editing/ParameterItem.js, packages/admin-panel/src/dataTables/query/useDataTablePreview.js, packages/admin-panel/src/dataTables/query/useFetchDataTableBuiltInParams.js, packages/admin-panel/src/dataTables/useParams.js, packages/data-table-server/src/__tests__/dataTableService/services/SqlDataTableService.test.ts, packages/data-table-server/src/dataTableService/services/SqlDataTableService.ts, packages/data-table-server/src/dataTableService/utils/dataTableParamsToYupSchema.ts
Original PR: https://github.com/beyondessential/tupaia/pull/4443
=> RN-857: Hotfix

packages/admin-panel/src/dataTables/DataTableEditFields.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/ArrayField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/BooleanField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/DataElementCodesField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/DataGroupCodeField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/DatePicker.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/HierarchyField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/NumberField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/OrganisationUnitCodesField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/TextField.js, packages/admin-panel/src/dataTables/components/PreviewFilters/filters/utils.js, packages/admin-panel/src/dataTables/components/editing/ParameterItem.js, packages/admin-panel/src/dataTables/query/useDataTablePreview.js, packages/admin-panel/src/dataTables/query/useFetchDataTableBuiltInParams.js, packages/admin-panel/src/dataTables/useParams.js, packages/data-table-server/src/__tests__/dataTableService/services/SqlDataTableService.test.ts, packages/data-table-server/src/dataTableService/services/SqlDataTableService.ts, packages/data-table-server/src/dataTableService/utils/dataTableParamsToYupSchema.ts
Bit of an awkward dance trying to get conflicts between master and dev resolved due our push to dev rules
(conflicts caused by this PR: https://github.com/beyondessential/tupaia/pull/4469)
=> Resolve master to dev

packages/dhis-api/examples.http
- Added an `example.http` file to `dhis-api` package so that the endpoints can be tested with a rest client.
=> WAITP-1186 add example.http to dhis-api

packages/ui-components/src/components/DataTable/useDataTableExport.js
- Avoid parsing percentage string for excel download.
=> RN-832: Avoid parsing percentage string

packages/central-server/src/apiV2/export/exportSurveys/cellBuilders/AutocompleteConfigCellBuilder.js, packages/central-server/src/apiV2/export/exportSurveys/cellBuilders/KeyValueCellBuilder.js
- Process the attributes object from the database back into dot separated values to match the import format
=> Waitp 1175 autocomplete attributes

packages/devops/ci/tupaia-ci-cd.Dockerfile
Broken build: https://app.codeship.com/projects/70159bc0-0dac-0138-fdcb-260b82737f4e/builds/b482cb2e-633c-4653-98f1-8604c1f24897?component=step_Validate_and_test_Test_Test_batch_1_Test_central-server
Not sure why the build failed on stopping in the middle of creating test database in some specific packages.
This reverts part of commit 989b9230a21df47f18c89deaef6dbc9ef66461f3. The rest should be fine to change.
=> Fix CI by reverting change

packages/admin-panel/src/pages/resources/PermissionGroupsPage.js, packages/admin-panel/src/routes.js, packages/central-server/src/apiV2/GETPermissionGroups.js
- Add permission group ancestors column to Admin Panel
---
=> MDEV-78: Add permission group ancestors column to Admin Panel

packages/admin-panel/src/table/DataFetchingTable.js
- A recent PR for MDEV broke the expandable tables being incorrectly setting a table prop
---
=> MDEV-101: Fix table props in admin panel

packages/web-frontend/src/actions.js, packages/web-frontend/src/projects/sagas.js, packages/web-frontend/src/reducers.js, packages/web-frontend/src/reducers/orgUnitReducers.js, packages/web-frontend/src/sagas/watchUser/watchAttemptUserLogout.js, packages/web-frontend/src/screens/LandingPage/useNavigation.js
- Add landing page logout saga so as not to redirect to tupaia home page after logout
=> WAITP-1151: Landing page logout flow

packages/admin-panel/package.json, packages/admin-panel/src/VizBuilderApp/components/PreviewSection.js, packages/admin-panel/src/editor/actions.js, packages/admin-panel/src/utilities/getColumns.js, packages/admin-panel/src/utilities/index.js, packages/ui-components/src/components/DataGrid.js, packages/ui-components/src/components/index.js, packages/ui-components/stories/tables/dataGrid.stories.js
=> RN-801a: Specifically add Data Grid

packages/admin-panel/src/utilities/getColumns.js, packages/ui-components/src/components/DataTable/DataTable.js, packages/ui-components/src/components/DataTable/DataTableCell.js, packages/ui-components/src/components/DataTable/StyledTable.js
Moved cell content formatting to DataTableCellComponent
- Added 'data-type-x' class name so that we can used css to colour different data types differently
- Added colour coding for number, boolean, and null values
=> RN-875: Fix booleans not showing up in data-table preview

packages/database/scripts/setupTestDatabase.sh
Because we can't set SUPERUSER on RDS, needed to modify the script a little to handle that.
=> [no-issue]: Got setupTestDatabase script working on RDS

packages/admin-panel/src/pages/resources/CustomLandingPagesPage.js, packages/admin-panel/src/widgets/InputField/registerInputFields.js, packages/central-server/src/apiV2/utilities/constructNewRecordValidationRules.js, packages/utils/src/__tests__/validation/validatorFunctions.test.js, packages/utils/src/validation/validatorFunctions.js, packages/web-frontend/src/containers/TopBar/index.js, packages/web-frontend/src/containers/UserMenu/DrawerMenu.js, packages/web-frontend/src/containers/UserMenu/MenuList.js, packages/web-frontend/src/containers/UserMenu/PopoverMenu.js, packages/web-frontend/src/containers/UserMenu/UserInfo.js, packages/web-frontend/src/containers/UserMenu/index.js, packages/web-frontend/src/screens/LandingPage/LandingPageFooter.js
- Fix issue where colour wasn't being pulled through for some parts of the top bar
- Fix handling of links when they don't contain `http` substring
- Add validation for length of fields `long_bio` and `extended_title`
- Update accepted image sizes 
Note: Note yet had final confirmation of image sizes, so the actual number values may change, but the logic will remain the same
=> Waitp 1191 admin config landing pages

packages/devops/ci/tupaia-ci-cd.Dockerfile, packages/devops/ci/validation.Dockerfile, packages/devops/scripts/deployment/buildDeployablePackages.sh, packages/meditrak-app/appcenter-post-clone.sh
--frozen-lockfile is deprecated
https://yarnpkg.com/cli/install#options-immutable
=> Change --frozen-lockfile to --immutable

packages/lesmis/src/utils/export/useExportToImage.js
=> RN-922: Fix PNG exports failing on LESMIS

packages/web-frontend/src/containers/TopBar/index.js, packages/web-frontend/src/screens/desktop/RootScreen/PDFExportPage.js
- Fix search bar styles
- Fix loading state on PDF export
=> WAITP-1151: Landing Page Bug Fixes

packages/tupaia-web/package.json, packages/tupaia-web/src/api/api.ts, packages/tupaia-web/src/api/fetchError.ts, packages/tupaia-web/src/api/mutations/index.ts, packages/tupaia-web/src/utils/getApiUrl.ts, packages/tupaia-web/src/utils/index.ts, yarn.lock
- Setup basic API files for `tupaia-web`
- Install `axios`
Note: No actual API calls in there yet, these will come when we do the associated functionality I believe
=> WAITP-1199 Setup API abstraction

packages/web-frontend/src/constants/constants.js
- Fix ordering of project access types, for issue found in regression testing
=> WAITP-1189 Update project access type ordering

packages/web-frontend/src/containers/SignupForm/SignupFormComponent.js
=> WAITP-1285: Update terms & conditions link on signup

packages/central-server/examples.http, packages/central-server/src/apiV2/DownloadFiles.js, packages/central-server/src/apiV2/export/exportSurveyResponses/exportResponsesToFile.js, packages/central-server/src/apiV2/index.js, packages/central-server/src/apiV2/utilities/index.js, packages/central-server/src/apiV2/utilities/zipMultipleFiles.js, packages/utils/src/filesystem.js, packages/utils/src/s3/S3Client.js, packages/web-config-server/src/apiV1/index.js, packages/web-config-server/src/appServer/handlers/downloadFiles.js, packages/web-config-server/src/appServer/index.js, packages/web-config-server/src/appServer/routes.js
In order for the document download viz type to work, we need a route that allows us to download files from S3 (so that we can user the server's AWS credentials to download private files).
=> RN-930: Added GET /downloadFiles route to central-server and web-config-server

packages/aggregator/src/analytics/aggregateAnalytics/aggregations/getFinalValuePerPeriod.js, packages/aggregator/src/analytics/aggregateAnalytics/aggregations/offsetPeriod.js, packages/aggregator/src/analytics/aggregateAnalytics/aggregations/utils/getPreferredPeriod.js, packages/aggregator/src/analytics/periodFromAnalytics.js, packages/central-server/src/dhis/pushers/data/aggregate/AggregateDataPusher.js, packages/report-server/src/__tests__/reportBuilder/transform/fetchData/fetchData.fixtures.ts, packages/report-server/src/reportBuilder/transform/functions/orderColumns/sortByFunctions.ts, packages/report-server/src/reportBuilder/transform/parser/functions/utils.ts, packages/tsutils/package.json, packages/tsutils/src/__tests__/period/period.test.ts, packages/tsutils/src/period/period.ts, packages/utils/src/period/period.js, packages/web-config-server/src/apiV1/dataBuilders/generic/analytics/analyticsYearOnYear.js, packages/web-config-server/src/apiV1/measureBuilders/checkTimeliness.js, packages/web-config-server/src/apiV1/measureBuilders/helpers.js, packages/web-config-server/src/apiV1/utils/layerYearOnYear.js, yarn.lock
Moving a few more of those across
=> [no-issue]: Move period type utils to tsutils

packages/central-server/src/apiV2/meditrakApp/postChanges.js, packages/central-server/src/apiV2/meditrakApp/utilities/addSurveyFile.js, packages/central-server/src/dataAccessors/upsertAnswers.js, packages/utils/src/s3/S3Client.js
- Update file upload function.
---
=> RN-928: Tupaia Api to S3 File Upload

packages/api-client/src/connections/WebConfigApi.ts, packages/api-client/src/connections/mocks/MockWebConfigApi.ts, packages/tupaia-web-server/examples.http, packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/ProjectRoute.ts, packages/tupaia-web-server/src/routes/index.ts
- Added `fetchProjects` to web config in  `api-client`
- Added `/project/:projectCode` route to `tupaia-web-server`
=> WAITP-1207 Add getProject route

packages/admin-panel/package.json, packages/web-frontend/package.json
- Update fullstack command to include data-table-server in admin-panel and web-frontend
=> NO-ISSUE: update fullstack command

packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web-server/src/routes/RequestCountryAccessRoute.ts, packages/tupaia-web-server/src/routes/index.ts
- Added endpoint to `tupaia-web-server` for requesting access to a country
=> WAITP-1207 add requestCountryAccess endpoint

packages/ui-components/src/components/Chart/Chart.js, packages/ui-components/src/components/Chart/Table/ChartTable.js, packages/ui-components/src/components/Chart/utils.js, packages/ui-components/src/components/DownloadFilesVisual/DownloadFilesVisual.js, packages/ui-components/src/components/DownloadFilesVisual/index.js, packages/ui-components/src/components/ListVisual/ListVisual.js, packages/ui-components/src/components/NoData.js, packages/ui-components/src/components/index.js, packages/web-frontend/src/components/View/DownloadFilesVisual.js, packages/web-frontend/src/components/View/View.js, packages/web-frontend/src/components/View/utils.js
Added a new viz type to the ui-components `DownloadFilesVisual`.
Added a wrapper component in web-frontend to handle downloading the files and error messages.
Also did a little refactor of the `NoData` component as it was starting to get re-used a lot.
=> RN-931: Added 'filesDownload' viz type

packages/tupaia-web/src/Routes.tsx, packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Dashboard/DashboardMenu.tsx, packages/tupaia-web/src/layout/UserMenu/UserMenu.tsx, packages/tupaia-web/src/types/types.d.ts, packages/tupaia-web/src/views/LandingPage/MultiProjectLandingPage.tsx, packages/tupaia-web/src/views/LandingPage/SingleProjectLandingPage.tsx, packages/tupaia-web/src/views/ProjectPage/ProjectPage.tsx, packages/tupaia-web/src/views/ProjectsModal.tsx, packages/web-config-server/src/apiV1/projects.js
- Refactor dashboardCode param dashboardName to match the behaviour on tupaia.org
=> FE ReWrite: Refactor dashboardCode param dashboardName

packages/admin-panel/src/pages/resources/DhisInstancesPage.js, packages/admin-panel/src/pages/resources/SupersetInstancesPage.js, packages/admin-panel/src/pages/resources/index.js, packages/admin-panel/src/routes.js, packages/central-server/src/apiV2/index.js, packages/central-server/src/apiV2/utilities/constructNewRecordValidationRules.js
=> MDEV-150 data service admin panel

packages/web-frontend/src/screens/LandingPage/SingleProjectLandingPage.js
- Increased font-size on single project landing page button
- Decreased top and bottom padding on single project landing page button
=> WAITP-1292 Update landing page button size

packages/central-server/src/kobo/startSyncWithKoBo.js
This is already fixed on lesmis.edu.la, just merging it into the mainline
=> RN-917: Fix KoBo sync error when no data is returned (#4572)

packages/lesmis/src/utils/export/useExportToImage.js
This is already fixed on lesmis.edu.la just merging in to mainline
=> RN-922: Fix PNG exports failing on LESMIS (#4583)

packages/admin-panel/src/App.js, packages/lesmis/src/routes/AdminPanelApp.js
- Pass in correct base url to Toolbar component
=> Re-write: Fix admin panel tabs

codeship-steps.yml, packages/tupaia-web/src/features/Dashboard/Breadcrumbs.tsx, packages/ui-components/jest.config.js, packages/utils/src/__tests__/period/periodGranularities.test.js
- Shuffle some of the longer running tests to a different test batch
- Fix up a type issue
- Allow jest to parse `.jsx` files in `ui-components`
- Skip `periodGranularity.test.js` (See WAITP-1269)
=> Update codeship steps for frontend-rewrite branch

packages/central-server/src/apiV2/DownloadFiles.js, packages/central-server/src/apiV2/meditrakApp/postChanges.js, packages/central-server/src/apiV2/meditrakApp/utilities/addSurveyFile.js, packages/meditrak-app/.env.example, packages/meditrak-app/app/Meditrak.js, packages/meditrak-app/app/api/TupaiaApi.js, packages/meditrak-app/app/assessment/actions/submitSurvey.js, packages/meditrak-app/app/database/DatabaseAccess.js, packages/meditrak-app/app/database/schema.js, packages/meditrak-app/app/database/types/File.js, packages/meditrak-app/app/version/index.js, packages/meditrak-app/app/version/isBeta.js, packages/ui-components/src/components/DownloadFilesVisual/DownloadFilesVisual.js, packages/utils/src/__tests__/filesystem.test.js, packages/utils/src/filesystem.js, packages/web-frontend/src/components/View/DownloadFilesVisual.js
Screen recording: https://linear.app/bes/issue/RN-934#comment-8fd8b1c7
=> RN-934 duplicate filenames

packages/meditrak-app/ios/TupaiaMediTrak/Info.plist, packages/meditrak-app/package.json
Bumping meditrak-app version for upcoming Doc Attach and QR Code features
=> [no-issue]: Bump meditrak-app version

packages/ui-chart-components/src/utils/parseChartConfig.ts
- Update default value of `chartConfig` in `parseChartConfig` to fix issue with chart columns
=> Fix issue with parsing chart config

packages/ui-components/src/components/CheckboxList.tsx, packages/ui-map-components/src/utils/markerFormats.ts
=> WAITP-1290: Fix UI component regressions

packages/api-client/src/constants.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/PushChangesRoute.test.ts, packages/meditrak-app-server/src/routes/sync/PushChangesRoute/PushChangesRoute.ts, packages/meditrak-app-server/src/routes/sync/PushChangesRoute/addSurveyFile.ts
=> RN-944 File upload meditrak-app-server

packages/tupaia-web/src/components/CheckboxField.tsx, packages/tupaia-web/src/views/LandingPage/SingleProjectLandingPage.tsx, packages/tupaia-web/src/views/RegisterModal/RegisterModal.tsx, packages/ui-components/src/components/Inputs/Checkbox.tsx
[WAITP-1285: Update terms & conditions link on signup](https://github.com/beyondessential/tupaia/pull/4637)
[WAITP-1292](https://linear.app/bes/issue/WAITP-1292/reduce-height-and-increase-font-of-button-on-custom-landing-pages): Update landing page button sizing
=> WAITP-1292 & WAITP-1285: Web Frontend changes from dev

packages/web-frontend/src/components/View/DownloadFilesVisual.js
=> RN-953: Show message on downloadFiles viz when user is not logged in

packages/meditrak-app/android/build.gradle, packages/meditrak-app/android/gradle/wrapper/gradle-wrapper.properties
=> RN-962 Upgrade android sdk

packages/devops/configs/servers.conf, packages/devops/scripts/ci/validateBranchName.sh, packages/devops/scripts/lambda/helpers/create_from_image.py, scripts/bash/getDeployablePackages.sh
- Add `tupaia-web` and `tupaia-web-server` to appropriate scripts in the repo
Separate to this PR I've also done the following:
- Upload new lambda scripts to AWS
- Add `.env` files to lastpass (our current source of truth)
=> WAITP-1334 Add tupaia web packages to deployment

.eslintrc-ts-frontend.json, packages/tupaia-web/.eslintrc.cjs, packages/ui-chart-components/.eslintrc.js, packages/ui-components/.eslintrc.js, packages/ui-map-components/.eslintrc.js
Create a new frontend config for typescript packages and apply it to the new typescript front end packages.
=> No-issue: Fix fe ts lint config

packages/admin-panel/src/qrCode/QrCode.js
=> RN-965: Make QR Code image with bigger text

packages/admin-panel/src/pages/resources/EntitiesPage.js, packages/admin-panel/src/table/columnTypes/QrCodeButton.js
=> RN-903 Prefix QR code (#4783)

packages/web-config-server/src/export/ExportSurveyDataHandler.js, packages/web-config-server/src/export/exportChartHandler.js, packages/web-config-server/src/export/requestFromTupaiaConfigServer.js
- Forward authorization headers if we're using them, rather than always assume we're using a session
=> WAITP-1247 Fixup auth on export route

packages/tupaia-web-server/src/app/createApp.ts
- Forward `downloadFiles` requests to `central-server`
=> WAITP-1343 Add forward route for downloadFiles to tupaia-web-server

packages/tupaia-web/src/constants/constants.ts, packages/tupaia-web/src/views/ForgotPasswordModal.tsx, packages/tupaia-web/src/views/LoginModal.tsx, packages/tupaia-web/src/views/RegisterModal/RegisterModal.tsx, packages/tupaia-web/src/views/RegisterModal/SignUpComplete.tsx
Form fixes relating to WAITP-1208, WAITP-1206 and WAITP-1205
=> WAITP-1208: Tupaia-web form fixes

packages/tupaia-web/src/Routes.tsx, packages/tupaia-web/src/api/mutations/index.ts, packages/tupaia-web/src/api/mutations/useExportDashboard.tsx, packages/tupaia-web/src/api/queries/useReport.ts, packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Dashboard/ExportDashboard.tsx, packages/tupaia-web/src/features/DashboardItem/DashboardItemContent.tsx, packages/tupaia-web/src/features/PDFExportDashboardItem/PDFExportDashboardItem.tsx, packages/tupaia-web/src/features/PDFExportDashboardItem/PDFExportHeader.tsx, packages/tupaia-web/src/features/PDFExportDashboardItem/index.ts, packages/tupaia-web/src/features/Visuals/Chart.tsx, packages/tupaia-web/src/utils/useDateRanges.ts, packages/tupaia-web/src/views/PDFExport.tsx, packages/tupaia-web/src/views/index.ts, packages/ui-chart-components/src/components/Charts/LineChart.tsx, packages/ui-components/src/components/CheckboxList.tsx
- Added PDF export modal with checkbox list for selecting export
- Added mutation for requesting export
- Added `PDFExport` route for `puppeteer` to hit when exporting
---
=> Waitp 1236 multi viz export

packages/ui-components/src/components/DateRangePicker/DateRangePicker.tsx, packages/ui-map-components/src/components/Markers/PopupMarker.tsx
- Fix styling regression on date range picker label
- Fix regression on Popup markers to stop them closing unexpectedly
=> Release-Hotfix-2023-31-1

packages/admin-panel/src/pages/resources/SurveysPage.js, packages/central-server/src/apiV2/surveys/CreateSurvey.js, packages/central-server/src/apiV2/surveys/EditSurvey.js, packages/central-server/src/apiV2/surveys/convertNamesToIds.js, packages/central-server/src/apiV2/surveys/surveyEditor/SurveyEditor.js, packages/central-server/src/apiV2/surveys/surveyEditor/index.js, packages/central-server/src/apiV2/surveys/surveyEditor/updateDataElementsConfig.js, packages/central-server/src/apiV2/surveys/surveyEditor/updateOrCreateDataGroup.js, packages/central-server/src/apiV2/surveys/surveyEditor/validateSurveyServiceType.js
Most of the delta here is just code cleanups.
The last commit 3ba8d118bf2c96405c268b586ef7d5d3a6a81b69 is where we make the functionality changes.
=> RN-972: Allow creating survey group when editing a survey (hotfix)

packages/tupaia-web/src/api/queries/index.ts, packages/tupaia-web/src/api/queries/useEntitySearch.ts, packages/tupaia-web/src/features/EntitySearch/EntitySearch.tsx, packages/tupaia-web/src/features/EntitySearch/SearchBar.tsx, packages/tupaia-web/src/features/EntitySearch/SearchResults.tsx, packages/tupaia-web/src/layout/UserMenu/UserMenu.tsx, packages/tupaia-web/src/types/mapOverlay.d.ts, packages/tupaia-web/src/types/types.d.ts, packages/tupaia-web/src/utils/index.ts, packages/tupaia-web/src/utils/useDebounce.ts
- Add Entity Search Bar on desktop and mobile
---
=> WAITP-1210: Entity search

packages/tupaia-web/src/api/queries/useUser.ts, packages/tupaia-web/src/layout/ProjectCardList/ProjectCard.tsx, packages/tupaia-web/src/layout/UserMenu/DrawerMenu.tsx, packages/tupaia-web/src/layout/UserMenu/MenuList.tsx, packages/tupaia-web/src/layout/UserMenu/UserMenu.tsx, packages/tupaia-web/src/views/ProjectsModal.tsx
The main bug relates to WAITP-1273 but there are a few others too
- Fix issue in Project Modal link where the Login Link wasn't showing if you were logged out
- Fix styles in mobile user menu
- Add Help Center link to user menu
- Fix absolute links in user menu
---
=> WAITP-1273: User Navigation Bug Fixes

packages/tupaia-web-server/package.json, packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/tupaia-web/src/components/Modal.tsx, packages/tupaia-web/src/constants/constants.ts, packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/DashboardItem/ExpandItemButton.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapOverlaySelectorTitle.tsx, packages/tupaia-web/src/layout/ProjectCardList/ProjectCard.tsx, yarn.lock
- Dashboards response returns adhering to sort order
- Fix up modal colours
- Update styling of project cards according to design
=> No issue: Tidy up styling and dashboard organisation

packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/tupaia-web-server/src/utils/generateFrontendExcludedFilter.ts
- Actually sort the dashboard items, not just the dashboards
- (Snuck in a separate small fix for exclusion filter)
=> WAITP-1256: Fixup dashboard item sort

packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/tupaia-web-server/src/routes/UserRoute.ts, packages/tupaia-web/src/api/queries/useUser.ts, packages/types/src/types/requests/tupaia-web-server/UserRequest.ts
- Allow returning no data dashboard
- Move dashboard sort to handle `null` values the same as prior to the rewrite
- Return minimal version of the user data
=> WAITP-1215: Misc backend fixups

packages/admin-panel/package.json
- Add fix for memory issue for build (intermittent issue) - this is a [known issue](https://github.com/vitejs/vite/issues/2433#issuecomment-1295494487) with Vite
=> WAITP-1283: Build fix

package.json, packages/psss/src/__tests__/weeklyReportsPanel.test.js, packages/psss/src/api/api.js, packages/psss/src/utils/PersistGateProvider.jsx
- Fix PSSS unit tests
- Arrange scripts in root `package.json`
=> WAITP-1392: Fix tests and arrange scripts

packages/tupaia-web/src/features/Dashboard/DashboardMenu.tsx, packages/tupaia-web/src/features/DashboardItem/DashboardItem.tsx, packages/tupaia-web/src/features/Visuals/Chart.tsx, packages/tupaia-web/src/features/Visuals/ProjectDescription.tsx, packages/tupaia-web/src/views/ProjectsModal.tsx
- Sort country names alphabetically in project details viz
- Disable dashboard menu when only one available dashboard
- Fix charts disappearing on mobile
- Fix issue with no dates being sent to dashboard items when they should be
=> WAITP-1319 dashboard viz fixes

packages/admin-panel/package.json, vite.config.js
Changes:
Update admin-panel build for the app and library to be in series rather than parallel to spread the cpu and memory load
Add manual chunks config so that the build gets split into smaller files which reduces resource usage on build but also improves front end performance on first load.
Testing
The test branch [waitp-1283-test-vite-build](https://github.com/beyondessential/tupaia/tree/waitp-1283-test-vite-build) is deployed with the same configuration as dev and the build works.
=> WAITP-1283: Update vite config

packages/tupaia-web/src/features/DashboardItem/DashboardItem.tsx, packages/tupaia-web/src/features/Visuals/View/SingleDate.tsx, packages/tupaia-web/src/features/Visuals/View/SingleDownloadLink.tsx, packages/tupaia-web/src/utils/transformDownloadLink.ts
- Fix differences in static text visuals
- Fix issue where url for download link is incorrect if there is no trailing `/`
=> WAITP-1239: Fixes for static text visuals

packages/meditrak-app/app/assessment/qrCodeScreen/MultipleQrCodeShare.js, packages/meditrak-app/app/assessment/qrCodeScreen/SingleQrCodeShare.js, packages/meditrak-app/app/widgets/QrCode.js
Screenshots: https://linear.app/bes/issue/RN-976#comment-2088f8c0
=> RN-976: Updated QR code format on Meditrak

packages/lesmis/src/components/Visuals/ListVisual/ListVisual.jsx, packages/web-config-server/src/export/ExportSurveyDataHandler.js
- Fix positioning of no data message on LESMIS dashboard items
- Fix export issue
=> No issue: fix regressions for release-2023-33

packages/admin-panel/package.json, packages/lesmis/package.json, vite.config.js, yarn.lock
- Fixed typo in chunking config
- Removed max memory change build script
=> WAITP-1283 fix build

packages/admin-panel/package.json, packages/lesmis/package.json, vite.config.js, yarn.lock
- Fix issue with memory in build
=> Hotfix release 2023 33

packages/tupaia-web/src/layout/UserMenu/UserMenu.tsx, packages/web-frontend/src/containers/UserMenu/index.js
=> MDEV-184: Update help centre link

packages/meditrak-app/ios/Podfile, packages/meditrak-app/ios/Podfile.lock, packages/meditrak-app/ios/TupaiaMediTrak.xcodeproj/project.pbxproj
- Update minimum iOS version in `Podfile`
- Regenerate `Podfile.lock`
=> Update minimum iOS version

packages/tupaia-web/src/features/DashboardItem/DashboardItem.tsx, packages/tupaia-web/src/features/DashboardItem/DashboardItemContent.tsx, packages/tupaia-web/src/features/DashboardItem/DashboardItemContext.ts, packages/tupaia-web/src/features/DashboardItem/DashboardItemError.tsx, packages/tupaia-web/src/features/DashboardItem/DashboardItemLoader.tsx, packages/tupaia-web/src/features/DashboardItem/ExpandItemButton.tsx, packages/tupaia-web/src/features/DashboardItem/index.ts, packages/tupaia-web/src/features/EnlargedDashboardItem/EnlargedDashboardVisual.tsx, packages/tupaia-web/src/features/PDFExportDashboardItem/PDFExportDashboardItem.tsx, packages/tupaia-web/src/features/Visuals/Chart.tsx, packages/tupaia-web/src/features/Visuals/Matrix.tsx, packages/tupaia-web/src/features/Visuals/View/View.tsx, packages/ui-map-components/package.json, packages/ui-map-components/src/utils/markerColors.ts, yarn.lock
- refactor of dashboard items to a `context` model, so that props don't get passed around as much
=> Rn 899 qr code refactor

packages/database/src/modelClasses/MapOverlayGroup.js, packages/database/src/modelClasses/index.js, packages/tupaia-web-server/src/models/MapOverlayGroups.ts, packages/tupaia-web-server/src/models/index.ts, packages/tupaia-web-server/src/routes/MapOverlaysRoute.ts, packages/tupaia-web-server/src/types.ts
- Updated MapOverlaysRoute in tupaia-web-server to fetch mapOverlayGroups data directly from the database
- Added new model for mapOverlayGroups in tupaia-web-server and added to directory
=> WAITP-1215: Navigation: Projects navigation via projects landing modal

packages/meditrak-app/android/build.gradle, packages/meditrak-app/package.json, yarn.lock
=> RN-974: Bump meditrak android api to level 33

packages/tupaia-web/src/components/Modal.tsx, packages/tupaia-web/src/features/Dashboard/ExportDashboard.tsx, packages/tupaia-web/src/features/EnlargedDashboardItem/ExportDashboardItem.tsx, packages/tupaia-web/src/features/Visuals/Chart.tsx, packages/tupaia-web/src/theme/theme.ts
- Fix export styling for single and multi report exports
- Reduce padding around enlarged dashboard items to reduce scroll
=> WAITP-1237 report exports

packages/central-server/package.json, packages/central-server/src/apiV2/index.js, packages/central-server/src/apiV2/middleware/auth/authenticationMiddleware.js, packages/central-server/src/createApp.js, packages/central-server/src/tests/testUtilities/database/addBaselineTestData.js, yarn.lock
- Swap authentication middleware in `central-server` to use `server-boilerplate` code
=> WAITP-1422 Use boilerplate authenticator in central server

packages/tupaia-web/src/api/queries/useMapOverlays.ts, packages/tupaia-web/src/components/Modal.tsx, packages/tupaia-web/src/constants/mapbox.ts, packages/tupaia-web/src/features/EnlargedDashboardItem/ExportDashboardItem.tsx, packages/tupaia-web/src/features/Map/Map.tsx, packages/tupaia-web/src/features/Map/MapLegend/MapLegend.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapOverlayList.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapOverlaySelectorTitle.tsx, packages/tupaia-web/src/features/Map/utils/useMapOverlayData.ts
- Fixed loading state on map overlay selector
- Fixed padding on modals
- Add in logic for the default tile in map tile picker
=> WAITP-1222 map overlay fixes

packages/tupaia-web/src/features/Visuals/Chart.tsx
- Fix issue with overlapping chart labels in multi viz export
=> WAITP-1236: fix export chart size

packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/EnlargedDashboardItem/EnlargedDashboardVisual.tsx, packages/tupaia-web/src/features/Visuals/Matrix.tsx, packages/ui-components/src/components/Matrix/EnlargedMatrixCell.tsx
- Fixed error being caught for some matrix description enlarged cells
- Added message on mobile about matrix not being good to view at this screen size
- Fixed drilldown dashboard items appearing in side panel
=> WAITP-1231: Matrix fixes

packages/tupaia-web/src/components/DateRangePicker.tsx, packages/tupaia-web/src/components/Modal.tsx, packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/EnlargedDashboardItem/EnlargedDashboardVisual.tsx, packages/tupaia-web/src/features/EnlargedDashboardItem/ExportButton.tsx, packages/ui-components/src/components/Dialog.tsx, packages/ui-components/src/components/Loaders/SpinningLoader.tsx
- Enlarged modal button styles
- Date range picker styles
- Dashboard loader
- Dashboard widths
---
=> WAITP-1235: front end dashboard fixes

packages/datatrak-web-server/src/routes/SurveyScreenComponentsRoute.ts, packages/datatrak-web/src/features/Questions/BinaryQuestion.tsx, packages/datatrak-web/src/features/Questions/CheckboxQuestion.tsx, packages/datatrak-web/src/features/Questions/DateQuestion.tsx, packages/datatrak-web/src/features/Questions/DateTimeQuestion.tsx, packages/datatrak-web/src/features/Questions/InstructionQuestion.tsx, packages/datatrak-web/src/features/Questions/RadioQuestion.tsx, packages/datatrak-web/src/features/Questions/TextQuestion.tsx, packages/datatrak-web/src/features/Questions/index.ts, packages/datatrak-web/src/features/Survey/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveyQuestion.tsx, packages/datatrak-web/src/features/Survey/SurveyScreen.tsx, packages/datatrak-web/src/layout/CentredLayout.tsx, packages/datatrak-web/src/theme/theme.ts, packages/datatrak-web/src/types/index.ts, packages/datatrak-web/src/types/surveys.ts, packages/types/src/schemas/schemas.ts, packages/types/src/types/requests/datatrak-web-server/SurveyScreenComponentsRequest.ts, packages/types/src/utils/casing.ts, packages/ui-components/src/components/Inputs/RadioGroup.tsx
- Created core question type components: Text, Radio, Binary, Date, DateTime, Instruction, Checkbox
- Updated types for request responses
- Added question numbers next to the question name, as per the design
- Updated the endpoint to parse any stringified JSON
---
Binary
Number
Radio
Date
Instruction
Checkbox
=> WAITP-1345: core question types

packages/tupaia-web-server/src/routes/DashboardsRoute.ts
- Fix issue where incorrect no data dashboards were showing
=> WAITP-1215: Show correct no data dashboards

packages/tupaia-web/src/features/Dashboard/DashboardMenu.tsx, packages/tupaia-web/src/features/DashboardItem/DashboardItem.tsx, packages/tupaia-web/src/features/Visuals/Matrix.tsx, packages/tupaia-web/src/features/Visuals/View/DataDownload.tsx, packages/types/src/schemas/schemas.ts, packages/types/src/types/models-extra/dashboard-item/matricies.ts, packages/ui-components/src/components/Matrix/MatrixRow.tsx, packages/ui-components/src/components/Matrix/utils.ts
- Fix issue with broken matrix data
- Fix issue with position of dashboard menu arrow
- Fix broken data download
- Fix dashboard item sizing
- Fix dashboard menu size
=> WAITP-1231: dashboard item fixes

packages/tupaia-web/src/layout/ProjectCardList/ProjectCard.tsx, packages/tupaia-web/src/views/ProjectsModal.tsx
WAITP-1273 Projects Modal: Update project cards
- Updated mobile [design ](https://www.figma.com/file/Yak1TFptG2hWlq25uYlOcK/Tupaia-Mobile?node-id=947%3A697&mode=dev)
- More info on this [ticket](https://linear.app/bes/issue/WAITP-1273#comment-ed79df0e)
=> Waitp 1273 update project cards

packages/tupaia-web-server/examples.http, packages/tupaia-web-server/src/models/Entity.ts, packages/tupaia-web-server/src/models/index.ts, packages/tupaia-web-server/src/routes/EntitiesRoute.ts, packages/tupaia-web-server/src/routes/EntityAncestorsRoute.ts, packages/tupaia-web-server/src/routes/EntitySearchRoute.ts, packages/tupaia-web-server/src/types.ts, packages/tupaia-web-server/src/utils/generateFrontendExcludedFilter.ts
- Exclude certain types from entities response, as specified by `database`
=> WAITP-1211: Exclude certain types from response

packages/central-server/src/tests/apiV2/submitMeditrakSurveyResponse.test.js
- Fix issue where test was flaky and caused build to fail more often than not
=> No issue: Fix flaky test

packages/datatrak-web/src/components/Modal.tsx, packages/datatrak-web/src/components/index.ts, packages/datatrak-web/src/features/Survey/CancelSurveyModal.tsx, packages/datatrak-web/src/features/Survey/SurveyScreen.tsx
- Created reusable modal for `datatrak-web`
- Added cancel survey workflow
---
=> WAITP-1350: Cancel survey workflow

packages/devops/configs/servers.conf
(I don't know about Tupaia PR etiquette)
=> No issue: Enable nginx on-the-fly compression

packages/tupaia-web/src/features/Visuals/Matrix.tsx, packages/types/src/schemas/schemas.ts, packages/types/src/types/models-extra/dashboard-item/matricies.ts, packages/types/src/types/models-extra/report.ts, packages/ui-components/src/components/Matrix/EnlargedMatrixCell.tsx, packages/ui-components/src/components/Matrix/MatrixRow.tsx
- Make button on expandable matrix row headers full width and height of cell
- Fix issue where matrix wasn't handling values that were objects
- Fix handling of expanded category cells
=> Issue WAITP-1231: Matrix fixes

packages/devops/configs/servers.conf, packages/devops/scripts/deployment/setupGoldMaster.sh
=> No issue: Revert nginx changes

packages/tupaia-web/src/features/DashboardItem/DashboardItem.tsx, packages/tupaia-web/src/features/Map/MapOverlays/DataVisualsLayer/DataVisualsLayer.tsx, packages/tupaia-web/src/features/Map/MapOverlays/PolygonNavigationLayer.tsx, packages/tupaia-web/src/features/Map/utils/useMapOverlayData.ts, packages/tupaia-web/src/features/Visuals/Matrix.tsx, packages/tupaia-web/src/features/Visuals/View/SingleDate.tsx, packages/tupaia-web/src/features/Visuals/View/SingleValue.tsx, packages/tupaia-web/src/features/Visuals/View/View.tsx
- Fixed issue where titles weren't showing for multi single values correctly
- Fixed value formatting in matrix visuals
- Updated map overlay measure level handling for arrays
- Added 'no search result' message for matrix search
- Don't show data visuals layer when loading map overlay data
=> WAITP-1418: Misc FE fixes

packages/datatrak-web-server/tsconfig-build.json
- Update the build configuration to actually output files into the `dist` dir 🤪
=> No Issue: Update datatrak server build config

packages/central-server/src/createMeditrakSyncView.js, packages/central-server/src/database/meditrakSyncQueue/MeditrakSyncQueue.js, packages/central-server/src/database/models/Survey.js, packages/database/src/TupaiaDatabase.js, packages/database/src/modelClasses/Option.js, packages/database/src/modelClasses/OptionSet.js, packages/database/src/modelClasses/PermissionGroup.js, packages/database/src/modelClasses/Question.js, packages/database/src/modelClasses/Survey.js, packages/database/src/modelClasses/SurveyScreen.js, packages/database/src/modelClasses/SurveyScreenComponent.js, packages/database/src/modelClasses/index.js, packages/meditrak-app-server/package.json, packages/meditrak-app-server/src/__tests__/__integration__/sync/CountChangesRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/PullChangesRoute.test.ts, packages/meditrak-app-server/src/models/Survey.ts, packages/meditrak-app-server/src/models/index.ts, packages/meditrak-app-server/src/routes/UserRewardsRoute.ts, packages/meditrak-app-server/src/sync/MeditrakSyncRecordUpdater.ts, packages/meditrak-app-server/src/sync/SyncableChangeEnqueuer.ts, packages/meditrak-app-server/src/sync/createMeditrakSyncView.ts, packages/meditrak-app-server/src/sync/createPermissionsBasedMeditrakSyncQueue.ts, packages/meditrak-app-server/src/sync/index.ts, packages/meditrak-app-server/src/sync/types.ts, packages/meditrak-app-server/src/types.ts, packages/server-boilerplate/src/models/types.ts, tupaia-packages.code-workspace
**Task 1 of 3:**
This change is just to copy over all the existing logic to setup and manage the permissions based meditrak-sync-queue over to the `meditrak-app-server`.
=> RN-664: Convert SyncableChangeEnqueuer to manage permissions based sync

packages/expression-parser/package.json, packages/expression-parser/src/expression-parser/ExpressionParser.js, packages/report-server/package.json, packages/report-server/src/reportBuilder/transform/parser/functions/math.ts, yarn.lock
Not sure what changed, but everything works now
=> no-issue: Switched back to mainline mathjs and bumped version

packages/central-server/src/apiV2/export/exportSurveys/cellBuilders/questionConfigCellBuilders/QuestionConfigCellBuilder.js, packages/central-server/src/tests/apiV2/export/exportSurveys/cellBuilders/utilities.js
- Re-order params for the configCellBuilder
=> No-issue: Fix cell builder params disorder

packages/tupaia-web/index.html, packages/tupaia-web/src/Routes.tsx
=> WAITP-1421: Handle user request errors

packages/tupaia-web/src/api/mutations/useLogout.ts, packages/tupaia-web/src/features/EnlargedDashboardItem/EnlargedDashboardVisual.tsx, packages/tupaia-web/src/features/EntitySearch/SearchResults.tsx, packages/tupaia-web/src/views/ProjectsModal.tsx
- Redirect to home on logout
- Fix load more button on Entity Search
=> WAITP-1210: Tupaia-web frontend fixes

packages/devops/scripts/lambda/actions/swap_out_tupaia_server.py
=> RN-994 Auto cleanup old ec2s

packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapTableModal.tsx, packages/tupaia-web/src/features/Map/MapOverlays/DataVisualsLayer/PolygonLayer.tsx, packages/tupaia-web/src/features/Map/utils/useMapOverlayData.ts
- Fix issues in map flippa table display
- Fix issue where point and poly layers display at the same time sometimes unnecessarily
=> WAITP-1316: Map overlay table fixes

packages/lesmis/src/api/queries/useVitalsData.js
=> MDEV-189: Switch LESMIS vitals to using new vitals reports

packages/web-config-server/src/apiV1/measureData.js
The `displayOnLevel` map overlay config setting was introduced so that we can limit the amount of data we show on the map by filtering by this level. For instance if we have `displayOnLevel=SubDistrict` we'll only render facilities within the selected sub district.
We've always fetched data for the whole country though. At the time it was really just a frontend concern about rendering too many map overlay markers, but now that we're having backend lag due to the amount of data it makes sense if we just fetch data for the displayOnLevel too.
=> MDEV-190: Only fetch map overlay data at displayOnLevel

packages/datatrak-web-server/src/routes/SurveyRoute.ts, packages/datatrak-web/package.json, packages/datatrak-web/public/mockServiceWorker.js, packages/datatrak-web/src/main.tsx, packages/datatrak-web/src/mocks/browser.js, packages/datatrak-web/src/mocks/handlers.js, packages/datatrak-web/src/mocks/mockData/survey.json, packages/datatrak-web/src/mocks/mockData/surveyScreenComponents.json, yarn.lock
WAITP-1423: Add mock api with MSW
- Add mock api for testing in development
This could also be a good strategy for adding some front end unit tests later on.
---
=> WAITP-1423: Add mock api with MSW

packages/meditrak-app/package.json
Bump the android app version to 1.13.128
=> Bump version to 1.13.128

packages/tupaia-web/src/features/Map/MapOverlaySelector/MapTableModal.tsx, packages/tupaia-web/src/features/Map/utils/useMapOverlayTableData.ts, packages/tupaia-web/src/features/Visuals/Matrix.tsx, packages/ui-components/src/components/Matrix/CellButton.tsx, packages/ui-components/src/components/Matrix/MatrixCell.tsx, packages/ui-components/src/components/Matrix/MatrixRow.tsx, packages/ui-components/src/types/types.ts
- fixed issue where drilldown crashed matrix
- fixed incorrect order of matrix columns on flippa table
- fixed extra entity showing in project level overlay table
=> WAITP-1235: matrix qa fixes

packages/ui-components/src/components/Matrix/MatrixCell.tsx, packages/ui-components/src/components/Matrix/utils.ts
=> WAITP-1231: fix matrix chart display

packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Map/MapOverlaysLayer/MarkerLayer.tsx, packages/tupaia-web/src/features/Map/MapOverlaysLayer/PolygonLayer.tsx, packages/tupaia-web/src/layout/TopBar/TopBar.tsx
- Fix issue where shaded-spectrum map overlays were not displaying at facility level
- Fix dashboard scroll glitch
- Fix entity search dropdown z index
=> WAITP-1221: tupaia web front end fixes

packages/tupaia-web/src/features/Visuals/Matrix.tsx, packages/ui-components/src/components/Matrix/utils.ts, packages/ui-components/stories/matrix.stories.js
- Fix incorrect parsing to int instead of float
- Fix null handling
=> WAITP-1231: matrix visual bugs

packages/report-server/src/__tests__/reportBuilder/transform/parser/functions.test.ts, packages/report-server/src/reportBuilder/transform/parser/functions/basic.ts, packages/report-server/src/reportBuilder/transform/parser/functions/index.ts
Would be handy when you want all the unique values in a column (eg. when fetching data element names based on the data elements being used)
=> no-issue: Added 'unique' function to the viz-builder

packages/meditrak-app/android/app/src/main/AndroidManifest.xml, packages/meditrak-app/app/assessment/QrCodeScreen.js, packages/meditrak-app/app/main.js, packages/meditrak-app/app/utilities/writePermission/permission.android.js, packages/meditrak-app/app/utilities/writePermission/permission.ios.js, packages/meditrak-app/package.json, yarn.lock
PR for hotfix, reviewed here: https://github.com/beyondessential/tupaia/pull/5051
=> RN-1042 media perm

packages/report-server/src/__tests__/reportBuilder/transform/orderColumns.test.ts, packages/report-server/src/reportBuilder/transform/functions/orderColumns/orderColumns.ts, packages/report-server/src/reportBuilder/transform/functions/sortRows.ts, packages/report-server/src/reportBuilder/transform/functions/utils/transformValidators.ts
=> no-issue: Add direction field to orderColumns transform

packages/database/src/migrations/20231012204228-DetachTimorLesteFromEntityHierarchies-modifies-data.js
- Migration to remove `Timor-Leste` from entity hierarchies
We don't display `Timor-Leste` in the frontend for historic reasons. Let's just remove it from the hierarchies for the future
=> WAITP-1458 Detach Timor-Leste from entity hierarchies

packages/datatrak-web-server/src/routes/SurveysRoute.ts, packages/datatrak-web/package.json, packages/datatrak-web/src/api/queries/useAutocompleteOptions.ts, packages/datatrak-web/src/features/Questions/CheckboxQuestion.tsx, packages/datatrak-web/src/features/Questions/GeolocateQuestion/MapModal/Map.tsx, packages/datatrak-web/src/features/RequestProjectAccess/ProjectAccessForm.tsx, packages/datatrak-web/src/features/Survey/Components/SurveyQuestion.tsx, packages/datatrak-web/src/features/Survey/SurveyLayout.tsx, packages/datatrak-web/src/features/Survey/useValidationResolver.ts, packages/datatrak-web/src/features/Survey/utils.ts, packages/datatrak-web/src/layout/UserMenu/DrawerMenu.tsx, packages/datatrak-web/src/layout/UserMenu/MenuList.tsx, packages/datatrak-web/src/layout/UserMenu/PopoverMenu.tsx, packages/datatrak-web/src/layout/UserMenu/UserInfo.tsx, packages/datatrak-web/src/theme/theme.ts, packages/datatrak-web/src/views/LandingPage.tsx, packages/types/src/schemas/schemas.ts, packages/types/src/types/requests/datatrak-web-server/SurveyRequest.ts, yarn.lock
- Fix geolocate question accuracy
- Fix UI styling
- Change whole form validation to occur on the last survey page instead of review screen, using `yup`
=> WAITP-1454: design updates

packages/database/src/ModelRegistry.js, packages/database/src/testUtilities/buildAndInsertSurveys.js, packages/meditrak-app-server/src/__tests__/__integration__/sync/pullChanges/PullChangesRoute.test.ts, packages/meditrak-app-server/src/__tests__/__integration__/sync/pullChanges/fixtures.ts, packages/meditrak-app-server/src/__tests__/types.ts, packages/meditrak-app-server/src/routes/sync/pullChanges/PullChangesRoute.ts, packages/meditrak-app-server/src/sync/appSupportedModels.ts, packages/meditrak-app-server/src/sync/syncRecordTranslators/index.ts, packages/meditrak-app-server/src/sync/syncRecordTranslators/surveyScreenComponent.ts
Copied over logic from central-server for translation surveyScreenComponents when syncing to earlier versions of meditrak.
=> RN-1071: Copy surveyScreenComponent sync translation logic to meditrak-app-server

packages/central-server/src/apiV2/surveyResponse.js, packages/central-server/src/apiV2/surveyResponses/saveResponsesToDatabase.js, packages/central-server/src/tests/apiV2/surveyResponse.test.js, packages/meditrak-app-server/src/routes/sync/PushChangesRoute/populateData.ts, packages/types/src/schemas/schemas.ts, packages/types/src/types/requests/central-server/MeditrakSurveyResponseRequest.ts
=> RN-502: Made timestamp and optional field of a survey response

packages/datatrak-web/src/api/queries/index.ts, packages/datatrak-web/src/api/queries/useSurveyResponses.ts, packages/datatrak-web/src/components/Tile.tsx, packages/datatrak-web/src/components/index.ts, packages/datatrak-web/src/views/LandingPage.tsx
=> WAITP-1357: Recent surveys

packages/datatrak-web-server/src/app/createApp.ts
- Fixes 404 error in datatrak web
=> WAITP-1377 Forward signup route to web config server

packages/ui-chart-components/src/components/CartesianChart.tsx
=> WAITP-1459: Remove brush from charts

packages/central-server/src/apiV2/surveyResponses/saveResponsesToDatabase.js, packages/central-server/src/dataAccessors/upsertAnswers.js, packages/datatrak-web-server/src/utils/processSurveyResponse.ts, packages/datatrak-web/src/features/Questions/PhotoQuestion.tsx, packages/datatrak-web/src/features/Questions/index.ts, packages/datatrak-web/src/features/Survey/Components/SurveyQuestion.tsx, packages/ui-components/src/components/ConfirmDeleteModal.tsx, packages/ui-components/src/components/Inputs/ImageUploadField.tsx
- Added photo question to `datatrak-web`
- Updated `ImageUploadField` in `ui-components` to fix issue where clicking the 'delete' button triggered file explorer to open, and added a few new optional props
- Updated comments in backend
Note: This will not look like the design because creating a drag and drop file upload is out of scope of this ticket, so we are using the existing input from `ui-components`
---
=> WAITP-1415: Photo upload question

packages/datatrak-web-server/src/__tests__/utils/processSurveyResponse.test.ts, packages/datatrak-web-server/src/types.ts, packages/datatrak-web-server/src/utils/buildUpsertEntity.ts, packages/datatrak-web-server/src/utils/processSurveyResponse.ts, packages/meditrak-app-server/src/routes/sync/PushChangesRoute/translateInboundSurveyResponse.ts, packages/types/src/schemas/schemas.ts, packages/types/src/types/requests/central-server/MeditrakSurveyResponseRequest.ts
Ran into some issues with tests failing for `datatrak-web-server` [here](https://github.com/beyondessential/tupaia/actions/runs/6540366652/job/17760151802?pr=5007) so updated some of the types there.
=> no-issue: Update MeditrakSurveyResponseRequest type

packages/tupaia-web-server/src/routes/DashboardsRoute.ts
- Use explicit type declarations
- Strip 'model' from Dashboards before returning
=> WAITP-1366 Bugfix circular recursion in tupaia-web-server

packages/datatrak-web-server/src/__tests__/utils/processSurveyResponse.test.ts, packages/datatrak-web-server/src/types.ts, packages/datatrak-web-server/src/utils/buildUpsertEntity.ts, packages/datatrak-web-server/src/utils/processSurveyResponse.ts, packages/meditrak-app-server/src/routes/sync/PushChangesRoute/translateInboundSurveyResponse.ts, packages/tupaia-web-server/src/routes/DashboardsRoute.ts, packages/tupaia-web/src/features/Visuals/View/DownloadFiles.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/Carousel.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/MultiPhotograph.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/MultiPhotographEnlarged.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/MultiPhotographPreview.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/index.ts, packages/tupaia-web/src/features/Visuals/View/View.tsx, packages/types/src/schemas/schemas.ts, packages/types/src/types/requests/central-server/MeditrakSurveyResponseRequest.ts
=> rn-1052-improve-ent-disp

packages/api-client/src/connections/DataTableApi.ts
Fix for a bug that snuck in due to stricter validation of the DataTable type
=> no-issue: Fixed error in dataTable/builtInParams

packages/tupaia-web-server/src/routes/LegacyDashboardReportRoute.ts, packages/tupaia-web/src/api/queries/useReport.ts, packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Dashboard/DashboardMenu.tsx, packages/tupaia-web/src/features/DashboardItem/DashboardItemContent.tsx, packages/tupaia-web/src/features/EnlargedDashboardItem/utils/useEnlargedDashboardItem.ts, packages/tupaia-web/src/features/Map/Map.tsx, packages/tupaia-web/src/features/Map/MapWatermark.tsx, packages/tupaia-web/src/features/Visuals/Matrix/Matrix.tsx, packages/tupaia-web/src/features/Visuals/Matrix/MatrixPreview.tsx, packages/tupaia-web/src/features/Visuals/Matrix/index.ts, packages/ui-components/src/components/Matrix/MatrixNavButtons.tsx
- Fix Matrix mobile screen warning
- Always use expanded state data for dashboard item reports
- Fix some styling issues
- Add mapbox attribution
=> WAITP-1418: rewrite fixes

packages/datatrak-web/src/features/Survey/useValidationResolver.ts
- Fixed issue where validation did not always handle geolocate questions and their `object` shape correctly
=> WAITP-1327: Fix validation on geolocate questions

packages/tupaia-web/src/AppProviders.tsx, packages/tupaia-web/src/features/Map/Map.tsx, packages/tupaia-web/src/features/Map/MapLegend/MapLegend.tsx, packages/tupaia-web/src/features/Map/MapLegend/MobileMapLegend.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MapOverlayList.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MobileMapOverlaySelector.tsx, packages/tupaia-web/src/features/Map/MapWatermark.tsx, packages/tupaia-web/src/utils/getTopBarHeight.ts, packages/ui-components/src/components/EnvBanner.tsx, packages/ui-map-components/src/components/Legend/Legend.tsx, packages/ui-map-components/src/components/Legend/SpectrumLegend.tsx, packages/web-frontend/src/components/mobile/MapAttribution.js
Fixes issues 6-12 that were raised in this ticket https://linear.app/bes/issue/WAITP-1214/mobile-dashboard-and-map-tabs
---
=> WAITP-1214: Mobile dashboard tabs fixes

packages/tupaia-web/src/api/mutations/useLogout.ts, packages/tupaia-web/src/api/mutations/useRequestCountryAccess.ts, packages/tupaia-web/src/api/queries/useLandingPage.ts, packages/tupaia-web/src/features/Map/utils/useNavigateToEntity.ts, packages/tupaia-web/src/layout/TopBar/Logo.tsx, packages/tupaia-web/src/layout/TopBar/TopBar.tsx, packages/tupaia-web/src/views/RequestProjectAccessModal/ModalHeader.tsx, packages/tupaia-web/src/views/RequestProjectAccessModal/ProjectAccessForm.tsx, packages/tupaia-web/src/views/RequestProjectAccessModal/RequestProjectAccessModal.tsx, packages/tupaia-web/src/views/RequestProjectAccessModal/RequestedCountries.tsx
- Fixed QA issues noted [here](https://linear.app/bes/issue/WAITP-1216/navigation-custom-landing-pages)
- Fixed issue where navigating to an entity via the map didn't reset the map overlay period, resulting in incorrect data
=> WAITP-1216: QA fixes

packages/datatrak-web/src/api/mutations/index.ts, packages/datatrak-web/src/api/mutations/useOneTimeLogin.ts, packages/datatrak-web/src/views/ResetPasswordPage.tsx, packages/ui-components/src/features/Auth/ResetPasswordForm/ResetPasswordForm.tsx
- Run one time login before presenting reset password form
=> WAITP-1276: Update datatrak reset password flow

packages/tupaia-web/src/api/api.ts, packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Dashboard/StaticMap.tsx, packages/tupaia-web/src/features/EnlargedDashboardItem/ExportDashboardItem.tsx, packages/tupaia-web/src/features/EnlargedDashboardItem/utils/useEnlargedDashboardItem.ts, packages/tupaia-web/src/features/Map/Map.tsx, packages/tupaia-web/src/features/Visuals/Chart.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/Carousel.tsx, packages/tupaia-web/src/views/LandingPage/LandingPage.tsx, packages/ui-components/src/components/Matrix/Matrix.tsx, packages/ui-components/src/components/NoData.jsx
- Fix issue with drilldown matrices not displaying correctly
- Redirect on landing page name being invalid
- Update no data message when no dates entered
- Update mobile export styling
- Fix missing entity images
- Update zoom level on point entities
- Add scroll to photo gallery carousel
- Fix error formatting
=> WAITP-1418: Misc QA updates

packages/ui-components/src/components/EnvBanner.tsx
=> No-issue: fix env banner

packages/datatrak-web/src/features/Leaderboard/Leaderboard.tsx, packages/datatrak-web/src/features/Leaderboard/UserRewardsSection.tsx, packages/datatrak-web/src/features/Survey/Components/SurveyQuestion.tsx, packages/datatrak-web/src/features/Survey/useValidationResolver.ts, packages/datatrak-web/src/features/Survey/utils.ts
- Remove unnecessary question name exception from Primary Entity question
- Fix user rewards types
=> WAITP-1424: Datatrak PrimaryEntity question fix

packages/tupaia-web/src/ModalRoutes.tsx, packages/tupaia-web/src/Routes.tsx, packages/tupaia-web/src/api/mutations/useLogout.ts, packages/tupaia-web/src/api/queries/useEntity.ts, packages/tupaia-web/src/api/queries/useLandingPage.ts, packages/tupaia-web/src/features/Map/MapWatermark.tsx, packages/tupaia-web/src/features/Visuals/Matrix/Matrix.tsx, packages/tupaia-web/src/layout/MainLayout.tsx, packages/tupaia-web/src/layout/TopBar/Logo.tsx, packages/tupaia-web/src/layout/TopBar/TopBar.tsx, packages/tupaia-web/src/layout/UserMenu/UserMenu.tsx, packages/tupaia-web/src/views/LandingPage/LandingPage.tsx, packages/tupaia-web/src/views/RequestProjectAccessModal/RequestProjectAccessModal.tsx, packages/tupaia-web/src/views/RequestProjectAccessModal/RequestedCountries.tsx
- Fix matrix mobile screen warning
- Fix landing page regressions and integrate url params into useLandingPage hook
- Fix permissions entity error handling
=> WAITP-1366: tupaia web fe fixes

packages/datatrak-web/src/Routes.tsx, packages/datatrak-web/src/api/mutations/useLogin.ts, packages/datatrak-web/src/views/ProjectSelectPage.tsx
- Redirect after login to deep linked url, and after project select
=> No issue: Login redirect

packages/tupaia-web/src/features/DashboardItem/ExpandItemButton.tsx, packages/tupaia-web/src/features/Map/MapLegend/MobileMapLegend.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MobileMapOverlaySelector.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/Carousel.tsx, packages/tupaia-web/src/features/Visuals/View/View.tsx, packages/tupaia-web/src/layout/TopBar/TopBar.tsx, packages/tupaia-web/src/layout/UserMenu/MenuList.tsx, packages/tupaia-web/src/layout/UserMenu/UserInfo.tsx
- Center text on download links
- Fix expand button appearing when shouldn't
- Hide map legend button when in overlay library
- Fix legend coloring
- Fix expanded photo hiding close button
- Fix custom landing page alignments
=> WAITP-1239: visuals fixes

packages/central-server/src/apiV2/meditrakApp/getUserRewards.js, packages/central-server/src/social/getRewardsForUser.js, packages/database/src/migrations/20231112212117-AddProjectIdToSurveys-modifies-schema.js, packages/database/src/modelClasses/SurveyResponse.js, packages/datatrak-web-server/src/routes/LeaderboardRoute.ts, packages/datatrak-web-server/src/routes/RecentSurveysRoute.ts, packages/datatrak-web-server/src/routes/SurveyResponsesRoute.ts, packages/datatrak-web-server/src/routes/SurveysRoute.ts, packages/datatrak-web/src/api/queries/useLeaderboard.ts, packages/datatrak-web/src/api/queries/useRecentSurveys.ts, packages/datatrak-web/src/api/queries/useSurveyResponses.ts, packages/datatrak-web/src/api/queries/useSurveys.ts, packages/datatrak-web/src/api/queries/useUserRewards.ts, packages/datatrak-web/src/features/Leaderboard/LeaderboardTable.tsx, packages/datatrak-web/src/views/SurveySelectPage/SurveySelectPage.tsx, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts, packages/types/src/types/requests/datatrak-web-server/LeaderboardRequest.ts, packages/types/src/types/requests/datatrak-web-server/RecentSurveysRequest.ts, packages/types/src/types/requests/datatrak-web-server/SurveyRequest.ts, packages/types/src/types/requests/datatrak-web-server/SurveyResponsesRequest.ts
- Add migration for project_id column in surveys
- Update queries that relate to surveys to allow for optional projectId filter
=> WAITP-1490: project id for surveys

packages/admin-panel/src/pages/resources/SurveysPage.jsx
- Add project column to surveys on admin panel
---
=> WAITP-1389: Add project column to admin panel

README.md
- Added Browserstack test text in `ReadME` file
=> No issue: Browserstack test

packages/datatrak-web-server/src/routes/SurveysRoute.ts, packages/datatrak-web/src/api/index.ts, packages/datatrak-web/src/api/queries/useRecentSurveys.ts, packages/datatrak-web/src/api/queries/useSurveyResponses.ts, packages/datatrak-web/src/api/queries/useUserRewards.ts
=> WAITP-1431: Fix survey select filter

packages/admin-panel/src/pages/resources/SurveysPage.jsx, packages/central-server/src/apiV2/surveys/CreateSurvey.js, packages/central-server/src/apiV2/surveys/EditSurvey.js, packages/central-server/src/apiV2/surveys/convertFieldsToIds.js, packages/central-server/src/apiV2/surveys/surveyEditor/SurveyEditor.js, packages/central-server/src/apiV2/utilities/constructNewRecordValidationRules.js, packages/central-server/src/tests/apiV2/surveys/CreateAndEditSurveys.test.js
- Added project field to edit/create survey in admin panel
---
=> WAITP-1387: Add survey project field

packages/datatrak-web/src/api/mutations/useLogin.ts, packages/datatrak-web/src/utils/index.ts, packages/datatrak-web/src/utils/useFromLocation.ts, packages/datatrak-web/src/views/ProjectSelectPage.tsx
Extract fetching of `location.state.from` to `useFromLocation()` hook.
Co-authored with @tcaiger.
=> no-issue: Fix `location.state` null

packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Dashboard/DashboardMenu.tsx, packages/tupaia-web/src/features/Dashboard/Media.tsx, packages/tupaia-web/src/features/Dashboard/Photo.tsx, packages/tupaia-web/src/features/Dashboard/StaticMap.tsx, packages/tupaia-web/src/features/DashboardItem/ExpandItemButton.tsx, packages/tupaia-web/src/features/Map/Map.tsx, packages/tupaia-web/src/features/Map/MapLegend/MapLegend.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/MobileMapOverlaySelector.tsx, packages/tupaia-web/src/features/Map/MapOverlaysLayer/MapOverlaysLayer.tsx, packages/tupaia-web/src/features/Map/MapWatermark.tsx, packages/tupaia-web/src/features/Visuals/Matrix/Matrix.tsx, packages/tupaia-web/src/features/Visuals/View/MultiPhotograph/Carousel.tsx, packages/tupaia-web/src/layout/TopBar/Logo.tsx, packages/ui-components/src/components/Matrix/Matrix.tsx, packages/ui-components/src/components/Matrix/MatrixRow.tsx
- Fixed issue where some visualisations weren't expandable
- Fixed styling of dashboard menu
- Fixed zoom issue
- Fix mobile map layout
=> WAITP-1221: Misc overlay fixes

packages/central-server/src/database/models/Question.js, packages/database/src/DatabaseModel.js, packages/database/src/modelClasses/AncestorDescendantRelation.js, packages/database/src/modelClasses/Entity.js, packages/database/src/runPostMigration.js
- Change the exclusion list to an allow list for tables that require triggers.
=> RN-865: Trigger adding looks at allow list instead of block list

packages/tupaia-web/src/features/Map/utils/useMapOverlayMapData.ts
- If an entity is selected that is non-spatial, and has non-spatial parents, map overlays should be handled differently, but getting the correct 'root' entity to fetch the data for the map overlay
=> WAITP-1499: Handle when entities are non-spatial

packages/tupaia-web-server/src/routes/MapOverlaysRoute.ts
- Don't filter out project level map overlays
=> WAITP-1221 Don't filter out project level overlays

packages/database/src/migrations/20231120003955-CreateDuplicateSurveys-modifies-data.js, packages/database/src/migrations/migrationData/20231120003955-CreateDuplicateSurveys/surveys.json
- Created a migration for duplicating surveys as specified in spreadsheet
=> WAITP-1480: survey duplication

packages/central-server/src/social/getRewardsForUser.js, packages/central-server/src/tests/apiV2/GETSurveyResponses.test.js
=> Release 2023 47 1 hotfix 1

packages/datatrak-web/index.html, packages/datatrak-web/src/api/mutations/useLogin.ts, packages/datatrak-web/src/api/mutations/useSubmitSurvey.ts, packages/datatrak-web/src/utils/ga.ts, packages/datatrak-web/src/utils/index.ts
- Added GA setup to Datatrak Web
=> WAITP-1464: google analytics setup

packages/tupaia-web/src/api/api.ts, packages/tupaia-web/src/api/mutations/useDownloadRawData.ts, packages/tupaia-web/src/features/Dashboard/Breadcrumbs.tsx, packages/tupaia-web/src/features/Dashboard/Media.tsx, packages/tupaia-web/src/features/Map/MapOverlaysLayer/MapOverlaysLayer.tsx, packages/tupaia-web/src/features/Map/MapOverlaysLayer/PolygonLayer.tsx, packages/tupaia-web/src/features/Map/utils/processMeasureData.ts, packages/tupaia-web/src/features/Map/utils/useMapOverlayMapData.ts, packages/tupaia-web/src/features/Map/utils/useMapOverlayTableData.ts, packages/tupaia-web/src/views/LandingPage/SingleProjectLandingPage.tsx, packages/tupaia-web/src/views/LoginModal.tsx, packages/ui-map-components/src/components/AreaTooltip.tsx, packages/web-config-server/src/apiV1/permissions/ExportSurveyResponsesPermissionsChecker.js
- Fixed issue where overlay labels were not being removed when data was loaded
- Updated hover colour for landing page project button
- Set entity polygons to show when overlay data is loading
- Fixed issue where error message was not showing on login
- Fixed issue with raw data downloads
=> WAITP-1418: misc qa changes

packages/admin-panel/src/pages/resources/DashboardMailingListsPage.jsx, packages/admin-panel/src/pages/resources/index.js, packages/admin-panel/src/routes.jsx, packages/central-server/src/apiV2/dashboardMailingListEntries/GETDashboardMailingListEntries.js, packages/central-server/src/apiV2/dashboardMailingLists/CreateDashboardMailingList.js, packages/central-server/src/apiV2/index.js, packages/central-server/src/tests/apiV2/dashboardMailingListEntries/GETDashboardMailingListEntries.test.js, packages/central-server/src/tests/apiV2/dashboardMailingLists/CreateDashboardMailingList.test.js
=> RN-1092: Add Dashboard Mailing List page to the Admin Panel

packages/tupaia-web/src/features/Map/utils/processMeasureData.ts
- Fix issue with 'no data' colour not showing up correctly
=> WAITP-1221: Fix issue where no data wasn't showing correctly

packages/tupaia-web/src/features/Dashboard/ExportDashboard/ExportDashboard.tsx, packages/tupaia-web/src/features/Dashboard/ExportDashboard/Preview.tsx, packages/tupaia-web/src/features/Dashboard/ExportDashboard/SelectVisualisations.tsx, packages/tupaia-web/src/features/Dashboard/ExportDashboard/index.ts, packages/tupaia-web/src/features/PDFExportDashboardItem/PDFExportDashboardItem.tsx, packages/tupaia-web/src/views/PDFExport.tsx, packages/ui-components/src/components/DataTable/DataTable.tsx, packages/ui-components/src/components/PDFExportComponent.tsx
Added the preview and a stub 'Export Settings' section.
See screenshots in the ticket.
=> RN-1049: Add preview screen to whole dashboard export

packages/datatrak-web/src/features/Survey/SurveyContext/utils.ts
- Fix issue where visibility criteria questions weren't resetting questions on value change
=> WAITP-1416: Visibility criteria fix

packages/tupaia-web/src/api/api.ts, packages/tupaia-web/src/constants/mapbox.ts, packages/tupaia-web/src/features/Map/Map.tsx
- Add custom tilesets
- Handle error message not showing for data downloads
=> WAITP-1418: rewrite updates

packages/tupaia-web/src/features/Dashboard/Breadcrumbs.tsx
=> WAITP-1418: Update breadcrumbs gradient

packages/tupaia-web/src/features/Map/MapOverlaysLayer/MapOverlaysLayer.tsx, packages/tupaia-web/src/features/Map/utils/useMapOverlayMapData.ts
- Fix issue with logic with `displayOnLevel` setting
=> HOTFIX: Fix displayOnLevel logic

packages/tupaia-web/src/features/Visuals/Chart.tsx
- Allow overflow of chart table when not being exported
=> Hotfix: Fix chart table overflow

packages/tupaia-web/src/features/Map/MapOverlaysLayer/PolygonLayer.tsx, packages/tupaia-web/src/features/Map/utils/useMapOverlayMapData.ts
=> Release Fix: Dedupe navigation entity requests

packages/tupaia-web/src/api/api.ts, packages/tupaia-web/src/features/Dashboard/ExportDashboard/Preview.tsx, packages/tupaia-web/src/views/PDFExport.tsx
- Fix export background issue for mobile
- Fix error messages
=> Release 2023 49 fix 5

packages/datatrak-web/src/layout/UserMenu/MenuList.tsx
- Fix error that occurred on Datatrak when opening user menu
=> No issue: Fix link issue

packages/ui-components/src/features/Auth/ForgotPasswordForm.tsx, packages/ui-components/src/features/Auth/LoginForm.tsx, packages/ui-components/src/features/Auth/RegisterForm.tsx, packages/ui-components/src/features/Auth/ResendVerificationEmailForm.tsx, packages/ui-components/src/features/Auth/ResetPasswordForm/PasswordForm.tsx
- Remove password validation rules from datatrak login form so that passwords that were created seperate to the tupaia password policy still work
- Add Field id prop for accessibility on ui component forms
=> No issue fix datatrak login validation

packages/datatrak-web/src/components/SelectList/ListItem.tsx
- Fix icons not appearing in Safari on select list
=> WAITP-1520: Fix safari icons not showing

packages/devops/configs/pm2/datatrak.config.js
Added `web-config-server` to DataTrak’s PM2 config.
=> no-issue: Fix DataTrak local deployment for devs

vite.config.js
=> No-issue: Fix for vite to open localhost

packages/datatrak-web/src/layout/UserMenu/DrawerMenu.tsx, packages/tupaia-web/index.html, packages/tupaia-web/src/features/Dashboard/ExpandButton.tsx, packages/tupaia-web/src/features/Dashboard/StaticMap.tsx, packages/tupaia-web/src/features/EnlargedDashboardItem/BackLink.tsx, packages/tupaia-web/src/features/Map/MapOverlaySelector/DesktopMapOverlaySelector.tsx, packages/tupaia-web/src/features/Map/MapWatermark.tsx, packages/tupaia-web/src/layout/UserMenu/UserMenu.tsx, packages/ui-components/src/components/IconButton.tsx, packages/ui-components/src/components/Loaders/SpinningLoader.tsx
- Add logic to stop css files render-blocking
- Add button titles
- Add loader aria label
- Add default static map bounds
=> WAITP-1518: Tupaia Web small Lighthouse fixes

packages/datatrak-web/src/__tests__/survey.test.tsx, packages/datatrak-web/src/components/TextInput.tsx, packages/datatrak-web/src/features/Questions/AutocompleteQuestion.tsx, packages/datatrak-web/src/features/Questions/EntityQuestion/EntityQuestion.tsx, packages/datatrak-web/src/features/Questions/EntityQuestion/SearchField.tsx, packages/datatrak-web/src/features/Questions/PhotoQuestion.tsx, packages/datatrak-web/src/features/Questions/RadioQuestion.tsx, packages/datatrak-web/src/features/Questions/TextQuestion.tsx, packages/datatrak-web/src/features/Survey/Components/SurveyQuestionGroup.tsx
- Plumbed in required form label asterisks for questions
=> WAITP-1513: Add asterisk where questions are required

packages/ui-components/src/components/Inputs/ImageUploadField.tsx
- Fix issue where image upload field was causing a scroll on datatrak when file picker was opening
=> RN-1126: Fix image upload field scroll issue

packages/tupaia-web/src/features/PDFExportDashboardItem/PDFExportDashboardItem.tsx, packages/tupaia-web/src/features/PDFExportDashboardItem/PDFExportHeader.tsx, packages/ui-components/src/__tests__/components/DateRangePicker/DateRangePicker.test.js, packages/ui-components/src/components/DateRangePicker/useDateRangePicker.tsx, packages/ui-components/src/components/PDFExportComponent.tsx, packages/web-frontend/src/tests/components/dateRangePicker.test.js
Reverts beyondessential/tupaia#5330
Needs to be tested!
=> Revert "RN-998: Logo on export"

README.md
=> PrAnother change

packages/server-utils/src/sendEmail.ts
=> no-issue: Change the name that appears in the email inbox to Tupaia

packages/ui-components/src/features/Auth/RegisterForm.tsx
Added `autocomplete` attributes to the registration form in DataTrak. This behaviour will match the upcoming **Change personal details** account settings section in #5169.
=> no-issue: DataTrak registration autocomplete

packages/tupaia-web/src/features/Visuals/Matrix/Matrix.tsx
- Fixed issue where an error occurred because of hook reordering for the matrix
=> Fix issue with hook reordering in loading states

packages/datatrak-web/src/features/Survey/useValidationResolver.ts
- Fix issue where old autocomplete validation causes error
=> No issue: Remove unnecessary autocomplete validation

packages/ui-chart-components/src/components/Charts/PieChart.tsx
- Fix issue where legend on pie chart was not appearing correctly
=> No issue: Fix broken legend

packages/devops/scripts/lambda/actions/spin_up_tupaia_deployment.py
=> RN-954: Change DB default size

packages/ui-chart-components/src/components/Axes/VerticalTick.tsx
- Fix issue where numbers were being passed to a string truncate function and breaking exports on LESMIS
=> No issue: Fix broken LESMIS exports

packages/lesmis/src/views/AdminPanel/components/ApproveButton.jsx, packages/lesmis/src/views/AdminPanel/components/RejectButton.jsx
- Fixed broken LESMIS deployments from admin panel causing deployments to break
=> No issue: Fix LESMIS imports breaking deployments

scripts/bash/downloadEnvironmentVariables.sh
- There is an issue where a script that works for mac doesn't work for linux, which causes deployments to fail. This fixes that.
=> fix(environmentVariables): RN-1225: Fix linux/unix discrepancy

.github/workflows/ci.yaml, packages/admin-panel-server/src/app/createApp.ts, packages/central-server/src/apiV2/deleteAccount.js, packages/central-server/src/apiV2/middleware/auth/clientAuth.js, packages/central-server/src/apiV2/requestCountryAccess.js, packages/central-server/src/ms1/api/Ms1Api.js, packages/datatrak-web-server/src/app/createApp.ts, packages/datatrak-web-server/src/app/middleware/attachAccessPolicy.ts, packages/lesmis-server/src/app/createApp.ts, packages/lesmis-server/src/connections/CentralConnection.ts, packages/lesmis-server/src/connections/EntityConnection.ts, packages/lesmis-server/src/connections/ReportConnection.ts, packages/lesmis-server/src/connections/SessionHandlingApiConnection.ts, packages/lesmis-server/src/connections/WebConfigConnection.ts, packages/psss-server/src/connections/CentralConnection.ts, packages/psss-server/src/connections/EntityConnection.ts, packages/psss-server/src/connections/ReportConnection.ts, packages/server-boilerplate/src/orchestrator/auth/AuthConnection.ts, packages/server-utils/src/sendEmail.ts, packages/tupaia-web-server/src/app/createApp.ts, packages/web-config-server/src/appServer/requestHelpers/fetchFromCentralServer.js, packages/web-config-server/src/connections/ReportConnection.js
- Fix issue with missing env vars and order of env vars being fetched
=> fix(environment): use requireEnv and catch errors when missing an env var

packages/admin-panel/src/VizBuilderApp/constants.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models-extra/dashboard-item/views/views.ts
=> fix(vizBuilder): Fix schema validator for dataDownload view

packages/database/src/TupaiaDatabase.js
Add support for lookup as json as well as text
=> fix(adminPanel): Fix UsedBy queries for data elements and data-tables

packages/datatrak-web/src/features/Survey/Screens/SurveyScreen.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/reducer.ts
This ticket hasn’t been tested yet
=> revert(datatrakWeb): #5576

packages/admin-panel/src/VizBuilderApp/views/CreateNew.jsx
- Fixed issue with overflow/scroll in viz builder create page
=> fix(adminPanel): Fix vertical scroll in viz builder

packages/admin-panel/src/layout/navigation/NavPanel.jsx
- Update hover state of nav panel as per design
=> tweak(adminPanel): RN-1292: Update hover styling for admin nav panel

packages/admin-panel/src/layout/navigation/HomeLink.jsx
- Removed hover state for home link
=> tweak(adminPanel): RN-1298: Remove home link hover state

packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web/src/features/EnlargedDashboardItem/ExportDashboardItem.tsx
- Add in export url to explicitly get forwarded to `web-config-server`
- Fix shrinking modal when exporting
=> fix(tupaiaWeb): Hotfix: Fix export matrix errors

packages/admin-panel/src/VizBuilderApp/components/Modal/SaveVisualisationModal.jsx
- Fix issue with undefined component
=> fix(adminPanel): FIx undefined component

packages/data-lake-api/scripts/checkTestDataLakeExists.sh, packages/database/scripts/checkTestDatabaseExists.sh, packages/database/scripts/dumpDatabase.sh
There still some remaining references in the docker deployment code, but all that's being left on ice until Felix picks it up so leaving as is for now.
=> tweak: Rename some references to Lastpass -> Bitwarden

packages/admin-panel-server/src/app/createApp.ts, packages/admin-panel/src/api/mutations/useRequestResetPassword.js, packages/datatrak-web/src/api/mutations/useRequestResetPassword.ts, packages/server-boilerplate/src/orchestrator/api/ApiBuilder.ts, packages/server-boilerplate/src/orchestrator/auth/AuthConnection.ts, packages/server-boilerplate/src/orchestrator/routes/RequestResetPasswordRoute.ts, packages/server-boilerplate/src/orchestrator/routes/index.ts, packages/server-boilerplate/src/orchestrator/types.ts, packages/tupaia-web-server/src/app/createApp.ts, packages/tupaia-web/src/api/mutations/useRequestResetPassword.ts, packages/web-config-server/src/apiV1/index.js, packages/web-config-server/src/appServer/handlers/requestResetPassword.js, packages/web-config-server/src/appServer/index.js, packages/web-config-server/src/appServer/routes.js
- Update server-boilerplate to handle `requestResetPassword` route and not attempt to use session here
=> tweak(serverBoilerplate): RN-1295: Bypass session handling for request reset password route

packages/admin-panel/src/layout/Page.jsx
- Reduce width of nav panel in admin panel
=> tweak(adminPanel): RN-1317: Reduce nav panel width

packages/admin-panel/src/layout/Breadcrumbs.jsx
- Update breadcrumb styles on admin panel
=> tweak(adminPanel): RN-1319: Update breadcrumb styles

packages/admin-panel/src/table/DataFetchingTable/DataFetchingTable.jsx
- Stringify basefilter param in `useEffect` to stop infinite reload on LESMIS admin panel
=> fix(LESMIS): Fix infinite reload on table on LESMIS admin panel

packages/admin-panel/src/layout/AppPageLayout.jsx, packages/admin-panel/src/layout/navigation/NavPanel.jsx
- Make animation on nav panel match Tamanu, as requested by Georgia
=> tweak(adminPanel): RN-1318: Change animation for nav menu

packages/admin-panel/src/VizBuilderApp/components/NavPanel.jsx, packages/admin-panel/src/layout/AppPageLayout.jsx, packages/admin-panel/src/layout/navigation/NavPanel.jsx, packages/admin-panel/src/main.jsx
- Fix overflow issue when env banner is present
- Fix padding on nav in viz builder
=> fix(adminPanel): Fix env banner scroll

yarn.lock
Ran `yarn dlx update-browserslist-db@latest` to suppress build warnings about outdated browsers list
=> deps: update browserslist

packages/tupaia-web/src/theme/theme.ts, packages/ui-components/src/components/Matrix/Cell.tsx, packages/ui-components/src/components/Matrix/Matrix.tsx, packages/ui-components/src/components/Matrix/MatrixHeader.tsx, packages/ui-components/src/components/Matrix/MatrixRow.tsx
- Fixed styling on nested columns
---
=> fix(tupaiaWeb): RN-1237: Fix styling for nested columns

.prettierrc.js, packages/datatrak-web/.prettierrc, packages/datatrak-web/.prettierrc.js
- Updated prettier files to be `.js` so can extend common one in `datatrak-web`, as was not being pulled through
=> fix(datatrakWeb): Fix prettier overrides

packages/ui-components/src/features/Auth/LoginForm.tsx
Adds `autocomplete` attributes to login form fields in `ui-components` for nicer browser and password manager support.
https://www.chromium.org/developers/design-documents/create-amazing-password-forms
=> tweak: Login form autocomplete

packages/admin-panel/src/layout/navigation/HomeLink.jsx
=> fix(adminPanel): Fix broken logo link

packages/admin-panel/src/routes/visualisations/dashboards.js, packages/admin-panel/src/routes/visualisations/mapOverlayGroupRelations.js, packages/admin-panel/src/routes/visualisations/mapOverlayGroups.js
Added a <kbd>Delete</kbd> action in drilled down views:
- Dashboards → Dashboard relations
- Map overlay groups → Map overlay group relations
=> feat(adminPanel): MDEV-236: delete action for drilled-down relations 

packages/datatrak-web/src/api/mutations/useCreateTask.ts
=> feat(datatrak): RN-1357: Task created toast message

packages/database/src/migrations/20240724001022-AddTaskAndUserQuestionTypes-modifies-schema.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/index.ts, packages/types/src/types/models-extra/index.ts, packages/types/src/types/models-extra/survey/index.ts, packages/types/src/types/models-extra/survey/surveyScreenComponent.ts, packages/types/src/types/models.ts
- Added a migration for task and user question types
- Added config types for task and user questions
=> feat(datatrakWeb): RN-1381: Add new question types

packages/admin-panel/src/routes/projects/projects.js
- update 'Add project' fields for baseline consistency
- see full conversation on [Slack](https://beyondessential.slack.com/archives/C01MAA3NKM1/p1722229172731909)
=> fix(adminPanel): RN-1375: update 'Add' project editor for consistency

packages/datatrak-web/src/features/Tasks/CancelTaskModal.tsx, packages/datatrak-web/src/features/Tasks/TaskActionsMenu.tsx, packages/datatrak-web/src/features/Tasks/TaskSummary.tsx, packages/datatrak-web/src/features/Tasks/TasksTable/AssignTaskModal.tsx, packages/datatrak-web/src/features/Tasks/TasksTable/TasksTable.tsx
The design for the Cancel Task Modal was updated to match the Assign Task Modal - this PR updates the UI to match the new design.
---
=> feat(datatrak) RN-1340: Cancel task modal design update

packages/meditrak-app/android/app/build.gradle, packages/meditrak-app/android/build.gradle, packages/meditrak-app/ios/TupaiaMediTrak.xcodeproj/project.pbxproj, packages/meditrak-app/package.json
- Bump Meditrak target Android version to 14 (API level 34)
---
=> feat(meditrakApp): RN-1389: Bump Meditrak target Android version to 14 (API level 34)

packages/admin-panel/src/importExport/ExportButton.jsx, packages/ui-components/src/components/FilterableTable/FilterCell.tsx
- updated download icon as per Figma UI layout
- upated search icon color as per Figma UI layout
---
=> tweak(adminPanel): RN-1399: Update icon and color as per Figma layouts

packages/database/src/__tests__/changeHandlers/TaskCreationHandler.test.js, packages/database/src/changeHandlers/TaskCreationHandler.js, packages/database/src/migrations/20240806015831-AddTaskInitialRequestId-modifies-schema.js, packages/datatrak-web-server/src/routes/TaskRoute.ts, packages/datatrak-web-server/src/routes/TasksRoute.ts, packages/datatrak-web/src/api/queries/index.ts, packages/datatrak-web/src/api/queries/useSurveyResponse.ts, packages/datatrak-web/src/features/Survey/utils/useSurveyResponseWithForm.ts, packages/datatrak-web/src/features/SurveyResponseModal.tsx, packages/datatrak-web/src/features/Tasks/TaskDetails/TaskDetails.tsx, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts
- Add initial_request_id to Task table in the db
- Save initial_request_id value
- Add button and modal to view initial request 
---
=> feat(datatrak): RN-1330: View initial request for a task

packages/web-config-server/src/apiV1/permissions/ReportPermissionsChecker.js
The export chart permissions checker was just using the first dashboard relation to check for access even ff there was more than one dashboard relation for a dashboard and dashboard item.
We want to ensure that we allow access to all the dashboard items that a user has permission to, so I have updated the permission checked to get all the the dashboard relations for the dashboard code and item and combine their permission groups, entity types and project codes.
=> fix(tupaiaWeb): RN-1414: Fix dashboard item permission error

yarn.lock
=> deps(security): RN-1096: Update version of `decode-uri-component`

packages/admin-panel-server/package.json, packages/central-server/package.json, packages/central-server/src/tests/apiV2/import/importStriveLabResults/importStriveLabResults.test.js, packages/ui-components/package.json, packages/ui-components/src/components/DataTable/useDataTableExport.tsx, packages/utils/package.json, packages/utils/src/WorkBookParser.js, packages/web-config-server/package.json, yarn.lock
- Updated `xlsx` to version `0.18.5`, as advised in [dependabot PR](https://github.com/beyondessential/tupaia/pull/5574)
- Fixed issues that arose from upgrade re: blank cells
Changelog can be found [here](https://git.sheetjs.com/sheetjs/sheetjs/src/branch/master/CHANGELOG.md)
=> deps(security): RN-1096: Update XLSX version

packages/admin-panel/src/importExport/EntityHierarchyExportModal.jsx, packages/admin-panel/src/layout/navigation/SecondaryNavbar.jsx, packages/admin-panel/src/logsTable/LogsButton.jsx, packages/admin-panel/src/pages/ChangePasswordPage.jsx, packages/admin-panel/src/pages/ProfilePage.jsx, packages/admin-panel/src/routes/surveys/surveys.js, packages/admin-panel/src/table/DataFetchingTable/DataFetchingTable.jsx, packages/admin-panel/src/theme/theme.js, packages/ui-components/src/components/Inputs/InputLabel.tsx
- Added scroll on profile and change password pages
- Fixed entity hierarchy export wording
- Fixed action column widths
- Bolded active nav tab text
- Moved survey questions to top of add survey form
- Fixed colours in forms
- Fixed logs button tooltip formatting
=> tweak(adminPanel): RN-1393: Minor Admin panel updates

packages/central-server/src/scheduledTasks/TaskOverdueChecker.js, packages/datatrak-web/src/features/Survey/SurveyContext/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveyLayout.tsx, packages/datatrak-web/src/features/Survey/utils/usePrimaryEntityQuestionAutoFill.ts
- Add a loader based on the loading state of the entity autofill
=> fix(datatrak): Fix survey autofill loading

README.md, package.json, packages/api-client/package.json, packages/central-server/package.json, packages/database/package.json, packages/datatrak-web-server/package.json, packages/tsutils/package.json, packages/tupaia-web-server/package.json, packages/types/package.json, packages/utils/package.json, packages/utils/tsconfig.json, scripts/bash/backendStartDev.sh
- Fixed internal deps watching script
- Added `build-watch` script
=> tweak(config): Add support for hot reloading on internal deps changes

packages/utils/src/__tests__/timezone.test.js
=> fix(tests): Fix broken timezone tests after DST changes

packages/datatrak-web/src/features/Questions/AutocompleteQuestion.tsx
=> fix(datatrakWeb): RN-1484: Fix autocomplete question not sticking

packages/datatrak-web/src/components/SelectList/SelectList.tsx, packages/datatrak-web/src/features/EntitySelector/EntitySelector.tsx, packages/datatrak-web/src/features/EntitySelector/ResultsList.tsx, packages/datatrak-web/src/features/Questions/EntityQuestion.tsx
=> fix(datatrakWeb): RN-1454: Don't show all entities when no value in review screen

packages/admin-panel/src/table/DataFetchingTable/useColumnFilters.js
- Updated the code responsible for the column filter to return all results once it is cleared.
=> fix(adminPanel): RN-1397: Filtering by sort order result inconsistency

packages/datatrak-web/src/api/mutations/useCreateTask.ts, packages/datatrak-web/src/features/Tasks/CreateTaskModal/CreateTaskModal.tsx
- Added GA events for task created
=> feat(datatrakWeb): RN-1485: Add GA events for task created

packages/admin-panel/src/importExport/ExportButton.jsx
- Make file type explicit so it doesn't get wrongly inferred
=> fix(adminPanel): RN-1496: Fix export button

packages/auth/src/Authenticator.js, packages/auth/src/__tests__/Authenticator/Authenticator.test.js, packages/auth/src/__tests__/Authenticator/testAuthenticatePassword.js, packages/database/scripts/setupNewDatabase.sh, packages/database/src/migrations/20241003224849-addDateColumnToMeditrakDeviceTable-modifies-schema.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts
- Save last login date of meditrak devices so we can track who uses the app
=> tweak(datatrak): RN-1492: Save last login date of meditrak devices

packages/meditrak-app/android/app/build.gradle, packages/meditrak-app/ios/TupaiaMediTrak.xcodeproj/project.pbxproj
This PR adds missing config that is needed to update the meditrak app to version 144
=> fix(meditrak): Hotfix meditrak app version

packages/database/src/__tests__/modelClasses/SurveyResponse.test.js, packages/database/src/modelClasses/SurveyResponse.js
- Update leaderboard to include internal users on internal projects
---
=> tweak(datatrak): RN-1507: Update leader board

packages/types/src/schemas/schemas.ts, packages/types/src/types/models-extra/common.ts
=> fix(vizBuilder): Make datePickerLimits offset non mandatory

packages/tupaia-web/src/features/Dashboard/ExportDashboard/ExportConfig.tsx
- RN-1494: Fix PDF Export Settings UI
=> fix(tupaiaWeb): RN-1494: Fix PDF Export Settings UI

packages/database/src/migrations/20241104002014-addPacmossiInsecticideTestEntityType-modifies-schema.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts
=> db(entityTypes): MAUI-4763: Add new entity types (pacmossi_insecticide_test) for PacMOSSI project

packages/database/src/migrations/20241205044234-addDocumentManagementProjectEntities-modifies-schema.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts
- Addition of two new entity types (document_group and document)
=> db(entityTypes): MAUI-4899: Add new entity types (document_group and document)

package.json, packages/datatrak-web/package.json, packages/datatrak-web/stories/surveyQuestions.stories.tsx, packages/datatrak-web/tsconfig.json, yarn.lock
=> feat: RN-1468: add storybook to datatrak-web

yarn.lock
Ran `yarn dlx update-browserslist-db@latest`
=> deps: update browserlist

packages/datatrak-web/src/components/CancelConfirmModal.tsx, packages/datatrak-web/src/features/Survey/Components/MobileSurveyHeader.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/actions.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/reducer.ts, packages/datatrak-web/src/layout/UserMenu/MenuList.tsx, packages/datatrak-web/src/views/SurveyPage.tsx
- Ensure the Survey back button goes to the previous page
---
=> fix(datatrak): RN-1452: Update survey back button logic

packages/datatrak-web/src/features/RequestProjectAccess.tsx, packages/datatrak-web/src/layout/UserMenu/ProjectSelectModal.tsx, packages/ui-components/src/features/RequestProjectAccess/ProjectAccessForm.tsx, packages/ui-components/src/features/RequestProjectAccess/RequestProjectAccess.tsx, packages/ui-components/src/features/RequestProjectAccess/RequestProjectAccessSuccessMessage.tsx, packages/ui-components/src/features/RequestProjectAccess/index.ts
- Update Request project access flow on mobile
---
**Project select screen**
**Request project access screen**
**Success state**
=> feat(datatrak): RN-1452: Request project access

packages/lesmis/src/components/Forms/LoginForm.jsx, packages/lesmis/src/components/Forms/RegisterForm.jsx, packages/lesmis/src/components/TextField.jsx, packages/lesmis/src/constants/colors.js, packages/lesmis/src/views/AdminPanel/authentication/LoginForm.jsx, packages/lesmis/src/views/AdminPanel/table/columnTypes/getColumnFilter.jsx, packages/ui-components/package.json, packages/ui-components/src/components/Inputs/TextField.tsx, yarn.lock
=> feat(lesmis): RN-1462: override input focus colour

packages/datatrak-web/src/components/DateTimeDisplay.tsx
=> tweak(datatrak): `<DateTimeDisplay>` component

packages/datatrak-web/src/views/Sync/SyncPage.tsx
=> fix(datatrak): RN-1465: padding

packages/central-server/src/apiV2/meditrakApp/utilities/updateOrCreateSurveyResponse.js, packages/database/src/modelClasses/Option.js
Fixes this issue
https://beyondessential.slack.com/archives/C01JD93J4E6/p1738276990985289
=> fix: 2024-49-1

packages/datatrak-web-server/examples.http, packages/datatrak-web-server/src/routes/TasksRoute.ts
=> doc(datatrak): document tasks API

packages/datatrak-web/src/components/PageContainer.tsx, packages/datatrak-web/src/components/Tile.tsx, packages/datatrak-web/src/layout/Header/Header.tsx, packages/datatrak-web/src/views/LandingPage/LandingPage.tsx
=> fix(datatrak): RN-1453: scroll dashboard in short viewports

packages/datatrak-web/src/components/Tile.tsx, packages/datatrak-web/src/views/LandingPage/LandingPage.tsx
=> fix(datatrak): RN-1453: dashboard grid layout, text overflow

packages/tupaia-web/src/features/Dashboard/Dashboard.tsx
Spotted a small easy performance win while working on #5884
=> refactor(tupaia): optimise dashboard render

packages/datatrak-web/src/api/queries/useSurvey.ts, packages/datatrak-web/src/features/Survey/Components/CopySurveyUrlButton.tsx, packages/datatrak-web/src/features/Survey/Components/CopyUrlButton.tsx, packages/datatrak-web/src/features/Survey/Components/DesktopSurveyHeader.tsx, packages/datatrak-web/src/features/Survey/Components/MobileSurveyMenu.tsx, packages/datatrak-web/src/views/LandingPage/SurveySelectSection.tsx
=> fix(datatrak): RN-1453: custom toast collision with Android 12+ toast

packages/database/src/migrations/20250204234806-AddVehicleEntityType-modifies-schema.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts
- Addition of two new entity types (vehicle)
=> db(entityTypes): MAUI-5175: Add new entity types (vehicle)

packages/datatrak-web/src/layout/Header/Header.tsx
=> fix(datatrak): RN-1585: set maximum header height

packages/datatrak-web/src/features/Survey/Components/CopyUrlButton.tsx, packages/datatrak-web/src/features/Survey/Components/SurveySuccess.tsx, packages/datatrak-web/src/features/Survey/SurveyQRCode/QRCodeModal.tsx, packages/datatrak-web/src/features/Survey/SurveyQRCode/QRCodePanel.tsx, packages/datatrak-web/src/features/Survey/SurveyQRCode/SurveyQRCode.tsx
=> fix(datatrak): RN-1585: survey success page layout

packages/datatrak-web/src/layout/UserMenu/ProjectSelectModal.tsx, packages/ui-components/src/components/SelectList/ListItem.tsx, packages/ui-components/src/components/SelectList/SelectList.tsx, packages/ui-components/src/components/SelectList/types.ts, packages/ui-components/src/features/ProjectSelectForm.tsx
=> refactor(datatrak): RN-1585: project selector tweaks

packages/datatrak-web/src/layout/UserMenu/ProjectSelectModal.tsx, packages/ui-components/src/components/SelectList/ListItem.tsx, packages/ui-components/src/components/SelectList/SelectList.tsx, packages/ui-components/src/components/SelectList/types.ts, packages/ui-components/src/features/ProjectSelectForm.tsx
=> fix(datatrak): RN-1585: list item alignment in project selector

packages/datatrak-web/src/layout/UserMenu/ProjectSelectModal.tsx, packages/ui-components/src/components/SelectList/ListItem.tsx
=> fix(uiComponents): `<ListItem>` hover state

packages/datatrak-web/src/api/queries/useCountryAccessList.ts, packages/datatrak-web/src/features/RequestProjectAccess.tsx, packages/datatrak-web/src/views/AccountSettingsPage/AccountSettingsSection.tsx, packages/datatrak-web/src/views/AccountSettingsPage/ChangePasswordSection/ChangePasswordSection.tsx, packages/datatrak-web/src/views/AccountSettingsPage/DeleteAccountSection/DeleteAccountSection.tsx, packages/datatrak-web/src/views/AccountSettingsPage/PersonalDetailsSection/PersonalDetailsSection.tsx, packages/datatrak-web/src/views/AccountSettingsPage/RequestCountryAccessSection/AccessGrantedCountryList.tsx, packages/datatrak-web/src/views/AccountSettingsPage/RequestCountryAccessSection/RequestCountryAccessForm.tsx, packages/datatrak-web/src/views/AccountSettingsPage/RequestCountryAccessSection/RequestCountryAccessSection.tsx, packages/datatrak-web/src/views/AccountSettingsPage/RequestCountryAccessSection/RequestableCountryChecklist.tsx, packages/datatrak-web/src/views/RequestProjectAccessPage.tsx, packages/ui-components/src/components/Inputs/Checkbox.tsx, packages/ui-components/src/features/Form/Form.tsx
=> refactor(datatrak): RN-1585: country access request tidy-ups

packages/datatrak-web-server/src/routes/EntityDescendantsRoute.ts, packages/datatrak-web/index.html, packages/datatrak-web/src/api/queries/useProjectEntities.ts, packages/datatrak-web/src/api/queries/useProjectSurveys.ts, packages/datatrak-web/src/api/queries/useUser.ts, packages/datatrak-web/src/components/FullScreenSelect.tsx, packages/datatrak-web/src/features/CountrySelector/CountrySelector.tsx, packages/datatrak-web/src/features/CountrySelector/useUserCountries.ts, packages/datatrak-web/src/features/GroupedSurveyList.tsx, packages/datatrak-web/src/features/MobileSelectList/MobileSelectList.tsx, packages/datatrak-web/src/features/Tasks/CreateTaskModal/CreateTaskModal.tsx, packages/datatrak-web/src/features/useGroupedSurveyList.tsx, packages/datatrak-web/src/views/SurveySelectPage/DesktopTemplate.tsx, packages/datatrak-web/src/views/SurveySelectPage/MobileTemplate.tsx, packages/datatrak-web/src/views/SurveySelectPage/SurveySelectPage.tsx
=> fix(datatrak): RN-1543: fix country selector not selecting country

packages/admin-panel/src/widgets/InputField/JsonEditor.jsx
Updates borders of JSON fields (unfocused and focused) to match that of regular text fields.
=> feat(datatrak): RN-1569: match JSON field style to text fields

packages/central-server/src/apiV2/surveyResponses/saveResponsesToDatabase.js, packages/central-server/src/dataAccessors/upsertAnswers.js
=> fix(centralServer): RN-1537: some image uploads throw `payload string too long`

packages/central-server/src/apiV2/requestPasswordReset.js, packages/server-utils/src/email/templates/content/passwordReset.html
=> tweak(centralServer): check for env var at initialisation time

packages/database/src/migrations/20250403043521-AddPacMOSSIAssetEntities-modifies-schema.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts
- Addition of two new entity types (pacmossi_asset_facility & pacmossi_asset_sub_facility)
=> db(entityTypes): MAUI-5318: Add new entity types (pacmossi_asset_facility & pacmossi_asset_sub_facility)

packages/admin-panel-server/src/app/createApp.ts, packages/central-server/src/apiV2/GETHandler/GETHandler.js, packages/database/src/DatabaseModel.js, packages/database/src/TupaiaDatabase.js, packages/ui-components/src/components/FilterableTable/FilterableTable.tsx
=> refactor(database): RN-1630: parallelise awaits & code style tweaks

packages/ui-components/src/components/CardTabs.tsx, packages/ui-components/src/components/DataTable/DataTable.tsx, packages/ui-components/src/components/EnvBanner.tsx, packages/ui-components/src/components/Inputs/AsyncAutocomplete.tsx, packages/ui-components/src/components/Inputs/ImageUploadField.tsx, packages/ui-components/src/components/Matrix/utils.ts, packages/ui-components/tsconfig.json
=> tweak: disallow unused variables in ui-components tsconfig

packages/datatrak-web/src/features/Tasks/CreateTaskModal/CreateTaskModal.tsx, packages/datatrak-web/src/features/Tasks/TaskDetails/TaskComments.tsx, packages/datatrak-web/src/features/Tasks/TaskDetails/TaskDetails.tsx, packages/datatrak-web/src/features/Tasks/TaskForm.tsx, packages/datatrak-web/src/features/Tasks/TasksTable/AssignTaskModal.tsx
=> fix(datatrak): flaky state management in Create Task form

packages/central-server/src/apiV2/meditrakApp/utilities/updateOrCreateSurveyResponse.js, packages/database/src/ModelRegistry.js, packages/database/src/TupaiaDatabase.js, packages/database/src/changeHandlers/ChangeHandler.js, packages/database/src/changeHandlers/TaskCreationHandler.js
=> fix(changeHandler): RN-1650: phantom reads when creating tasks from survey response

packages/ui-components/src/hooks/useCurrentPosition.ts
=> feat(datatrak): RN-1460: `useCurrentPosition` hook

packages/devops/scripts/deployment-aws/buildDeployablePackages.sh, packages/devops/scripts/deployment-vm-app/install.sh
=> fix: temporarily pin Bitwarden CLI to last working version

packages/devops/scripts/deployment-aws/buildDeployablePackages.sh
=> fix: pin Bitwarden CLI version on `baseline-2025-23`

packages/datatrak-web/src/features/Survey/SurveyQRCode/QRCodeItem.tsx
=> fix(datatrak): broken layout on generated QR codes

packages/datatrak-web/src/features/Questions/EntityQuestion.tsx, packages/datatrak-web/src/features/Survey/Components/CancelSurveyConfirmationToken.tsx, packages/datatrak-web/src/features/Survey/Components/MobileSurveyMenu.tsx, packages/datatrak-web/src/features/Survey/Components/SurveyPaginator.tsx, packages/datatrak-web/src/features/Survey/Components/SurveySideMenu/SurveySideMenu.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/SurveyContext.tsx, packages/datatrak-web/src/features/Survey/SurveyContext/reducer.ts, packages/datatrak-web/src/features/Survey/SurveyLayout.tsx
=> fix(datatrak): hide entity selector search field on resubmission review screen

packages/devops/scripts/deployment-common/setup.sh
=> fix: pin Bitwarden CLI to single version

.storybook/theme/darkTheme.js, .storybook/theme/lightTheme.js, packages/admin-panel/src/theme/theme.js, packages/datatrak-web/src/theme/theme.ts, packages/tupaia-web/src/features/Map/MapOverlaySelector/DesktopMapOverlaySelector.tsx, packages/tupaia-web/src/theme/theme.ts, packages/ui-components/stories/story-utils/theme/darkTheme.js, packages/ui-components/stories/story-utils/theme/lightTheme.js
=> fix(tupaiaWeb): RN-1705: unscrollable accordion

packages/admin-panel/src/table/DataFetchingTable/DataFetchingTable.jsx, packages/admin-panel/src/table/columnTypes/DeleteButton.jsx, packages/admin-panel/src/table/columnTypes/generateConfigForColumnType.jsx, packages/ui-components/src/components/Modal/Modal.tsx
=> fix(adminPanel): RN-1712: broken action buttons

packages/central-server/src/hooks/utilities.js
=> fix(centralServer): `ReferenceError` when trying to throw error

.github/workflows/cd-android.yaml, packages/meditrak-app/package.json
=> ci(meditrak): RN-1663: fetch env vars from Bitwarden

packages/database/src/migrations/20250723062724-AddConsumableEntityType-modifies-schema.js, packages/types/src/schemas/schemas.ts, packages/types/src/types/models.ts
- Addition of new entity type (consumable)
=> db(entityTypes): MAUI-5705: Add new entity types (consumable)

packages/admin-panel/src/pages/resources/TreeResourcePage.jsx
Addressing Gemini comment: https://github.com/beyondessential/tupaia/pull/6341#discussion_r2230161036
=> fix(adminPanel): fix default prop declaration

llm/docs/initial-overview.md
Addresses Gemini comment https://github.com/beyondessential/tupaia/pull/6343#discussion_r2234165002
=> fix(llm): repeated word in rules file

packages/database/src/TupaiaDatabase.js, packages/database/src/changeHandlers/ChangeHandler.js
- Properly wait for change handlers
=> fix(database): Properly wait for change handlers

packages/central-server/src/apiV2/userAccounts/EditUserForMe.js, packages/central-server/src/apiV2/userAccounts/GETUserForMe.js, packages/central-server/src/permissions/permissions.js, packages/server-boilerplate/src/utils/forwardRequest.ts
=> tweak: log when permission assertion is skipped

packages/utils/src/errors.js
=> fix(utils): `TypeError` when trying to throw `DatabaseError`

packages/central-server/src/apiV2/GETClinics.js, packages/central-server/src/apiV2/GETCountries.js, packages/central-server/src/apiV2/GETGeographicalAreas.js, packages/central-server/src/apiV2/accessRequests/assertAccessRequestPermissions.js, packages/central-server/src/apiV2/answers/assertAnswerPermissions.js, packages/central-server/src/apiV2/entities/assertEntityPermissions.js, packages/central-server/src/apiV2/import/importSurveyResponses/assertCanImportSurveyResponses.js, packages/central-server/src/apiV2/projects/EditProject.js, packages/central-server/src/apiV2/surveyResponses/assertSurveyResponsePermissions.js, packages/central-server/src/apiV2/surveyScreenComponents/assertSurveyScreenComponentPermissions.js, packages/central-server/src/apiV2/surveys/assertSurveyPermissions.js, packages/central-server/src/apiV2/syncGroups/assertSyncGroupPermissions.js, packages/central-server/src/apiV2/tasks/assertTaskPermissions.js, packages/central-server/src/apiV2/userAccounts/assertUserAccountPermissions.js, packages/central-server/src/apiV2/userEntityPermissions/assertUserEntityPermissionPermissions.js, packages/central-server/src/permissions/assertions.js, packages/database/src/modelClasses/AccessRequest.js, packages/database/src/modelClasses/DataGroup.js, packages/database/src/modelClasses/DataServiceSyncGroup.js, packages/database/src/modelClasses/GeographicalArea.js, packages/database/src/modelClasses/Task.js, packages/database/src/modelClasses/User.js, packages/database/src/modelClasses/UserEntityPermission.js, packages/tsutils/src/typeGuards.ts
Alternative approach to #6352, which I slightly prefer
=> tweak(centralServer): RN-1722: throw when database record is unexpectedly null, revised

packages/tupaia-web/src/features/Dashboard/Dashboard.tsx
=> fix(tupaiaWeb): RN-1728: subscribing/unsubscribing to mailing list shows undesirable loading spinner

packages/central-server/src/apiV2/verifyEmail.js
Addresses https://github.com/beyondessential/tupaia/pull/6371#discussion_r2268578681
=> fix(centralServer): RN-1728: bad import

packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/utils/useDefaultDashboardName.ts
=> fix: RN-1728: preserve location hash and search params when redirecting

packages/tupaia-web-server/src/routes/CountriesRoute.ts, packages/web-config-server/src/authSession/authSession.js
=> fix: RN-1731: unhide Timor-Leste

env/servers.env.example
=> env: comment deprecation of `API_CLIENT_SALT`

packages/admin-panel/src/editor/actions.js
- Fix release issues:
- https://linear.app/bes/issue/RN-1737/release-2025-36-regressions#comment-afa8ebf6
- https://linear.app/bes/issue/RN-1737/release-2025-36-regressions#comment-7d32a3d3
=> fix(admin): RN-1737: Fix survey import release issues

packages/admin-panel/src/editor/actions.js, packages/tupaia-web/src/constants/mapbox.ts, packages/tupaia-web/src/features/Dashboard/Breadcrumbs.tsx, packages/tupaia-web/src/features/Dashboard/Dashboard.tsx, packages/tupaia-web/src/features/Dashboard/StaticMap.tsx, packages/tupaia-web/src/types/entity.d.ts, packages/ui-map-components/src/constants/constants.ts
=> merge: dev ← release

packages/admin-panel/src/VizBuilderApp/components/DataLibrary/component/TransformEditor.jsx
https://beyondessential.slack.com/archives/C01JD93J4E6/p1756693078581529
=> fix(adminPanel): inaccessible SQL editor

packages/admin-panel/src/VizBuilderApp/components/DataLibrary/component/TransformEditor.jsx
=> fix(adminPanel): RN-1737: inaccessible SQL editor

packages/datatrak-web/src/api/queries/useDatabaseQuery.ts
=> fix(datatrak): “Access policy is required” error
